/**
 * @module MenuIcons
 * @description Icon mapping for AURA navigation menu
 * @project AURA HCM Platform
 * @reference docs/aura-master-instructions.md
 */

import {
  Brain,
  Clock,
  Shield,
  Gift,
  TrendingUp,
  MessageSquare,
  DollarSign,
  Target,
  FileText,
  Users,
  Heart,
  User,
  ThumbsUp,
  PartyPopper,
  Gamepad2,
  HeartPulse,
  Calculator,
  HelpCircle,
  Headphones,
  Briefcase,
  GraduationCap,
  Scale,
  Calendar,
  Globe,
  Smartphone,
  UserCheck,
  LogOut,
  UserPlus,
  Network,
  Wallet,
  BarChart3,
  FileCheck,
  Building2,
  Search,
  Home as HomeIcon,
  Plane,
  Settings,
  Award,
  Workflow,
  LineChart,
  LayoutDashboard,
  LogOutIcon,
  type LucideIcon,
} from 'lucide-react';

import type { MenuIconName } from '@aura/types';

export const menuIconMap: Record<MenuIconName, LucideIcon> = {
  ai: Brain,
  attendance: Clock,
  security: Shield,
  benefits: Gift,
  career: TrendingUp,
  chatbot: MessageSquare,
  compensation: DollarSign,
  competency: Target,
  contract: FileText,
  coreHr: Users,
  dei: Heart,
  ess: User,
  engagementEmployee: ThumbsUp,
  engagement: PartyPopper,
  gamification: Gamepad2,
  healthSafety: HeartPulse,
  hrBudgeting: Calculator,
  hrHelpdesk: HelpCircle,
  hrsd: Headphones,
  jobLibrary: Briefcase,
  learning: GraduationCap,
  labor: Scale,
  leave: Calendar,
  localization: Globe,
  mobile: Smartphone,
  mss: UserCheck,
  offboarding: LogOut,
  onboarding: UserPlus,
  orgDesign: Network,
  payroll: Wallet,
  performance: BarChart3,
  policy: FileCheck,
  positionBudgeting: Building2,
  recruitment: Search,
  remoteWork: HomeIcon,
  reports: LineChart,
  succession: Award,
  travel: Plane,
  userManagement: Settings,
  wellness: HeartPulse,
  workflow: Workflow,
  workforcePlanning: LineChart,
  dashboard: LayoutDashboard,
  settings: Settings,
  help: HelpCircle,
  logout: LogOutIcon,
};

export const getMenuIcon = (iconName: MenuIconName): LucideIcon => {
  return menuIconMap[iconName] || HelpCircle;
};
