import { describe, it, expect, beforeEach, vi } from 'vitest';
import { EmploymentHistoryService } from '../employment-history.service';
import { PrismaClient } from '@aura/database';

// Mock Prisma
vi.mock('@aura/database', () => {
  const mockPrisma = {
    employmentHistory: {
      findMany: vi.fn(),
      findFirst: vi.fn(),
      count: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
      groupBy: vi.fn(),
    },
    employee: {
      findFirst: vi.fn(),
    },
  };
  return {
    PrismaClient: vi.fn(() => mockPrisma),
  };
});

describe('EmploymentHistoryService', () => {
  // Get mocked prisma instance
  const prisma = new PrismaClient() as any;

  // Mock data fixtures
  const mockDepartment = {
    id: 'dept-1',
    code: 'ENG',
    name: 'Engineering',
  };

  const mockJobProfile = {
    id: 'job-1',
    code: 'SE',
    title: 'Software Engineer',
  };

  const mockGrade = {
    id: 'grade-1',
    code: 'L4',
    name: 'Senior Engineer',
  };

  const mockLocation = {
    id: 'loc-1',
    code: 'HQ',
    name: 'Headquarters',
  };

  const mockHistoryRecord = {
    id: 'history-1',
    tenantId: 'tenant-1',
    employeeId: 'emp-1',
    changeType: 'PROMOTION',
    effectiveDate: new Date('2024-01-15'),
    reason: 'Performance Excellence',
    notes: 'Promoted to Senior Engineer',
    previousDepartmentId: 'dept-1',
    previousJobProfileId: 'job-1',
    previousGradeId: 'grade-1',
    previousLocationId: 'loc-1',
    previousManagerId: null,
    previousSalary: 80000,
    previousEmploymentType: 'FULL_TIME',
    newDepartmentId: 'dept-1',
    newJobProfileId: 'job-1',
    newGradeId: 'grade-2',
    newLocationId: 'loc-1',
    newManagerId: null,
    newSalary: 100000,
    newEmploymentType: 'FULL_TIME',
    requestedBy: 'manager-1',
    approvedBy: 'hr-1',
    approvedAt: new Date('2024-01-10'),
    status: 'COMPLETED',
    isAutoGenerated: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-10'),
    previousDepartment: mockDepartment,
    previousJobProfile: mockJobProfile,
    previousGrade: mockGrade,
    previousLocation: mockLocation,
    newDepartment: mockDepartment,
    newJobProfile: mockJobProfile,
    newGrade: { id: 'grade-2', code: 'L5', name: 'Staff Engineer' },
    newLocation: mockLocation,
  };

  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('findAll', () => {
    it('should return paginated employment history records', async () => {
      const mockRecords = [mockHistoryRecord];
      vi.mocked(prisma.employmentHistory.findMany).mockResolvedValue(mockRecords);
      vi.mocked(prisma.employmentHistory.count).mockResolvedValue(1);

      const result = await EmploymentHistoryService.findAll({ tenantId: 'tenant-1' });

      expect(result.data).toEqual(mockRecords);
      expect(result.pagination).toEqual({
        page: 1,
        limit: 20,
        total: 1,
        totalPages: 1,
      });
    });

    it('should filter by employee ID', async () => {
      vi.mocked(prisma.employmentHistory.findMany).mockResolvedValue([mockHistoryRecord]);
      vi.mocked(prisma.employmentHistory.count).mockResolvedValue(1);

      await EmploymentHistoryService.findAll({ tenantId: 'tenant-1', employeeId: 'emp-1' });

      expect(prisma.employmentHistory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({
            tenantId: 'tenant-1',
            employeeId: 'emp-1',
          }),
        })
      );
    });

    it('should filter by change type', async () => {
      vi.mocked(prisma.employmentHistory.findMany).mockResolvedValue([mockHistoryRecord]);
      vi.mocked(prisma.employmentHistory.count).mockResolvedValue(1);

      await EmploymentHistoryService.findAll({ tenantId: 'tenant-1', changeType: 'PROMOTION' });

      expect(prisma.employmentHistory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({
            changeType: 'PROMOTION',
          }),
        })
      );
    });

    it('should filter by date range', async () => {
      vi.mocked(prisma.employmentHistory.findMany).mockResolvedValue([mockHistoryRecord]);
      vi.mocked(prisma.employmentHistory.count).mockResolvedValue(1);

      await EmploymentHistoryService.findAll({
        tenantId: 'tenant-1',
        startDate: '2024-01-01',
        endDate: '2024-12-31',
      });

      expect(prisma.employmentHistory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({
            effectiveDate: {
              gte: new Date('2024-01-01'),
              lte: new Date('2024-12-31'),
            },
          }),
        })
      );
    });

    it('should support pagination', async () => {
      vi.mocked(prisma.employmentHistory.findMany).mockResolvedValue([mockHistoryRecord]);
      vi.mocked(prisma.employmentHistory.count).mockResolvedValue(50);

      const result = await EmploymentHistoryService.findAll({
        tenantId: 'tenant-1',
        page: 2,
        limit: 10,
      });

      expect(result.pagination.totalPages).toBe(5);
      expect(prisma.employmentHistory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          skip: 10,
          take: 10,
        })
      );
    });
  });

  describe('findById', () => {
    it('should find employment history record by ID', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(mockHistoryRecord);

      const result = await EmploymentHistoryService.findById('history-1', 'tenant-1');

      expect(result).toEqual(mockHistoryRecord);
      expect(prisma.employmentHistory.findFirst).toHaveBeenCalledWith({
        where: { id: 'history-1', tenantId: 'tenant-1' },
        include: expect.any(Object),
      });
    });

    it('should return null if record not found', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(null);

      const result = await EmploymentHistoryService.findById('non-existent', 'tenant-1');

      expect(result).toBeNull();
    });
  });

  describe('getEmployeeTimeline', () => {
    it('should return employment timeline for employee', async () => {
      const mockTimeline = [mockHistoryRecord];
      vi.mocked(prisma.employmentHistory.findMany).mockResolvedValue(mockTimeline);

      const result = await EmploymentHistoryService.getEmployeeTimeline('emp-1', 'tenant-1');

      expect(result).toEqual(mockTimeline);
      expect(prisma.employmentHistory.findMany).toHaveBeenCalledWith({
        where: { employeeId: 'emp-1', tenantId: 'tenant-1' },
        orderBy: { effectiveDate: 'desc' },
        include: expect.any(Object),
      });
    });
  });

  describe('create', () => {
    it('should create new employment history record', async () => {
      const createData = {
        tenantId: 'tenant-1',
        employeeId: 'emp-1',
        changeType: 'PROMOTION' as const,
        effectiveDate: '2024-01-15',
        reason: 'Performance Excellence',
        newGradeId: 'grade-2',
        newSalary: 100000,
      };

      vi.mocked(prisma.employmentHistory.create).mockResolvedValue(mockHistoryRecord);

      const result = await EmploymentHistoryService.create(createData);

      expect(result).toEqual(mockHistoryRecord);
      expect(prisma.employmentHistory.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({
            tenantId: 'tenant-1',
            employeeId: 'emp-1',
            changeType: 'PROMOTION',
            effectiveDate: expect.any(Date),
          }),
        })
      );
    });

    it('should validate input data', async () => {
      const invalidData = {
        tenantId: 'tenant-1',
        employeeId: 'emp-1',
        changeType: 'INVALID_TYPE', // Invalid change type
        effectiveDate: '2024-01-15',
      };

      await expect(EmploymentHistoryService.create(invalidData as any)).rejects.toThrow();
    });
  });

  describe('update', () => {
    it('should update employment history record', async () => {
      const updateData = {
        reason: 'Updated reason',
        notes: 'Updated notes',
      };

      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(mockHistoryRecord);
      vi.mocked(prisma.employmentHistory.update).mockResolvedValue({
        ...mockHistoryRecord,
        ...updateData,
      });

      const result = await EmploymentHistoryService.update('history-1', 'tenant-1', updateData);

      expect(result.reason).toBe('Updated reason');
      expect(result.notes).toBe('Updated notes');
    });

    it('should throw error if record not found', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(null);

      await expect(
        EmploymentHistoryService.update('non-existent', 'tenant-1', {})
      ).rejects.toThrow('Employment history record not found');
    });
  });

  describe('delete', () => {
    it('should delete employment history record', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(mockHistoryRecord);
      vi.mocked(prisma.employmentHistory.delete).mockResolvedValue(mockHistoryRecord);

      const result = await EmploymentHistoryService.delete('history-1', 'tenant-1');

      expect(result).toEqual({ success: true });
      expect(prisma.employmentHistory.delete).toHaveBeenCalledWith({ where: { id: 'history-1' } });
    });

    it('should throw error if record not found', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(null);

      await expect(EmploymentHistoryService.delete('non-existent', 'tenant-1')).rejects.toThrow(
        'Employment history record not found'
      );
    });
  });

  describe('createFromEmployeeChange', () => {
    it('should auto-create history record from employee change', async () => {
      const previousState = {
        departmentId: 'dept-1',
        jobProfileId: 'job-1',
        gradeId: 'grade-1',
        locationId: 'loc-1',
        managerId: null,
      };

      const newState = {
        departmentId: 'dept-2',
        jobProfileId: 'job-2',
        gradeId: 'grade-2',
        locationId: 'loc-2',
        managerId: 'mgr-1',
      };

      vi.mocked(prisma.employmentHistory.create).mockResolvedValue(mockHistoryRecord);

      const result = await EmploymentHistoryService.createFromEmployeeChange(
        'emp-1',
        'tenant-1',
        previousState,
        newState,
        'TRANSFER',
        new Date('2024-01-15'),
        'manager-1'
      );

      expect(result).toEqual(mockHistoryRecord);
      expect(prisma.employmentHistory.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({
            isAutoGenerated: true,
            status: 'COMPLETED',
          }),
        })
      );
    });
  });

  describe('getStatistics', () => {
    it('should return employment change statistics', async () => {
      vi.mocked(prisma.employmentHistory.count)
        .mockResolvedValueOnce(100) // totalChanges
        .mockResolvedValueOnce(25) // promotions
        .mockResolvedValueOnce(5) // demotions
        .mockResolvedValueOnce(30) // transfers
        .mockResolvedValueOnce(15) // lateralMoves
        .mockResolvedValueOnce(20) // newHires
        .mockResolvedValueOnce(5); // terminations

      vi.mocked(prisma.employmentHistory.groupBy).mockResolvedValue([
        { changeType: 'PROMOTION', _count: 25 },
        { changeType: 'TRANSFER', _count: 30 },
      ] as any);

      const result = await EmploymentHistoryService.getStatistics('tenant-1');

      expect(result).toEqual({
        totalChanges: 100,
        promotions: 25,
        demotions: 5,
        transfers: 30,
        lateralMoves: 15,
        newHires: 20,
        terminations: 5,
        changesByType: [
          { changeType: 'PROMOTION', _count: 25 },
          { changeType: 'TRANSFER', _count: 30 },
        ],
      });
    });
  });

  describe('getCurrentPositionTenure', () => {
    it('should calculate tenure from latest history record', async () => {
      const pastDate = new Date('2023-01-01');
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue({
        ...mockHistoryRecord,
        effectiveDate: pastDate,
      });

      const result = await EmploymentHistoryService.getCurrentPositionTenure('emp-1', 'tenant-1');

      expect(result).toBeDefined();
      expect(result?.days).toBeGreaterThan(0);
      expect(result?.sinceDate).toEqual(pastDate);
    });

    it('should use employee creation date if no history exists', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(null);
      vi.mocked(prisma.employee.findFirst).mockResolvedValue({
        createdAt: new Date('2023-01-01'),
      } as any);

      const result = await EmploymentHistoryService.getCurrentPositionTenure('emp-1', 'tenant-1');

      expect(result).toBeDefined();
      expect(result?.days).toBeGreaterThan(0);
    });

    it('should return null if employee not found', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(null);
      vi.mocked(prisma.employee.findFirst).mockResolvedValue(null);

      const result = await EmploymentHistoryService.getCurrentPositionTenure('emp-1', 'tenant-1');

      expect(result).toBeNull();
    });
  });

  describe('compare', () => {
    it('should compare two employment history records', async () => {
      const record2 = {
        ...mockHistoryRecord,
        id: 'history-2',
        newDepartmentId: 'dept-2',
        newSalary: 120000,
      };

      vi.mocked(prisma.employmentHistory.findFirst)
        .mockResolvedValueOnce(mockHistoryRecord)
        .mockResolvedValueOnce(record2);

      const result = await EmploymentHistoryService.compare('history-1', 'history-2', 'tenant-1');

      expect(result.record1).toEqual(mockHistoryRecord);
      expect(result.record2).toEqual(record2);
      expect(result.changes).toEqual({
        department: true,
        jobProfile: false,
        grade: false,
        location: false,
        manager: false,
        salary: true,
        employmentType: false,
      });
    });

    it('should throw error if records not found', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(null);

      await expect(
        EmploymentHistoryService.compare('history-1', 'history-2', 'tenant-1')
      ).rejects.toThrow('One or both records not found');
    });
  });

  describe('getPendingApprovals', () => {
    it('should return pending approval records', async () => {
      const pendingRecord = { ...mockHistoryRecord, status: 'PENDING' };
      vi.mocked(prisma.employmentHistory.findMany).mockResolvedValue([pendingRecord]);

      const result = await EmploymentHistoryService.getPendingApprovals('tenant-1');

      expect(result).toEqual([pendingRecord]);
      expect(prisma.employmentHistory.findMany).toHaveBeenCalledWith({
        where: { tenantId: 'tenant-1', status: 'PENDING' },
        orderBy: { createdAt: 'asc' },
        include: expect.any(Object),
      });
    });
  });

  describe('approve', () => {
    it('should approve pending employment history record', async () => {
      const pendingRecord = { ...mockHistoryRecord, status: 'PENDING', approvedBy: null, approvedAt: null };
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(pendingRecord);
      vi.mocked(prisma.employmentHistory.update).mockResolvedValue({
        ...pendingRecord,
        status: 'APPROVED',
        approvedBy: 'approver-1',
        approvedAt: new Date(),
      });

      const result = await EmploymentHistoryService.approve('history-1', 'tenant-1', 'approver-1');

      expect(result.status).toBe('APPROVED');
      expect(result.approvedBy).toBe('approver-1');
    });

    it('should throw error if record not found', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(null);

      await expect(
        EmploymentHistoryService.approve('non-existent', 'tenant-1', 'approver-1')
      ).rejects.toThrow('Employment history record not found');
    });

    it('should throw error if record is not pending', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(mockHistoryRecord);

      await expect(
        EmploymentHistoryService.approve('history-1', 'tenant-1', 'approver-1')
      ).rejects.toThrow('Only pending records can be approved');
    });
  });

  describe('reject', () => {
    it('should reject pending employment history record', async () => {
      const pendingRecord = { ...mockHistoryRecord, status: 'PENDING', approvedBy: null, approvedAt: null };
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(pendingRecord);
      vi.mocked(prisma.employmentHistory.update).mockResolvedValue({
        ...pendingRecord,
        status: 'REJECTED',
        approvedBy: 'rejector-1',
        approvedAt: new Date(),
      });

      const result = await EmploymentHistoryService.reject(
        'history-1',
        'tenant-1',
        'rejector-1',
        'Not qualified'
      );

      expect(result.status).toBe('REJECTED');
      expect(result.approvedBy).toBe('rejector-1');
    });

    it('should throw error if record is not pending', async () => {
      vi.mocked(prisma.employmentHistory.findFirst).mockResolvedValue(mockHistoryRecord);

      await expect(
        EmploymentHistoryService.reject('history-1', 'tenant-1', 'rejector-1')
      ).rejects.toThrow('Only pending records can be rejected');
    });
  });
});
