/**
 * @reference docs/aura-master-instructions.md
 */

export type MenuModule = {
    code: string;
    label: string;
    icon: string;
    path?: string;
    permissions?: string[];
    featureFlag?: string;
    feature?: string[]; // Legacy support during migration if needed, but 'features' is the main one
    features: string[];
    items?: MenuModule[];
};

export type MenuDefinition = {
    role: 'SUPER_ADMIN';
    menuName: string;
    items: MenuModule[];
};

export const superAdminMenu: MenuDefinition = {
    role: 'SUPER_ADMIN',
    menuName: 'CONSTELLATION_FULL',
    items: [
        {
            code: 'AI_AUTOMATION',
            label: 'AI & Automation',
            icon: 'ai',
            path: '/dashboard/ai-automation',
            features: [
                'AI Analytics',
                'Org Health Predictor',
                'AI Coaching Bot',
                'Workflow Generator',
                'Resume Screening',
                'Attrition Prediction',
                'Leave Forecasting',
                'Anomaly Detection',
                'Chatbot',
                'Interview Scheduling',
                'Performance Analysis',
                'L&D Recommendation',
                'Job Matching',
                'Job Boards',
                'Email Parsing',
                'Auto Accruals',
                'NLP Insights',
            ],
        },
        {
            code: 'ATTENDANCE',
            label: 'Attendance',
            icon: 'attendance',
            path: '/dashboard/attendance',
            features: [
                'Shift Management',
                'Roster Assignment',
                'Time Capture',
                'Punch Rules',
                'Geo-Fencing',
                'IP Restriction',
                'Attendance Exceptions',
                'Regularization Request',
                'Work From Home',
                'Comp-off Management',
                'Overtime Management',
                'Time Rounding',
                'Approval Workflow',
                'Timesheets',
            ],
        },
        {
            code: 'AUDIT_SECURITY',
            label: 'Audit & Security',
            icon: 'security',
            path: '/dashboard/security',
            features: [
                'Audit Logs',
                'Login Logs',
                'Role-based Access',
                'Field-level Security',
                'Dual Authentication',
                'Document Access Logs',
                'Compliance Tracker',
                'Policy Acknowledgement',
                'Approval Logs',
                'GDPR Tools',
                'Alert Rules',
                'Data Retention',
            ],
        },
        {
            code: 'BENEFITS',
            label: 'Benefits',
            icon: 'benefits',
            path: '/dashboard/benefits',
            features: [
                'Benefit Types',
                'Plan Eligibility',
                'Enrollment Window',
                'Dependent Management',
                'Insurance Coverage',
                'Premium Sharing',
                'Claims',
                'Claim Status',
                'Provider Directory',
                'Notification',
                'Exception Handling',
                'Reporting',
            ],
        },
        {
            code: 'CAREER_PLANNING',
            label: 'Career Planning',
            icon: 'career',
            path: '/dashboard/career',
            features: [
                'Career Ladders',
                'Internal Mobility',
                'Career Goals',
                'Aspirations',
            ],
        },
        {
            code: 'CHATBOT_BUILDER',
            label: 'Chatbot Builder',
            icon: 'chatbot',
            path: '/dashboard/chatbot-builder',
            features: [
                'Dialogue Designer',
                'Entity Management',
                'Intent Library',
                'Training Data',
                'Multi-Channel',
                'Analytics Dashboard',
                'Handoff Rules',
                'Multi-lingual',
            ],
        },
        {
            code: 'COMPENSATION',
            label: 'Compensation',
            icon: 'compensation',
            path: '/dashboard/compensation',
            features: [
                'Salary Structure',
                'Grade & Bands',
                'Increment Planning',
                'Bonus Management',
                'Stock Options',
                'Loan & Advances',
                'Arrears Processing',
                'Total Rewards',
                'Market Benchmarking',
                'Budget Simulation',
                'Loans',
            ],
        },
        {
            code: 'COMPETENCY_LIBRARY',
            label: 'Competency Library',
            icon: 'competency',
            path: '/dashboard/performance/competency-library',
            features: [
                'Competency Catalog',
                'Proficiency Levels',
                'Job-Competency Map',
                'Skill Assessment',
                'Gap Analysis',
            ],
        },
        {
            code: 'CONTRACT_WORKFORCE',
            label: 'Contract Workforce',
            icon: 'contract',
            path: '/dashboard/recruitment/vendors',
            features: [
                'Vendor Management',
                'Contract Types',
                'Rate Cards',
                'Timesheet',
                'Invoice Processing',
                'Compliance Docs',
                'Contract Renewal',
                'Performance Rating',
            ],
        },
        {
            code: 'CORE_HR',
            label: 'Core HR',
            icon: 'coreHr',
            path: '/dashboard/core-hr',
            features: [
                'Employee Database',
                'Organization Structure',
                'Employment History',
                'Document Management',
                'Position Management',
                'Cost Center',
                'Employee Life Events',
                'Mass Updates',
                'Employee ID Cards',
                'Letter Generation',
                'Exit Management',
                'Anniversary Alerts',
                'Auto-Numbering',
                'Probation Tracking',
                'Confirmation Letters',
                'Asset Management',
            ],
        },
        {
            code: 'DEI',
            label: 'DEI',
            icon: 'dei',
            path: '/dashboard/dei',
            features: [
                'Diversity Metrics',
                'Inclusion Survey',
                'Pay Equity Analysis',
                'Bias Training',
                'ERG Management',
                'Mentorship Program',
                'Accessibility',
                'DEI Goals',
            ],
        },
        {
            code: 'ESS',
            label: 'ESS',
            icon: 'ess',
            path: '/dashboard/my-services',
            features: [
                'Personal Info Update',
                'Leave Application',
                'Payslip Access',
                'Tax Declaration',
                'Attendance View',
                'Team Directory',
                'Request Center',
                'My Documents',
            ],
        },
        {
            code: 'EMPLOYEE_ENGAGEMENT',
            label: 'Employee Engagement',
            icon: 'engagementEmployee',
            path: '/dashboard/engagement',
            features: [
                'Engagement Analytics',
                'Pulse Surveys',
                'Recognition Wall',
                'Suggestion Box',
                'Social Feed',
                'Event Calendar',
                'Referral Program',
                'Polls Quizzes',
                'CSR Activities',
                'Classifieds',
            ],
        },
        {
            code: 'ENGAGEMENT',
            label: 'Engagement',
            icon: 'engagement',
            path: '/dashboard/engagement',
            features: [
                'Event Calendar',
                'Birthday/Anniversary',
                'Newsletter',
                'Polls & Quizzes',
                'Social Feed',
                'Rewards Catalog',
                'Referral Program',
                'CSR Activities',
                'Surveys',
            ],
        },
        {
            code: 'GAMIFICATION',
            label: 'Gamification',
            icon: 'gamification',
            path: '/dashboard/gamification',
            features: [
                'Points System',
                'Leaderboards',
                'Badges',
                'Challenges',
                'Levels & Tiers',
                'Missions',
                'Virtual Currency',
                'Achievement Wall',
            ],
        },
        {
            code: 'HEALTH_SAFETY',
            label: 'Health & Safety',
            icon: 'healthSafety',
            path: '/dashboard/health-safety',
            features: [
                'Incident Reporting',
                'Safety Training',
                'Health Checkups',
                'Emergency Contacts',
                'COVID Tracker',
            ],
        },
        {
            code: 'HR_BUDGETING',
            label: 'HR Budgeting',
            icon: 'hrBudgeting',
            path: '/dashboard/finance/budget',
            features: [
                'Headcount Planning',
                'Salary Budgets',
                'Cost Projections',
                'Budget vs Actual',
                'Scenario Planning',
                'Department Allocation',
                'Approval Workflow',
                'Budget Templates',
            ],
        },
        {
            code: 'FINANCE',
            label: 'Finance',
            icon: 'hrBudgeting',
            path: '/dashboard/finance',
            items: [
                {
                    code: 'FINANCE_BUDGET',
                    label: 'Budgeting',
                    icon: 'hrBudgeting',
                    path: '/dashboard/finance/budget',
                    features: [
                        'Headcount Planning',
                        'Salary Budgets',
                        'Scenario Planning',
                        'Budget vs Actual',
                        'Approvals',
                    ],
                },
                {
                    code: 'FINANCE_ASSETS',
                    label: 'Assets',
                    icon: 'payroll',
                    path: '/dashboard/finance/assets',
                    features: [
                        'Capital Assets',
                        'Operational Assets',
                        'Depreciation',
                        'Cost Centers',
                    ],
                },
                {
                    code: 'FINANCE_PETTY_CASH',
                    label: 'Petty Cash',
                    icon: 'payroll',
                    path: '/dashboard/finance/petty-cash',
                    features: [
                        'Disbursements',
                        'Reconciliation',
                        'Policy Controls',
                    ],
                },
                {
                    code: 'FINANCE_VENDORS',
                    label: 'Vendors',
                    icon: 'contract',
                    path: '/dashboard/finance/vendors',
                    features: [
                        'Vendor Onboarding',
                        'Contracts',
                        'Compliance',
                    ],
                },
            ],
            features: [
                'Assets',
                'Budget',
                'Petty Cash',
                'Vendors',
            ],
        },
        {
            code: 'HR_HELPDESK',
            label: 'HR Helpdesk',
            icon: 'hrHelpdesk',
            path: '/dashboard/helpdesk',
            features: [
                'Ticket Management',
                'SLA Tracking',
                'Knowledge Base',
                'Agent Assignment',
                'Escalation Matrix',
                'Customer Satisfaction',
                'Canned Responses',
                'Analytics',
                'Tickets',
            ],
        },
        {
            code: 'HRSD',
            label: 'HRSD',
            icon: 'hrsd',
            path: '/dashboard/hr-helpdesk',
            features: [
                'Service Catalog',
                'Request Portal',
                'Case Management',
                'Service Automation',
                'Chat Support',
                'Omnichannel',
                'Performance Metrics',
                'Continuous Improvement',
            ],
        },
        {
            code: 'JOB_LIBRARY',
            label: 'Job Library',
            icon: 'jobLibrary',
            path: '/dashboard/job-library',
            features: [
                'Job Catalog',
                'Job Families',
                'Job Evaluation',
                'Market Pricing',
                'Job Posting Templates',
            ],
        },
        {
            code: 'LEARNING_DEVELOPMENT',
            label: 'L&D',
            icon: 'learning',
            path: '/dashboard/learning',
            features: [
                'Course Catalog',
                'Learning Paths',
                'Training Calendar',
                'Enrollment',
                'Attendance Tracking',
                'Assessment Engine',
                'Certifications',
                'External Training',
                'Training Feedback',
                'Skill Gap Analysis',
                'Training Budget',
                'Vendor Management',
                'E-Learning Platform',
                'Mentoring',
                'Knowledge Repository',
                'Compliance Training',
                'ROI Measurement',
            ],
        },
        {
            code: 'INTEGRATION_HUB',
            label: 'Integration Hub',
            icon: 'Plug',
            path: '/dashboard/integration-hub',
            features: [
                'API Marketplace',
                'Webhook Manager',
                'App Directory',
            ],
        },
        {
            code: 'GLOBAL_MOBILITY',
            label: 'Global Mobility',
            icon: 'Globe',
            path: '/dashboard/mobility',
            features: [
                'Visa & Immigration',
                'Relocation Packages',
                'Expat Tax Manager',
            ],
        },
        {
            code: 'ALUMNI_NETWORK',
            label: 'Alumni Network',
            icon: 'Users2',
            path: '/dashboard/alumni-network',
            features: [
                'Alumni Directory',
                'Events & Reunions',
                'Alumni Jobs',
            ],
        },
        {
            code: 'LABOR_RELATIONS',
            label: 'Labor Relations',
            icon: 'labor',
            path: '/dashboard/compliance',
            features: [
                'Union Database',
                'Grievance Management',
                'Collective Bargaining',
                'Disciplinary Actions',
                'Labor Law Compliance',
                'Strike Management',
                'Arbitration',
                'Communication Log',
            ],
        },
        {
            code: 'LEAVE',
            label: 'Leave',
            icon: 'leave',
            path: '/dashboard/leave',
            features: [
                'Leave Types',
                'Leave Policy',
                'Leave Balance',
                'Leave Application',
                'Leave Calendar',
                'Holiday Management',
                'Leave Encashment',
                'Carry Forward',
                'Comp-off Tracking',
                'Leave Reports',
                'My Leaves',
            ],
        },
        {
            code: 'LOCALIZATION',
            label: 'Localization',
            icon: 'localization',
            path: '/dashboard/admin/master-data',
            features: [
                'Multi-Currency',
                'Multi-Language',
                'Country-Specific Fields',
                'Tax Regimes',
                'Statutory Compliance',
                'Date/Time Formats',
                'Calendar Types',
                'Bank Integration',
                'Government Reports',
                'Regional Holidays',
                'Address Formats',
            ],
        },
        {
            code: 'MOBILE_APP',
            label: 'Mobile App',
            icon: 'mobile',
            path: '/dashboard/mobile-app',
            features: [
                'Native Apps',
                'Push Notifications',
                'Offline Mode',
                'Biometric Login',
                'GPS Attendance',
                'Mobile Approvals',
                'Document Upload',
                'Team View',
                'Expense Claims',
                'Mobile Timesheets',
                'Quick Actions',
                'Voice Commands',
                'Mobile Analytics',
                'Chat Messaging',
                'Profile Management',
            ],
        },
        {
            code: 'MSS',
            label: 'MSS',
            icon: 'mss',
            path: '/dashboard/manager',
            features: [
                'Team Dashboard',
                'Approval Center',
                'Team Reports',
                'Delegation',
            ],
        },
        {
            code: 'OFFBOARDING',
            label: 'Offboarding',
            icon: 'offboarding',
            path: '/dashboard/offboarding',
            features: [
                'Exit Process',
                'Exit Interview',
                'Clearance Checklist',
                'F&F Settlement',
            ],
        },
        {
            code: 'ONBOARDING',
            label: 'Onboarding',
            icon: 'onboarding',
            path: '/dashboard/onboarding',
            features: [
                'Pre-boarding',
                'First Day Experience',
                'Induction Program',
                'Buddy Assignment',
                '30-60-90 Day Plan',
            ],
        },
        {
            code: 'ORG_DESIGN',
            label: 'Org Design',
            icon: 'orgDesign',
            path: '/dashboard/org-design',
            features: [
                'Org Chart Builder',
                'Scenario Planning',
                'Span of Control',
                'Position Hierarchy',
                'Matrix Structure',
                'Succession Pool',
                'Org Analytics',
                'Change Management',
            ],
        },
        {
            code: 'PAYROLL',
            label: 'Payroll',
            icon: 'payroll',
            path: '/dashboard/payroll',
            features: [
                'Payroll Processing',
                'Tax Calculation',
                'Statutory Deductions',
                'Bank File Generation',
                'Payslip Generation',
                'Reimbursements',
                'Loan Recovery',
                'Arrears Management',
                'Bonus Processing',
                'Year-end Processing',
                'Multi-State Payroll',
                'Payroll Reconciliation',
                'Garnishments',
                'Off-cycle Payments',
                'Payroll Reports',
                'Additional Tasks (per doc)',
                'Payslips',
            ],
        },
        {
            code: 'PERFORMANCE',
            label: 'Performance',
            icon: 'performance',
            path: '/dashboard/performance',
            features: [
                'Goal Setting',
                'Review Cycles',
                'Self-Assessment',
                'Manager Assessment',
                '360 Feedback',
                'Continuous Feedback',
                'Rating Scales',
                'Bell Curve',
                'Calibration',
                '1-on-1 Meetings',
                'PIP Management',
                'Competency Assessment',
                'Development Plans',
                'Performance Analytics',
                'Reward Linkage',
                'My Reviews',
                'Skills Gap',
            ],
        },
        {
            code: 'POLICY_MGMT',
            label: 'Policy Mgmt',
            icon: 'policy',
            path: '/dashboard/policy-mgmt',
            features: [
                'Policy Repository',
                'Policy Creation',
                'Approval Workflow',
                'Policy Distribution',
                'Acknowledgement',
                'Policy Updates',
                'Compliance Tracking',
                'Policy FAQs',
            ],
        },
        {
            code: 'POSITION_BUDGETING',
            label: 'Position Budgeting',
            icon: 'positionBudgeting',
            path: '/dashboard/position-budgeting',
            features: [
                'Position Creation',
                'Budget Allocation',
                'Vacancy Tracking',
                'Position History',
                'Position Freeze',
                'Position Transfer',
                'Budget vs Actual',
                'Position Analytics',
            ],
        },
        {
            code: 'RECRUITMENT',
            label: 'Recruitment',
            icon: 'recruitment',
            path: '/dashboard/recruitment',
            features: [
                'Job Requisition',
                'Job Posting',
                'Career Site',
                'Application Tracking',
                'Resume Parsing',
                'Candidate Screening',
                'Interview Management',
                'Assessment Tests',
                'Interview Feedback',
                'Offer Management',
                'Background Verification',
                'Recruitment Analytics',
                'Talent Pool',
            ],
        },
        {
            code: 'REMOTE_WORK',
            label: 'Remote Work',
            icon: 'remoteWork',
            path: '/dashboard/remote-work',
            features: [
                'Remote Policy',
                'Equipment Tracking',
                'Virtual Onboarding',
                'Productivity Tracking',
                'Communication Tools',
                'Virtual Team Building',
                'Expense Management',
                'Well-being Support',
            ],
        },
        {
            code: 'REPORTS',
            label: 'Reports',
            icon: 'reports',
            path: '/dashboard/analytics',
            features: [
                'Standard Reports',
                'Custom Reports',
                'Dashboard Builder',
                'Scheduled Reports',
                'Export Options',
                'Real-time Analytics',
                'Drill-down Reports',
                'Cross-module Reports',
                'Compliance Reports',
                'Executive Dashboards',
                'Predictive Analytics',
                'Report Security',
            ],
        },
        {
            code: 'SUCCESSION_PLANNING',
            label: 'Succession Planning',
            icon: 'succession',
            path: '/dashboard/succession-planning',
            features: [
                'Critical Positions',
                'Talent Matrix',
                'Successor Identification',
                'Development Planning',
                'Emergency Succession',
                'Talent Review',
                'Career Pathing',
                'Succession Analytics',
            ],
        },
        {
            code: 'TRAVEL',
            label: 'Travel',
            icon: 'travel',
            path: '/dashboard/travel',
            features: [
                'Travel Request',
                'Travel Policy',
                'Booking Integration',
                'Advance Request',
                'Expense Claims',
                'Per Diem',
                'Travel Insurance',
                'Visa Support',
                'Travel Dashboard',
                'Travel History',
                'Mileage Tracking',
                'Travel Analytics',
                'Dashboard',
            ],
        },
        {
            code: 'USER_MANAGEMENT',
            label: 'User Management',
            icon: 'userManagement',
            path: '/dashboard/user-management',
            features: [
                'Users',
                'Role Management',
                'Access Control',
                'Password Policy',
                'Single Sign-On',
                'Session Management',
                'Audit Trail',
                'User Delegation',
                'License Management',
                'User Deactivation',
                'Profile Management',
                'Multi-Factor Auth',
            ],
        },
        {
            code: 'INDUSTRY_SOLUTIONS',
            label: 'Industry Solutions',
            icon: 'briefcase',
            path: '/dashboard/industry-solutions',
            features: [
                'Collaboration',
                'Manufacturing',
                'Healthcare',
                'Retail',
                'Education',
                'Government',
                'Agriculture',
                'Mining & Resources',
                'Hospitality',
                'Automotive',
                'Aviation',
                'Maritime',
                'Nonprofit / NGO',
                'Logistics',
            ],
            items: [
                {
                    code: 'COLLABORATION',
                    label: 'Collaboration',
                    icon: 'users',
                    path: '/dashboard/industry/collaboration',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'MANUFACTURING',
                    label: 'Manufacturing',
                    icon: 'factory',
                    path: '/dashboard/industry/manufacturing',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'HEALTHCARE',
                    label: 'Healthcare',
                    icon: 'activity',
                    path: '/dashboard/industry/healthcare',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'RETAIL',
                    label: 'Retail',
                    icon: 'shoppingBag',
                    path: '/dashboard/industry/retail',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'EDUCATION',
                    label: 'Education',
                    icon: 'graduationCap',
                    path: '/dashboard/industry/education',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'GOVERNMENT',
                    label: 'Government',
                    icon: 'building',
                    path: '/dashboard/industry/government',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'AGRICULTURE',
                    label: 'Agriculture',
                    icon: 'leaf',
                    path: '/dashboard/industry/agriculture',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'MINING_RESOURCES',
                    label: 'Mining & Resources',
                    icon: 'pickaxe',
                    path: '/dashboard/industry/mining',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'HOSPITALITY',
                    label: 'Hospitality',
                    icon: 'coffee',
                    path: '/dashboard/industry/hospitality',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'AUTOMOTIVE',
                    label: 'Automotive',
                    icon: 'car',
                    path: '/dashboard/industry/automotive',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'AVIATION',
                    label: 'Aviation',
                    icon: 'plane',
                    path: '/dashboard/industry/aviation',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'MARITIME',
                    label: 'Maritime',
                    icon: 'anchor',
                    path: '/dashboard/industry/maritime',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'NONPROFIT',
                    label: 'Nonprofit / NGO',
                    icon: 'heart',
                    path: '/dashboard/industry/nonprofit',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'LOGISTICS',
                    label: 'Logistics',
                    icon: 'truck',
                    path: '/dashboard/industry/logistics',
                    features: ['Dashboard', 'Settings'],
                },
                // Preserving existing detailed modules
                {
                    code: 'WELLNESS',
                    label: 'Wellness',
                    icon: 'wellness',
                    path: '/dashboard/wellness',
                    features: [
                        'Health Programs',
                        'Mental Health',
                        'Health Risk Assessment',
                        'Wellness Challenges',
                        'Wellness Points',
                        'Gym Membership',
                        'Wellness Dashboard',
                        'Dashboard',
                    ],
                },
                {
                    code: 'WORKFLOW_ENGINE',
                    label: 'Workflow Engine',
                    icon: 'workflow',
                    path: '/dashboard/workflow-engine',
                    features: [
                        'Workflow Designer',
                        'Approval Chains',
                        'Conditional Logic',
                        'Email Notifications',
                        'Escalation Rules',
                        'Form Builder',
                        'Integration Points',
                        'Workflow Templates',
                        'Workflow Analytics',
                        'Version Control',
                        'Testing Mode',
                        'Audit Log',
                    ],
                },
                {
                    code: 'WORKFORCE_PLANNING',
                    label: 'Workforce Planning',
                    icon: 'workforcePlanning',
                    path: '/dashboard/workforce-planning',
                    features: [
                        'Demand Forecasting',
                        'Supply Analysis',
                        'Gap Analysis',
                        'Scenario Modeling',
                        'Workforce Costs',
                        'Succession Readiness',
                        'Talent Acquisition Plan',
                        'Workforce Analytics',
                    ],
                },
            ],
        },

        {
            code: 'MASTER_DATA',
            label: 'Master Data',
            icon: 'settings',
            path: '/dashboard/admin/master-data',
            features: [
                'Companies',
                'Countries',
                'States',
                'Cities',
                'Currencies',
                'Languages',
                'Departments',
                'Designations',
                'Grades',
                'Cost Centers',
                'Business Units',
                'Locations',
                'Employment Types',
                'Employment Statuses',
                'Employment Statuses',
                'Job Families',
                'Job Functions',
                'Job Profiles',
                'Document Types',
                'Banks',
                'Education Levels',
                'Relationships',
                'Exit Reasons',
                'Skills',
                'Competencies',
                'Leave Types',
                'Shift Types',
                'Holidays',
                'Tax Regimes',
                'Pay Components',
                'Roles & Permissions',
                'System Settings',
            ],
        },
        {
            code: 'ADMIN_CONSOLE',
            label: 'Admin',
            icon: 'settings',
            path: '/dashboard/admin',
            items: [
                {
                    code: 'ADMIN_MASTER_DATA',
                    label: 'Master Data',
                    icon: 'settings',
                    path: '/dashboard/admin/master-data',
                    features: ['Companies', 'Locations', 'Job Families', 'Grades', 'Roles & Permissions'],
                },
                {
                    code: 'ADMIN_INTEGRATIONS',
                    label: 'Integrations',
                    icon: 'orgDesign',
                    path: '/dashboard/admin/integrations',
                    features: ['App Directory', 'API Marketplace', 'Webhooks'],
                },
                {
                    code: 'ADMIN_AI',
                    label: 'AI & Automation',
                    icon: 'ai',
                    path: '/dashboard/admin/ai',
                    features: ['Workflows', 'Copilot', 'Predictions'],
                },
                {
                    code: 'ADMIN_WORKFLOWS',
                    label: 'Workflows',
                    icon: 'workflow',
                    path: '/dashboard/admin/workflows',
                    features: ['Designer', 'Routing Rules', 'Approvals'],
                },
                {
                    code: 'ADMIN_COMPLIANCE',
                    label: 'Compliance & Audit',
                    icon: 'policy',
                    path: '/dashboard/admin/compliance/audit',
                    features: ['Audit Logs', 'Data Retention', 'Policy Acknowledgement'],
                },
                {
                    code: 'ADMIN_DOCUMENTS',
                    label: 'Documents',
                    icon: 'policy',
                    path: '/dashboard/admin/documents',
                    features: ['Templates', 'Document Governance', 'Access Control'],
                },
                {
                    code: 'ADMIN_STATIONERY',
                    label: 'Stationery',
                    icon: 'policy',
                    path: '/dashboard/admin/stationery',
                    features: ['Branding', 'ID Cards', 'Letterheads'],
                },
                {
                    code: 'ADMIN_ASSETS',
                    label: 'Assets',
                    icon: 'compensation',
                    path: '/dashboard/admin/assets',
                    features: ['Asset Catalog', 'Assignments', 'Audits'],
                },
                {
                    code: 'ADMIN_PAYROLL',
                    label: 'Payroll Settings',
                    icon: 'payroll',
                    path: '/dashboard/admin/payroll/settings',
                    features: ['Bank Integration', 'Payroll Policies'],
                },
                {
                    code: 'ADMIN_TRAVEL',
                    label: 'Travel',
                    icon: 'travel',
                    path: '/dashboard/admin/travel',
                    features: ['Travel Policies', 'Rates', 'Vendors'],
                },
                {
                    code: 'ADMIN_SYSTEM',
                    label: 'System',
                    icon: 'settings',
                    path: '/dashboard/admin/system/health',
                    features: ['Health', 'Localization', 'Notifications', 'Import/Export'],
                },
            ],
            features: [
                'Master Data',
                'Integrations',
                'Documents',
                'Stationery',
                'Assets',
                'Travel',
            ],
        },
    ],
};
