/**
 * @reference docs/aura-master-instructions.md
 */

export type MenuModule = {
  code: string;
  label: string;
  icon: string;
  path?: string;
  permissions?: string[];
  featureFlag?: string;
  features: string[];
};

export type MenuDefinition = {
  role: 'SUPER_ADMIN';
  menuName: string;
  items: MenuModule[];
};

export const superAdminMenu: MenuDefinition = {
  role: 'SUPER_ADMIN',
  menuName: 'CONSTELLATION_FULL',
  items: [
    {
      code: 'AI_AUTOMATION',
      label: 'AI & Automation',
      icon: 'ai',
      features: [
        'Org Health Predictor',
        'AI Coaching Bot',
        'Workflow Generator',
        'Resume Screening',
        'Attrition Prediction',
        'Leave Forecasting',
        'Anomaly Detection',
        'Chatbot',
        'Interview Scheduling',
        'Performance Analysis',
        'L&D Recommendation',
        'Job Matching',
        'Email Parsing',
        'Auto Accruals',
        'NLP Insights',
      ],
    },
    {
      code: 'ATTENDANCE',
      label: 'Attendance',
      icon: 'attendance',
      features: [
        'Shift Management',
        'Roster Assignment',
        'Time Capture',
        'Punch Rules',
        'Geo-Fencing',
        'IP Restriction',
        'Attendance Exceptions',
        'Regularization Request',
        'Work From Home',
        'Comp-off Management',
        'Overtime Management',
        'Time Rounding',
        'Approval Workflow',
      ],
    },
    {
      code: 'AUDIT_SECURITY',
      label: 'Audit & Security',
      icon: 'security',
      features: [
        'Audit Logs',
        'Login Logs',
        'Role-based Access',
        'Field-level Security',
        'Dual Authentication',
        'Document Access Logs',
        'Compliance Tracker',
        'Policy Acknowledgement',
        'Approval Logs',
        'GDPR Tools',
        'Alert Rules',
        'Data Retention',
      ],
    },
    {
      code: 'BENEFITS',
      label: 'Benefits',
      icon: 'benefits',
      features: [
        'Benefit Types',
        'Plan Eligibility',
        'Enrollment Window',
        'Dependent Management',
        'Insurance Coverage',
        'Premium Sharing',
        'Claims',
        'Claim Status',
        'Provider Directory',
        'Notification',
        'Exception Handling',
        'Reporting',
      ],
    },
    {
      code: 'CAREER_PLANNING',
      label: 'Career Planning',
      icon: 'career',
      features: [
        'Career Ladders',
        'Internal Mobility',
        'Career Goals',
        'Aspirations',
      ],
    },
    {
      code: 'CHATBOT_BUILDER',
      label: 'Chatbot Builder',
      icon: 'chatbot',
      features: [
        'Dialogue Designer',
        'Entity Management',
        'Intent Library',
        'Training Data',
        'Multi-Channel',
        'Analytics Dashboard',
        'Handoff Rules',
        'Multi-lingual',
      ],
    },
    {
      code: 'COMPENSATION',
      label: 'Compensation',
      icon: 'compensation',
      features: [
        'Salary Structure',
        'Grade & Bands',
        'Increment Planning',
        'Bonus Management',
        'Stock Options',
        'Loan & Advances',
        'Arrears Processing',
        'Total Rewards',
        'Market Benchmarking',
        'Budget Simulation',
      ],
    },
    {
      code: 'COMPETENCY_LIBRARY',
      label: 'Competency Library',
      icon: 'competency',
      features: [
        'Competency Catalog',
        'Proficiency Levels',
        'Job-Competency Map',
        'Skill Assessment',
        'Gap Analysis',
      ],
    },
    {
      code: 'CONTRACT_WORKFORCE',
      label: 'Contract Workforce',
      icon: 'contract',
      features: [
        'Vendor Management',
        'Contract Types',
        'Rate Cards',
        'Timesheet',
        'Invoice Processing',
        'Compliance Docs',
        'Contract Renewal',
        'Performance Rating',
      ],
    },
    {
      code: 'CORE_HR',
      label: 'Core HR',
      icon: 'coreHr',
      features: [
        'Employee Database',
        'Organization Structure',
        'Employment History',
        'Document Management',
        'Position Management',
        'Cost Center',
        'Employee Life Events',
        'Mass Updates',
        'Employee ID Cards',
        'Letter Generation',
        'Exit Management',
        'Anniversary Alerts',
        'Auto-Numbering',
        'Probation Tracking',
        'Confirmation Letters',
      ],
    },
    {
      code: 'DEI',
      label: 'DEI',
      icon: 'dei',
      features: [
        'Diversity Metrics',
        'Inclusion Survey',
        'Pay Equity Analysis',
        'Bias Training',
        'ERG Management',
        'Mentorship Program',
        'Accessibility',
        'DEI Goals',
      ],
    },
    {
      code: 'ESS',
      label: 'ESS',
      icon: 'ess',
      features: [
        'Personal Info Update',
        'Leave Application',
        'Payslip Access',
        'Tax Declaration',
        'Attendance View',
        'Team Directory',
        'Request Center',
        'My Documents',
      ],
    },
    {
      code: 'EMPLOYEE_ENGAGEMENT',
      label: 'Employee Engagement',
      icon: 'engagementEmployee',
      features: [
        'Pulse Surveys',
        'Recognition Wall',
        'Suggestion Box',
      ],
    },
    {
      code: 'ENGAGEMENT',
      label: 'Engagement',
      icon: 'engagement',
      features: [
        'Event Calendar',
        'Birthday/Anniversary',
        'Newsletter',
        'Polls & Quizzes',
        'Social Feed',
        'Rewards Catalog',
        'Referral Program',
        'CSR Activities',
      ],
    },
    {
      code: 'GAMIFICATION',
      label: 'Gamification',
      icon: 'gamification',
      features: [
        'Points System',
        'Leaderboards',
        'Badges',
        'Challenges',
        'Levels & Tiers',
        'Missions',
        'Virtual Currency',
        'Achievement Wall',
      ],
    },
    {
      code: 'HEALTH_SAFETY',
      label: 'Health & Safety',
      icon: 'healthSafety',
      features: [
        'Incident Reporting',
        'Safety Training',
        'Health Checkups',
        'Emergency Contacts',
        'COVID Tracker',
      ],
    },
    {
      code: 'HR_BUDGETING',
      label: 'HR Budgeting',
      icon: 'hrBudgeting',
      features: [
        'Headcount Planning',
        'Salary Budgets',
        'Cost Projections',
        'Budget vs Actual',
        'Scenario Planning',
        'Department Allocation',
        'Approval Workflow',
        'Budget Templates',
      ],
    },
    {
      code: 'HR_HELPDESK',
      label: 'HR Helpdesk',
      icon: 'hrHelpdesk',
      features: [
        'Ticket Management',
        'SLA Tracking',
        'Knowledge Base',
        'Agent Assignment',
        'Escalation Matrix',
        'Customer Satisfaction',
        'Canned Responses',
        'Analytics',
      ],
    },
    {
      code: 'HRSD',
      label: 'HRSD',
      icon: 'hrsd',
      features: [
        'Service Catalog',
        'Request Portal',
        'Case Management',
        'Service Automation',
        'Chat Support',
        'Omnichannel',
        'Performance Metrics',
        'Continuous Improvement',
      ],
    },
    {
      code: 'JOB_LIBRARY',
      label: 'Job Library',
      icon: 'jobLibrary',
      features: [
        'Job Catalog',
        'Job Families',
        'Job Evaluation',
        'Market Pricing',
        'Job Posting Templates',
      ],
    },
    {
      code: 'LEARNING_DEVELOPMENT',
      label: 'L&D',
      icon: 'learning',
      features: [
        'Course Catalog',
        'Learning Paths',
        'Training Calendar',
        'Enrollment',
        'Attendance Tracking',
        'Assessment Engine',
        'Certifications',
        'External Training',
        'Training Feedback',
        'Skill Gap Analysis',
        'Training Budget',
        'Vendor Management',
        'E-Learning Platform',
        'Mentoring',
        'Knowledge Repository',
        'Compliance Training',
        'ROI Measurement',
      ],
    },
    {
      code: 'LABOR_RELATIONS',
      label: 'Labor Relations',
      icon: 'labor',
      features: [
        'Union Database',
        'Grievance Management',
        'Collective Bargaining',
        'Disciplinary Actions',
        'Labor Law Compliance',
        'Strike Management',
        'Arbitration',
        'Communication Log',
      ],
    },
    {
      code: 'LEAVE',
      label: 'Leave',
      icon: 'leave',
      features: [
        'Leave Types',
        'Leave Policy',
        'Leave Balance',
        'Leave Application',
        'Leave Calendar',
        'Holiday Management',
        'Leave Encashment',
        'Carry Forward',
        'Comp-off Tracking',
        'Leave Reports',
      ],
    },
    {
      code: 'LOCALIZATION',
      label: 'Localization',
      icon: 'localization',
      features: [
        'Multi-Currency',
        'Multi-Language',
        'Country-Specific Fields',
        'Tax Regimes',
        'Statutory Compliance',
        'Date/Time Formats',
        'Calendar Types',
        'Bank Integration',
        'Government Reports',
        'Regional Holidays',
        'Address Formats',
      ],
    },
    {
      code: 'MOBILE_APP',
      label: 'Mobile App',
      icon: 'mobile',
      features: [
        'Native Apps',
        'Push Notifications',
        'Offline Mode',
        'Biometric Login',
        'GPS Attendance',
        'Mobile Approvals',
        'Document Upload',
        'Team View',
        'Expense Claims',
        'Mobile Timesheets',
        'Quick Actions',
        'Voice Commands',
        'Mobile Analytics',
        'Chat/Messaging',
        'Profile Management',
      ],
    },
    {
      code: 'MSS',
      label: 'MSS',
      icon: 'mss',
      features: [
        'Team Dashboard',
        'Approval Center',
        'Team Reports',
        'Delegation',
      ],
    },
    {
      code: 'OFFBOARDING',
      label: 'Offboarding',
      icon: 'offboarding',
      features: [
        'Exit Process',
        'Exit Interview',
        'Clearance Checklist',
        'F&F Settlement',
      ],
    },
    {
      code: 'ONBOARDING',
      label: 'Onboarding',
      icon: 'onboarding',
      features: [
        'Pre-boarding',
        'First Day Experience',
        'Induction Program',
        'Buddy Assignment',
        '30-60-90 Day Plan',
      ],
    },
    {
      code: 'ORG_DESIGN',
      label: 'Org Design',
      icon: 'orgDesign',
      features: [
        'Org Chart Builder',
        'Scenario Planning',
        'Span of Control',
        'Position Hierarchy',
        'Matrix Structure',
        'Succession Pool',
        'Org Analytics',
        'Change Management',
      ],
    },
    {
      code: 'PAYROLL',
      label: 'Payroll',
      icon: 'payroll',
      features: [
        'Payroll Processing',
        'Tax Calculation',
        'Statutory Deductions',
        'Bank File Generation',
        'Payslip Generation',
        'Reimbursements',
        'Loan Recovery',
        'Arrears Management',
        'Bonus Processing',
        'Year-end Processing',
        'Multi-State Payroll',
        'Payroll Reconciliation',
        'Garnishments',
        'Off-cycle Payments',
        'Payroll Reports',
        'Additional Tasks (per doc)',
      ],
    },
    {
      code: 'PERFORMANCE',
      label: 'Performance',
      icon: 'performance',
      features: [
        'Goal Setting',
        'Review Cycles',
        'Self-Assessment',
        'Manager Assessment',
        '360 Feedback',
        'Continuous Feedback',
        'Rating Scales',
        'Bell Curve',
        'Calibration',
        '1-on-1 Meetings',
        'PIP Management',
        'Competency Assessment',
        'Development Plans',
        'Performance Analytics',
        'Reward Linkage',
      ],
    },
    {
      code: 'POLICY_MGMT',
      label: 'Policy Mgmt',
      icon: 'policy',
      features: [
        'Policy Repository',
        'Policy Creation',
        'Approval Workflow',
        'Policy Distribution',
        'Acknowledgement',
        'Policy Updates',
        'Compliance Tracking',
        'Policy FAQs',
      ],
    },
    {
      code: 'POSITION_BUDGETING',
      label: 'Position Budgeting',
      icon: 'positionBudgeting',
      features: [
        'Position Creation',
        'Budget Allocation',
        'Vacancy Tracking',
        'Position History',
        'Position Freeze',
        'Position Transfer',
        'Budget vs Actual',
        'Position Analytics',
      ],
    },
    {
      code: 'RECRUITMENT',
      label: 'Recruitment',
      icon: 'recruitment',
      features: [
        'Job Requisition',
        'Job Posting',
        'Career Site',
        'Application Tracking',
        'Resume Parsing',
        'Candidate Screening',
        'Interview Management',
        'Assessment Tests',
        'Interview Feedback',
        'Offer Management',
        'Background Verification',
        'Recruitment Analytics',
        'Talent Pool',
      ],
    },
    {
      code: 'REMOTE_WORK',
      label: 'Remote Work',
      icon: 'remoteWork',
      features: [
        'Remote Policy',
        'Equipment Tracking',
        'Virtual Onboarding',
        'Productivity Tracking',
        'Communication Tools',
        'Virtual Team Building',
        'Expense Management',
        'Well-being Support',
      ],
    },
    {
      code: 'REPORTS',
      label: 'Reports',
      icon: 'reports',
      features: [
        'Standard Reports',
        'Custom Reports',
        'Dashboard Builder',
        'Scheduled Reports',
        'Export Options',
        'Real-time Analytics',
        'Drill-down Reports',
        'Cross-module Reports',
        'Compliance Reports',
        'Executive Dashboards',
        'Predictive Analytics',
        'Report Security',
      ],
    },
    {
      code: 'SUCCESSION_PLANNING',
      label: 'Succession Planning',
      icon: 'succession',
      features: [
        'Critical Positions',
        'Talent Matrix',
        'Successor Identification',
        'Development Planning',
        'Emergency Succession',
        'Talent Review',
        'Career Pathing',
        'Succession Analytics',
      ],
    },
    {
      code: 'TRAVEL',
      label: 'Travel',
      icon: 'travel',
      features: [
        'Travel Request',
        'Travel Policy',
        'Booking Integration',
        'Advance Request',
        'Expense Claims',
        'Per Diem',
        'Travel Insurance',
        'Visa Support',
        'Travel Dashboard',
        'Travel History',
        'Mileage Tracking',
        'Travel Analytics',
      ],
    },
    {
      code: 'USER_MANAGEMENT',
      label: 'User Management',
      icon: 'userManagement',
      features: [
        'User Creation',
        'Role Management',
        'Access Control',
        'Password Policy',
        'Single Sign-On',
        'Session Management',
        'Audit Trail',
        'User Delegation',
        'License Management',
        'User Deactivation',
        'Profile Management',
        'Multi-Factor Auth',
      ],
    },
    {
      code: 'WELLNESS',
      label: 'Wellness',
      icon: 'wellness',
      features: [
        'Health Programs',
        'Mental Health',
        'Health Risk Assessment',
        'Wellness Challenges',
        'Wellness Points',
        'Gym Membership',
        'Wellness Dashboard',
      ],
    },
    {
      code: 'WORKFLOW_ENGINE',
      label: 'Workflow Engine',
      icon: 'workflow',
      features: [
        'Workflow Designer',
        'Approval Chains',
        'Conditional Logic',
        'Email Notifications',
        'Escalation Rules',
        'Form Builder',
        'Integration Points',
        'Workflow Templates',
        'Workflow Analytics',
        'Version Control',
        'Testing Mode',
        'Audit Log',
      ],
    },
    {
      code: 'WORKFORCE_PLANNING',
      label: 'Workforce Planning',
      icon: 'workforcePlanning',
      features: [
        'Demand Forecasting',
        'Supply Analysis',
        'Gap Analysis',
        'Scenario Modeling',
        'Workforce Costs',
        'Succession Readiness',
        'Talent Acquisition Plan',
        'Workforce Analytics',
      ],
    },
  ],
};
