/**
 * @reference docs/aura-master-instructions.md
 */

export type MenuModule = {
    code: string;
    label: string;
    icon: string;
    path?: string;
    permissions?: string[];
    featureFlag?: string;
    feature?: string[]; // Legacy support during migration if needed, but 'features' is the main one
    features: string[];
    items?: MenuModule[];
};

export type MenuDefinition = {
    role: 'SUPER_ADMIN';
    menuName: string;
    items: MenuModule[];
};

export const superAdminMenu: MenuDefinition = {
    role: 'SUPER_ADMIN',
    menuName: 'CONSTELLATION_FULL',
    items: [
        {
            code: 'AI_AUTOMATION',
            label: 'AI & Automation',
            icon: 'ai',
            path: '/dashboard/ai-automation',
            features: [
                'AI Analytics',
                'Org Health Predictor',
                'AI Coaching Bot',
                'Workflow Generator',
                'Resume Screening',
                'Attrition Prediction',
                'Leave Forecasting',
                'Anomaly Detection',
                'Chatbot',
                'Interview Scheduling',
                'Performance Analysis',
                'L&D Recommendation',
                'Job Matching',
                'Job Boards',
                'Email Parsing',
                'Auto Accruals',
                'NLP Insights',
            ],
        },
        {
            code: 'AGENTS',
            label: 'Agents',
            icon: 'ai',
            path: '/dashboard/agents',
            features: [
                'Overview',
                'HR Agent',
                'Recruitment Agent',
                'Analytics Agent',
                'Metrics',
            ],
        },
        {
            code: 'ATTENDANCE',
            label: 'Attendance',
            icon: 'attendance',
            path: '/dashboard/attendance',
            features: [
                'Time Capture',
                'Timesheets',
                'Shift Management',
                'Roster Assignment',
                'Shift Swapping',
                'Attendance Exceptions',
                'Regularization',
                'Regularization Request',
                'Overtime',
                'Overtime Management',
                'Comp-off',
                'Comp-off Management',
                'Punch Rules',
                'Rules',
                'Time Rounding',
                'Geo-Fencing',
                'IP Restriction',
                'Field Force',
                'Work From Home',
                'Approval Workflow',
            ],
        },
        {
            code: 'AUDIT_SECURITY',
            label: 'Audit & Security',
            icon: 'security',
            path: '/dashboard/security',
            features: [
                'Audit Logs',
                'Login Logs',
                'Role-based Access',
                'Field-level Security',
                'Dual Authentication',
                'Document Access Logs',
                'Compliance Tracker',
                'Policy Acknowledgement',
                'Approval Logs',
                'GDPR Tools',
                'Alert Rules',
                'Data Retention',
            ],
        },
        {
            code: 'BENEFITS',
            label: 'Benefits',
            icon: 'benefits',
            path: '/dashboard/benefits',
            features: [
                'Benefit Types',
                'Plan Eligibility',
                'Enrollment Window',
                'Benefits Enrollment',
                'Dependent Management',
                'Insurance Coverage',
                'Premium Sharing',
                'Claims',
                'Claim Status',
                'HSA FSA',
                'Retirement',
                'Wellness Tracker',
                'Perks Marketplace',
                'Provider Directory',
                'Notification',
                'Exception Handling',
                'Reporting',
            ],
        },
        {
            code: 'CAREER_PLANNING',
            label: 'Career Planning',
            icon: 'career',
            path: '/dashboard/career',
            features: [
                'Career Ladders',
                'Internal Mobility',
                'Career Goals',
                'Aspirations',
            ],
        },
        {
            code: 'CHATBOT_BUILDER',
            label: 'Chatbot Builder',
            icon: 'chatbot',
            path: '/dashboard/chatbot-builder',
            features: [
                'Dialogue Designer',
                'Entity Management',
                'Intent Library',
                'Training Data',
                'Multi-Channel',
                'Analytics Dashboard',
                'Handoff Rules',
                'Multi-lingual',
            ],
        },
        {
            code: 'COMPENSATION',
            label: 'Compensation',
            icon: 'compensation',
            path: '/dashboard/compensation',
            features: [
                'Salary Structure',
                'Grade & Bands',
                'Increment Planning',
                'Compensation Planning',
                'Bonus Management',
                'Stock Options',
                'Equity Management',
                'Loan & Advances',
                'Arrears Processing',
                'Total Rewards',
                'Market Benchmarking',
                'Budget Simulation',
                'Loans',
                'Expense Reimbursement',
            ],
        },
        {
            code: 'COMPLIANCE',
            label: 'Compliance',
            icon: 'labor',
            path: '/dashboard/compliance',
            features: [
                'Labor Law Compliance',
                'Statutory Compliance',
                'Compliance Tracker',
                'Policy Acknowledgement',
                'Audit Trail',
                'GDPR Tools',
                'Data Retention',
                'Regulatory Reports',
            ],
        },
        {
            code: 'GCC_COMPLIANCE',
            label: 'GCC Compliance',
            icon: 'localization',
            path: '/dashboard/gcc-landscape',
            features: [
                'GCC Landscape',
                'Country Rule Library',
                'Compliance Calendar',
                'Checklist & Red-Flag Engine',
                'KPI Scorecard',
                'Wage Protection (WPS)',
                'GOSI (KSA)',
                'GPSSA (UAE)',
                'SIO (Bahrain)',
                'Emiratisation (UAE)',
                'Nitaqat (Saudization)',
            ],
            items: [
                {
                    code: 'EXECUTIVE_COMPLIANCE',
                    label: 'Executive Compliance Rollup',
                    icon: 'dashboard',
                    path: '/dashboard/executive-compliance',
                    features: [
                        '21-Domain RAG Status Grid',
                        'Compliance Risk Heatmap (L × I)',
                        'Corrective Action Register',
                        'Compliance Review Calendar',
                        'Executive Monthly Certificate',
                    ],
                },
                {
                    code: 'GCC_LANDSCAPE',
                    label: 'GCC Landscape',
                    icon: 'dashboard',
                    path: '/dashboard/gcc-landscape',
                    features: [
                        'Executive Landscape',
                        'Countries & Entities',
                        'Country Reference Dataset',
                        'Workforce Classification',
                        'Platform Alerts',
                        'GCC Personas / RBAC',
                        'Compliance Risk Register',
                        'Workforce KPI Baseline',
                        'Digital Maturity Scorecard',
                    ],
                },
                {
                    code: 'GCC_RULE_LIBRARY',
                    label: 'Country Rule Library',
                    icon: 'policy',
                    path: '/dashboard/gcc-rule-library',
                    features: [
                        'Rule Packs (UAE/KSA/BH/QA/OM/KW)',
                        'GCC Comparison Tables',
                        'Country Risk Matrix',
                        'Monthly Country Certificate',
                        'Rule Change Requests (Maker-Checker, Rollback)',
                    ],
                },
                {
                    code: 'COMPLIANCE_CALENDAR',
                    label: 'Compliance Calendar',
                    icon: 'leave',
                    path: '/dashboard/compliance-calendar',
                    features: [
                        'Task Register',
                        'Recurrence Rules',
                        'Annual Audit Plan',
                        'Monthly Calendar Certificate',
                    ],
                },
                {
                    code: 'CHECKLIST_ENGINE',
                    label: 'Checklist & Red-Flag Engine',
                    icon: 'policy',
                    path: '/dashboard/checklist-engine',
                    features: [
                        'Checklist Templates',
                        'Run Workspace',
                        'Red Flags',
                        'Exception Register',
                        'Compliance Certificates',
                    ],
                },
                {
                    code: 'KPI_SCORECARD',
                    label: 'KPI Scorecard',
                    icon: 'reports',
                    path: '/dashboard/kpi-scorecard',
                    features: [
                        'KPI Catalogue',
                        'Threshold Library',
                        'Executive Scorecard',
                        'Monthly KPI Certificate',
                    ],
                },
                {
                    code: 'WPS_COMPLIANCE',
                    label: 'Wage Protection (WPS)',
                    icon: 'payroll',
                    path: '/dashboard/wps-compliance',
                    features: [
                        'WPS Submissions',
                        'Exceptions & Delay Flags',
                        'Penalties Register',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'GOSI_COMPLIANCE',
                    label: 'GOSI (KSA)',
                    icon: 'benefits',
                    path: '/dashboard/gosi-compliance',
                    features: [
                        'Employee Registrations',
                        'Wages & Contributions',
                        'Reconciliation & Variance',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'GPSSA_COMPLIANCE',
                    label: 'GPSSA (UAE)',
                    icon: 'benefits',
                    path: '/dashboard/gpssa-compliance',
                    features: [
                        'Registrations & Transfers',
                        'Wages & Contributions',
                        'Reconciliation',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'SIO_COMPLIANCE',
                    label: 'SIO (Bahrain)',
                    icon: 'benefits',
                    path: '/dashboard/sio-compliance',
                    features: [
                        'Registrations',
                        'Wages & Contributions',
                        'Reconciliation',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'EMIRATISATION_COMPLIANCE',
                    label: 'Emiratisation (UAE)',
                    icon: 'localization',
                    path: '/dashboard/emiratisation-compliance',
                    features: [
                        'Establishment Scope',
                        'Annual Targets',
                        'Hires & Evidence',
                        'Checkpoint Snapshots',
                        'Fines',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'NITAQAT_COMPLIANCE',
                    label: 'Nitaqat / Saudization',
                    icon: 'localization',
                    path: '/dashboard/nitaqat-compliance',
                    features: [
                        'Establishment Scope',
                        'Band Thresholds',
                        'Hires',
                        'Band Snapshots',
                        'Privilege Check',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'HSE_VISA_EXTENSIONS',
                    label: 'HSE + Visa-Exit Extensions',
                    icon: 'reports',
                    path: '/dashboard/hse-visa-extensions',
                    features: [
                        'Safety Officer Registry · Heat-Stress Rules · Toolbox Talks',
                        'Emergency Drill Tracker · First-Aid Stations · Welfare Inspections',
                        'Visa-Exit Dependents Register (cascade)',
                        'Visa-Exit Benefits Closure (insurance/accommodation/EOS/loan)',
                        'Visa-Exit Comm Templates (bilingual) · TRANSFER PRO chain',
                    ],
                },
                {
                    code: 'WORKFORCE_EXTENSIONS',
                    label: 'Workforce Extensions',
                    icon: 'localization',
                    path: '/dashboard/workforce-extensions',
                    features: [
                        'Contractor Assignments (Attendance/Holidays/Accommodation/HSE)',
                        'Employee Loans + Salary Advances (with amortization)',
                        'Uniform / PPE / Tools Issuance Register',
                        'Accommodation Transport Routes · Clinics · Maintenance Tickets',
                    ],
                },
                {
                    code: 'COMPLIANCE_AUDIT_REGISTER',
                    label: 'Audit Checklist + Risk Register',
                    icon: 'reports',
                    path: '/dashboard/compliance-audit-register',
                    features: [
                        'Checklist Items (ER · Disciplinary · Separation · EOSB · Visa-Exit)',
                        'Risk Register with L × I → band auto-derivation',
                        'Per-domain default seeds',
                        'Mandatory item completion enforcement',
                    ],
                },
                {
                    code: 'NATIONALISATION_OVERLAY',
                    label: 'Nationalisation Overlays',
                    icon: 'localization',
                    path: '/dashboard/nationalisation-overlay',
                    features: [
                        'TA Pipeline Tags · Requisition + Job/Position',
                        'Retention Ledger · Early-Attrition Tracker',
                        'National L&D Plans',
                        'Fake / Artificial Detection (GPSSA × Payroll × WPS)',
                        'Saudi Profession-Localisation Codes (S09)',
                    ],
                },
                {
                    code: 'BAHRAINIZATION_COMPLIANCE',
                    label: 'Bahrainization',
                    icon: 'localization',
                    path: '/dashboard/bahrainization-compliance',
                    features: [
                        'Establishment Scope',
                        'Sector × Size Targets',
                        'Bahraini Hires & Artificial-Risk',
                        'Ratio Snapshots & LMRA Gating',
                        'Tender Eligibility',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'OVERTIME_COMPLIANCE',
                    label: 'Overtime (GCC)',
                    icon: 'leave',
                    path: '/dashboard/overtime-compliance',
                    features: [
                        'OT Policies (country × grade)',
                        'Rate Cards (country × OT type)',
                        'Requests & Approval',
                        'Actuals & Fraud Detection',
                        'Budget Control',
                        'Monthly Certificate',
                    ],
                },
                {
                    code: 'EOSB_COMPLIANCE',
                    label: 'End-of-Service Benefits',
                    icon: 'payroll',
                    path: '/dashboard/eosb-compliance',
                    features: [
                        'Finalized Calculations (DRAFT→APPROVED→SETTLED)',
                        'Monthly Accruals & GL Posting',
                        'Dispute Register',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'VISA_EXIT_COMPLIANCE',
                    label: 'Visa / Immigration Exit',
                    icon: 'policy',
                    path: '/dashboard/visa-exit-compliance',
                    features: [
                        'Exit Case Orchestration (auto-seed PRO actions)',
                        'PRO Action Register',
                        'Grace Period Register',
                        'Authority Portal Evidence',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'DOCUMENT_RETENTION_COMPLIANCE',
                    label: 'Document Retention & HR Audit',
                    icon: 'reports',
                    path: '/dashboard/document-retention-compliance',
                    features: [
                        'Retention Schedule (per record type × country)',
                        'HR Document Register (auto retentionUntil)',
                        'Litigation Holds',
                        'Disposal Workflow (refuses held / pre-retention docs)',
                        'HR Audit Cycles & Findings',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'BENEFITS_COMPLIANCE',
                    label: 'Employee Benefits (GCC)',
                    icon: 'benefits',
                    path: '/dashboard/benefits-compliance',
                    features: [
                        'Benefit Catalogue (medical, life, ticket, housing, etc.)',
                        'Coverage Register + Renewal + Accrual',
                        'Vendor Management & DPA Tracking',
                        'Exceptions & Mandatory-Gap Detection',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'HR_POLICIES_COMPLIANCE',
                    label: 'HR Policies',
                    icon: 'policy',
                    path: '/dashboard/hr-policies-compliance',
                    features: [
                        'Policy Lifecycle (publish auto-creates 12-month review)',
                        'Acknowledgement Coverage (≥90% required)',
                        'Exception Register',
                        'Scheduled Reviews',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'HR_FORMS_COMPLIANCE',
                    label: 'HR Forms & Templates',
                    icon: 'reports',
                    path: '/dashboard/hr-forms-compliance',
                    features: [
                        'Template Catalogue (8 lifecycle groups, versioned)',
                        'Routing & SLA Config',
                        'Submissions + Approval + E-Signature',
                        'Writeback Status & SLA Breach Detection',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'ATTENDANCE_COMPLIANCE',
                    label: 'Attendance (GCC)',
                    icon: 'leave',
                    path: '/dashboard/attendance-compliance',
                    features: [
                        'Country × Grade Policy (tolerances, SLAs, Ramadan)',
                        'Fraud Register (BUDDY_PUNCH / GEO_MISMATCH / TIME_DRIFT)',
                        'Biometric & Geolocation Consent Register',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'LEAVE_COMPLIANCE',
                    label: 'Leave (GCC)',
                    icon: 'leave',
                    path: '/dashboard/leave-compliance',
                    features: [
                        'Country × Leave Code Entitlement (annual/sick/maternity/Hajj)',
                        'Misuse Register (Monday/Friday pattern, medical forgery)',
                        'Medical Evidence Vault (RESTRICTED + retention)',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'HOLIDAYS_COMPLIANCE',
                    label: 'Holidays (GCC)',
                    icon: 'leave',
                    path: '/dashboard/holidays-compliance',
                    features: [
                        'Country × Holiday Class Pay Rules (base × + OT ×)',
                        'Holiday Work Approval (auto comp-off accrual)',
                        'Comp-Off Ledger (6-month expiry)',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'ACCOMMODATION_COMPLIANCE',
                    label: 'Accommodation & Labour Camps',
                    icon: 'benefits',
                    path: '/dashboard/accommodation-compliance',
                    features: [
                        'Site Master (DORMITORY / LABOUR_CAMP / VILLA)',
                        'Assignment Register (capacity gated)',
                        'Inspection Register (CRITICAL/MAJOR/MINOR findings)',
                        'Complaint Register (48h default SLA)',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'HSE_COMPLIANCE',
                    label: 'Health, Safety & Welfare',
                    icon: 'reports',
                    path: '/dashboard/hse-compliance',
                    features: [
                        'Risk Assessments (L × S → residual band)',
                        'Incident Register (NEAR_MISS → FATALITY + GOSI notify)',
                        'Permit-to-Work (HOT_WORK / CONFINED_SPACE / WAH)',
                        'Training Register with Expiry',
                        'Monthly Compliance Certificate (LTIFR)',
                    ],
                },
                {
                    code: 'ER_COMPLIANCE',
                    label: 'Employee Relations',
                    icon: 'policy',
                    path: '/dashboard/er-compliance',
                    features: [
                        'Grievance Register (multi-channel + SLA)',
                        'Disciplinary Actions (hearing-gated issuance)',
                        'Investigation Register',
                        'Appeals',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'SEPARATION_COMPLIANCE',
                    label: 'Termination & Separation',
                    icon: 'policy',
                    path: '/dashboard/separation-compliance',
                    features: [
                        'Separation Case Orchestration (10 types)',
                        'Exit Clearance Checklist (HR/IT/FIN/SEC/LM/ADMIN)',
                        'Handover & Exit Interview',
                        'Notice / Garden Leave / Buyout Tracking',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'HRMS_CONFIG',
                    label: 'HRMS Configuration',
                    icon: 'settings',
                    path: '/dashboard/hrms-config',
                    features: [
                        'Versioned Country Rule Sets',
                        'Approval Workflow Templates',
                        'Notification Rules (multi-channel, bilingual)',
                        'Audit Trail Capture Policy per Domain',
                        'Config Objects Registry · Maker-Checker (21 domains)',
                        'Implementation Checklist · Go-Live Control Sheet',
                        'Integration Connectors · Health + Secret Rotation',
                        'Data Migration Plans · Run Validation',
                        'Monthly + Go-Live Certificate (with gating)',
                    ],
                },
                {
                    code: 'PAYROLL_GOVERNANCE_COMPLIANCE',
                    label: 'Payroll Governance & Compliance',
                    icon: 'payroll',
                    path: '/dashboard/payroll-compliance',
                    features: [
                        'Governance Controls (8 categories)',
                        'Audit Findings Register',
                        'Payroll Risk Register (L×I bands)',
                        'Monthly Compliance Certificate (Recon/Bank-File/GL)',
                    ],
                },
                {
                    code: 'ORG_COMPLIANCE',
                    label: 'Org & Position Compliance',
                    icon: 'organization',
                    path: '/dashboard/org-compliance',
                    features: [
                        'Org Audit Checklist (13 categories)',
                        'Position Control & Headcount Budget',
                        'Vacancy Register (raise/approve/fill with ageing)',
                        'Monthly Compliance Certificate (Overhire/Aged>90d/Unapproved)',
                    ],
                },
                {
                    code: 'RECORDS_COMPLIANCE',
                    label: 'Employee Records Compliance',
                    icon: 'folder',
                    path: '/dashboard/records-compliance',
                    features: [
                        'Mandatory Document Matrix (country × code)',
                        'Per-Employee Completeness Score (GREEN/AMBER/RED)',
                        'Records Audit Checklist',
                        'Records Risk Register (L×I)',
                        'Monthly Compliance Certificate',
                    ],
                },
                {
                    code: 'TA_COMPLIANCE',
                    label: 'Talent Acquisition Compliance',
                    icon: 'recruitment',
                    path: '/dashboard/talent-acquisition-compliance',
                    features: [
                        'Lifecycle Audit Checklist (5 stages, 25 categories)',
                        'TA Risk Register (L×I bands)',
                        'Stage Breakdown (PLANNING/SOURCING/SELECTION/OFFER/PRE-EMPLOYMENT)',
                        'Monthly TA Compliance Certificate',
                    ],
                },
                {
                    code: 'IMMIGRATION_COMPLIANCE',
                    label: 'Immigration & Work Authorization',
                    icon: 'passport',
                    path: '/dashboard/immigration-compliance',
                    features: [
                        'Country Authorization Matrix (MOHRE/ICP/GDRFA/MHRSD/Qiwa/LMRA/PAM)',
                        'Renewal Alert Ladder (60/30/7-day + EXPIRED)',
                        'Transfer & Mobility Cases (REQUESTED → APPROVED → COMPLETED)',
                        'Immigration Audit Checklist & Risk Register',
                        'Monthly Compliance Certificate',
                    ],
                },
            ],
        },
        {
            code: 'COMPETENCY_LIBRARY',
            label: 'Competency Library',
            icon: 'competency',
            path: '/dashboard/performance/competency-library',
            features: [
                'Competency Catalog',
                'Proficiency Levels',
                'Job-Competency Map',
                'Skill Assessment',
                'Gap Analysis',
            ],
        },
        {
            code: 'CONTRACT_WORKFORCE',
            label: 'Contract Workforce',
            icon: 'contract',
            path: '/dashboard/recruitment/vendors',
            features: [
                'Vendor Management',
                'Contract Types',
                'Rate Cards',
                'Timesheet',
                'Invoice Processing',
                'Compliance Docs',
                'Contract Renewal',
                'Performance Rating',
            ],
        },
        {
            code: 'CORE_HR',
            label: 'Core HR',
            icon: 'coreHr',
            path: '/core-hr',
            features: [
                'Employee Database',
                'Organization Structure',
                'Employment History',
                'Document Intelligence',
                'Position Management',
                'Global Transfers',
                'Shared Services Hub',
                'Cost Center',
                'Employee Life Events',
                'Mass Updates',
                'Employee ID Cards',
                'Letter Generation',
                'Exit Management',
                'Anniversary Alerts',
                'Auto-Numbering',
                'Probation Tracking',
                'Confirmation Letters',
                'Asset Management',
            ],
        },
        {
            code: 'DEI',
            label: 'DEI',
            icon: 'dei',
            path: '/dashboard/dei',
            features: [
                'Diversity Metrics',
                'Inclusion Survey',
                'Pay Equity Analysis',
                'Bias Training',
                'ERG Management',
                'Mentorship Program',
                'Accessibility',
                'DEI Goals',
            ],
        },
        {
            code: 'ESS',
            label: 'ESS',
            icon: 'ess',
            path: '/dashboard/my-services',
            features: [
                'Personal Info Update',
                'Leave Application',
                'Payslip Access',
                'Tax Declaration',
                'Tax Documents',
                'Attendance View',
                'Team Directory',
                'Request Center',
                'My Documents',
                'Benefits Enrollment',
                'Life Events',
                'Dependents',
                'Career Interests',
            ],
        },
        {
            code: 'ENGAGEMENT',
            label: 'Employee Engagement',
            icon: 'engagement',
            path: '/dashboard/engagement',
            features: [
                'Overview',
                'Engagement Analytics',
                'Pulse Surveys',
                'Event Calendar',
                'Birthday/Anniversary',
                'Recognition Wall',
                'Suggestion Box',
                'Social Feed',
                'Newsletter',
                'Polls & Quizzes',
                'Rewards Catalog',
                'Referral Program',
                'CSR Activities',
                'Surveys',
                'Classifieds',
            ],
        },
        {
            code: 'GAMIFICATION',
            label: 'Gamification',
            icon: 'gamification',
            path: '/dashboard/gamification',
            features: [
                'Points System',
                'Leaderboards',
                'Badges',
                'Challenges',
                'Levels & Tiers',
                'Missions',
                'Virtual Currency',
                'Achievement Wall',
            ],
        },
        {
            code: 'HEALTH_SAFETY',
            label: 'Health & Safety',
            icon: 'healthSafety',
            path: '/dashboard/health-safety',
            features: [
                'Incident Reporting',
                'Safety Training',
                'Health Checkups',
                'Emergency Contacts',
                'COVID Tracker',
            ],
        },
        {
            code: 'HR_BUDGETING',
            label: 'HR Budgeting',
            icon: 'hrBudgeting',
            path: '/dashboard/finance/budget',
            features: [
                'Headcount Planning',
                'Salary Budgets',
                'Cost Projections',
                'Budget vs Actual',
                'Scenario Planning',
                'Department Allocation',
                'Approval Workflow',
                'Budget Templates',
            ],
        },
        {
            code: 'FINANCE',
            label: 'Finance',
            icon: 'hrBudgeting',
            path: '/dashboard/finance',
            items: [
                {
                    code: 'FINANCE_BUDGET',
                    label: 'Budgeting',
                    icon: 'hrBudgeting',
                    path: '/dashboard/finance/budget',
                    features: [
                        'Headcount Planning',
                        'Salary Budgets',
                        'Scenario Planning',
                        'Budget vs Actual',
                        'Approvals',
                    ],
                },
                {
                    code: 'FINANCE_ASSETS',
                    label: 'Assets',
                    icon: 'payroll',
                    path: '/dashboard/finance/assets',
                    features: [
                        'Capital Assets',
                        'Operational Assets',
                        'Depreciation',
                        'Cost Centers',
                    ],
                },
                {
                    code: 'FINANCE_PETTY_CASH',
                    label: 'Petty Cash',
                    icon: 'payroll',
                    path: '/dashboard/finance/petty-cash',
                    features: [
                        'Disbursements',
                        'Reconciliation',
                        'Policy Controls',
                    ],
                },
                {
                    code: 'FINANCE_VENDORS',
                    label: 'Vendors',
                    icon: 'contract',
                    path: '/dashboard/finance/vendors',
                    features: [
                        'Vendor Onboarding',
                        'Contracts',
                        'Compliance',
                    ],
                },
            ],
            features: [
                'Assets',
                'Budget',
                'Petty Cash',
                'Vendors',
            ],
        },
        {
            code: 'HR_HELPDESK',
            label: 'HR Helpdesk',
            icon: 'hrHelpdesk',
            path: '/dashboard/helpdesk',
            features: [
                'Ticket Management',
                'SLA Tracking',
                'Knowledge Base',
                'Agent Assignment',
                'Escalation Matrix',
                'Customer Satisfaction',
                'Canned Responses',
                'Analytics',
                'Tickets',
            ],
        },
        {
            code: 'HRSD',
            label: 'HRSD',
            icon: 'hrsd',
            path: '/dashboard/hr-helpdesk',
            features: [
                'Service Catalog',
                'Request Portal',
                'Case Management',
                'Service Automation',
                'Chat Support',
                'Omnichannel',
                'Performance Metrics',
                'Continuous Improvement',
            ],
        },
        {
            code: 'JOB_LIBRARY',
            label: 'Job Library',
            icon: 'jobLibrary',
            path: '/dashboard/job-library',
            features: [
                'Job Catalog',
                'Job Families',
                'Job Evaluation',
                'Market Pricing',
                'Job Posting Templates',
            ],
        },
        {
            code: 'LEARNING_DEVELOPMENT',
            label: 'Learning & Development',
            icon: 'learning',
            path: '/dashboard/learning',
            features: [
                'Course Catalog',
                'Learning Paths',
                'Training Calendar',
                'Enrollment',
                'Attendance Tracking',
                'Assessment Engine',
                'Quiz Builder',
                'Certifications',
                'External Training',
                'Training Feedback',
                'Skill Gap Analysis',
                'AI Recommendations',
                'Training Budget',
                'Vendor Management',
                'E-Learning Platform',
                'Mentoring',
                'Learning Community',
                'Knowledge Repository',
                'Compliance Training',
                'ROI Measurement',
            ],
        },
        {
            code: 'INTEGRATION_HUB',
            label: 'Integration Hub',
            icon: 'Plug',
            path: '/dashboard/integration-hub',
            features: [
                'API Marketplace',
                'Webhook Manager',
                'App Directory',
            ],
        },
        {
            code: 'GLOBAL_MOBILITY',
            label: 'Global Mobility',
            icon: 'Globe',
            path: '/dashboard/mobility',
            features: [
                'Visa & Immigration',
                'Relocation Packages',
                'Expat Tax Manager',
            ],
        },
        {
            code: 'ALUMNI_NETWORK',
            label: 'Alumni Network',
            icon: 'Users2',
            path: '/dashboard/alumni-network',
            features: [
                'Alumni Directory',
                'Events & Reunions',
                'Alumni Jobs',
            ],
        },
        {
            code: 'LABOR_RELATIONS',
            label: 'Labor Relations',
            icon: 'labor',
            path: '/dashboard/compliance',
            features: [
                'Union Database',
                'Grievance Management',
                'Collective Bargaining',
                'Disciplinary Actions',
                'Labor Law Compliance',
                'Strike Management',
                'Arbitration',
                'Communication Log',
            ],
        },
        {
            code: 'LEAVE',
            label: 'Leave',
            icon: 'leave',
            path: '/leave',
            features: [
                'Leave Types',
                'Leave Policy',
                'Leave Balance',
                'Leave Application',
                'Leave Calendar',
                'Holiday Management',
                'Leave Encashment',
                'Carry Forward',
                'Comp-off Tracking',
                'Leave Reports',
                'My Leaves',
                'Accrual Engine',
                'Hijri Calendar',
                'Hajj Leave',
                'Country-Specific Rules',
            ],
            items: [
                {
                    code: 'LEAVE_COMMAND_CENTER',
                    label: 'Leave Command Center',
                    icon: 'leave',
                    path: '/leave',
                    features: ['Dashboard', 'Pending Approvals', 'AI Insights'],
                },
                {
                    code: 'LEAVE_BALANCES',
                    label: 'Balances',
                    icon: 'leave',
                    path: '/leave/balances',
                    features: ['Employee Balances', 'Carry Forward', 'Encashment'],
                },
                {
                    code: 'LEAVE_POLICIES',
                    label: 'Policies',
                    icon: 'leave',
                    path: '/leave/policies',
                    features: ['Policy Config', 'Country Rules', 'Accrual Schedules'],
                },
                {
                    code: 'LEAVE_REQUESTS',
                    label: 'Requests',
                    icon: 'leave',
                    path: '/leave/requests',
                    features: ['Applications', 'Approvals', 'History'],
                },
                {
                    code: 'LEAVE_CALENDAR',
                    label: 'Calendar',
                    icon: 'leave',
                    path: '/leave/calendar',
                    features: ['Gregorian', 'Hijri', 'Holidays', 'Ramadan Hours'],
                },
            ],
        },
        {
            code: 'ATTENDANCE',
            label: 'Attendance & Time',
            icon: 'attendance',
            path: '/attendance',
            features: [
                'Shift Management',
                'Biometric Integration',
                'GPS Attendance',
                'Geofencing',
                'Facial Recognition',
                'Overtime Calculation',
                'Ramadan Hours',
                'Time Tracking',
                'Wi-Fi Proximity',
                'Live Feed',
                'Attendance Reports',
            ],
            items: [
                {
                    code: 'ATTENDANCE_COMMAND',
                    label: 'Attendance Center',
                    icon: 'attendance',
                    path: '/attendance',
                    features: ['Live Tracking', 'Multi-Modal Capture', 'AI Insights'],
                },
                {
                    code: 'ATTENDANCE_SHIFTS',
                    label: 'Shift Management',
                    icon: 'attendance',
                    path: '/attendance/shift-management',
                    features: ['Shift Templates', 'Roster', 'Ramadan Auto-Switch'],
                },
                {
                    code: 'ATTENDANCE_OVERTIME',
                    label: 'Overtime Management',
                    icon: 'attendance',
                    path: '/attendance/overtime-management',
                    features: ['OT Rules', 'Multi-Jurisdiction', 'Holiday Multipliers'],
                },
                {
                    code: 'ATTENDANCE_TIME',
                    label: 'Time Tracking',
                    icon: 'attendance',
                    path: '/attendance/time-tracking',
                    features: ['Timesheets', 'Project Hours', 'Billable Tracking'],
                },
            ],
        },
        {
            code: 'PERFORMANCE',
            label: 'Performance',
            icon: 'performance',
            path: '/performance',
            features: [
                'Goal Setting (OKR/MBO)',
                'Performance Reviews',
                '360 Feedback',
                'Continuous Feedback',
                'Competency Framework',
                'Calibration',
                '9-Box Grid',
                'Review Cycles',
                'AI Insights',
            ],
            items: [
                {
                    code: 'PERF_COMMAND',
                    label: 'Performance Center',
                    icon: 'performance',
                    path: '/performance',
                    features: ['Dashboard', 'Reviews', 'Feedback', 'AI Insights'],
                },
            ],
        },
        {
            code: 'LOCALIZATION',
            label: 'Localization',
            icon: 'localization',
            path: '/localization',
            features: [
                'Multi-Currency',
                'Multi-Language',
                'Country-Specific Fields',
                'Tax Regimes',
                'Statutory Compliance',
                'Date/Time Formats',
                'Calendar Types',
                'Bank Integration',
                'Government Reports',
                'Regional Holidays',
                'Address Formats',
            ],
        },
        {
            code: 'MOBILE_APP',
            label: 'Mobile App',
            icon: 'mobile',
            path: '/dashboard/mobile-app',
            features: [
                'Native Apps',
                'Push Notifications',
                'Offline Mode',
                'Biometric Login',
                'GPS Attendance',
                'Mobile Approvals',
                'Document Upload',
                'Team View',
                'Expense Claims',
                'Mobile Timesheets',
                'Quick Actions',
                'Voice Commands',
                'Mobile Analytics',
                'Chat Messaging',
                'Profile Management',
            ],
        },
        {
            code: 'MSS',
            label: 'MSS',
            icon: 'mss',
            path: '/dashboard/manager',
            features: [
                'Team Dashboard',
                'Approval Center',
                'One-on-Ones',
                'Team Capacity',
                'Team Reports',
                'Delegation',
                'Team Analytics',
            ],
        },
        {
            code: 'OFFBOARDING',
            label: 'Offboarding',
            icon: 'offboarding',
            path: '/dashboard/offboarding',
            features: [
                'Exit Process',
                'Exit Interview',
                'Clearance Checklist',
                'F&F Settlement',
            ],
        },
        {
            code: 'ONBOARDING',
            label: 'Onboarding',
            icon: 'onboarding',
            path: '/dashboard/onboarding',
            features: [
                'Pre-boarding',
                'First Day Experience',
                'Induction Program',
                'Buddy Assignment',
                '30-60-90 Day Plan',
            ],
        },
        {
            code: 'ORG_DESIGN',
            label: 'Org Design',
            icon: 'orgDesign',
            path: '/dashboard/org-design',
            features: [
                'Org Chart Builder',
                'Scenario Planning',
                'Span of Control',
                'Position Hierarchy',
                'Matrix Structure',
                'Succession Pool',
                'Org Analytics',
                'Change Management',
            ],
        },
        {
            code: 'PAYROLL',
            label: 'Payroll',
            icon: 'payroll',
            path: '/payroll',
            features: [
                'Payroll Processing',
                'Tax Calculation',
                'Statutory Deductions',
                'Bank File Generation',
                'Payslip Generation',
                'Reimbursements',
                'Loan Recovery',
                'Arrears Management',
                'Bonus Processing',
                'Year-end Processing',
                'Multi-State Payroll',
                'Payroll Reconciliation',
                'Garnishments',
                'Off-cycle Payments',
                'Payroll Reports',
                'Tax Manager',
                'Disbursement',
                'Payslips',
            ],
            items: [
                {
                    code: 'PAYROLL_OVERVIEW',
                    label: 'Global Payroll Hub',
                    icon: 'payroll',
                    path: '/payroll',
                    features: ['Dashboard', 'Payroll Run', 'Analytics'],
                },
                {
                    code: 'PAYROLL_TAX_MANAGER',
                    label: 'Tax Manager',
                    icon: 'payroll',
                    path: '/payroll/tax-manager',
                    features: ['Tax Regimes', 'TDS Computation', 'Year-End Filing'],
                },
                {
                    code: 'PAYROLL_DISBURSEMENT',
                    label: 'Disbursement & Bank Files',
                    icon: 'payroll',
                    path: '/payroll/disbursement',
                    features: ['Multi-Bank Orchestration', 'SIF Generation', 'NEFT/RTGS/SWIFT'],
                },
            ],
        },
        {
            code: 'PAYROLL_COMPLIANCE',
            label: 'Payroll Compliance',
            icon: 'labor',
            path: '/payroll-compliance',
            features: [
                'Overview',
                'GOSI',
                'Labour Law',
                'Mudad',
                'EOSB',
                'India Statutory',
                'Nitaqat',
                'WPS',
                'Bahrain SIO',
                'Qatar WPS',
                'Oman SPF',
                'Kuwait PIFSS',
            ],
            items: [
                {
                    code: 'COMPLIANCE_OVERVIEW',
                    label: 'Compliance Hub',
                    icon: 'labor',
                    path: '/payroll-compliance',
                    features: ['Dashboard', 'Health Monitor', 'Alerts'],
                },
                {
                    code: 'COMPLIANCE_WPS',
                    label: 'UAE WPS',
                    icon: 'labor',
                    path: '/payroll-compliance/wps',
                    features: ['SIF Generation', 'MoHRE Validation', 'File History'],
                },
                {
                    code: 'COMPLIANCE_GOSI',
                    label: 'KSA GOSI',
                    icon: 'labor',
                    path: '/payroll-compliance/gosi',
                    features: ['Contribution Simulation', 'Saudization', 'Mudad Bridge'],
                },
                {
                    code: 'COMPLIANCE_INDIA',
                    label: 'India Statutory',
                    icon: 'labor',
                    path: '/payroll-compliance/india-statutory',
                    features: ['PF/ESI', 'TDS', 'Professional Tax', 'LWF'],
                },
                {
                    code: 'COMPLIANCE_EOSB',
                    label: 'EOSB & Gratuity',
                    icon: 'labor',
                    path: '/payroll-compliance/eosb',
                    features: ['Settlement Simulation', 'Multi-Jurisdiction', 'Accruals'],
                },
            ],
        },
        {
            code: 'PERFORMANCE',
            label: 'Performance',
            icon: 'performance',
            path: '/dashboard/performance',
            features: [
                'Goal Setting',
                'Goal Alignment',
                'Review Cycles',
                'Self-Assessment',
                'Manager Assessment',
                '360 Feedback',
                'Continuous Feedback',
                'Recognition Wall',
                'Rating Scales',
                'Bell Curve',
                'Calibration',
                '1-on-1 Meetings',
                'Check-in Templates',
                'PIP Management',
                'Competency Assessment',
                'Development Plans',
                'Performance Analytics',
                'Reward Linkage',
                'My Reviews',
                'Skills Gap',
            ],
        },
        {
            code: 'POLICY_MGMT',
            label: 'Policy Mgmt',
            icon: 'policy',
            path: '/dashboard/policy-mgmt',
            features: [
                'Policy Repository',
                'Policy Creation',
                'Approval Workflow',
                'Policy Distribution',
                'Acknowledgement',
                'Policy Updates',
                'Compliance Tracking',
                'Policy FAQs',
            ],
        },
        {
            code: 'POSITION_BUDGETING',
            label: 'Position Budgeting',
            icon: 'positionBudgeting',
            path: '/dashboard/position-budgeting',
            features: [
                'Position Creation',
                'Budget Allocation',
                'Vacancy Tracking',
                'Position History',
                'Position Freeze',
                'Position Transfer',
                'Budget vs Actual',
                'Position Analytics',
            ],
        },
        {
            code: 'RECRUITMENT',
            label: 'Recruitment',
            icon: 'recruitment',
            path: '/recruitment',
            features: [
                'Job Requisition',
                'Job Posting',
                'Career Site',
                'Application Tracking',
                'Resume Parsing',
                'Candidate Screening',
                'Interview Management',
                'Assessment Tests',
                'Interview Feedback',
                'Offer Management',
                'Background Verification',
                'Recruitment Analytics',
                'Talent Pool',
            ],
        },
        {
            code: 'REMOTE_WORK',
            label: 'Remote Work',
            icon: 'remoteWork',
            path: '/dashboard/remote-work',
            features: [
                'Remote Policy',
                'Equipment Tracking',
                'Virtual Onboarding',
                'Productivity Tracking',
                'Communication Tools',
                'Virtual Team Building',
                'Expense Management',
                'Well-being Support',
            ],
        },
        {
            code: 'REPORTS',
            label: 'Reports',
            icon: 'reports',
            path: '/dashboard/analytics',
            features: [
                'Standard Reports',
                'Custom Reports',
                'Report Builder',
                'People Analytics',
                'Dashboard Builder',
                'Scheduled Reports',
                'Export Options',
                'Real-time Analytics',
                'Turnover Analysis',
                'DEI Dashboard',
                'Headcount Planning',
                'Compensation Analytics',
                'Drill-down Reports',
                'Cross-module Reports',
                'Compliance Reports',
                'Executive Dashboards',
                'Predictive Analytics',
                'Report Security',
            ],
        },
        {
            code: 'SUCCESSION_PLANNING',
            label: 'Succession Planning',
            icon: 'succession',
            path: '/dashboard/succession-planning',
            features: [
                'Critical Positions',
                'Talent Matrix',
                'Successor Identification',
                'Development Planning',
                'Emergency Succession',
                'Talent Review',
                'Career Pathing',
                'Succession Analytics',
            ],
        },
        {
            code: 'TRAVEL',
            label: 'Travel',
            icon: 'travel',
            path: '/dashboard/travel',
            features: [
                'Travel Request',
                'Travel Policy',
                'Booking Integration',
                'Advance Request',
                'Expense Claims',
                'Per Diem',
                'Travel Insurance',
                'Visa Support',
                'Travel Dashboard',
                'Travel History',
                'Mileage Tracking',
                'Travel Analytics',
                'Dashboard',
            ],
        },
        {
            code: 'USER_MANAGEMENT',
            label: 'User Management',
            icon: 'userManagement',
            path: '/dashboard/user-management',
            features: [
                'Users',
                'Role Management',
                'Access Control',
                'Password Policy',
                'Single Sign-On',
                'Session Management',
                'Audit Trail',
                'User Delegation',
                'License Management',
                'User Deactivation',
                'Profile Management',
                'Multi-Factor Auth',
            ],
        },
        {
            code: 'WORKFLOW_ENGINE',
            label: 'Workflow Engine',
            icon: 'workflow',
            path: '/workflow-engine',
            features: [
                'Workflow Designer',
                'Approval Chains',
                'Conditional Logic',
                'Email Notifications',
                'Escalation Rules',
                'Form Builder',
                'Integration Points',
                'Workflow Templates',
                'Workflow Analytics',
                'Version Control',
                'Testing Mode',
                'Audit Log',
                'SLA Tracking',
                'AI Path Prediction',
            ],
        },
        {
            code: 'INDUSTRY_SOLUTIONS',
            label: 'Industry Solutions',
            icon: 'briefcase',
            path: '/dashboard/industry-solutions',
            features: [
                'Collaboration',
                'Manufacturing',
                'Healthcare',
                'Retail',
                'Education',
                'Government',
                'Agriculture',
                'Mining & Resources',
                'Hospitality',
                'Automotive',
                'Aviation',
                'Maritime',
                'Nonprofit / NGO',
                'Logistics',
            ],
            items: [
                {
                    code: 'COLLABORATION',
                    label: 'Collaboration',
                    icon: 'users',
                    path: '/dashboard/industry/collaboration',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'MANUFACTURING',
                    label: 'Manufacturing',
                    icon: 'factory',
                    path: '/dashboard/industry/manufacturing',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'HEALTHCARE',
                    label: 'Healthcare',
                    icon: 'activity',
                    path: '/dashboard/industry/healthcare',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'RETAIL',
                    label: 'Retail',
                    icon: 'shoppingBag',
                    path: '/dashboard/industry/retail',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'EDUCATION',
                    label: 'Education',
                    icon: 'graduationCap',
                    path: '/dashboard/industry/education',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'GOVERNMENT',
                    label: 'Government',
                    icon: 'building',
                    path: '/dashboard/industry/government',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'AGRICULTURE',
                    label: 'Agriculture',
                    icon: 'leaf',
                    path: '/dashboard/industry/agriculture',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'MINING_RESOURCES',
                    label: 'Mining & Resources',
                    icon: 'pickaxe',
                    path: '/dashboard/industry/mining',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'HOSPITALITY',
                    label: 'Hospitality',
                    icon: 'coffee',
                    path: '/dashboard/industry/hospitality',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'AUTOMOTIVE',
                    label: 'Automotive',
                    icon: 'car',
                    path: '/dashboard/industry/automotive',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'AVIATION',
                    label: 'Aviation',
                    icon: 'plane',
                    path: '/dashboard/industry/aviation',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'MARITIME',
                    label: 'Maritime',
                    icon: 'anchor',
                    path: '/dashboard/industry/maritime',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'NONPROFIT',
                    label: 'Nonprofit / NGO',
                    icon: 'heart',
                    path: '/dashboard/industry/nonprofit',
                    features: ['Dashboard', 'Settings'],
                },
                {
                    code: 'LOGISTICS',
                    label: 'Logistics',
                    icon: 'truck',
                    path: '/dashboard/industry/logistics',
                    features: ['Dashboard', 'Settings'],
                },
                // Preserving existing detailed modules
                {
                    code: 'WELLNESS',
                    label: 'Wellness',
                    icon: 'wellness',
                    path: '/dashboard/wellness',
                    features: [
                        'Health Programs',
                        'Mental Health',
                        'Health Risk Assessment',
                        'Wellness Challenges',
                        'Wellness Points',
                        'Gym Membership',
                        'Wellness Dashboard',
                        'Dashboard',
                    ],
                },
                {
                    code: 'WORKFLOW_ENGINE',
                    label: 'Workflow Engine',
                    icon: 'workflow',
                    path: '/workflow-engine',
                    features: [
                        'Workflow Designer',
                        'Approval Chains',
                        'Conditional Logic',
                        'Email Notifications',
                        'Escalation Rules',
                        'Form Builder',
                        'Integration Points',
                        'Workflow Templates',
                        'Workflow Analytics',
                        'Version Control',
                        'Testing Mode',
                        'Audit Log',
                    ],
                },
                {
                    code: 'WORKFORCE_PLANNING',
                    label: 'Workforce Planning',
                    icon: 'workforcePlanning',
                    path: '/dashboard/workforce-planning',
                    features: [
                        'Demand Forecasting',
                        'Supply Analysis',
                        'Gap Analysis',
                        'Scenario Modeling',
                        'Workforce Costs',
                        'Succession Readiness',
                        'Talent Acquisition Plan',
                        'Workforce Analytics',
                    ],
                },
            ],
        },

        {
            code: 'MASTER_DATA',
            label: 'Master Data',
            icon: 'settings',
            path: '/master-data',
            features: [
                'Companies',
                'Departments',
                'Locations',
                'Business Units',
                'Cost Centers',
                'Designations',
                'Grades',
                'Job Families',
                'Job Functions',
                'Job Profiles',
                'Skills',
                'Competencies',
                'Countries',
                'States',
                'Cities',
                'Currencies',
                'Languages',
                'Banks',
                'Holidays',
                'Leave Types',
                'Shift Types',
                'Document Types',
                'Employment Types',
                'Employment Statuses',
                'Education Levels',
                'Relationships',
                'Exit Reasons',
                'Pay Components',
                'Salary Structures',
                'Statutory',
                'Tax Regimes',
                'Roles & Permissions',
                'System Settings',
            ],
        },
        {
            code: 'ADMIN_CONSOLE',
            label: 'Admin',
            icon: 'settings',
            path: '/dashboard/admin',
            items: [
                {
                    code: 'ADMIN_MASTER_DATA',
                    label: 'Master Data',
                    icon: 'settings',
                    path: '/master-data',
                    features: ['Companies', 'Locations', 'Job Families', 'Grades', 'Roles & Permissions'],
                },
                {
                    code: 'ADMIN_INTEGRATIONS',
                    label: 'Integrations',
                    icon: 'orgDesign',
                    path: '/dashboard/admin/integrations',
                    features: ['App Directory', 'API Marketplace', 'Webhooks'],
                },
                {
                    code: 'ADMIN_AI',
                    label: 'AI & Automation',
                    icon: 'ai',
                    path: '/dashboard/admin/ai',
                    features: ['Workflows', 'Copilot', 'Predictions'],
                },
                {
                    code: 'ADMIN_WORKFLOWS',
                    label: 'Workflows',
                    icon: 'workflow',
                    path: '/dashboard/admin/workflows',
                    features: ['Designer', 'Routing Rules', 'Approvals'],
                },
                {
                    code: 'ADMIN_COMPLIANCE',
                    label: 'Compliance & Audit',
                    icon: 'policy',
                    path: '/dashboard/admin/compliance/audit',
                    features: ['Audit Logs', 'Data Retention', 'Policy Acknowledgement'],
                },
                {
                    code: 'ADMIN_DOCUMENTS',
                    label: 'Documents',
                    icon: 'policy',
                    path: '/dashboard/admin/documents',
                    features: ['Templates', 'Document Governance', 'Access Control'],
                },
                {
                    code: 'ADMIN_STATIONERY',
                    label: 'Stationery',
                    icon: 'policy',
                    path: '/dashboard/admin/stationery',
                    features: ['Branding', 'ID Cards', 'Letterheads'],
                },
                {
                    code: 'ADMIN_ASSETS',
                    label: 'Assets',
                    icon: 'compensation',
                    path: '/dashboard/admin/assets',
                    features: ['Asset Catalog', 'Assignments', 'Audits'],
                },
                {
                    code: 'ADMIN_PAYROLL',
                    label: 'Payroll Settings',
                    icon: 'payroll',
                    path: '/dashboard/admin/payroll/settings',
                    features: ['Bank Integration', 'Payroll Policies'],
                },
                {
                    code: 'ADMIN_TRAVEL',
                    label: 'Travel',
                    icon: 'travel',
                    path: '/dashboard/admin/travel',
                    features: ['Travel Policies', 'Rates', 'Vendors'],
                },
                {
                    code: 'ADMIN_SYSTEM',
                    label: 'System',
                    icon: 'settings',
                    path: '/dashboard/admin/system/health',
                    features: ['Health', 'Localization', 'Notifications', 'Import/Export'],
                },
            ],
            features: [
                'Master Data',
                'Integrations',
                'Documents',
                'Stationery',
                'Assets',
                'Travel',
            ],
        },
    ],
};
