/**
 * Sample Employee Data
 */

import type { Employee } from './types';

export const generateSampleEmployees = (): Employee[] => [
    {
        id: 'emp001',
        name: 'Alice Cooper',
        email: 'alice.cooper@company.com',
        avatar: 'https://i.pravatar.cc/150?u=alice',
        role: 'Senior Product Designer',
        department: 'Design',
        location: 'San Francisco',
        personalInfo: {
            dateOfBirth: '1990-05-15',
            gender: 'Female',
            maritalStatus: 'Married',
            nationality: 'USA',
            phone: '+1 555-0101',
            personalEmail: 'alice.personal@email.com',
            address: {
                street: '123 Main Street',
                city: 'San Francisco',
                state: 'California',
                zipCode: '94102',
                country: 'United States',
            },
            emergencyContacts: [
                {
                    name: 'Bob Cooper',
                    relationship: 'Spouse',
                    phone: '+1 555-0102',
                    email: 'bob@email.com',
                },
            ],
            familyMembers: [
                {
                    name: 'Bob Cooper',
                    relationship: 'Spouse',
                    dateOfBirth: '1988-03-20',
                    dependent: false,
                },
                {
                    name: 'Emma Cooper',
                    relationship: 'Daughter',
                    dateOfBirth: '2018-07-10',
                    dependent: true,
                },
            ],
        },
        jobDetails: {
            employeeId: 'EMP001',
            title: 'Senior Product Designer',
            department: 'Design',
            location: 'San Francisco',
            manager: 'Grace Hopper',
            managerId: 'emp007',
            employmentType: 'Full-time',
            employmentStatus: 'Active',
            hireDate: '2020-01-15',
            probationEndDate: '2020-04-15',
            reportingTo: ['emp007'],
            workSchedule: 'Monday-Friday, 9:00 AM - 5:00 PM',
            costCenter: 'CC-DES-001',
        },
        compensation: {
            baseSalary: 120000,
            currency: 'USD',
            payFrequency: 'Monthly',
            effectiveDate: '2024-01-01',
            bonus: 15000,
            stockOptions: 1000,
            benefits: ['Health Insurance', 'Dental Insurance', '401k Match', 'PTO 20 days'],
            bankAccountNumber: '****1234',
            bankName: 'Chase Bank',
            taxId: '***-**-1234',
        },
        documents: [
            {
                id: 'doc001',
                name: 'Resume_Alice_Cooper.pdf',
                type: 'Resume',
                uploadedDate: '2020-01-01',
                uploadedBy: 'HR System',
                fileSize: 245000,
                verified: true,
            },
            {
                id: 'doc002',
                name: 'Offer_Letter_2020.pdf',
                type: 'Offer Letter',
                uploadedDate: '2020-01-05',
                uploadedBy: 'HR System',
                fileSize: 180000,
                verified: true,
            },
            {
                id: 'doc003',
                name: 'ID_Card.pdf',
                type: 'ID Card',
                uploadedDate: '2020-01-15',
                uploadedBy: 'Security',
                fileSize: 95000,
                verified: true,
            },
        ],
        employmentHistory: [
            {
                id: 'hist001',
                date: '2024-01-01',
                type: 'Salary Change',
                description: 'Annual salary review and adjustment',
                fromValue: '$110,000',
                toValue: '$120,000',
                notes: 'Merit increase based on performance',
            },
            {
                id: 'hist002',
                date: '2022-06-15',
                type: 'Promoted',
                description: 'Promoted to Senior Product Designer',
                fromValue: 'Product Designer',
                toValue: 'Senior Product Designer',
                notes: 'Excellent performance, led major redesign project',
            },
            {
                id: 'hist003',
                date: '2020-01-15',
                type: 'Hired',
                description: 'Joined as Product Designer',
                notes: 'Welcome to the team!',
            },
        ],
        createdAt: '2020-01-15T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'emp002',
        name: 'Bob Marley',
        email: 'bob.marley@company.com',
        avatar: 'https://i.pravatar.cc/150?u=bob',
        role: 'Frontend Engineer',
        department: 'Engineering',
        location: 'Remote',
        personalInfo: {
            dateOfBirth: '1992-08-22',
            gender: 'Male',
            maritalStatus: 'Single',
            nationality: 'Canada',
            phone: '+1 555-0103',
            personalEmail: 'bob.m@email.com',
            address: {
                street: '456 Oak Avenue',
                city: 'Toronto',
                state: 'Ontario',
                zipCode: 'M5H 2N2',
                country: 'Canada',
            },
            emergencyContacts: [
                {
                    name: 'Rita Marley',
                    relationship: 'Mother',
                    phone: '+1 555-0104',
                },
            ],
            familyMembers: [],
        },
        jobDetails: {
            employeeId: 'EMP002',
            title: 'Frontend Engineer',
            department: 'Engineering',
            location: 'Remote',
            manager: 'David Bowie',
            managerId: 'emp004',
            employmentType: 'Full-time',
            employmentStatus: 'Active',
            hireDate: '2021-03-01',
            reportingTo: ['emp004'],
            workSchedule: 'Flexible hours',
            costCenter: 'CC-ENG-001',
        },
        compensation: {
            baseSalary: 110000,
            currency: 'USD',
            payFrequency: 'Monthly',
            effectiveDate: '2024-01-01',
            bonus: 10000,
            stockOptions: 500,
            benefits: ['Health Insurance', 'Dental Insurance', 'Remote Stipend', 'PTO 15 days'],
            bankAccountNumber: '****5678',
            bankName: 'TD Bank',
            taxId: '***-**-5678',
        },
        documents: [
            {
                id: 'doc004',
                name: 'Bob_Resume.pdf',
                type: 'Resume',
                uploadedDate: '2021-02-15',
                uploadedBy: 'HR System',
                fileSize: 198000,
                verified: true,
            },
        ],
        employmentHistory: [
            {
                id: 'hist004',
                date: '2023-09-01',
                type: 'Salary Change',
                description: 'Performance bonus and raise',
                fromValue: '$100,000',
                toValue: '$110,000',
            },
            {
                id: 'hist005',
                date: '2021-03-01',
                type: 'Hired',
                description: 'Joined as Frontend Engineer',
            },
        ],
        createdAt: '2021-03-01T00:00:00Z',
        updatedAt: '2023-09-01T00:00:00Z',
    },
    {
        id: 'emp003',
        name: 'Charlie Puth',
        email: 'charlie.puth@company.com',
        avatar: 'https://i.pravatar.cc/150?u=charlie',
        role: 'Marketing Manager',
        department: 'Marketing',
        location: 'New York',
        personalInfo: {
            dateOfBirth: '1988-12-02',
            gender: 'Male',
            maritalStatus: 'Married',
            nationality: 'USA',
            phone: '+1 555-0105',
            personalEmail: 'charlie.p@email.com',
            address: {
                street: '789 Park Ave',
                city: 'New York',
                state: 'New York',
                zipCode: '10022',
                country: 'United States',
            },
            emergencyContacts: [
                {
                    name: 'Diana Puth',
                    relationship: 'Spouse',
                    phone: '+1 555-0106',
                    email: 'diana@email.com',
                },
            ],
            familyMembers: [
                {
                    name: 'Diana Puth',
                    relationship: 'Spouse',
                    dateOfBirth: '1989-04-15',
                    dependent: false,
                },
            ],
        },
        jobDetails: {
            employeeId: 'EMP003',
            title: 'Marketing Manager',
            department: 'Marketing',
            location: 'New York',
            manager: 'Grace Hopper',
            managerId: 'emp007',
            employmentType: 'Full-time',
            employmentStatus: 'Active',
            hireDate: '2019-06-01',
            reportingTo: ['emp007'],
            workSchedule: 'Monday-Friday, 9:00 AM - 6:00 PM',
            costCenter: 'CC-MKT-001',
        },
        compensation: {
            baseSalary: 95000,
            currency: 'USD',
            payFrequency: 'Monthly',
            effectiveDate: '2024-01-01',
            bonus: 12000,
            benefits: ['Health Insurance', 'Dental Insurance', '401k Match', 'PTO 18 days'],
            bankAccountNumber: '****9012',
            bankName: 'Bank of America',
            taxId: '***-**-9012',
        },
        documents: [
            {
                id: 'doc005',
                name: 'Charlie_Resume.pdf',
                type: 'Resume',
                uploadedDate: '2019-05-15',
                uploadedBy: 'HR System',
                fileSize: 210000,
                verified: true,
            },
        ],
        employmentHistory: [
            {
                id: 'hist006',
                date: '2022-01-01',
                type: 'Promoted',
                description: 'Promoted to Marketing Manager',
                fromValue: 'Senior Marketing Specialist',
                toValue: 'Marketing Manager',
            },
            {
                id: 'hist007',
                date: '2019-06-01',
                type: 'Hired',
                description: 'Joined as Marketing Specialist',
            },
        ],
        createdAt: '2019-06-01T00:00:00Z',
        updatedAt: '2022-01-01T00:00:00Z',
    },
    {
        id: 'emp004',
        name: 'David Bowie',
        email: 'david.bowie@company.com',
        avatar: 'https://i.pravatar.cc/150?u=david',
        role: 'Engineering Manager',
        department: 'Engineering',
        location: 'London',
        personalInfo: {
            dateOfBirth: '1985-01-08',
            gender: 'Male',
            maritalStatus: 'Married',
            nationality: 'United Kingdom',
            phone: '+44 20 7123 4567',
            personalEmail: 'david.b@email.com',
            address: {
                street: '10 Downing Street',
                city: 'London',
                state: 'England',
                zipCode: 'SW1A 2AA',
                country: 'United Kingdom',
            },
            emergencyContacts: [
                {
                    name: 'Iman Bowie',
                    relationship: 'Spouse',
                    phone: '+44 20 7123 4568',
                },
            ],
            familyMembers: [
                {
                    name: 'Iman Bowie',
                    relationship: 'Spouse',
                    dateOfBirth: '1987-06-15',
                    dependent: false,
                },
            ],
        },
        jobDetails: {
            employeeId: 'EMP004',
            title: 'Engineering Manager',
            department: 'Engineering',
            location: 'London',
            manager: 'Grace Hopper',
            managerId: 'emp007',
            employmentType: 'Full-time',
            employmentStatus: 'Active',
            hireDate: '2018-04-01',
            reportingTo: ['emp007'],
            workSchedule: 'Monday-Friday, 9:00 AM - 5:30 PM',
            costCenter: 'CC-ENG-002',
        },
        compensation: {
            baseSalary: 140000,
            currency: 'USD',
            payFrequency: 'Monthly',
            effectiveDate: '2024-01-01',
            bonus: 20000,
            stockOptions: 2000,
            benefits: ['Health Insurance', 'Dental Insurance', '401k Match', 'PTO 22 days', 'Relocation Assistance'],
            bankAccountNumber: '****3456',
            bankName: 'Barclays',
            taxId: '***-**-3456',
        },
        documents: [
            {
                id: 'doc006',
                name: 'David_Resume.pdf',
                type: 'Resume',
                uploadedDate: '2018-03-15',
                uploadedBy: 'HR System',
                fileSize: 225000,
                verified: true,
            },
        ],
        employmentHistory: [
            {
                id: 'hist008',
                date: '2021-04-01',
                type: 'Promoted',
                description: 'Promoted to Engineering Manager',
                fromValue: 'Senior Software Engineer',
                toValue: 'Engineering Manager',
            },
            {
                id: 'hist009',
                date: '2018-04-01',
                type: 'Hired',
                description: 'Joined as Senior Software Engineer',
            },
        ],
        createdAt: '2018-04-01T00:00:00Z',
        updatedAt: '2021-04-01T00:00:00Z',
    },
    {
        id: 'emp005',
        name: 'Eva Green',
        email: 'eva.green@company.com',
        avatar: 'https://i.pravatar.cc/150?u=eva',
        role: 'HR Business Partner',
        department: 'People',
        location: 'Berlin',
        personalInfo: {
            dateOfBirth: '1991-07-06',
            gender: 'Female',
            maritalStatus: 'Single',
            nationality: 'Germany',
            phone: '+49 30 123456',
            personalEmail: 'eva.g@email.com',
            address: {
                street: 'Unter den Linden 77',
                city: 'Berlin',
                state: 'Berlin',
                zipCode: '10117',
                country: 'Germany',
            },
            emergencyContacts: [
                {
                    name: 'Hans Green',
                    relationship: 'Father',
                    phone: '+49 30 123457',
                },
            ],
            familyMembers: [],
        },
        jobDetails: {
            employeeId: 'EMP005',
            title: 'HR Business Partner',
            department: 'People',
            location: 'Berlin',
            manager: 'Grace Hopper',
            managerId: 'emp007',
            employmentType: 'Full-time',
            employmentStatus: 'Active',
            hireDate: '2020-09-01',
            reportingTo: ['emp007'],
            workSchedule: 'Monday-Friday, 9:00 AM - 5:00 PM',
            costCenter: 'CC-PPL-001',
        },
        compensation: {
            baseSalary: 85000,
            currency: 'USD',
            payFrequency: 'Monthly',
            effectiveDate: '2024-01-01',
            bonus: 8000,
            benefits: ['Health Insurance', 'Dental Insurance', 'PTO 20 days', 'Transportation Allowance'],
            bankAccountNumber: '****7890',
            bankName: 'Deutsche Bank',
            taxId: '***-**-7890',
        },
        documents: [
            {
                id: 'doc007',
                name: 'Eva_Resume.pdf',
                type: 'Resume',
                uploadedDate: '2020-08-15',
                uploadedBy: 'HR System',
                fileSize: 189000,
                verified: true,
            },
        ],
        employmentHistory: [
            {
                id: 'hist010',
                date: '2023-06-01',
                type: 'Salary Change',
                description: 'Annual salary adjustment',
                fromValue: '$78,000',
                toValue: '$85,000',
            },
            {
                id: 'hist011',
                date: '2020-09-01',
                type: 'Hired',
                description: 'Joined as HR Business Partner',
            },
        ],
        createdAt: '2020-09-01T00:00:00Z',
        updatedAt: '2023-06-01T00:00:00Z',
    },
];
