// @ts-nocheck — Dev/demo seed data, intentionally loose-typed.
import type {
  VisaApplication,
  VisaApplicationStatus,
  VisaType,
  VisaStage,
  RequiredDocument,
  Document,
  Dependent,
  ImmigrationCompliance,
  RelocationPackage,
  Address,
  RelocationBenefit,
  RelocationService,
  RelocationAllowance,
  RelocationPhase,
  RelocationTask,
  RelocationVendor,
  ExpatTaxProfile,
  TaxResidencyStatus,
  IncomeSource,
  TaxDeduction,
  TaxCredit,
  TaxReturn,
  TaxProjection,
  MobilityAnalytics,
  MobilitySettings,
  Priority,
} from './types';

// Sample Visa Applications
export const sampleVisaApplications: VisaApplication[] = [
  {
    applicationId: 'visa-001',
    applicationNumber: 'VA-2024-001',
    applicationStatus: 'in_progress' as VisaApplicationStatus,
    employeeId: 'emp-001',
    employeeName: 'Sarah Mitchell',
    visaType: 'work_permit' as VisaType,
    destinationCountry: 'United Kingdom',
    originCountry: 'United States',
    assignmentType: 'long_term',
    assignmentStartDate: new Date('2025-03-01'),
    assignmentEndDate: new Date('2027-03-01'),
    currentStage: {
      stageId: 'stage-002',
      stageName: 'Document Collection',
      stageNumber: 2,
      stageStatus: 'in_progress',
      startDate: new Date('2024-12-01'),
      expectedEndDate: new Date('2024-12-31'),
      completionPercentage: 65,
      assignedTo: 'hr-specialist-001',
      assignedToName: 'Jennifer Lopez',
      milestones: [
        {
          milestoneId: 'ms-001',
          milestoneName: 'Gather Personal Documents',
          status: 'completed',
          dueDate: new Date('2024-12-10'),
          completedDate: new Date('2024-12-08'),
          notes: 'All personal documents collected',
        },
        {
          milestoneId: 'ms-002',
          milestoneName: 'Obtain Employment Letter',
          status: 'in_progress',
          dueDate: new Date('2024-12-20'),
          notes: 'Waiting for final approval',
        },
      ],
    },
    stages: [
      {
        stageId: 'stage-001',
        stageName: 'Application Initiation',
        stageNumber: 1,
        stageStatus: 'completed',
        startDate: new Date('2024-11-15'),
        endDate: new Date('2024-11-30'),
        expectedEndDate: new Date('2024-11-30'),
        completionPercentage: 100,
        assignedTo: 'hr-specialist-001',
        assignedToName: 'Jennifer Lopez',
        milestones: [],
      },
      {
        stageId: 'stage-002',
        stageName: 'Document Collection',
        stageNumber: 2,
        stageStatus: 'in_progress',
        startDate: new Date('2024-12-01'),
        expectedEndDate: new Date('2024-12-31'),
        completionPercentage: 65,
        assignedTo: 'hr-specialist-001',
        assignedToName: 'Jennifer Lopez',
        milestones: [
          {
            milestoneId: 'ms-001',
            milestoneName: 'Gather Personal Documents',
            status: 'completed',
            dueDate: new Date('2024-12-10'),
            completedDate: new Date('2024-12-08'),
            notes: 'All personal documents collected',
          },
          {
            milestoneId: 'ms-002',
            milestoneName: 'Obtain Employment Letter',
            status: 'in_progress',
            dueDate: new Date('2024-12-20'),
            notes: 'Waiting for final approval',
          },
        ],
      },
      {
        stageId: 'stage-003',
        stageName: 'Application Submission',
        stageNumber: 3,
        stageStatus: 'pending',
        expectedEndDate: new Date('2025-01-15'),
        completionPercentage: 0,
        assignedTo: 'immigration-team',
        assignedToName: 'Immigration Team',
        milestones: [],
      },
      {
        stageId: 'stage-004',
        stageName: 'Government Processing',
        stageNumber: 4,
        stageStatus: 'pending',
        expectedEndDate: new Date('2025-02-15'),
        completionPercentage: 0,
        assignedTo: 'immigration-team',
        assignedToName: 'Immigration Team',
        milestones: [],
      },
      {
        stageId: 'stage-005',
        stageName: 'Visa Issuance',
        stageNumber: 5,
        stageStatus: 'pending',
        expectedEndDate: new Date('2025-02-28'),
        completionPercentage: 0,
        assignedTo: 'immigration-team',
        assignedToName: 'Immigration Team',
        milestones: [],
      },
    ],
    requiredDocuments: [
      {
        documentId: 'doc-req-001',
        documentName: 'Passport Copy',
        documentType: 'identity',
        isMandatory: true,
        isSubmitted: true,
        submittedDate: new Date('2024-12-05'),
        validUntil: new Date('2030-05-15'),
        notes: 'Valid until 2030',
      },
      {
        documentId: 'doc-req-002',
        documentName: 'Employment Letter',
        documentType: 'employment',
        isMandatory: true,
        isSubmitted: false,
        notes: 'Pending final approval',
      },
      {
        documentId: 'doc-req-003',
        documentName: 'Educational Certificates',
        documentType: 'educational',
        isMandatory: true,
        isSubmitted: true,
        submittedDate: new Date('2024-12-06'),
        notes: "Bachelor's and Master's degrees",
      },
      {
        documentId: 'doc-req-004',
        documentName: 'Medical Certificate',
        documentType: 'medical',
        isMandatory: true,
        isSubmitted: false,
        notes: 'Appointment scheduled for Dec 18',
      },
      {
        documentId: 'doc-req-005',
        documentName: 'Police Clearance Certificate',
        documentType: 'legal',
        isMandatory: true,
        isSubmitted: false,
        notes: 'Applied on Dec 10',
      },
    ],
    submittedDocuments: [
      {
        documentId: 'doc-001',
        documentName: 'Passport Copy',
        documentType: 'identity',
        fileUrl: '/documents/passport-sarah-mitchell.pdf',
        fileSize: 2456789,
        uploadedDate: new Date('2024-12-05'),
        uploadedBy: 'emp-001',
        uploadedByName: 'Sarah Mitchell',
        verificationStatus: 'verified',
        verifiedBy: 'hr-specialist-001',
        verifiedByName: 'Jennifer Lopez',
        verifiedDate: new Date('2024-12-05'),
        expiryDate: new Date('2030-05-15'),
      },
      {
        documentId: 'doc-002',
        documentName: 'Educational Certificates',
        documentType: 'educational',
        fileUrl: '/documents/education-sarah-mitchell.pdf',
        fileSize: 3567890,
        uploadedDate: new Date('2024-12-06'),
        uploadedBy: 'emp-001',
        uploadedByName: 'Sarah Mitchell',
        verificationStatus: 'verified',
        verifiedBy: 'hr-specialist-001',
        verifiedByName: 'Jennifer Lopez',
        verifiedDate: new Date('2024-12-06'),
      },
    ],
    dependents: [
      {
        dependentId: 'dep-001',
        firstName: 'John',
        lastName: 'Mitchell',
        relationship: 'spouse',
        dateOfBirth: new Date('1988-07-22'),
        nationality: 'United States',
        passportNumber: 'US8765432',
        passportExpiry: new Date('2029-08-15'),
        includeInVisa: true,
        visaStatus: 'pending',
      },
      {
        dependentId: 'dep-002',
        firstName: 'Emma',
        lastName: 'Mitchell',
        relationship: 'child',
        dateOfBirth: new Date('2018-03-15'),
        nationality: 'United States',
        passportNumber: 'US7654321',
        passportExpiry: new Date('2028-04-20'),
        includeInVisa: true,
        visaStatus: 'pending',
      },
    ],
    sponsoringEntity: 'TechCorp UK Ltd',
    sponsorLicenseNumber: 'SPL-12345',
    estimatedCost: 8500,
    actualCost: 3200,
    totalCost: 3200,
    currency: 'USD',
    costBreakdown: [
      {
        category: 'Application Fees',
        description: 'Government visa application fees',
        amount: 1500,
        currency: 'USD',
      },
      {
        category: 'Legal Fees',
        description: 'Immigration attorney consultation',
        amount: 1200,
        currency: 'USD',
      },
      {
        category: 'Medical Examination',
        description: 'Required medical tests',
        amount: 500,
        currency: 'USD',
        isPaid: false,
      },
    ],
    applicationDate: new Date('2024-11-15'),
    expectedProcessingTime: 90,
    priority: 'high' as Priority,
    notes: 'Fast-track processing requested for key technical hire',
    createdDate: new Date('2024-11-15'),
    createdBy: 'hr-specialist-001',
    createdByName: 'Jennifer Lopez',
    lastUpdatedDate: new Date('2024-12-13'),
    lastUpdatedBy: 'hr-specialist-001',
    lastUpdatedByName: 'Jennifer Lopez',
  },
  {
    applicationId: 'visa-002',
    applicationNumber: 'VA-2024-002',
    applicationStatus: 'approved' as VisaApplicationStatus,
    employeeId: 'emp-002',
    employeeName: 'Raj Patel',
    visaType: 'intra_company_transfer' as VisaType,
    destinationCountry: 'Singapore',
    originCountry: 'India',
    assignmentType: 'short_term',
    assignmentStartDate: new Date('2025-01-15'),
    assignmentEndDate: new Date('2025-07-15'),
    currentStage: {
      stageId: 'stage-005',
      stageName: 'Visa Issuance',
      stageNumber: 5,
      stageStatus: 'completed',
      startDate: new Date('2024-11-25'),
      endDate: new Date('2024-12-05'),
      expectedEndDate: new Date('2024-12-10'),
      completionPercentage: 100,
      assignedTo: 'immigration-team',
      assignedToName: 'Immigration Team',
      milestones: [],
    },
    stages: [
      {
        stageId: 'stage-001',
        stageName: 'Application Initiation',
        stageNumber: 1,
        stageStatus: 'completed',
        startDate: new Date('2024-10-01'),
        endDate: new Date('2024-10-10'),
        expectedEndDate: new Date('2024-10-10'),
        completionPercentage: 100,
        assignedTo: 'hr-specialist-002',
        assignedToName: 'Michael Chen',
        milestones: [],
      },
      {
        stageId: 'stage-002',
        stageName: 'Document Collection',
        stageNumber: 2,
        stageStatus: 'completed',
        startDate: new Date('2024-10-11'),
        endDate: new Date('2024-10-25'),
        expectedEndDate: new Date('2024-10-31'),
        completionPercentage: 100,
        assignedTo: 'hr-specialist-002',
        assignedToName: 'Michael Chen',
        milestones: [],
      },
      {
        stageId: 'stage-003',
        stageName: 'Application Submission',
        stageNumber: 3,
        stageStatus: 'completed',
        startDate: new Date('2024-10-26'),
        endDate: new Date('2024-11-05'),
        expectedEndDate: new Date('2024-11-10'),
        completionPercentage: 100,
        assignedTo: 'immigration-team',
        assignedToName: 'Immigration Team',
        milestones: [],
      },
      {
        stageId: 'stage-004',
        stageName: 'Government Processing',
        stageNumber: 4,
        stageStatus: 'completed',
        startDate: new Date('2024-11-06'),
        endDate: new Date('2024-11-24'),
        expectedEndDate: new Date('2024-11-30'),
        completionPercentage: 100,
        assignedTo: 'immigration-team',
        assignedToName: 'Immigration Team',
        milestones: [],
      },
      {
        stageId: 'stage-005',
        stageName: 'Visa Issuance',
        stageNumber: 5,
        stageStatus: 'completed',
        startDate: new Date('2024-11-25'),
        endDate: new Date('2024-12-05'),
        expectedEndDate: new Date('2024-12-10'),
        completionPercentage: 100,
        assignedTo: 'immigration-team',
        assignedToName: 'Immigration Team',
        milestones: [],
      },
    ],
    requiredDocuments: [
      {
        documentId: 'doc-req-006',
        documentName: 'Passport Copy',
        documentType: 'identity',
        isMandatory: true,
        isSubmitted: true,
        submittedDate: new Date('2024-10-12'),
        validUntil: new Date('2028-06-20'),
      },
      {
        documentId: 'doc-req-007',
        documentName: 'Employment Letter',
        documentType: 'employment',
        isMandatory: true,
        isSubmitted: true,
        submittedDate: new Date('2024-10-15'),
      },
      {
        documentId: 'doc-req-008',
        documentName: 'Educational Certificates',
        documentType: 'educational',
        isMandatory: true,
        isSubmitted: true,
        submittedDate: new Date('2024-10-14'),
      },
    ],
    submittedDocuments: [
      {
        documentId: 'doc-003',
        documentName: 'Passport Copy',
        documentType: 'identity',
        fileUrl: '/documents/passport-raj-patel.pdf',
        fileSize: 2234567,
        uploadedDate: new Date('2024-10-12'),
        uploadedBy: 'emp-002',
        uploadedByName: 'Raj Patel',
        verificationStatus: 'verified',
        verifiedBy: 'hr-specialist-002',
        verifiedByName: 'Michael Chen',
        verifiedDate: new Date('2024-10-12'),
        expiryDate: new Date('2028-06-20'),
      },
    ],
    dependents: [],
    sponsoringEntity: 'TechCorp Singapore Pte Ltd',
    sponsorLicenseNumber: 'SPL-SG-67890',
    estimatedCost: 4500,
    actualCost: 4200,
    totalCost: 4200,
    currency: 'USD',
    costBreakdown: [
      {
        category: 'Application Fees',
        description: 'Government visa application fees',
        amount: 800,
        currency: 'USD',
        isPaid: true,
        paidDate: new Date('2024-10-26'),
      },
      {
        category: 'Legal Fees',
        description: 'Immigration attorney consultation',
        amount: 2500,
        currency: 'USD',
        isPaid: true,
        paidDate: new Date('2024-10-20'),
      },
      {
        category: 'Document Processing',
        description: 'Notarization and authentication',
        amount: 900,
        currency: 'USD',
        isPaid: true,
        paidDate: new Date('2024-10-18'),
      },
    ],
    applicationDate: new Date('2024-10-01'),
    submissionDate: new Date('2024-10-26'),
    approvalDate: new Date('2024-11-24'),
    visaNumber: 'SG-2024-ICT-5678',
    visaIssueDate: new Date('2024-12-05'),
    visaExpiryDate: new Date('2025-07-15'),
    expectedProcessingTime: 45,
    actualProcessingTime: 49,
    priority: 'medium' as Priority,
    notes: 'Intra-company transfer for 6-month project',
    createdDate: new Date('2024-10-01'),
    createdBy: 'hr-specialist-002',
    createdByName: 'Michael Chen',
    lastUpdatedDate: new Date('2024-12-05'),
    lastUpdatedBy: 'immigration-team',
    lastUpdatedByName: 'Immigration Team',
  },
];

// Sample Immigration Compliance
export const sampleImmigrationCompliance: ImmigrationCompliance[] = [
  {
    complianceId: 'comp-001',
    employeeId: 'emp-001',
    employeeName: 'Sarah Mitchell',
    country: 'United Kingdom',
    visaType: 'work_permit' as VisaType,
    visaStatus: 'pending',
    visaExpiryDate: new Date('2027-03-01'),
    workAuthorizationStatus: 'pending',
    complianceStatus: 'pending',
    requirements: [
      {
        requirementId: 'req-001',
        requirementName: 'Valid Work Permit',
        category: 'visa',
        status: 'pending',
        dueDate: new Date('2025-02-28'),
        description: 'Obtain valid UK work permit before assignment start',
      },
      {
        requirementId: 'req-002',
        requirementName: 'Right to Work Check',
        category: 'work_authorization',
        status: 'pending',
        dueDate: new Date('2025-02-28'),
        description: 'Complete right to work verification',
      },
    ],
    upcomingDeadlines: [
      {
        deadlineId: 'deadline-001',
        deadlineName: 'Visa Application Submission',
        deadlineDate: new Date('2025-01-15'),
        category: 'visa',
        priority: 'high' as Priority,
        status: 'upcoming',
      },
    ],
    alerts: [
      {
        alertId: 'alert-001',
        alertType: 'warning',
        alertDate: new Date('2024-12-13'),
        message: 'Visa application in progress - ensure submission by Jan 15, 2025',
        category: 'visa',
        isRead: false,
      },
    ],
    lastReviewDate: new Date('2024-12-01'),
    nextReviewDate: new Date('2025-01-01'),
    reviewedBy: 'hr-specialist-001',
    reviewedByName: 'Jennifer Lopez',
  },
  {
    complianceId: 'comp-002',
    employeeId: 'emp-002',
    employeeName: 'Raj Patel',
    country: 'Singapore',
    visaType: 'intra_company_transfer' as VisaType,
    visaNumber: 'SG-2024-ICT-5678',
    visaIssueDate: new Date('2024-12-05'),
    visaExpiryDate: new Date('2025-07-15'),
    visaStatus: 'active',
    workAuthorizationStatus: 'authorized',
    complianceStatus: 'compliant',
    requirements: [
      {
        requirementId: 'req-003',
        requirementName: 'Valid Work Permit',
        category: 'visa',
        status: 'completed',
        completionDate: new Date('2024-12-05'),
        description: 'Obtain valid Singapore work permit',
      },
      {
        requirementId: 'req-004',
        requirementName: 'Employment Pass Collection',
        category: 'work_authorization',
        status: 'pending',
        dueDate: new Date('2025-01-10'),
        description: 'Collect physical employment pass upon arrival',
      },
    ],
    upcomingDeadlines: [
      {
        deadlineId: 'deadline-002',
        deadlineName: 'Employment Pass Collection',
        deadlineDate: new Date('2025-01-10'),
        category: 'work_authorization',
        priority: 'medium' as Priority,
        status: 'upcoming',
      },
    ],
    alerts: [],
    lastReviewDate: new Date('2024-12-10'),
    nextReviewDate: new Date('2025-01-10'),
    reviewedBy: 'hr-specialist-002',
    reviewedByName: 'Michael Chen',
  },
];

// Sample Relocation Packages
export const sampleRelocationPackages: RelocationPackage[] = [
  {
    packageId: 'relo-001',
    packageNumber: 'RP-2024-001',
    employeeId: 'emp-001',
    employeeName: 'Sarah Mitchell',
    employeeLevel: 'Senior',
    employeeGrade: 'L5',
    assignmentType: 'international',
    relocationType: 'permanent',
    originLocation: {
      addressId: 'addr-001',
      addressLine1: '123 Tech Street',
      city: 'San Francisco',
      state: 'California',
      country: 'United States',
      postalCode: '94105',
    },
    destinationLocation: {
      addressId: 'addr-002',
      addressLine1: '456 Innovation Road',
      city: 'London',
      state: 'England',
      country: 'United Kingdom',
      postalCode: 'EC1A 1BB',
    },
    moveDate: new Date('2025-03-01'),
    packageStatus: 'planning',
    benefits: [
      {
        benefitId: 'benefit-001',
        benefitName: 'Temporary Housing',
        benefitType: 'housing',
        description: '90 days of temporary housing in serviced apartment',
        value: 15000,
        currency: 'USD',
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-05-30'),
        status: 'pending',
      },
      {
        benefitId: 'benefit-002',
        benefitName: 'Home Finding Trip',
        benefitType: 'travel',
        description: '7-day trip to search for permanent housing',
        value: 3500,
        currency: 'USD',
        status: 'pending',
      },
      {
        benefitId: 'benefit-003',
        benefitName: 'Household Goods Shipment',
        benefitType: 'shipping',
        description: 'Full container shipment of household goods',
        value: 12000,
        currency: 'USD',
        status: 'pending',
      },
      {
        benefitId: 'benefit-004',
        benefitName: 'Cost of Living Allowance',
        benefitType: 'allowance',
        description: 'Monthly COLA to offset cost differences',
        value: 2000,
        currency: 'USD',
        frequency: 'monthly',
        duration: 24,
        status: 'pending',
      },
    ],
    services: [
      {
        serviceId: 'service-001',
        serviceName: 'Destination Services',
        serviceType: 'destination_services',
        description: 'Orientation, area tours, school search, settling-in assistance',
        provider: 'Global Relocation Services Ltd',
        status: 'pending',
        scheduledDate: new Date('2025-03-01'),
        cost: 4500,
        currency: 'USD',
      },
      {
        serviceId: 'service-002',
        serviceName: 'Immigration Assistance',
        serviceType: 'immigration',
        description: 'Visa application and work permit processing',
        provider: 'Immigration Law Partners',
        status: 'in_progress',
        startDate: new Date('2024-11-15'),
        cost: 8500,
        currency: 'USD',
      },
      {
        serviceId: 'service-003',
        serviceName: 'Cultural Training',
        serviceType: 'cultural_training',
        description: 'UK culture and business etiquette training',
        provider: 'Cultural Bridges Inc',
        status: 'pending',
        scheduledDate: new Date('2025-02-15'),
        cost: 2500,
        currency: 'USD',
      },
    ],
    allowances: [
      {
        allowanceId: 'allow-001',
        allowanceName: 'Miscellaneous Allowance',
        allowanceType: 'miscellaneous',
        description: 'One-time allowance for incidental expenses',
        amount: 5000,
        currency: 'USD',
        frequency: 'one_time',
        status: 'pending',
      },
      {
        allowanceId: 'allow-002',
        allowanceName: 'Storage Allowance',
        allowanceType: 'storage',
        description: 'Storage of household goods for 12 months',
        amount: 300,
        currency: 'USD',
        frequency: 'monthly',
        duration: 12,
        status: 'pending',
      },
    ],
    approvedBudget: 75000,
    actualSpent: 11200,
    committedCost: 15500,
    remainingBudget: 48300,
    currency: 'USD',
    phases: [
      {
        phaseId: 'phase-001',
        phaseName: 'Pre-Move',
        phaseNumber: 1,
        status: 'in_progress',
        startDate: new Date('2024-11-15'),
        endDate: new Date('2025-02-28'),
        tasks: ['Immigration processing', 'Home finding trip', 'Cultural training', 'Shipment arrangement'],
        completionPercentage: 35,
      },
      {
        phaseId: 'phase-002',
        phaseName: 'Move',
        phaseNumber: 2,
        status: 'pending',
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-03-07'),
        tasks: ['Travel to destination', 'Temporary housing check-in', 'Initial orientation'],
        completionPercentage: 0,
      },
      {
        phaseId: 'phase-003',
        phaseName: 'Post-Move',
        phaseNumber: 3,
        status: 'pending',
        startDate: new Date('2025-03-08'),
        endDate: new Date('2025-06-01'),
        tasks: ['Permanent housing search', 'Household goods delivery', 'School enrollment', 'Settling-in'],
        completionPercentage: 0,
      },
    ],
    tasks: [
      {
        taskId: 'task-001',
        taskName: 'Complete visa application',
        taskType: 'immigration',
        priority: 'high' as Priority,
        status: 'in_progress',
        dueDate: new Date('2025-01-15'),
        assignedTo: 'immigration-team',
        assignedToName: 'Immigration Team',
        completionPercentage: 65,
        notes: 'Document collection phase ongoing',
      },
      {
        taskId: 'task-002',
        taskName: 'Book home finding trip',
        taskType: 'housing',
        priority: 'high' as Priority,
        status: 'pending',
        dueDate: new Date('2025-02-01'),
        assignedTo: 'relo-coordinator',
        assignedToName: 'Emma Wilson',
        notes: 'Waiting for visa approval before booking',
      },
      {
        taskId: 'task-003',
        taskName: 'Arrange household goods shipment',
        taskType: 'shipping',
        priority: 'medium' as Priority,
        status: 'pending',
        dueDate: new Date('2025-02-15'),
        assignedTo: 'relo-coordinator',
        assignedToName: 'Emma Wilson',
      },
      {
        taskId: 'task-004',
        taskName: 'Schedule cultural training',
        taskType: 'cultural_training',
        priority: 'medium' as Priority,
        status: 'pending',
        dueDate: new Date('2025-02-15'),
        assignedTo: 'relo-coordinator',
        assignedToName: 'Emma Wilson',
      },
    ],
    vendors: [
      {
        vendorId: 'vendor-001',
        vendorName: 'Global Relocation Services Ltd',
        vendorType: 'destination_services',
        serviceProvided: 'Destination services and orientation',
        contactPerson: 'James Thompson',
        contactEmail: 'james.thompson@globalrelo.com',
        contactPhone: '+44-20-1234-5678',
        status: 'active',
        contractValue: 4500,
        currency: 'USD',
      },
      {
        vendorId: 'vendor-002',
        vendorName: 'Immigration Law Partners',
        vendorType: 'immigration',
        serviceProvided: 'Visa and immigration services',
        contactPerson: 'Sarah Johnson',
        contactEmail: 'sarah.johnson@immilaw.com',
        contactPhone: '+44-20-8765-4321',
        status: 'active',
        contractValue: 8500,
        currency: 'USD',
      },
      {
        vendorId: 'vendor-003',
        vendorName: 'International Moving Co',
        vendorType: 'moving',
        serviceProvided: 'Household goods shipping and storage',
        contactPerson: 'Michael Davis',
        contactEmail: 'michael.davis@intlmoving.com',
        contactPhone: '+1-415-555-0123',
        status: 'active',
        contractValue: 12000,
        currency: 'USD',
      },
    ],
    expenses: [
      {
        expenseId: 'exp-001',
        expenseDate: new Date('2024-11-20'),
        expenseType: 'immigration',
        description: 'Initial immigration consultation',
        amount: 1200,
        currency: 'USD',
        vendor: 'Immigration Law Partners',
        status: 'approved',
        approvedDate: new Date('2024-11-22'),
        paidDate: new Date('2024-11-25'),
      },
      {
        expenseId: 'exp-002',
        expenseDate: new Date('2024-12-05'),
        expenseType: 'immigration',
        description: 'Visa application government fees',
        amount: 1500,
        currency: 'USD',
        vendor: 'UK Home Office',
        status: 'approved',
        approvedDate: new Date('2024-12-06'),
        paidDate: new Date('2024-12-08'),
      },
      {
        expenseId: 'exp-003',
        expenseDate: new Date('2024-12-10'),
        expenseType: 'cultural_training',
        description: 'Cultural training deposit',
        amount: 500,
        currency: 'USD',
        vendor: 'Cultural Bridges Inc',
        status: 'pending',
      },
    ],
    familyMembers: [
      {
        memberId: 'fam-001',
        firstName: 'John',
        lastName: 'Mitchell',
        relationship: 'spouse',
        dateOfBirth: new Date('1988-07-22'),
        isRelocating: true,
      },
      {
        memberId: 'fam-002',
        firstName: 'Emma',
        lastName: 'Mitchell',
        relationship: 'child',
        dateOfBirth: new Date('2018-03-15'),
        isRelocating: true,
      },
    ],
    coordinator: 'relo-coordinator',
    coordinatorName: 'Emma Wilson',
    coordinatorEmail: 'emma.wilson@company.com',
    coordinatorPhone: '+1-650-555-0100',
    notes: 'Family relocation with school-age child - prioritize school search and enrollment assistance',
    createdDate: new Date('2024-11-15'),
    createdBy: 'hr-specialist-001',
    createdByName: 'Jennifer Lopez',
    lastUpdatedDate: new Date('2024-12-13'),
    lastUpdatedBy: 'relo-coordinator',
    lastUpdatedByName: 'Emma Wilson',
  },
  {
    packageId: 'relo-002',
    packageNumber: 'RP-2024-002',
    employeeId: 'emp-002',
    employeeName: 'Raj Patel',
    employeeLevel: 'Mid-Level',
    employeeGrade: 'L4',
    assignmentType: 'international',
    relocationType: 'temporary',
    originLocation: {
      addressId: 'addr-003',
      addressLine1: '789 Tech Park',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
      postalCode: '560001',
    },
    destinationLocation: {
      addressId: 'addr-004',
      addressLine1: '321 Business Center',
      city: 'Singapore',
      country: 'Singapore',
      postalCode: '018956',
    },
    moveDate: new Date('2025-01-15'),
    packageStatus: 'approved',
    benefits: [
      {
        benefitId: 'benefit-005',
        benefitName: 'Serviced Apartment',
        benefitType: 'housing',
        description: 'Fully furnished serviced apartment for 6 months',
        value: 4500,
        currency: 'USD',
        frequency: 'monthly',
        duration: 6,
        startDate: new Date('2025-01-15'),
        endDate: new Date('2025-07-15'),
        status: 'approved',
      },
      {
        benefitId: 'benefit-006',
        benefitName: 'Flights',
        benefitType: 'travel',
        description: 'Round-trip business class flights',
        value: 3200,
        currency: 'USD',
        status: 'approved',
      },
      {
        benefitId: 'benefit-007',
        benefitName: 'Per Diem',
        benefitType: 'allowance',
        description: 'Daily living allowance for first 30 days',
        value: 100,
        currency: 'USD',
        frequency: 'daily',
        duration: 30,
        status: 'approved',
      },
    ],
    services: [
      {
        serviceId: 'service-004',
        serviceName: 'Immigration Support',
        serviceType: 'immigration',
        description: 'Intra-company transfer visa processing',
        provider: 'Asia Pacific Immigration Services',
        status: 'completed',
        startDate: new Date('2024-10-01'),
        completionDate: new Date('2024-12-05'),
        cost: 4200,
        currency: 'USD',
      },
      {
        serviceId: 'service-005',
        serviceName: 'Orientation',
        serviceType: 'destination_services',
        description: 'City orientation and settling-in assistance',
        provider: 'Singapore Relocation Services',
        status: 'scheduled',
        scheduledDate: new Date('2025-01-15'),
        cost: 1500,
        currency: 'USD',
      },
    ],
    allowances: [
      {
        allowanceId: 'allow-003',
        allowanceName: 'Setup Allowance',
        allowanceType: 'miscellaneous',
        description: 'One-time allowance for initial setup',
        amount: 2000,
        currency: 'USD',
        frequency: 'one_time',
        status: 'approved',
      },
    ],
    approvedBudget: 40000,
    actualSpent: 4200,
    committedCost: 32700,
    remainingBudget: 3100,
    currency: 'USD',
    phases: [
      {
        phaseId: 'phase-004',
        phaseName: 'Pre-Move',
        phaseNumber: 1,
        status: 'completed',
        startDate: new Date('2024-10-01'),
        endDate: new Date('2025-01-10'),
        tasks: ['Visa processing', 'Flight booking', 'Housing arrangement'],
        completionPercentage: 100,
      },
      {
        phaseId: 'phase-005',
        phaseName: 'Move',
        phaseNumber: 2,
        status: 'pending',
        startDate: new Date('2025-01-15'),
        endDate: new Date('2025-01-20'),
        tasks: ['Travel', 'Apartment check-in', 'Orientation'],
        completionPercentage: 0,
      },
      {
        phaseId: 'phase-006',
        phaseName: 'Assignment',
        phaseNumber: 3,
        status: 'pending',
        startDate: new Date('2025-01-21'),
        endDate: new Date('2025-07-15'),
        tasks: ['Work on project', 'Monthly check-ins'],
        completionPercentage: 0,
      },
    ],
    tasks: [
      {
        taskId: 'task-005',
        taskName: 'Book flights',
        taskType: 'travel',
        priority: 'high' as Priority,
        status: 'completed',
        dueDate: new Date('2024-12-15'),
        completionDate: new Date('2024-12-12'),
        assignedTo: 'relo-coordinator',
        assignedToName: 'Emma Wilson',
        completionPercentage: 100,
      },
      {
        taskId: 'task-006',
        taskName: 'Confirm serviced apartment',
        taskType: 'housing',
        priority: 'high' as Priority,
        status: 'completed',
        dueDate: new Date('2025-01-05'),
        completionDate: new Date('2025-01-03'),
        assignedTo: 'relo-coordinator',
        assignedToName: 'Emma Wilson',
        completionPercentage: 100,
      },
      {
        taskId: 'task-007',
        taskName: 'Schedule orientation',
        taskType: 'destination_services',
        priority: 'medium' as Priority,
        status: 'completed',
        dueDate: new Date('2025-01-10'),
        completionDate: new Date('2025-01-08'),
        assignedTo: 'relo-coordinator',
        assignedToName: 'Emma Wilson',
        completionPercentage: 100,
      },
    ],
    vendors: [
      {
        vendorId: 'vendor-004',
        vendorName: 'Asia Pacific Immigration Services',
        vendorType: 'immigration',
        serviceProvided: 'Visa and immigration processing',
        contactPerson: 'Lisa Wang',
        contactEmail: 'lisa.wang@apimmi.com',
        contactPhone: '+65-6789-1234',
        status: 'active',
        contractValue: 4200,
        currency: 'USD',
      },
      {
        vendorId: 'vendor-005',
        vendorName: 'Singapore Relocation Services',
        vendorType: 'destination_services',
        serviceProvided: 'Orientation and settling-in services',
        contactPerson: 'David Tan',
        contactEmail: 'david.tan@sgrelo.com',
        contactPhone: '+65-6543-2109',
        status: 'active',
        contractValue: 1500,
        currency: 'USD',
      },
    ],
    expenses: [
      {
        expenseId: 'exp-004',
        expenseDate: new Date('2024-10-26'),
        expenseType: 'immigration',
        description: 'Visa application fees',
        amount: 800,
        currency: 'USD',
        vendor: 'Singapore Immigration',
        status: 'approved',
        approvedDate: new Date('2024-10-27'),
        paidDate: new Date('2024-10-30'),
      },
      {
        expenseId: 'exp-005',
        expenseDate: new Date('2024-10-20'),
        expenseType: 'immigration',
        description: 'Immigration services',
        amount: 2500,
        currency: 'USD',
        vendor: 'Asia Pacific Immigration Services',
        status: 'approved',
        approvedDate: new Date('2024-10-22'),
        paidDate: new Date('2024-10-25'),
      },
      {
        expenseId: 'exp-006',
        expenseDate: new Date('2024-12-12'),
        expenseType: 'travel',
        description: 'Round-trip business class flights',
        amount: 3200,
        currency: 'USD',
        vendor: 'Singapore Airlines',
        status: 'approved',
        approvedDate: new Date('2024-12-13'),
        paidDate: new Date('2024-12-14'),
      },
    ],
    familyMembers: [],
    coordinator: 'relo-coordinator',
    coordinatorName: 'Emma Wilson',
    coordinatorEmail: 'emma.wilson@company.com',
    coordinatorPhone: '+1-650-555-0100',
    notes: 'Solo assignment for 6-month project',
    createdDate: new Date('2024-10-01'),
    createdBy: 'hr-specialist-002',
    createdByName: 'Michael Chen',
    lastUpdatedDate: new Date('2025-01-08'),
    lastUpdatedBy: 'relo-coordinator',
    lastUpdatedByName: 'Emma Wilson',
  },
];

// Sample Expat Tax Profiles
export const sampleExpatTaxProfiles: ExpatTaxProfile[] = [
  {
    profileId: 'tax-001',
    employeeId: 'emp-001',
    employeeName: 'Sarah Mitchell',
    assignmentStartDate: new Date('2025-03-01'),
    assignmentEndDate: new Date('2027-03-01'),
    homeCountry: 'United States',
    hostCountry: 'United Kingdom',
    homeCountryTaxResidency: 'resident' as TaxResidencyStatus,
    hostCountryTaxResidency: 'resident' as TaxResidencyStatus,
    taxEqualizationApplicable: true,
    taxEqualizationType: 'tax_protection',
    hypotheticalTax: 35000,
    currentYearTaxLiability: 42000,
    taxBalance: -7000,
    incomeSources: [
      {
        sourceId: 'income-001',
        incomeType: 'base_salary',
        description: 'Base salary',
        homeCountryAmount: 120000,
        hostCountryAmount: 95000,
        currency: 'USD',
        taxableInHomeCountry: true,
        taxableInHostCountry: true,
        taxTreaty: {
          treatyName: 'US-UK Tax Treaty',
          treatyArticle: 'Article 15 - Dependent Personal Services',
          exemptionApplicable: false,
          creditApplicable: true,
        },
      },
      {
        sourceId: 'income-002',
        incomeType: 'bonus',
        description: 'Annual performance bonus',
        homeCountryAmount: 30000,
        hostCountryAmount: 23750,
        currency: 'USD',
        taxableInHomeCountry: true,
        taxableInHostCountry: true,
      },
      {
        sourceId: 'income-003',
        incomeType: 'allowance',
        description: 'Cost of living allowance',
        homeCountryAmount: 0,
        hostCountryAmount: 24000,
        currency: 'USD',
        taxableInHomeCountry: false,
        taxableInHostCountry: true,
      },
    ],
    deductions: [
      {
        deductionId: 'ded-001',
        deductionType: 'housing',
        description: 'Temporary housing costs',
        amount: 15000,
        currency: 'USD',
        applicableCountry: 'host',
        taxYear: 2025,
      },
      {
        deductionId: 'ded-002',
        deductionType: 'moving_expenses',
        description: 'Relocation expenses',
        amount: 12000,
        currency: 'USD',
        applicableCountry: 'host',
        taxYear: 2025,
      },
    ],
    credits: [
      {
        creditId: 'credit-001',
        creditType: 'foreign_tax_credit',
        description: 'Foreign tax credit for UK taxes paid',
        amount: 28000,
        currency: 'USD',
        applicableCountry: 'home',
        taxYear: 2025,
      },
    ],
    taxReturns: [
      {
        returnId: 'return-001',
        taxYear: 2024,
        country: 'United States',
        returnType: 'annual',
        filingStatus: 'pending',
        dueDate: new Date('2025-04-15'),
        totalIncome: 150000,
        totalDeductions: 15000,
        taxableIncome: 135000,
        taxLiability: 35000,
        taxWithheld: 32000,
        taxOwed: 3000,
        currency: 'USD',
      },
    ],
    taxProjections: [
      {
        projectionId: 'proj-001',
        taxYear: 2025,
        country: 'United States',
        projectedIncome: 174000,
        projectedDeductions: 27000,
        projectedTaxableIncome: 147000,
        projectedTaxLiability: 38500,
        projectedWithholding: 36000,
        projectedBalance: -2500,
        currency: 'USD',
        lastUpdatedDate: new Date('2024-12-01'),
      },
      {
        projectionId: 'proj-002',
        taxYear: 2025,
        country: 'United Kingdom',
        projectedIncome: 142750,
        projectedDeductions: 0,
        projectedTaxableIncome: 142750,
        projectedTaxLiability: 42800,
        projectedWithholding: 40000,
        projectedBalance: -2800,
        currency: 'USD',
        lastUpdatedDate: new Date('2024-12-01'),
      },
    ],
    complianceStatus: 'compliant',
    filingRequirements: [
      {
        requirementId: 'filing-001',
        country: 'United States',
        filingType: 'annual_return',
        dueDate: new Date('2025-04-15'),
        status: 'pending',
        description: 'Federal income tax return (Form 1040)',
      },
      {
        requirementId: 'filing-002',
        country: 'United States',
        filingType: 'disclosure',
        dueDate: new Date('2025-04-15'),
        status: 'pending',
        description: 'Foreign Bank Account Report (FBAR)',
      },
      {
        requirementId: 'filing-003',
        country: 'United Kingdom',
        filingType: 'annual_return',
        dueDate: new Date('2026-01-31'),
        status: 'pending',
        description: 'Self Assessment tax return',
      },
    ],
    alerts: [
      {
        alertId: 'tax-alert-001',
        alertType: 'info',
        alertDate: new Date('2024-12-13'),
        message: 'Upcoming filing deadline for 2024 US tax return - April 15, 2025',
        category: 'tax_filing',
        isRead: false,
      },
      {
        alertId: 'tax-alert-002',
        alertType: 'warning',
        alertDate: new Date('2024-12-13'),
        message: 'Ensure proper tax equalization calculations before year-end',
        category: 'tax_compliance',
        isRead: false,
      },
    ],
    taxAdvisor: 'tax-advisor-001',
    taxAdvisorName: 'Robert Anderson',
    taxAdvisorEmail: 'robert.anderson@taxadvisors.com',
    taxAdvisorPhone: '+1-212-555-0150',
    taxAdvisorFirm: 'Global Tax Advisors LLP',
    notes: 'Tax equalization policy in effect - employee held harmless for tax differences',
    createdDate: new Date('2024-11-15'),
    createdBy: 'tax-team',
    createdByName: 'Tax Team',
    lastUpdatedDate: new Date('2024-12-01'),
    lastUpdatedBy: 'tax-advisor-001',
    lastUpdatedByName: 'Robert Anderson',
  },
  {
    profileId: 'tax-002',
    employeeId: 'emp-002',
    employeeName: 'Raj Patel',
    assignmentStartDate: new Date('2025-01-15'),
    assignmentEndDate: new Date('2025-07-15'),
    homeCountry: 'India',
    hostCountry: 'Singapore',
    homeCountryTaxResidency: 'resident' as TaxResidencyStatus,
    hostCountryTaxResidency: 'non_resident' as TaxResidencyStatus,
    taxEqualizationApplicable: false,
    taxEqualizationType: 'laissez_faire',
    hypotheticalTax: 0,
    currentYearTaxLiability: 15000,
    taxBalance: 15000,
    incomeSources: [
      {
        sourceId: 'income-004',
        incomeType: 'base_salary',
        description: 'Base salary',
        homeCountryAmount: 75000,
        hostCountryAmount: 75000,
        currency: 'USD',
        taxableInHomeCountry: true,
        taxableInHostCountry: true,
        taxTreaty: {
          treatyName: 'India-Singapore Tax Treaty',
          treatyArticle: 'Article 15',
          exemptionApplicable: false,
          creditApplicable: true,
        },
      },
      {
        sourceId: 'income-005',
        incomeType: 'allowance',
        description: 'Per diem allowance',
        homeCountryAmount: 0,
        hostCountryAmount: 3000,
        currency: 'USD',
        taxableInHomeCountry: false,
        taxableInHostCountry: false,
      },
    ],
    deductions: [],
    credits: [],
    taxReturns: [],
    taxProjections: [
      {
        projectionId: 'proj-003',
        taxYear: 2025,
        country: 'India',
        projectedIncome: 75000,
        projectedDeductions: 7500,
        projectedTaxableIncome: 67500,
        projectedTaxLiability: 18000,
        projectedWithholding: 15000,
        projectedBalance: -3000,
        currency: 'USD',
        lastUpdatedDate: new Date('2024-12-10'),
      },
      {
        projectionId: 'proj-004',
        taxYear: 2025,
        country: 'Singapore',
        projectedIncome: 37500,
        projectedDeductions: 0,
        projectedTaxableIncome: 37500,
        projectedTaxLiability: 3750,
        projectedWithholding: 3500,
        projectedBalance: -250,
        currency: 'USD',
        lastUpdatedDate: new Date('2024-12-10'),
      },
    ],
    complianceStatus: 'compliant',
    filingRequirements: [
      {
        requirementId: 'filing-004',
        country: 'India',
        filingType: 'annual_return',
        dueDate: new Date('2025-07-31'),
        status: 'pending',
        description: 'Income tax return for FY 2024-25',
      },
      {
        requirementId: 'filing-005',
        country: 'Singapore',
        filingType: 'annual_return',
        dueDate: new Date('2026-04-15'),
        status: 'pending',
        description: 'Tax return for Year of Assessment 2026',
      },
    ],
    alerts: [],
    taxAdvisor: 'tax-advisor-002',
    taxAdvisorName: 'Priya Sharma',
    taxAdvisorEmail: 'priya.sharma@asiatax.com',
    taxAdvisorPhone: '+65-6123-4567',
    taxAdvisorFirm: 'Asia Tax Consultants',
    notes: 'Short-term assignment - laissez-faire approach with employee responsible for own tax affairs',
    createdDate: new Date('2024-10-01'),
    createdBy: 'tax-team',
    createdByName: 'Tax Team',
    lastUpdatedDate: new Date('2024-12-10'),
    lastUpdatedBy: 'tax-advisor-002',
    lastUpdatedByName: 'Priya Sharma',
  },
];

// Sample Mobility Analytics
export const sampleMobilityAnalytics: MobilityAnalytics = {
  totalActiveAssignments: 45,
  totalVisaApplications: 78,
  totalRelocationPackages: 62,
  totalExpatTaxProfiles: 45,
  assignmentsByType: [
    { assignmentType: 'Long-term', count: 28, percentage: 62.2 },
    { assignmentType: 'Short-term', count: 12, percentage: 26.7 },
    { assignmentType: 'Permanent', count: 5, percentage: 11.1 },
  ],
  assignmentsByRegion: [
    { region: 'Europe', count: 18, percentage: 40.0 },
    { region: 'Asia Pacific', count: 15, percentage: 33.3 },
    { region: 'North America', count: 8, percentage: 17.8 },
    { region: 'Middle East', count: 4, percentage: 8.9 },
  ],
  topDestinationCountries: [
    { country: 'United Kingdom', count: 12 },
    { country: 'Singapore', count: 9 },
    { country: 'United States', count: 7 },
    { country: 'Germany', count: 6 },
    { country: 'Australia', count: 5 },
  ],
  topOriginCountries: [
    { country: 'India', count: 15 },
    { country: 'United States', count: 12 },
    { country: 'United Kingdom', count: 8 },
    { country: 'China', count: 6 },
    { country: 'Brazil', count: 4 },
  ],
  visaApplicationsByStatus: [
    { status: 'Approved', count: 32, percentage: 41.0 },
    { status: 'In Progress', count: 25, percentage: 32.1 },
    { status: 'Submitted', count: 12, percentage: 15.4 },
    { status: 'Pending', count: 7, percentage: 9.0 },
    { status: 'Rejected', count: 2, percentage: 2.6 },
  ],
  visaApplicationsByType: [
    { visaType: 'Work Permit', count: 35, percentage: 44.9 },
    { visaType: 'Intra-company Transfer', count: 22, percentage: 28.2 },
    { visaType: 'Business Visa', count: 12, percentage: 15.4 },
    { visaType: 'Skilled Worker', count: 9, percentage: 11.5 },
  ],
  averageVisaProcessingTime: 52,
  visaApprovalRate: 94.2,
  relocationCostsByType: [
    { relocationType: 'International - Permanent', averageCost: 72500, count: 18 },
    { relocationType: 'International - Temporary', averageCost: 38000, count: 28 },
    { relocationType: 'Domestic', averageCost: 15000, count: 16 },
  ],
  totalRelocationBudget: 3850000,
  totalRelocationSpent: 2675000,
  relocationBudgetUtilization: 69.5,
  taxEqualizationCases: 28,
  averageTaxLiability: 38500,
  totalTaxLiability: 1078000,
  complianceRate: 97.8,
  upcomingVisaExpirations: [
    { month: 'Jan 2025', count: 3 },
    { month: 'Feb 2025', count: 5 },
    { month: 'Mar 2025', count: 7 },
    { month: 'Apr 2025', count: 4 },
    { month: 'May 2025', count: 6 },
    { month: 'Jun 2025', count: 8 },
  ],
  upcomingTaxFilingDeadlines: [
    { deadline: '2025-04-15', description: 'US Federal Tax Return', count: 12 },
    { deadline: '2025-05-31', description: 'UK Self Assessment', count: 8 },
    { deadline: '2025-07-31', description: 'India Income Tax Return', count: 15 },
  ],
};

// Sample Mobility Settings
export const sampleMobilitySettings: MobilitySettings = {
  settingsId: 'settings-001',
  visaSettings: {
    autoApprovalEnabled: false,
    autoApprovalThreshold: 0,
    requireDocumentVerification: true,
    allowDependentVisa: true,
    notifyExpiryDaysBefore: 90,
    autoRenewalEnabled: false,
  },
  relocationSettings: {
    budgetApprovalRequired: true,
    budgetApprovalThreshold: 50000,
    allowTemporaryHousing: true,
    maxTemporaryHousingDays: 90,
    allowPermanentHousing: true,
    allowHomeFindingTrip: true,
    maxHomeFindingTripDays: 7,
    allowHouseholdGoodsShipment: true,
    allowStorageReimbursement: true,
    maxStorageMonths: 12,
  },
  taxSettings: {
    taxEqualizationEnabled: true,
    defaultTaxEqualizationType: 'tax_protection',
    hypotheticalTaxRate: 35,
    autoCalculateTaxProjections: true,
    requireTaxAdvisorReview: true,
    notifyFilingDeadlineDaysBefore: 60,
  },
  complianceSettings: {
    autoComplianceChecks: true,
    complianceCheckFrequency: 'monthly',
    requireComplianceReview: true,
    escalateNonCompliance: true,
    escalationDays: 7,
  },
  notificationSettings: {
    notifyOnVisaApproval: true,
    notifyOnVisaRejection: true,
    notifyOnVisaExpiry: true,
    notifyOnRelocationMilestone: true,
    notifyOnTaxDeadline: true,
    notifyOnComplianceIssue: true,
    emailNotifications: true,
    smsNotifications: false,
    inAppNotifications: true,
  },
  workflowSettings: {
    visaApprovalWorkflow: [
      { stepNumber: 1, stepName: 'HR Review', approverRole: 'hr_specialist' },
      { stepNumber: 2, stepName: 'Manager Approval', approverRole: 'manager' },
      { stepNumber: 3, stepName: 'Legal Review', approverRole: 'legal' },
    ],
    relocationApprovalWorkflow: [
      { stepNumber: 1, stepName: 'HR Review', approverRole: 'hr_specialist' },
      { stepNumber: 2, stepName: 'Manager Approval', approverRole: 'manager' },
      { stepNumber: 3, stepName: 'Finance Approval', approverRole: 'finance' },
    ],
  },
  integrationSettings: {
    payrollIntegrationEnabled: false,
    hrisIntegrationEnabled: false,
    expenseIntegrationEnabled: false,
  },
  lastUpdatedDate: new Date('2024-11-01'),
  lastUpdatedBy: 'admin-001',
  lastUpdatedByName: 'System Administrator',
};
