import { CrewMember, PortOperation, OffshoreCompliance, MaritimeSettings } from './types';

export const sampleCrewMembers: CrewMember[] = [{ crewId: 'crew-001', employeeId: 'emp-001', employeeName: 'Captain James Anderson', nationality: 'United Kingdom', rank: 'master', certificates: [{ certificateId: 'cert-001', certificateType: 'Master Unlimited', certificateNumber: 'UK-M-123456', issueDate: '2020-01-15', expiryDate: '2030-01-15', issuingAuthority: 'UK Maritime and Coastguard Agency', status: 'valid' }], seamanBook: { bookNumber: 'UK-SB-789012', issueDate: '2015-01-01', expiryDate: '2030-01-01', issuingCountry: 'United Kingdom' }, medicalCertificate: { certificateNumber: 'MED-2024-001', examDate: '2024-06-01', expiryDate: '2026-06-01', examiner: 'Dr. Maritime Health', fitnessLevel: 'fit' }, contracts: [{ contractId: 'contract-001', contractType: 'rotational', signOnDate: '2024-09-01', signOffDate: '2025-03-01', vesselName: 'MV Ocean Carrier', vesselType: 'Container Ship', position: 'Master', salary: 15000, currency: 'USD', status: 'active' }], seaService: { totalSeaTime: 8760, totalVessels: 15, lastSignOff: '2024-03-01', serviceHistory: [] }, status: 'active', createdAt: '2015-01-01T00:00:00Z' }];

export const samplePortOperations: PortOperation[] = [{ operationId: 'op-001', operationType: 'loading', vesselId: 'vessel-001', vesselName: 'MV Ocean Carrier', portName: 'Port of Singapore', portCode: 'SGSIN', country: 'Singapore', eta: '2024-12-15T08:00:00Z', etd: '2024-12-17T18:00:00Z', cargoDetails: { cargoType: 'Containerized Goods', quantity: 5000, unit: 'TEU', manifests: ['MANIFEST-2024-001'] }, services: [{ serviceType: 'Pilotage', provider: 'Singapore Pilots', cost: 8500, currency: 'USD' }, { serviceType: 'Towage', provider: 'Singapore Tugs', cost: 4200, currency: 'USD' }], costs: [{ costCategory: 'Port Dues', amount: 15000, currency: 'USD', paid: false }], status: 'scheduled', createdAt: '2024-12-01T00:00:00Z' }];

export const sampleOffshoreCompliance: OffshoreCompliance[] = [{ complianceId: 'comp-001', vesselId: 'vessel-001', vesselName: 'MV Ocean Carrier', complianceType: 'safety', regulation: 'SOLAS Safety Management Certificate', inspectionDate: '2024-11-15', inspector: 'Classification Society Inspector', findings: [], correctiveActions: [], status: 'compliant', certificateIssued: true, certificateExpiry: '2025-11-15', createdAt: '2024-11-15T00:00:00Z' }];

export const sampleMaritimeSettings: MaritimeSettings = { settingsId: 'settings-001', organizationId: 'org-001', crewSettings: { certificateExpiryWarningDays: 90, medicalExpiryWarningDays: 60, rotationPeriodDays: 180 }, portSettings: { advanceNoticeDays: 7, costTrackingEnabled: true }, complianceSettings: { inspectionFrequencyDays: 365, autoReminderEnabled: true }, notifications: { certificateExpiring: true, portArrivalAlert: true, complianceIssue: true }, updatedAt: '2024-01-01T00:00:00Z' };
