import { NextRequest, NextResponse } from 'next/server';
import { withEnhancedAuth } from '@/lib/auth';
import { prisma } from '@/lib/database';
import { z } from 'zod';

// Validation schema for creating an employment history record
const createHistorySchema = z.object({
  tenantId: z.string().min(1, 'Tenant ID is required'),
  employeeId: z.string().uuid('Valid employee ID is required'),
  changeType: z.string().min(1, 'Change type is required'), // PROMOTION, DEMOTION, TRANSFER, LATERAL_MOVE, NEW_HIRE, TERMINATION, REHIRE
  effectiveDate: z.string().or(z.date()),
  reason: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  previousDepartmentId: z.string().uuid().optional().nullable(),
  previousJobProfileId: z.string().uuid().optional().nullable(),
  previousGradeId: z.string().uuid().optional().nullable(),
  previousLocationId: z.string().uuid().optional().nullable(),
  previousPositionId: z.string().uuid().optional().nullable(),
  previousManagerId: z.string().uuid().optional().nullable(),
  previousSalary: z.number().or(z.string()).optional().nullable(),
  previousEmploymentType: z.string().optional().nullable(),
  newDepartmentId: z.string().uuid().optional().nullable(),
  newJobProfileId: z.string().uuid().optional().nullable(),
  newGradeId: z.string().uuid().optional().nullable(),
  newLocationId: z.string().uuid().optional().nullable(),
  newPositionId: z.string().uuid().optional().nullable(),
  newManagerId: z.string().uuid().optional().nullable(),
  newSalary: z.number().or(z.string()).optional().nullable(),
  newEmploymentType: z.string().optional().nullable(),
  requestedBy: z.string().optional().nullable(),
  approvedBy: z.string().optional().nullable(),
  approvedAt: z.string().or(z.date()).optional().nullable(),
  status: z.string().optional(),
  isAutoGenerated: z.boolean().optional(),
});

export const GET = withEnhancedAuth(async (request, context) => {
  try {
    const { user } = context;
    const { searchParams } = new URL(request.url);

    const employeeId = searchParams.get('employeeId');
    const changeType = searchParams.get('changeType');
    const page = parseInt(searchParams.get('page') || '1', 10);
    const limit = parseInt(searchParams.get('limit') || '50', 10);
    const skip = (page - 1) * limit;

    // Build where clause
    const where: any = {};

    if (employeeId) {
      where.employeeId = employeeId;
    }

    if (changeType) {
      where.changeType = changeType;
    }

    const [records, total] = await Promise.all([
      prisma.employmentHistory.findMany({
        where,
        include: {
          previousDepartment: {
            select: { id: true, name: true, code: true },
          },
          previousJobProfile: {
            select: { id: true, title: true, code: true },
          },
          previousGrade: {
            select: { id: true, name: true, code: true },
          },
          previousLocation: {
            select: { id: true, name: true },
          },
          newDepartment: {
            select: { id: true, name: true, code: true },
          },
          newJobProfile: {
            select: { id: true, title: true, code: true },
          },
          newGrade: {
            select: { id: true, name: true, code: true },
          },
          newLocation: {
            select: { id: true, name: true },
          },
        },
        orderBy: { effectiveDate: 'desc' },
        skip,
        take: limit,
      }),
      prisma.employmentHistory.count({ where }),
    ]);

    return NextResponse.json(
      {
        history: records,
        pagination: {
          page,
          limit,
          total,
          totalPages: Math.ceil(total / limit),
        },
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('GET /api/core-hr/employment-history error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
});

export const POST = withEnhancedAuth(async (request, context) => {
  try {
    const { user } = context;
    const body = await request.json();

    // Use tenantId from JWT if not provided in body
    const bodyWithTenant = {
      ...body,
      tenantId: body.tenantId || user.tenantId,
    };

    // Validate input
    const validation = createHistorySchema.safeParse(bodyWithTenant);
    if (!validation.success) {
      return NextResponse.json(
        { error: 'Validation failed', details: validation.error.flatten().fieldErrors },
        { status: 400 }
      );
    }

    const data = validation.data;

    // Verify the employee exists
    const employee = await prisma.employee.findUnique({
      where: { id: data.employeeId },
    });

    if (!employee) {
      return NextResponse.json({ error: 'Employee not found' }, { status: 404 });
    }

    const record = await prisma.employmentHistory.create({
      data: {
        tenantId: data.tenantId,
        employeeId: data.employeeId,
        changeType: data.changeType,
        effectiveDate: new Date(data.effectiveDate),
        reason: data.reason ?? undefined,
        notes: data.notes ?? undefined,
        previousDepartmentId: data.previousDepartmentId ?? undefined,
        previousJobProfileId: data.previousJobProfileId ?? undefined,
        previousGradeId: data.previousGradeId ?? undefined,
        previousLocationId: data.previousLocationId ?? undefined,
        previousPositionId: data.previousPositionId ?? undefined,
        previousManagerId: data.previousManagerId ?? undefined,
        previousSalary: data.previousSalary != null ? data.previousSalary : undefined,
        previousEmploymentType: data.previousEmploymentType ?? undefined,
        newDepartmentId: data.newDepartmentId ?? undefined,
        newJobProfileId: data.newJobProfileId ?? undefined,
        newGradeId: data.newGradeId ?? undefined,
        newLocationId: data.newLocationId ?? undefined,
        newPositionId: data.newPositionId ?? undefined,
        newManagerId: data.newManagerId ?? undefined,
        newSalary: data.newSalary != null ? data.newSalary : undefined,
        newEmploymentType: data.newEmploymentType ?? undefined,
        requestedBy: data.requestedBy ?? user.userId,
        approvedBy: data.approvedBy ?? undefined,
        approvedAt: data.approvedAt ? new Date(data.approvedAt as string) : undefined,
        status: data.status || 'COMPLETED',
        isAutoGenerated: data.isAutoGenerated ?? false,
      },
      include: {
        previousDepartment: {
          select: { id: true, name: true, code: true },
        },
        previousJobProfile: {
          select: { id: true, title: true, code: true },
        },
        previousGrade: {
          select: { id: true, name: true, code: true },
        },
        previousLocation: {
          select: { id: true, name: true },
        },
        newDepartment: {
          select: { id: true, name: true, code: true },
        },
        newJobProfile: {
          select: { id: true, title: true, code: true },
        },
        newGrade: {
          select: { id: true, name: true, code: true },
        },
        newLocation: {
          select: { id: true, name: true },
        },
      },
    });

    return NextResponse.json({ record }, { status: 201 });
  } catch (error) {
    console.error('POST /api/core-hr/employment-history error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
});
