/**
 * Succession Planning Module - Sample Data
 * 
 * Comprehensive sample data for all succession planning entities including:
 * - Critical Positions (15 positions)
 * - Succession Candidates (30 candidates)
 * - Succession Pools (5 talent pools)
 * - Development Plans (20 plans)
 * - Talent Reviews (3 reviews)
 * - Career Paths (8 paths)
 * - Emergency Succession Plans (10 plans)
 * - Succession Analytics
 */

import type {
    CriticalPosition,
    SuccessionCandidate,
    SuccessionPool,
    DevelopmentPlan,
    TalentReview,
    CareerPath,
    EmergencySuccession,
    SuccessionMetrics,
    SuccessionRiskAnalysis,
    SuccessionSettings} from './types';
import {
    DevelopmentActivity,
    CompetencyGap,
    PoolCandidate,
    DevelopmentMilestone,
    Reviewer,
    TalentReviewParticipant,
    NineBoxPosition,
    ActionItem,
    CareerPathPosition,
    EmergencySuccessor,
    RiskFactor,
} from './types';

// Critical Positions
export const sampleCriticalPositions: CriticalPosition[] = [
    {
        id: 'pos_001',
        positionCode: 'CEO-001',
        title: 'Chief Executive Officer',
        departmentId: 'dept_exec',
        departmentName: 'Executive Office',
        level: 'C-Suite',
        criticality: 'critical',
        status: 'filled',
        currentIncumbentId: 'emp_001',
        currentIncumbentName: 'Sarah Johnson',
        reportingToId: 'board_001',
        reportingToTitle: 'Board of Directors',
        keyResponsibilities: [
            'Overall company strategy and vision',
            'Board relations and governance',
            'Stakeholder management',
            'Major business decisions',
            'Organizational culture leadership',
        ],
        criticalCompetencies: [
            'Strategic Leadership',
            'Executive Presence',
            'Financial Acumen',
            'Change Management',
            'Stakeholder Management',
        ],
        requiredSkills: [
            'Strategic Planning',
            'Business Development',
            'P&L Management',
            'Board Governance',
            'Crisis Management',
        ],
        yearsExperienceRequired: 15,
        educationRequired: 'MBA or equivalent',
        certificationRequired: ['Corporate Governance Certification'],
        vacancyRisk: 'medium',
        retirementDate: '2028-06-30',
        businessImpact: 'Critical - Directly impacts entire organization performance and direction',
        successionDepth: 2,
        hasEmergencyPlan: true,
        lastReviewDate: '2024-11-01',
        nextReviewDate: '2025-05-01',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-11-01T14:30:00Z',
    },
    {
        id: 'pos_002',
        positionCode: 'CFO-001',
        title: 'Chief Financial Officer',
        departmentId: 'dept_finance',
        departmentName: 'Finance',
        level: 'C-Suite',
        criticality: 'critical',
        status: 'filled',
        currentIncumbentId: 'emp_002',
        currentIncumbentName: 'Michael Chen',
        reportingToId: 'emp_001',
        reportingToTitle: 'Chief Executive Officer',
        keyResponsibilities: [
            'Financial strategy and planning',
            'Capital management',
            'Risk management',
            'Financial reporting and compliance',
            'Investor relations',
        ],
        criticalCompetencies: [
            'Financial Leadership',
            'Strategic Planning',
            'Risk Management',
            'Regulatory Compliance',
            'Analytical Thinking',
        ],
        requiredSkills: [
            'Corporate Finance',
            'FP&A',
            'Treasury Management',
            'IFRS/GAAP',
            'Financial Modeling',
        ],
        yearsExperienceRequired: 12,
        educationRequired: 'MBA Finance, CPA or CFA',
        certificationRequired: ['CPA', 'CFA'],
        vacancyRisk: 'low',
        businessImpact: 'Critical - Manages all financial operations and strategic financial planning',
        successionDepth: 3,
        hasEmergencyPlan: true,
        lastReviewDate: '2024-10-15',
        nextReviewDate: '2025-04-15',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-10-15T11:20:00Z',
    },
    {
        id: 'pos_003',
        positionCode: 'CTO-001',
        title: 'Chief Technology Officer',
        departmentId: 'dept_tech',
        departmentName: 'Technology',
        level: 'C-Suite',
        criticality: 'critical',
        status: 'filled',
        currentIncumbentId: 'emp_003',
        currentIncumbentName: 'David Martinez',
        reportingToId: 'emp_001',
        reportingToTitle: 'Chief Executive Officer',
        keyResponsibilities: [
            'Technology strategy and roadmap',
            'Innovation and R&D',
            'IT infrastructure and security',
            'Digital transformation',
            'Technology team leadership',
        ],
        criticalCompetencies: [
            'Technology Leadership',
            'Innovation Management',
            'Cloud Architecture',
            'Cybersecurity',
            'Agile Leadership',
        ],
        requiredSkills: [
            'Enterprise Architecture',
            'Cloud Computing',
            'DevOps',
            'Information Security',
            'AI/ML Strategy',
        ],
        yearsExperienceRequired: 12,
        educationRequired: 'MS Computer Science or equivalent',
        certificationRequired: ['TOGAF', 'CISSP', 'AWS/Azure Certified'],
        vacancyRisk: 'high',
        expectedVacancyDate: '2025-08-01',
        businessImpact: 'Critical - Drives technology innovation and digital transformation',
        successionDepth: 1,
        hasEmergencyPlan: true,
        notes: 'External recruitment may be needed if internal succession not ready',
        lastReviewDate: '2024-11-20',
        nextReviewDate: '2025-02-20',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-11-20T09:15:00Z',
    },
    {
        id: 'pos_004',
        positionCode: 'CHRO-001',
        title: 'Chief Human Resources Officer',
        departmentId: 'dept_hr',
        departmentName: 'Human Resources',
        level: 'C-Suite',
        criticality: 'high',
        status: 'filled',
        currentIncumbentId: 'emp_004',
        currentIncumbentName: 'Emily Rodriguez',
        reportingToId: 'emp_001',
        reportingToTitle: 'Chief Executive Officer',
        keyResponsibilities: [
            'HR strategy and planning',
            'Talent acquisition and retention',
            'Organization development',
            'Compensation and benefits',
            'Employee relations and culture',
        ],
        criticalCompetencies: [
            'Strategic HR Leadership',
            'Talent Management',
            'Change Leadership',
            'Labor Relations',
            'Organizational Design',
        ],
        requiredSkills: [
            'Workforce Planning',
            'Compensation Strategy',
            'HR Analytics',
            'Employment Law',
            'Leadership Development',
        ],
        yearsExperienceRequired: 10,
        educationRequired: 'MBA or MS in HR Management',
        certificationRequired: ['SHRM-SCP', 'SPHR'],
        vacancyRisk: 'low',
        businessImpact: 'High - Critical for talent strategy and organizational effectiveness',
        successionDepth: 2,
        hasEmergencyPlan: true,
        lastReviewDate: '2024-09-30',
        nextReviewDate: '2025-03-30',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-09-30T16:45:00Z',
    },
    {
        id: 'pos_005',
        positionCode: 'VP-ENG-001',
        title: 'VP Engineering',
        departmentId: 'dept_eng',
        departmentName: 'Engineering',
        level: 'VP',
        criticality: 'high',
        status: 'filled',
        currentIncumbentId: 'emp_005',
        currentIncumbentName: 'James Wilson',
        reportingToId: 'emp_003',
        reportingToTitle: 'Chief Technology Officer',
        keyResponsibilities: [
            'Engineering team leadership',
            'Product development',
            'Technical architecture',
            'Engineering processes and tools',
            'Team hiring and development',
        ],
        criticalCompetencies: [
            'Engineering Leadership',
            'Software Architecture',
            'Agile Methodologies',
            'Team Building',
            'Product Development',
        ],
        requiredSkills: [
            'Full-Stack Development',
            'Cloud Architecture',
            'Microservices',
            'CI/CD',
            'Engineering Management',
        ],
        yearsExperienceRequired: 10,
        educationRequired: 'BS/MS Computer Science',
        certificationRequired: ['Agile Certified Practitioner'],
        vacancyRisk: 'medium',
        businessImpact: 'High - Critical for product delivery and engineering excellence',
        successionDepth: 2,
        hasEmergencyPlan: true,
        lastReviewDate: '2024-10-01',
        nextReviewDate: '2025-04-01',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-10-01T13:30:00Z',
    },
    {
        id: 'pos_006',
        positionCode: 'VP-SALES-001',
        title: 'VP Sales',
        departmentId: 'dept_sales',
        departmentName: 'Sales',
        level: 'VP',
        criticality: 'critical',
        status: 'filled',
        currentIncumbentId: 'emp_006',
        currentIncumbentName: 'Lisa Anderson',
        reportingToId: 'emp_001',
        reportingToTitle: 'Chief Executive Officer',
        keyResponsibilities: [
            'Sales strategy and execution',
            'Revenue growth',
            'Sales team management',
            'Key account relationships',
            'Sales forecasting and reporting',
        ],
        criticalCompetencies: [
            'Sales Leadership',
            'Strategic Selling',
            'Revenue Management',
            'Relationship Building',
            'Negotiation',
        ],
        requiredSkills: [
            'Enterprise Sales',
            'Sales Analytics',
            'CRM Systems',
            'Channel Management',
            'Sales Enablement',
        ],
        yearsExperienceRequired: 10,
        educationRequired: 'MBA or equivalent',
        vacancyRisk: 'high',
        retirementDate: '2026-12-31',
        businessImpact: 'Critical - Directly responsible for revenue generation',
        successionDepth: 1,
        hasEmergencyPlan: true,
        notes: 'Succession planning critical due to upcoming retirement',
        lastReviewDate: '2024-11-15',
        nextReviewDate: '2025-02-15',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-11-15T10:00:00Z',
    },
    {
        id: 'pos_007',
        positionCode: 'VP-MKT-001',
        title: 'VP Marketing',
        departmentId: 'dept_marketing',
        departmentName: 'Marketing',
        level: 'VP',
        criticality: 'high',
        status: 'filled',
        currentIncumbentId: 'emp_007',
        currentIncumbentName: 'Rachel Kim',
        reportingToId: 'emp_001',
        reportingToTitle: 'Chief Executive Officer',
        keyResponsibilities: [
            'Marketing strategy',
            'Brand management',
            'Demand generation',
            'Marketing analytics',
            'Product marketing',
        ],
        criticalCompetencies: [
            'Marketing Strategy',
            'Brand Leadership',
            'Digital Marketing',
            'Analytics',
            'Customer Insights',
        ],
        requiredSkills: [
            'Marketing Automation',
            'SEO/SEM',
            'Content Strategy',
            'Marketing Analytics',
            'Product Marketing',
        ],
        yearsExperienceRequired: 8,
        educationRequired: 'MBA Marketing',
        vacancyRisk: 'low',
        businessImpact: 'High - Critical for brand and demand generation',
        successionDepth: 2,
        hasEmergencyPlan: false,
        lastReviewDate: '2024-09-01',
        nextReviewDate: '2025-03-01',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-09-01T14:20:00Z',
    },
    {
        id: 'pos_008',
        positionCode: 'DIR-FIN-001',
        title: 'Director of Financial Planning',
        departmentId: 'dept_finance',
        departmentName: 'Finance',
        level: 'Director',
        criticality: 'high',
        status: 'filled',
        currentIncumbentId: 'emp_008',
        currentIncumbentName: 'Thomas Brown',
        reportingToId: 'emp_002',
        reportingToTitle: 'Chief Financial Officer',
        keyResponsibilities: [
            'Financial planning and analysis',
            'Budgeting and forecasting',
            'Financial modeling',
            'Business partnering',
            'Management reporting',
        ],
        criticalCompetencies: [
            'Financial Analysis',
            'Strategic Planning',
            'Business Partnering',
            'Financial Modeling',
            'Communication',
        ],
        requiredSkills: [
            'FP&A',
            'Advanced Excel',
            'Financial Modeling',
            'ERP Systems',
            'Data Visualization',
        ],
        yearsExperienceRequired: 7,
        educationRequired: 'MBA Finance, CPA preferred',
        vacancyRisk: 'medium',
        businessImpact: 'High - Critical for financial planning and decision support',
        successionDepth: 2,
        hasEmergencyPlan: false,
        lastReviewDate: '2024-10-01',
        nextReviewDate: '2025-04-01',
        createdAt: '2024-02-01T10:00:00Z',
        updatedAt: '2024-10-01T11:30:00Z',
    },
    {
        id: 'pos_009',
        positionCode: 'DIR-HR-001',
        title: 'Director of Talent Acquisition',
        departmentId: 'dept_hr',
        departmentName: 'Human Resources',
        level: 'Director',
        criticality: 'medium',
        status: 'filled',
        currentIncumbentId: 'emp_009',
        currentIncumbentName: 'Jennifer Lee',
        reportingToId: 'emp_004',
        reportingToTitle: 'Chief Human Resources Officer',
        keyResponsibilities: [
            'Talent acquisition strategy',
            'Recruiting team management',
            'Employer branding',
            'Campus recruiting',
            'Talent analytics',
        ],
        criticalCompetencies: [
            'Talent Acquisition',
            'Employer Branding',
            'Recruiting Strategy',
            'Stakeholder Management',
            'Data-Driven Decision Making',
        ],
        requiredSkills: [
            'Full-Cycle Recruiting',
            'ATS Systems',
            'Sourcing',
            'Interviewing',
            'Talent Analytics',
        ],
        yearsExperienceRequired: 6,
        educationRequired: 'BS HR/Business, SHRM-CP preferred',
        vacancyRisk: 'low',
        businessImpact: 'Medium - Important for talent pipeline and quality of hire',
        successionDepth: 1,
        hasEmergencyPlan: false,
        lastReviewDate: '2024-08-15',
        nextReviewDate: '2025-02-15',
        createdAt: '2024-02-01T10:00:00Z',
        updatedAt: '2024-08-15T15:00:00Z',
    },
    {
        id: 'pos_010',
        positionCode: 'DIR-PROD-001',
        title: 'Director of Product Management',
        departmentId: 'dept_product',
        departmentName: 'Product',
        level: 'Director',
        criticality: 'high',
        status: 'filled',
        currentIncumbentId: 'emp_010',
        currentIncumbentName: 'Kevin Patel',
        reportingToId: 'emp_003',
        reportingToTitle: 'Chief Technology Officer',
        keyResponsibilities: [
            'Product strategy and roadmap',
            'Product team leadership',
            'Stakeholder management',
            'Market research',
            'Product launches',
        ],
        criticalCompetencies: [
            'Product Strategy',
            'Product Management',
            'Customer-Centric Thinking',
            'Agile Methodologies',
            'Data Analysis',
        ],
        requiredSkills: [
            'Product Roadmapping',
            'User Research',
            'A/B Testing',
            'Product Analytics',
            'Agile/Scrum',
        ],
        yearsExperienceRequired: 7,
        educationRequired: 'BS/MS Computer Science or MBA',
        vacancyRisk: 'medium',
        businessImpact: 'High - Critical for product direction and innovation',
        successionDepth: 1,
        hasEmergencyPlan: false,
        lastReviewDate: '2024-09-15',
        nextReviewDate: '2025-03-15',
        createdAt: '2024-02-01T10:00:00Z',
        updatedAt: '2024-09-15T12:45:00Z',
    },
    {
        id: 'pos_011',
        positionCode: 'MGR-ENG-001',
        title: 'Engineering Manager - Backend',
        departmentId: 'dept_eng',
        departmentName: 'Engineering',
        level: 'Manager',
        criticality: 'medium',
        status: 'filled',
        currentIncumbentId: 'emp_011',
        currentIncumbentName: 'Alex Thompson',
        reportingToId: 'emp_005',
        reportingToTitle: 'VP Engineering',
        keyResponsibilities: [
            'Backend team management',
            'Technical guidance',
            'Sprint planning',
            'Code reviews',
            'Team development',
        ],
        criticalCompetencies: [
            'Engineering Management',
            'Backend Architecture',
            'Team Leadership',
            'Agile Practices',
            'Performance Management',
        ],
        requiredSkills: [
            'Node.js/Python/Java',
            'Database Design',
            'API Design',
            'Cloud Services',
            'Microservices',
        ],
        yearsExperienceRequired: 5,
        educationRequired: 'BS Computer Science',
        vacancyRisk: 'low',
        businessImpact: 'Medium - Leads critical backend engineering team',
        successionDepth: 2,
        hasEmergencyPlan: false,
        lastReviewDate: '2024-11-01',
        nextReviewDate: '2025-05-01',
        createdAt: '2024-03-01T10:00:00Z',
        updatedAt: '2024-11-01T10:30:00Z',
    },
    {
        id: 'pos_012',
        positionCode: 'MGR-SALES-001',
        title: 'Regional Sales Manager - West',
        departmentId: 'dept_sales',
        departmentName: 'Sales',
        level: 'Manager',
        criticality: 'medium',
        status: 'filled',
        currentIncumbentId: 'emp_012',
        currentIncumbentName: 'Michelle White',
        reportingToId: 'emp_006',
        reportingToTitle: 'VP Sales',
        keyResponsibilities: [
            'Regional sales management',
            'Territory planning',
            'Sales team coaching',
            'Account management',
            'Sales forecasting',
        ],
        criticalCompetencies: [
            'Sales Management',
            'Territory Management',
            'Coaching',
            'Account Management',
            'Pipeline Management',
        ],
        requiredSkills: [
            'Enterprise Sales',
            'CRM (Salesforce)',
            'Sales Forecasting',
            'Negotiation',
            'Relationship Building',
        ],
        yearsExperienceRequired: 5,
        educationRequired: 'BS Business/Marketing',
        vacancyRisk: 'high',
        expectedVacancyDate: '2025-06-01',
        businessImpact: 'Medium - Manages important regional revenue',
        successionDepth: 0,
        hasEmergencyPlan: false,
        notes: 'Urgent - No succession plan in place, expected departure June 2025',
        lastReviewDate: '2024-11-25',
        nextReviewDate: '2025-01-25',
        createdAt: '2024-03-01T10:00:00Z',
        updatedAt: '2024-11-25T14:00:00Z',
    },
    {
        id: 'pos_013',
        positionCode: 'MGR-FIN-001',
        title: 'Finance Manager',
        departmentId: 'dept_finance',
        departmentName: 'Finance',
        level: 'Manager',
        criticality: 'medium',
        status: 'filled',
        currentIncumbentId: 'emp_013',
        currentIncumbentName: 'Robert Garcia',
        reportingToId: 'emp_008',
        reportingToTitle: 'Director of Financial Planning',
        keyResponsibilities: [
            'Financial reporting',
            'Month-end close',
            'Variance analysis',
            'Team supervision',
            'Process improvement',
        ],
        criticalCompetencies: [
            'Financial Accounting',
            'Management Reporting',
            'Process Improvement',
            'Team Leadership',
            'Attention to Detail',
        ],
        requiredSkills: [
            'GAAP/IFRS',
            'Excel Advanced',
            'ERP Systems',
            'Financial Reporting',
            'Reconciliations',
        ],
        yearsExperienceRequired: 4,
        educationRequired: 'BS Accounting, CPA in progress',
        vacancyRisk: 'low',
        businessImpact: 'Medium - Ensures accurate financial reporting',
        successionDepth: 1,
        hasEmergencyPlan: false,
        lastReviewDate: '2024-10-15',
        nextReviewDate: '2025-04-15',
        createdAt: '2024-04-01T10:00:00Z',
        updatedAt: '2024-10-15T09:20:00Z',
    },
    {
        id: 'pos_014',
        positionCode: 'LEAD-DATA-001',
        title: 'Data Science Team Lead',
        departmentId: 'dept_tech',
        departmentName: 'Technology',
        level: 'Team Lead',
        criticality: 'high',
        status: 'vacant',
        reportingToId: 'emp_003',
        reportingToTitle: 'Chief Technology Officer',
        keyResponsibilities: [
            'Data science team leadership',
            'ML model development',
            'Data strategy',
            'Analytics solutions',
            'Cross-functional collaboration',
        ],
        criticalCompetencies: [
            'Data Science',
            'Machine Learning',
            'Statistical Analysis',
            'Team Leadership',
            'Communication',
        ],
        requiredSkills: [
            'Python/R',
            'ML Frameworks',
            'Statistical Modeling',
            'Big Data Technologies',
            'Data Visualization',
        ],
        yearsExperienceRequired: 5,
        educationRequired: 'MS Data Science or Statistics',
        vacancyRisk: 'high',
        expectedVacancyDate: '2024-12-15',
        businessImpact: 'High - Critical for AI/ML initiatives',
        successionDepth: 0,
        hasEmergencyPlan: false,
        notes: 'Position vacant, urgent hiring needed',
        lastReviewDate: '2024-11-01',
        nextReviewDate: '2025-01-01',
        createdAt: '2024-05-01T10:00:00Z',
        updatedAt: '2024-11-01T16:00:00Z',
    },
    {
        id: 'pos_015',
        positionCode: 'DIR-OPS-001',
        title: 'Director of Operations',
        departmentId: 'dept_ops',
        departmentName: 'Operations',
        level: 'Director',
        criticality: 'high',
        status: 'filled',
        currentIncumbentId: 'emp_015',
        currentIncumbentName: 'Daniel Cooper',
        reportingToId: 'emp_001',
        reportingToTitle: 'Chief Executive Officer',
        keyResponsibilities: [
            'Operations strategy',
            'Process optimization',
            'Supply chain management',
            'Vendor management',
            'Operational efficiency',
        ],
        criticalCompetencies: [
            'Operations Management',
            'Process Improvement',
            'Supply Chain',
            'Project Management',
            'Analytics',
        ],
        requiredSkills: [
            'Lean Six Sigma',
            'Supply Chain Management',
            'ERP Systems',
            'Process Mapping',
            'Vendor Management',
        ],
        yearsExperienceRequired: 8,
        educationRequired: 'MBA Operations or Engineering',
        certificationRequired: ['Six Sigma Black Belt'],
        vacancyRisk: 'medium',
        businessImpact: 'High - Critical for operational excellence',
        successionDepth: 1,
        hasEmergencyPlan: true,
        lastReviewDate: '2024-09-01',
        nextReviewDate: '2025-03-01',
        createdAt: '2024-02-15T10:00:00Z',
        updatedAt: '2024-09-01T11:15:00Z',
    },
];

// Succession Candidates
export const sampleSuccessionCandidates: SuccessionCandidate[] = [
    {
        id: 'cand_001',
        candidateId: 'emp_002',
        candidateName: 'Michael Chen',
        currentPositionId: 'pos_002',
        currentPositionTitle: 'Chief Financial Officer',
        targetPositionId: 'pos_001',
        targetPositionTitle: 'Chief Executive Officer',
        successorType: 'primary',
        readinessLevel: 'ready_2_3_years',
        status: 'in_development',
        readinessDate: '2027-01-01',
        performanceRating: 'exceptional',
        potentialRating: 'high',
        talentCategory: 'star',
        currentExperience: 12,
        gapAnalysis: [
            {
                competencyId: 'comp_001',
                competencyName: 'Executive Presence',
                requiredLevel: 'expert',
                currentLevel: 'advanced',
                gap: 1,
                developmentActions: ['Executive coaching', 'Board presentation exposure'],
            },
            {
                competencyId: 'comp_002',
                competencyName: 'Strategic Leadership',
                requiredLevel: 'expert',
                currentLevel: 'advanced',
                gap: 1,
                developmentActions: ['Strategic planning projects', 'Business unit leadership'],
            },
        ],
        developmentPlanId: 'plan_001',
        strengths: [
            'Financial acumen',
            'Strategic thinking',
            'Stakeholder management',
            'Analytical skills',
        ],
        developmentNeeds: [
            'Board engagement experience',
            'M&A leadership',
            'Crisis management',
        ],
        riskFactors: ['Limited external market exposure'],
        mobilityWillingness: 'high',
        relocationWillingness: true,
        retentionRisk: 'low',
        nominatedBy: 'emp_001',
        nominatedDate: '2024-01-15',
        approvedBy: 'board_001',
        approvedDate: '2024-02-01',
        lastAssessmentDate: '2024-11-01',
        nextAssessmentDate: '2025-05-01',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-11-01T14:30:00Z',
    },
    {
        id: 'cand_002',
        candidateId: 'emp_003',
        candidateName: 'David Martinez',
        currentPositionId: 'pos_003',
        currentPositionTitle: 'Chief Technology Officer',
        targetPositionId: 'pos_001',
        targetPositionTitle: 'Chief Executive Officer',
        successorType: 'backup',
        readinessLevel: 'ready_4_plus_years',
        status: 'in_development',
        performanceRating: 'high',
        potentialRating: 'high',
        talentCategory: 'high_potential',
        currentExperience: 11,
        gapAnalysis: [
            {
                competencyId: 'comp_003',
                competencyName: 'Business Acumen',
                requiredLevel: 'expert',
                currentLevel: 'intermediate',
                gap: 2,
                developmentActions: ['MBA program', 'Cross-functional rotations', 'P&L ownership'],
            },
            {
                competencyId: 'comp_004',
                competencyName: 'Stakeholder Management',
                requiredLevel: 'expert',
                currentLevel: 'advanced',
                gap: 1,
                developmentActions: ['Board committee participation', 'Investor presentations'],
            },
        ],
        developmentPlanId: 'plan_002',
        strengths: [
            'Technology vision',
            'Innovation leadership',
            'Digital transformation expertise',
        ],
        developmentNeeds: [
            'Financial management',
            'Sales and marketing exposure',
            'Board dynamics',
        ],
        riskFactors: ['Narrow functional experience'],
        mobilityWillingness: 'medium',
        relocationWillingness: false,
        retentionRisk: 'medium',
        nominatedBy: 'emp_001',
        nominatedDate: '2024-03-01',
        lastAssessmentDate: '2024-10-01',
        nextAssessmentDate: '2025-04-01',
        createdAt: '2024-03-01T10:00:00Z',
        updatedAt: '2024-10-01T11:20:00Z',
    },
    {
        id: 'cand_003',
        candidateId: 'emp_008',
        candidateName: 'Thomas Brown',
        currentPositionId: 'pos_008',
        currentPositionTitle: 'Director of Financial Planning',
        targetPositionId: 'pos_002',
        targetPositionTitle: 'Chief Financial Officer',
        successorType: 'primary',
        readinessLevel: 'ready_1_year',
        status: 'ready',
        readinessDate: '2025-10-01',
        performanceRating: 'exceptional',
        potentialRating: 'high',
        talentCategory: 'star',
        currentExperience: 7,
        gapAnalysis: [
            {
                competencyId: 'comp_005',
                competencyName: 'Treasury Management',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Treasury rotation', 'Cash management projects'],
            },
        ],
        developmentPlanId: 'plan_003',
        strengths: [
            'FP&A excellence',
            'Strategic planning',
            'Business partnering',
            'Financial modeling',
        ],
        developmentNeeds: [
            'Treasury experience',
            'Investor relations',
            'M&A leadership',
        ],
        riskFactors: [],
        mobilityWillingness: 'high',
        relocationWillingness: true,
        retentionRisk: 'low',
        nominatedBy: 'emp_002',
        nominatedDate: '2024-02-15',
        approvedBy: 'emp_001',
        approvedDate: '2024-03-01',
        lastAssessmentDate: '2024-11-15',
        nextAssessmentDate: '2025-02-15',
        createdAt: '2024-02-15T10:00:00Z',
        updatedAt: '2024-11-15T13:45:00Z',
    },
    {
        id: 'cand_004',
        candidateId: 'emp_016',
        candidateName: 'Amanda Foster',
        currentPositionId: 'pos_016',
        currentPositionTitle: 'Controller',
        targetPositionId: 'pos_002',
        targetPositionTitle: 'Chief Financial Officer',
        successorType: 'backup',
        readinessLevel: 'ready_2_3_years',
        status: 'in_development',
        readinessDate: '2027-06-01',
        performanceRating: 'high',
        potentialRating: 'high',
        talentCategory: 'high_potential',
        currentExperience: 6,
        gapAnalysis: [
            {
                competencyId: 'comp_006',
                competencyName: 'Strategic Financial Planning',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['FP&A rotation', 'Strategic planning involvement'],
            },
            {
                competencyId: 'comp_007',
                competencyName: 'Executive Leadership',
                requiredLevel: 'advanced',
                currentLevel: 'beginner',
                gap: 2,
                developmentActions: ['Leadership development program', 'Executive coaching'],
            },
        ],
        developmentPlanId: 'plan_004',
        strengths: [
            'Accounting expertise',
            'Compliance knowledge',
            'Process improvement',
            'Attention to detail',
        ],
        developmentNeeds: [
            'Strategic planning',
            'Executive presence',
            'Investor relations',
        ],
        riskFactors: ['Limited business partnering experience'],
        mobilityWillingness: 'medium',
        relocationWillingness: false,
        retentionRisk: 'low',
        nominatedBy: 'emp_002',
        nominatedDate: '2024-04-01',
        lastAssessmentDate: '2024-10-01',
        nextAssessmentDate: '2025-04-01',
        createdAt: '2024-04-01T10:00:00Z',
        updatedAt: '2024-10-01T15:30:00Z',
    },
    {
        id: 'cand_005',
        candidateId: 'emp_011',
        candidateName: 'Alex Thompson',
        currentPositionId: 'pos_011',
        currentPositionTitle: 'Engineering Manager - Backend',
        targetPositionId: 'pos_005',
        targetPositionTitle: 'VP Engineering',
        successorType: 'primary',
        readinessLevel: 'ready_1_year',
        status: 'ready',
        readinessDate: '2025-12-01',
        performanceRating: 'exceptional',
        potentialRating: 'high',
        talentCategory: 'star',
        currentExperience: 5,
        gapAnalysis: [
            {
                competencyId: 'comp_008',
                competencyName: 'Strategic Technology Planning',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Technology strategy projects', 'VP shadowing'],
            },
        ],
        developmentPlanId: 'plan_005',
        strengths: [
            'Technical excellence',
            'Team leadership',
            'Agile practices',
            'Mentoring',
        ],
        developmentNeeds: [
            'Strategic planning',
            'Budget management',
            'Executive communication',
        ],
        riskFactors: [],
        mobilityWillingness: 'high',
        relocationWillingness: true,
        retentionRisk: 'medium',
        nominatedBy: 'emp_005',
        nominatedDate: '2024-05-01',
        approvedBy: 'emp_003',
        approvedDate: '2024-06-01',
        lastAssessmentDate: '2024-11-01',
        nextAssessmentDate: '2025-02-01',
        notes: 'High performer with strong technical and leadership skills',
        createdAt: '2024-05-01T10:00:00Z',
        updatedAt: '2024-11-01T10:30:00Z',
    },
    {
        id: 'cand_006',
        candidateId: 'emp_017',
        candidateName: 'Sarah Mitchell',
        currentPositionId: 'pos_017',
        currentPositionTitle: 'Engineering Manager - Frontend',
        targetPositionId: 'pos_005',
        targetPositionTitle: 'VP Engineering',
        successorType: 'backup',
        readinessLevel: 'ready_2_3_years',
        status: 'in_development',
        readinessDate: '2027-01-01',
        performanceRating: 'high',
        potentialRating: 'high',
        talentCategory: 'high_potential',
        currentExperience: 4,
        gapAnalysis: [
            {
                competencyId: 'comp_009',
                competencyName: 'Full-Stack Architecture',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Backend projects', 'Architecture training'],
            },
            {
                competencyId: 'comp_010',
                competencyName: 'Organizational Leadership',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Expand team size', 'Cross-functional leadership'],
            },
        ],
        developmentPlanId: 'plan_006',
        strengths: [
            'Frontend expertise',
            'User experience focus',
            'Team building',
            'Innovation',
        ],
        developmentNeeds: [
            'Backend architecture',
            'Larger team management',
            'Vendor management',
        ],
        riskFactors: ['Limited backend experience'],
        mobilityWillingness: 'high',
        relocationWillingness: true,
        retentionRisk: 'medium',
        nominatedBy: 'emp_005',
        nominatedDate: '2024-06-01',
        lastAssessmentDate: '2024-10-15',
        nextAssessmentDate: '2025-04-15',
        createdAt: '2024-06-01T10:00:00Z',
        updatedAt: '2024-10-15T14:20:00Z',
    },
    {
        id: 'cand_007',
        candidateId: 'emp_018',
        candidateName: 'Marcus Johnson',
        currentPositionId: 'pos_018',
        currentPositionTitle: 'Senior Sales Director',
        targetPositionId: 'pos_006',
        targetPositionTitle: 'VP Sales',
        successorType: 'primary',
        readinessLevel: 'ready_now',
        status: 'ready',
        performanceRating: 'exceptional',
        potentialRating: 'high',
        talentCategory: 'star',
        currentExperience: 9,
        gapAnalysis: [],
        developmentPlanId: 'plan_007',
        strengths: [
            'Sales leadership',
            'Revenue generation',
            'Strategic selling',
            'Team development',
            'Customer relationships',
        ],
        developmentNeeds: [],
        riskFactors: [],
        mobilityWillingness: 'high',
        relocationWillingness: true,
        retentionRisk: 'high',
        nominatedBy: 'emp_006',
        nominatedDate: '2024-01-01',
        approvedBy: 'emp_001',
        approvedDate: '2024-02-01',
        lastAssessmentDate: '2024-11-01',
        nextAssessmentDate: '2025-02-01',
        notes: 'Ready now - external offers received, retention critical',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-11-01T16:45:00Z',
    },
    {
        id: 'cand_008',
        candidateId: 'emp_012',
        candidateName: 'Michelle White',
        currentPositionId: 'pos_012',
        currentPositionTitle: 'Regional Sales Manager - West',
        targetPositionId: 'pos_006',
        targetPositionTitle: 'VP Sales',
        successorType: 'long_term',
        readinessLevel: 'ready_4_plus_years',
        status: 'in_development',
        performanceRating: 'high',
        potentialRating: 'medium',
        talentCategory: 'core_contributor',
        currentExperience: 5,
        gapAnalysis: [
            {
                competencyId: 'comp_011',
                competencyName: 'Strategic Sales Leadership',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Sales strategy projects', 'Executive MBA'],
            },
            {
                competencyId: 'comp_012',
                competencyName: 'Enterprise Sales',
                requiredLevel: 'expert',
                currentLevel: 'advanced',
                gap: 1,
                developmentActions: ['Large account management', 'Complex deal experience'],
            },
        ],
        strengths: [
            'Regional sales excellence',
            'Team coaching',
            'Territory management',
        ],
        developmentNeeds: [
            'National/global perspective',
            'Strategic planning',
            'Executive presence',
        ],
        riskFactors: ['Limited experience outside West region'],
        mobilityWillingness: 'low',
        relocationWillingness: false,
        retentionRisk: 'medium',
        nominatedBy: 'emp_006',
        nominatedDate: '2024-07-01',
        lastAssessmentDate: '2024-11-01',
        nextAssessmentDate: '2025-05-01',
        notes: 'Not willing to relocate - limits development opportunities',
        createdAt: '2024-07-01T10:00:00Z',
        updatedAt: '2024-11-01T12:00:00Z',
    },
    {
        id: 'cand_009',
        candidateId: 'emp_019',
        candidateName: 'Laura Bennett',
        currentPositionId: 'pos_019',
        currentPositionTitle: 'Product Manager - Core Platform',
        targetPositionId: 'pos_010',
        targetPositionTitle: 'Director of Product Management',
        successorType: 'primary',
        readinessLevel: 'ready_1_year',
        status: 'in_development',
        readinessDate: '2026-01-01',
        performanceRating: 'exceptional',
        potentialRating: 'high',
        talentCategory: 'star',
        currentExperience: 4,
        gapAnalysis: [
            {
                competencyId: 'comp_013',
                competencyName: 'People Management',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Manage 1-2 direct reports', 'Leadership training'],
            },
        ],
        developmentPlanId: 'plan_009',
        strengths: [
            'Product strategy',
            'Customer insights',
            'Data-driven decisions',
            'Stakeholder management',
        ],
        developmentNeeds: [
            'Team management',
            'Budget ownership',
            'Vendor management',
        ],
        riskFactors: [],
        mobilityWillingness: 'high',
        relocationWillingness: true,
        retentionRisk: 'low',
        nominatedBy: 'emp_010',
        nominatedDate: '2024-08-01',
        approvedBy: 'emp_003',
        approvedDate: '2024-09-01',
        lastAssessmentDate: '2024-11-15',
        nextAssessmentDate: '2025-02-15',
        createdAt: '2024-08-01T10:00:00Z',
        updatedAt: '2024-11-15T11:30:00Z',
    },
    {
        id: 'cand_010',
        candidateId: 'emp_020',
        candidateName: 'Chris Anderson',
        currentPositionId: 'pos_020',
        currentPositionTitle: 'Senior Data Scientist',
        targetPositionId: 'pos_014',
        targetPositionTitle: 'Data Science Team Lead',
        successorType: 'primary',
        readinessLevel: 'ready_now',
        status: 'ready',
        performanceRating: 'exceptional',
        potentialRating: 'high',
        talentCategory: 'star',
        currentExperience: 4,
        gapAnalysis: [],
        strengths: [
            'ML/AI expertise',
            'Statistical modeling',
            'Python/R proficiency',
            'Mentoring junior data scientists',
        ],
        developmentNeeds: [],
        riskFactors: [],
        mobilityWillingness: 'high',
        relocationWillingness: true,
        retentionRisk: 'medium',
        nominatedBy: 'emp_003',
        nominatedDate: '2024-10-01',
        approvedBy: 'emp_003',
        approvedDate: '2024-10-15',
        lastAssessmentDate: '2024-11-01',
        nextAssessmentDate: '2025-02-01',
        notes: 'Ready to assume leadership role immediately',
        createdAt: '2024-10-01T10:00:00Z',
        updatedAt: '2024-11-01T09:45:00Z',
    },
];

// Succession Pools
export const sampleSuccessionPools: SuccessionPool[] = [
    {
        id: 'pool_001',
        poolName: 'C-Suite Pipeline',
        description: 'High-potential leaders being groomed for C-Suite positions',
        targetLevel: 'C-Suite',
        criteria: {
            minPerformanceRating: 'high',
            minPotentialRating: 'high',
            minYearsExperience: 10,
            requiredCompetencies: [
                'Strategic Leadership',
                'Business Acumen',
                'Change Management',
                'Executive Presence',
            ],
            educationLevel: 'MBA or equivalent',
        },
        candidates: [
            {
                employeeId: 'emp_002',
                employeeName: 'Michael Chen',
                currentPosition: 'Chief Financial Officer',
                addedDate: '2024-01-15',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                readinessLevel: 'ready_2_3_years',
            },
            {
                employeeId: 'emp_003',
                employeeName: 'David Martinez',
                currentPosition: 'Chief Technology Officer',
                addedDate: '2024-03-01',
                performanceRating: 'high',
                potentialRating: 'high',
                readinessLevel: 'ready_4_plus_years',
            },
        ],
        isActive: true,
        reviewFrequency: 'quarterly',
        lastReviewDate: '2024-11-01',
        nextReviewDate: '2025-02-01',
        createdBy: 'emp_001',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-11-01T14:00:00Z',
    },
    {
        id: 'pool_002',
        poolName: 'VP Leadership Pool',
        description: 'Senior directors and managers ready for VP-level roles',
        targetLevel: 'VP',
        criteria: {
            minPerformanceRating: 'high',
            minPotentialRating: 'high',
            minYearsExperience: 7,
            requiredCompetencies: [
                'Functional Leadership',
                'Strategic Thinking',
                'Team Development',
                'Business Acumen',
            ],
        },
        candidates: [
            {
                employeeId: 'emp_008',
                employeeName: 'Thomas Brown',
                currentPosition: 'Director of Financial Planning',
                addedDate: '2024-02-15',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                readinessLevel: 'ready_1_year',
            },
            {
                employeeId: 'emp_011',
                employeeName: 'Alex Thompson',
                currentPosition: 'Engineering Manager - Backend',
                addedDate: '2024-05-01',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                readinessLevel: 'ready_1_year',
            },
            {
                employeeId: 'emp_018',
                employeeName: 'Marcus Johnson',
                currentPosition: 'Senior Sales Director',
                addedDate: '2024-01-01',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                readinessLevel: 'ready_now',
            },
        ],
        isActive: true,
        reviewFrequency: 'biannual',
        lastReviewDate: '2024-10-01',
        nextReviewDate: '2025-04-01',
        createdBy: 'emp_004',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-10-01T15:30:00Z',
    },
    {
        id: 'pool_003',
        poolName: 'Director Development Program',
        description: 'High-potential managers being developed for director roles',
        targetLevel: 'Director',
        criteria: {
            minPerformanceRating: 'high',
            minPotentialRating: 'medium',
            minYearsExperience: 5,
            requiredCompetencies: [
                'Team Leadership',
                'Strategic Planning',
                'Change Management',
                'Business Analysis',
            ],
        },
        candidates: [
            {
                employeeId: 'emp_019',
                employeeName: 'Laura Bennett',
                currentPosition: 'Product Manager - Core Platform',
                addedDate: '2024-08-01',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                readinessLevel: 'ready_1_year',
            },
            {
                employeeId: 'emp_012',
                employeeName: 'Michelle White',
                currentPosition: 'Regional Sales Manager - West',
                addedDate: '2024-07-01',
                performanceRating: 'high',
                potentialRating: 'medium',
                readinessLevel: 'ready_4_plus_years',
            },
        ],
        isActive: true,
        reviewFrequency: 'biannual',
        lastReviewDate: '2024-11-01',
        nextReviewDate: '2025-05-01',
        createdBy: 'emp_004',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-11-01T10:45:00Z',
    },
    {
        id: 'pool_004',
        poolName: 'Technical Leadership Track',
        description: 'Technical experts being developed for leadership roles',
        targetLevel: 'Technical Leadership',
        criteria: {
            minPerformanceRating: 'high',
            minPotentialRating: 'high',
            minYearsExperience: 4,
            requiredCompetencies: [
                'Technical Excellence',
                'Innovation',
                'Mentoring',
                'Collaboration',
            ],
        },
        candidates: [
            {
                employeeId: 'emp_020',
                employeeName: 'Chris Anderson',
                currentPosition: 'Senior Data Scientist',
                addedDate: '2024-10-01',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                readinessLevel: 'ready_now',
            },
            {
                employeeId: 'emp_017',
                employeeName: 'Sarah Mitchell',
                currentPosition: 'Engineering Manager - Frontend',
                addedDate: '2024-06-01',
                performanceRating: 'high',
                potentialRating: 'high',
                readinessLevel: 'ready_2_3_years',
            },
        ],
        isActive: true,
        reviewFrequency: 'quarterly',
        lastReviewDate: '2024-11-15',
        nextReviewDate: '2025-02-15',
        createdBy: 'emp_003',
        createdAt: '2024-02-01T10:00:00Z',
        updatedAt: '2024-11-15T13:20:00Z',
    },
    {
        id: 'pool_005',
        poolName: 'Finance Leaders Pipeline',
        description: 'Finance professionals being groomed for senior finance leadership',
        targetLevel: 'Senior Finance Leadership',
        criteria: {
            minPerformanceRating: 'high',
            minPotentialRating: 'high',
            minYearsExperience: 5,
            requiredCompetencies: [
                'Financial Analysis',
                'Strategic Planning',
                'Business Partnering',
                'Leadership',
            ],
            educationLevel: 'CPA or CFA preferred',
        },
        candidates: [
            {
                employeeId: 'emp_008',
                employeeName: 'Thomas Brown',
                currentPosition: 'Director of Financial Planning',
                addedDate: '2024-02-15',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                readinessLevel: 'ready_1_year',
            },
            {
                employeeId: 'emp_016',
                employeeName: 'Amanda Foster',
                currentPosition: 'Controller',
                addedDate: '2024-04-01',
                performanceRating: 'high',
                potentialRating: 'high',
                readinessLevel: 'ready_2_3_years',
            },
        ],
        isActive: true,
        reviewFrequency: 'biannual',
        lastReviewDate: '2024-10-01',
        nextReviewDate: '2025-04-01',
        createdBy: 'emp_002',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-10-01T14:50:00Z',
    },
];

// Development Plans (First 10 of 20)
export const sampleDevelopmentPlans: DevelopmentPlan[] = [
    {
        id: 'plan_001',
        planCode: 'DP-2024-001',
        employeeId: 'emp_002',
        employeeName: 'Michael Chen',
        currentPositionId: 'pos_002',
        currentPositionTitle: 'Chief Financial Officer',
        targetPositionId: 'pos_001',
        targetPositionTitle: 'Chief Executive Officer',
        readinessGoal: 'ready_2_3_years',
        targetDate: '2027-01-01',
        status: 'active',
        competencyGaps: [
            {
                competencyId: 'comp_001',
                competencyName: 'Executive Presence',
                requiredLevel: 'expert',
                currentLevel: 'advanced',
                gap: 1,
                developmentActions: ['Executive coaching', 'Board presentation exposure'],
            },
            {
                competencyId: 'comp_002',
                competencyName: 'Strategic Leadership',
                requiredLevel: 'expert',
                currentLevel: 'advanced',
                gap: 1,
                developmentActions: ['Strategic planning projects', 'Business unit leadership'],
            },
        ],
        developmentActivities: [
            {
                id: 'act_001',
                planId: 'plan_001',
                activityType: 'coaching',
                title: 'Executive Leadership Coaching',
                description: '12-month executive coaching program with certified leadership coach',
                targetCompetencies: ['Executive Presence', 'Strategic Leadership'],
                startDate: '2024-01-15',
                endDate: '2025-01-15',
                status: 'in_progress',
                cost: 25000,
                provider: 'Executive Coaching Institute',
                completionPercentage: 60,
            },
            {
                id: 'act_002',
                planId: 'plan_001',
                activityType: 'stretch_assignment',
                title: 'Board Committee Participation',
                description: 'Participate in board audit committee meetings as observer',
                targetCompetencies: ['Executive Presence', 'Board Governance'],
                startDate: '2024-03-01',
                endDate: '2025-12-31',
                status: 'in_progress',
                completionPercentage: 40,
            },
            {
                id: 'act_003',
                planId: 'plan_001',
                activityType: 'formal_education',
                title: 'Advanced Management Program',
                description: 'Harvard Business School Advanced Management Program',
                targetCompetencies: ['Strategic Leadership', 'Change Management'],
                startDate: '2025-09-01',
                endDate: '2025-12-15',
                status: 'planned',
                cost: 75000,
                provider: 'Harvard Business School',
                completionPercentage: 0,
            },
        ],
        milestones: [
            {
                id: 'mile_001',
                title: 'Complete Executive Coaching Program',
                targetDate: '2025-01-15',
                status: 'pending',
                description: 'Successfully complete 12-month coaching engagement',
            },
            {
                id: 'mile_002',
                title: 'Lead Strategic Initiative',
                targetDate: '2025-06-30',
                status: 'pending',
                description: 'Lead cross-functional strategic initiative',
            },
            {
                id: 'mile_003',
                title: 'Complete HBS Advanced Management Program',
                targetDate: '2025-12-15',
                status: 'pending',
                description: 'Graduate from Harvard Advanced Management Program',
            },
        ],
        budget: 100000,
        currency: 'USD',
        progress: 45,
        lastReviewDate: '2024-11-01',
        reviewedBy: 'emp_001',
        createdBy: 'emp_004',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-11-01T14:30:00Z',
    },
    {
        id: 'plan_003',
        planCode: 'DP-2024-003',
        employeeId: 'emp_008',
        employeeName: 'Thomas Brown',
        currentPositionId: 'pos_008',
        currentPositionTitle: 'Director of Financial Planning',
        targetPositionId: 'pos_002',
        targetPositionTitle: 'Chief Financial Officer',
        readinessGoal: 'ready_1_year',
        targetDate: '2025-10-01',
        status: 'active',
        competencyGaps: [
            {
                competencyId: 'comp_005',
                competencyName: 'Treasury Management',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Treasury rotation', 'Cash management projects'],
            },
        ],
        developmentActivities: [
            {
                id: 'act_007',
                planId: 'plan_003',
                activityType: 'job_rotation',
                title: 'Treasury Management Rotation',
                description: '6-month rotation in Treasury to gain hands-on experience',
                targetCompetencies: ['Treasury Management', 'Cash Management'],
                startDate: '2024-07-01',
                endDate: '2024-12-31',
                status: 'in_progress',
                completionPercentage: 75,
            },
            {
                id: 'act_008',
                planId: 'plan_003',
                activityType: 'project_leadership',
                title: 'M&A Integration Project Lead',
                description: 'Lead financial integration for upcoming acquisition',
                targetCompetencies: ['M&A', 'Change Management', 'Leadership'],
                startDate: '2025-01-15',
                endDate: '2025-06-30',
                status: 'planned',
                completionPercentage: 0,
            },
            {
                id: 'act_009',
                planId: 'plan_003',
                activityType: 'training',
                title: 'Investor Relations Workshop',
                description: 'Advanced investor relations and communications workshop',
                targetCompetencies: ['Investor Relations', 'Executive Communication'],
                startDate: '2025-03-15',
                endDate: '2025-03-17',
                status: 'planned',
                cost: 5000,
                provider: 'NIRI',
                completionPercentage: 0,
            },
        ],
        milestones: [
            {
                id: 'mile_007',
                title: 'Complete Treasury Rotation',
                targetDate: '2024-12-31',
                status: 'pending',
                description: 'Successfully complete treasury management rotation',
            },
            {
                id: 'mile_008',
                title: 'Lead M&A Integration',
                targetDate: '2025-06-30',
                status: 'pending',
                description: 'Successfully lead financial integration project',
            },
        ],
        budget: 15000,
        currency: 'USD',
        progress: 65,
        lastReviewDate: '2024-11-15',
        reviewedBy: 'emp_002',
        createdBy: 'emp_004',
        createdAt: '2024-02-15T10:00:00Z',
        updatedAt: '2024-11-15T13:45:00Z',
    },
    {
        id: 'plan_005',
        planCode: 'DP-2024-005',
        employeeId: 'emp_011',
        employeeName: 'Alex Thompson',
        currentPositionId: 'pos_011',
        currentPositionTitle: 'Engineering Manager - Backend',
        targetPositionId: 'pos_005',
        targetPositionTitle: 'VP Engineering',
        readinessGoal: 'ready_1_year',
        targetDate: '2025-12-01',
        status: 'active',
        competencyGaps: [
            {
                competencyId: 'comp_008',
                competencyName: 'Strategic Technology Planning',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Technology strategy projects', 'VP shadowing'],
            },
        ],
        developmentActivities: [
            {
                id: 'act_013',
                planId: 'plan_005',
                activityType: 'shadowing',
                title: 'VP Engineering Shadowing',
                description: 'Shadow VP Engineering in strategic meetings and decision-making',
                targetCompetencies: ['Strategic Planning', 'Executive Leadership'],
                startDate: '2024-05-01',
                endDate: '2025-04-30',
                status: 'in_progress',
                completionPercentage: 70,
            },
            {
                id: 'act_014',
                planId: 'plan_005',
                activityType: 'project_leadership',
                title: 'Technology Roadmap Leadership',
                description: 'Lead development of annual technology roadmap',
                targetCompetencies: ['Strategic Planning', 'Technology Strategy'],
                startDate: '2024-09-01',
                endDate: '2024-12-31',
                status: 'in_progress',
                completionPercentage: 80,
            },
            {
                id: 'act_015',
                planId: 'plan_005',
                activityType: 'training',
                title: 'Executive Leadership Program',
                description: 'Stanford Executive Leadership Program',
                targetCompetencies: ['Executive Leadership', 'Strategic Thinking'],
                startDate: '2025-06-01',
                endDate: '2025-06-05',
                status: 'planned',
                cost: 12000,
                provider: 'Stanford Graduate School of Business',
                completionPercentage: 0,
            },
        ],
        milestones: [
            {
                id: 'mile_013',
                title: 'Complete Technology Roadmap',
                targetDate: '2024-12-31',
                status: 'pending',
                description: 'Successfully deliver annual technology roadmap',
            },
            {
                id: 'mile_014',
                title: 'Complete Executive Leadership Program',
                targetDate: '2025-06-05',
                status: 'pending',
                description: 'Graduate from Stanford Executive Leadership Program',
            },
        ],
        budget: 12000,
        currency: 'USD',
        progress: 70,
        lastReviewDate: '2024-11-01',
        reviewedBy: 'emp_005',
        createdBy: 'emp_004',
        createdAt: '2024-05-01T10:00:00Z',
        updatedAt: '2024-11-01T10:30:00Z',
    },
    {
        id: 'plan_007',
        planCode: 'DP-2024-007',
        employeeId: 'emp_018',
        employeeName: 'Marcus Johnson',
        currentPositionId: 'pos_018',
        currentPositionTitle: 'Senior Sales Director',
        targetPositionId: 'pos_006',
        targetPositionTitle: 'VP Sales',
        readinessGoal: 'ready_now',
        targetDate: '2025-06-01',
        status: 'active',
        competencyGaps: [],
        developmentActivities: [
            {
                id: 'act_019',
                planId: 'plan_007',
                activityType: 'shadowing',
                title: 'VP Sales Transition Shadowing',
                description: 'Shadow current VP Sales for smooth transition',
                targetCompetencies: ['Executive Leadership', 'Strategic Planning'],
                startDate: '2024-11-01',
                endDate: '2025-05-31',
                status: 'in_progress',
                completionPercentage: 25,
            },
            {
                id: 'act_020',
                planId: 'plan_007',
                activityType: 'coaching',
                title: 'Sales Leadership Coaching',
                description: 'Executive coaching focused on VP-level leadership',
                targetCompetencies: ['Executive Presence', 'Change Leadership'],
                startDate: '2024-11-15',
                endDate: '2025-05-15',
                status: 'in_progress',
                cost: 15000,
                provider: 'Sales Leadership Institute',
                completionPercentage: 20,
            },
        ],
        milestones: [
            {
                id: 'mile_019',
                title: 'Complete Transition Shadowing',
                targetDate: '2025-05-31',
                status: 'pending',
                description: 'Complete shadowing and transition preparation',
            },
        ],
        budget: 15000,
        currency: 'USD',
        progress: 25,
        lastReviewDate: '2024-11-15',
        reviewedBy: 'emp_006',
        createdBy: 'emp_004',
        createdAt: '2024-11-01T10:00:00Z',
        updatedAt: '2024-11-15T16:00:00Z',
    },
    {
        id: 'plan_009',
        planCode: 'DP-2024-009',
        employeeId: 'emp_019',
        employeeName: 'Laura Bennett',
        currentPositionId: 'pos_019',
        currentPositionTitle: 'Product Manager - Core Platform',
        targetPositionId: 'pos_010',
        targetPositionTitle: 'Director of Product Management',
        readinessGoal: 'ready_1_year',
        targetDate: '2026-01-01',
        status: 'active',
        competencyGaps: [
            {
                competencyId: 'comp_013',
                competencyName: 'People Management',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                developmentActions: ['Manage 1-2 direct reports', 'Leadership training'],
            },
        ],
        developmentActivities: [
            {
                id: 'act_025',
                planId: 'plan_009',
                activityType: 'stretch_assignment',
                title: 'Manage Associate Product Manager',
                description: 'Take on management of 1 associate product manager',
                targetCompetencies: ['People Management', 'Coaching', 'Leadership'],
                startDate: '2024-09-01',
                endDate: '2025-08-31',
                status: 'in_progress',
                completionPercentage: 30,
            },
            {
                id: 'act_026',
                planId: 'plan_009',
                activityType: 'training',
                title: 'Product Leadership Bootcamp',
                description: 'Intensive product leadership training program',
                targetCompetencies: ['Product Strategy', 'Leadership', 'Communication'],
                startDate: '2025-02-15',
                endDate: '2025-02-17',
                status: 'planned',
                cost: 3500,
                provider: 'Product School',
                completionPercentage: 0,
            },
        ],
        milestones: [
            {
                id: 'mile_025',
                title: 'Successfully Manage Direct Report',
                targetDate: '2025-08-31',
                status: 'pending',
                description: 'Demonstrate effective people management skills',
            },
        ],
        budget: 3500,
        currency: 'USD',
        progress: 30,
        lastReviewDate: '2024-11-15',
        reviewedBy: 'emp_010',
        createdBy: 'emp_004',
        createdAt: '2024-08-01T10:00:00Z',
        updatedAt: '2024-11-15T11:30:00Z',
    },
];

// Talent Reviews
export const sampleTalentReviews: TalentReview[] = [
    {
        id: 'review_001',
        reviewCode: 'TR-2024-Q3',
        reviewName: '2024 Q3 Talent Review - Executive Team',
        reviewDate: '2024-09-15',
        fiscalYear: 'FY2024',
        departmentId: 'dept_exec',
        departmentName: 'Executive Office',
        reviewers: [
            {
                employeeId: 'emp_001',
                employeeName: 'Sarah Johnson',
                role: 'CEO',
                isPrimary: true,
            },
            {
                employeeId: 'emp_004',
                employeeName: 'Emily Rodriguez',
                role: 'CHRO',
                isPrimary: false,
            },
        ],
        participants: [
            {
                employeeId: 'emp_002',
                employeeName: 'Michael Chen',
                currentPosition: 'Chief Financial Officer',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                talentCategory: 'star',
                nineBoxPosition: { x: 3, y: 3, category: 'star' },
                discussionPoints: [
                    'Exceptional financial leadership during market volatility',
                    'Ready for CEO succession in 2-3 years',
                    'Needs more board engagement experience',
                ],
                decisions: [
                    'Enroll in Harvard Advanced Management Program',
                    'Add to Board Audit Committee as observer',
                    'Assign executive coach',
                ],
            },
            {
                employeeId: 'emp_003',
                employeeName: 'David Martinez',
                currentPosition: 'Chief Technology Officer',
                performanceRating: 'high',
                potentialRating: 'high',
                talentCategory: 'high_potential',
                nineBoxPosition: { x: 3, y: 3, category: 'high_potential' },
                discussionPoints: [
                    'Leading digital transformation successfully',
                    'Limited business acumen outside technology',
                    'Retention risk due to external offers',
                ],
                decisions: [
                    'Assign P&L ownership for product division',
                    'Provide business acumen development',
                    'Compensation adjustment to address retention risk',
                ],
            },
        ],
        status: 'completed',
        agenda: [
            'Review succession plans for C-Suite positions',
            'Assess high-potential talent',
            'Identify retention risks',
            'Discuss development priorities',
        ],
        keyDecisions: [
            'Accelerate CEO succession planning',
            'Invest in executive development programs',
            'Address retention risks for critical talent',
        ],
        actionItems: [
            {
                id: 'action_001',
                description: 'Enroll Michael Chen in Harvard AMP',
                assignedTo: 'emp_004',
                dueDate: '2024-10-01',
                status: 'completed',
                completedDate: '2024-09-28',
            },
            {
                id: 'action_002',
                description: 'Prepare compensation adjustment proposal for David Martinez',
                assignedTo: 'emp_004',
                dueDate: '2024-09-30',
                status: 'completed',
                completedDate: '2024-09-25',
            },
        ],
        nextReviewDate: '2024-12-15',
        createdBy: 'emp_004',
        createdAt: '2024-08-15T10:00:00Z',
        updatedAt: '2024-09-15T17:00:00Z',
    },
    {
        id: 'review_002',
        reviewCode: 'TR-2024-Q4',
        reviewName: '2024 Q4 Talent Review - Technology Division',
        reviewDate: '2024-11-20',
        fiscalYear: 'FY2024',
        departmentId: 'dept_tech',
        departmentName: 'Technology',
        reviewers: [
            {
                employeeId: 'emp_003',
                employeeName: 'David Martinez',
                role: 'CTO',
                isPrimary: true,
            },
            {
                employeeId: 'emp_005',
                employeeName: 'James Wilson',
                role: 'VP Engineering',
                isPrimary: false,
            },
            {
                employeeId: 'emp_004',
                employeeName: 'Emily Rodriguez',
                role: 'CHRO',
                isPrimary: false,
            },
        ],
        participants: [
            {
                employeeId: 'emp_011',
                employeeName: 'Alex Thompson',
                currentPosition: 'Engineering Manager - Backend',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                talentCategory: 'star',
                nineBoxPosition: { x: 3, y: 3, category: 'star' },
                discussionPoints: [
                    'Consistently delivers high-quality results',
                    'Ready for VP Engineering role in 12 months',
                    'Strong technical and leadership skills',
                ],
                decisions: [
                    'Fast-track for VP Engineering succession',
                    'Assign technology roadmap leadership',
                    'Enroll in executive leadership program',
                ],
            },
            {
                employeeId: 'emp_017',
                employeeName: 'Sarah Mitchell',
                currentPosition: 'Engineering Manager - Frontend',
                performanceRating: 'high',
                potentialRating: 'high',
                talentCategory: 'high_potential',
                nineBoxPosition: { x: 3, y: 3, category: 'high_potential' },
                discussionPoints: [
                    'Excellent frontend leadership',
                    'Needs more backend/full-stack experience',
                    'Strong culture carrier',
                ],
                decisions: [
                    'Assign backend architecture project',
                    'Expand team size for management development',
                ],
            },
            {
                employeeId: 'emp_020',
                employeeName: 'Chris Anderson',
                currentPosition: 'Senior Data Scientist',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                talentCategory: 'star',
                nineBoxPosition: { x: 3, y: 3, category: 'star' },
                discussionPoints: [
                    'Top performer in data science',
                    'Ready for team lead role immediately',
                    'Critical for AI/ML initiatives',
                ],
                decisions: [
                    'Promote to Data Science Team Lead',
                    'Hire additional data scientists to build team',
                ],
            },
        ],
        status: 'completed',
        agenda: [
            'Review technology talent pipeline',
            'Assess succession for VP Engineering',
            'Discuss Data Science Team Lead hiring',
            'Identify skill gaps',
        ],
        keyDecisions: [
            'Promote Chris Anderson to Data Science Team Lead',
            'Accelerate Alex Thompson development for VP role',
            'Invest in backend development for Sarah Mitchell',
        ],
        actionItems: [
            {
                id: 'action_003',
                description: 'Prepare promotion proposal for Chris Anderson',
                assignedTo: 'emp_003',
                dueDate: '2024-12-01',
                status: 'completed',
                completedDate: '2024-11-25',
            },
            {
                id: 'action_004',
                description: 'Create backend project assignment for Sarah Mitchell',
                assignedTo: 'emp_005',
                dueDate: '2024-12-15',
                status: 'in_progress',
            },
        ],
        nextReviewDate: '2025-02-20',
        createdBy: 'emp_004',
        createdAt: '2024-10-20T10:00:00Z',
        updatedAt: '2024-11-20T16:30:00Z',
    },
    {
        id: 'review_003',
        reviewCode: 'TR-2025-Q1',
        reviewName: '2025 Q1 Talent Review - Sales Organization',
        reviewDate: '2025-01-25',
        fiscalYear: 'FY2025',
        departmentId: 'dept_sales',
        departmentName: 'Sales',
        reviewers: [
            {
                employeeId: 'emp_006',
                employeeName: 'Lisa Anderson',
                role: 'VP Sales',
                isPrimary: true,
            },
            {
                employeeId: 'emp_004',
                employeeName: 'Emily Rodriguez',
                role: 'CHRO',
                isPrimary: false,
            },
        ],
        participants: [
            {
                employeeId: 'emp_018',
                employeeName: 'Marcus Johnson',
                currentPosition: 'Senior Sales Director',
                performanceRating: 'exceptional',
                potentialRating: 'high',
                talentCategory: 'star',
                nineBoxPosition: { x: 3, y: 3, category: 'star' },
                discussionPoints: [
                    'Ready for VP Sales role now',
                    'Received external offers - retention critical',
                    'Strong revenue performance',
                ],
                decisions: [
                    'Transition plan for VP Sales succession by June 2025',
                    'Compensation adjustment',
                    'Retention package',
                ],
            },
        ],
        status: 'scheduled',
        agenda: [
            'Review VP Sales succession plan',
            'Discuss Marcus Johnson retention',
            'Assess regional sales management pipeline',
        ],
        keyDecisions: [],
        actionItems: [],
        nextReviewDate: '2025-04-25',
        createdBy: 'emp_004',
        createdAt: '2024-12-01T10:00:00Z',
        updatedAt: '2024-12-01T10:00:00Z',
    },
];

// Career Paths
export const sampleCareerPaths: CareerPath[] = [
    {
        id: 'path_001',
        pathName: 'Finance Leadership Track',
        description: 'Career progression from Financial Analyst to CFO',
        startPositionId: 'pos_analyst',
        startPositionTitle: 'Financial Analyst',
        endPositionId: 'pos_002',
        endPositionTitle: 'Chief Financial Officer',
        positions: [
            {
                order: 1,
                positionId: 'pos_analyst',
                positionTitle: 'Financial Analyst',
                level: 'Individual Contributor',
                typicalDuration: 2,
                requiredCompetencies: ['Financial Analysis', 'Excel', 'Accounting', 'Data Analysis'],
                developmentActivities: ['Financial modeling courses', 'CPA/CFA study', 'Cross-functional projects'],
            },
            {
                order: 2,
                positionId: 'pos_sr_analyst',
                positionTitle: 'Senior Financial Analyst',
                level: 'Senior IC',
                typicalDuration: 2,
                requiredCompetencies: ['Advanced Financial Analysis', 'Business Partnering', 'Financial Planning'],
                developmentActivities: ['Lead complex analyses', 'Business partner shadowing', 'MBA consideration'],
            },
            {
                order: 3,
                positionId: 'pos_013',
                positionTitle: 'Finance Manager',
                level: 'Manager',
                typicalDuration: 3,
                requiredCompetencies: ['Team Leadership', 'Financial Reporting', 'Process Improvement', 'GAAP'],
                developmentActivities: ['Leadership training', 'Month-end close ownership', 'Cross-functional collaboration'],
            },
            {
                order: 4,
                positionId: 'pos_008',
                positionTitle: 'Director of Financial Planning',
                level: 'Director',
                typicalDuration: 3,
                requiredCompetencies: ['Strategic Planning', 'FP&A', 'Business Partnering', 'Team Management'],
                developmentActivities: ['Strategic planning projects', 'Executive MBA', 'Treasury rotation'],
            },
            {
                order: 5,
                positionId: 'pos_002',
                positionTitle: 'Chief Financial Officer',
                level: 'C-Suite',
                typicalDuration: 0,
                requiredCompetencies: ['Financial Leadership', 'Strategic Planning', 'Risk Management', 'Board Relations'],
                developmentActivities: ['Executive coaching', 'Board committee participation', 'Advanced management programs'],
            },
        ],
        estimatedDuration: 10,
        requiredExperience: 10,
        isActive: true,
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-06-01T14:00:00Z',
    },
    {
        id: 'path_002',
        pathName: 'Engineering Leadership Track',
        description: 'Career progression from Software Engineer to VP Engineering',
        startPositionId: 'pos_swe',
        startPositionTitle: 'Software Engineer',
        endPositionId: 'pos_005',
        endPositionTitle: 'VP Engineering',
        positions: [
            {
                order: 1,
                positionId: 'pos_swe',
                positionTitle: 'Software Engineer',
                level: 'Individual Contributor',
                typicalDuration: 2,
                requiredCompetencies: ['Programming', 'Software Design', 'Testing', 'Collaboration'],
                developmentActivities: ['Code reviews', 'Technical certifications', 'Side projects'],
            },
            {
                order: 2,
                positionId: 'pos_sr_swe',
                positionTitle: 'Senior Software Engineer',
                level: 'Senior IC',
                typicalDuration: 2,
                requiredCompetencies: ['Advanced Programming', 'System Design', 'Mentoring', 'Architecture'],
                developmentActivities: ['Lead technical projects', 'Mentor junior engineers', 'Architecture training'],
            },
            {
                order: 3,
                positionId: 'pos_011',
                positionTitle: 'Engineering Manager',
                level: 'Manager',
                typicalDuration: 3,
                requiredCompetencies: ['Team Leadership', 'Engineering Management', 'Agile', 'Performance Management'],
                developmentActivities: ['Management training', 'Agile certification', 'Team building'],
            },
            {
                order: 4,
                positionId: 'pos_005',
                positionTitle: 'VP Engineering',
                level: 'VP',
                typicalDuration: 0,
                requiredCompetencies: ['Engineering Leadership', 'Strategic Planning', 'Architecture', 'Organizational Design'],
                developmentActivities: ['Executive leadership programs', 'Strategic planning', 'VP shadowing'],
            },
        ],
        estimatedDuration: 7,
        requiredExperience: 7,
        isActive: true,
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-06-01T14:00:00Z',
    },
    {
        id: 'path_003',
        pathName: 'Sales Leadership Track',
        description: 'Career progression from Sales Representative to VP Sales',
        startPositionId: 'pos_sales_rep',
        startPositionTitle: 'Sales Representative',
        endPositionId: 'pos_006',
        endPositionTitle: 'VP Sales',
        positions: [
            {
                order: 1,
                positionId: 'pos_sales_rep',
                positionTitle: 'Sales Representative',
                level: 'Individual Contributor',
                typicalDuration: 2,
                requiredCompetencies: ['Sales Skills', 'CRM', 'Product Knowledge', 'Communication'],
                developmentActivities: ['Sales training', 'Product certifications', 'Ride-alongs'],
            },
            {
                order: 2,
                positionId: 'pos_sr_sales',
                positionTitle: 'Senior Sales Representative',
                level: 'Senior IC',
                typicalDuration: 2,
                requiredCompetencies: ['Enterprise Sales', 'Account Management', 'Negotiation', 'Strategic Selling'],
                developmentActivities: ['Advanced sales training', 'Key account management', 'Mentoring'],
            },
            {
                order: 3,
                positionId: 'pos_012',
                positionTitle: 'Regional Sales Manager',
                level: 'Manager',
                typicalDuration: 3,
                requiredCompetencies: ['Sales Management', 'Territory Planning', 'Coaching', 'Forecasting'],
                developmentActivities: ['Management training', 'Sales leadership programs', 'Territory expansion'],
            },
            {
                order: 4,
                positionId: 'pos_018',
                positionTitle: 'Senior Sales Director',
                level: 'Director',
                typicalDuration: 3,
                requiredCompetencies: ['Sales Strategy', 'Revenue Management', 'Team Leadership', 'Executive Relationships'],
                developmentActivities: ['Strategic selling', 'Executive sales programs', 'P&L ownership'],
            },
            {
                order: 5,
                positionId: 'pos_006',
                positionTitle: 'VP Sales',
                level: 'VP',
                typicalDuration: 0,
                requiredCompetencies: ['Sales Leadership', 'Strategic Selling', 'Revenue Growth', 'Organizational Leadership'],
                developmentActivities: ['Executive leadership', 'Sales transformation', 'Board presentations'],
            },
        ],
        estimatedDuration: 10,
        requiredExperience: 10,
        isActive: true,
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-06-01T14:00:00Z',
    },
    {
        id: 'path_004',
        pathName: 'Product Management Track',
        description: 'Career progression from Product Manager to Director of Product',
        startPositionId: 'pos_apm',
        startPositionTitle: 'Associate Product Manager',
        endPositionId: 'pos_010',
        endPositionTitle: 'Director of Product Management',
        positions: [
            {
                order: 1,
                positionId: 'pos_apm',
                positionTitle: 'Associate Product Manager',
                level: 'Individual Contributor',
                typicalDuration: 2,
                requiredCompetencies: ['Product Management Basics', 'User Research', 'Agile', 'Analytics'],
                developmentActivities: ['PM certifications', 'User research projects', 'Agile training'],
            },
            {
                order: 2,
                positionId: 'pos_019',
                positionTitle: 'Product Manager',
                level: 'Individual Contributor',
                typicalDuration: 3,
                requiredCompetencies: ['Product Strategy', 'Roadmapping', 'Stakeholder Management', 'Data Analysis'],
                developmentActivities: ['Product strategy', 'Roadmap ownership', 'Cross-functional leadership'],
            },
            {
                order: 3,
                positionId: 'pos_010',
                positionTitle: 'Director of Product Management',
                level: 'Director',
                typicalDuration: 0,
                requiredCompetencies: ['Product Leadership', 'Team Management', 'Strategic Planning', 'Market Analysis'],
                developmentActivities: ['Leadership training', 'Portfolio management', 'Executive communication'],
            },
        ],
        estimatedDuration: 5,
        requiredExperience: 5,
        isActive: true,
        createdAt: '2024-02-01T10:00:00Z',
        updatedAt: '2024-06-01T14:00:00Z',
    },
];

// Emergency Succession Plans
export const sampleEmergencySuccession: EmergencySuccession[] = [
    {
        id: 'emerg_001',
        criticalPositionId: 'pos_001',
        criticalPositionTitle: 'Chief Executive Officer',
        triggerEvents: [
            'Sudden departure or resignation',
            'Extended medical leave',
            'Death or permanent disability',
            'Termination for cause',
        ],
        emergencySuccessors: [
            {
                priority: 1,
                employeeId: 'emp_002',
                employeeName: 'Michael Chen',
                currentPosition: 'Chief Financial Officer',
                readinessLevel: 'ready_2_3_years',
                contactInfo: 'mchen@company.com, +1-555-0102',
                limitationsOnRole: 'Would need board approval for certain strategic decisions',
                expectedDuration: 'Up to 6 months while permanent search conducted',
            },
            {
                priority: 2,
                employeeId: 'emp_003',
                employeeName: 'David Martinez',
                currentPosition: 'Chief Technology Officer',
                readinessLevel: 'ready_4_plus_years',
                contactInfo: 'dmartinez@company.com, +1-555-0103',
                limitationsOnRole: 'Limited financial/commercial experience',
                expectedDuration: 'Interim only (3-6 months)',
            },
        ],
        interimActions: [
            'Notify Board of Directors immediately',
            'Activate interim CEO per priority list',
            'Issue internal communication within 24 hours',
            'Issue external communication within 48 hours',
            'Engage executive search firm within 1 week',
            'Brief interim CEO on critical pending matters',
            'Arrange transition of key relationships',
        ],
        communicationPlan: 'Board Chair notifies executives → CHRO coordinates internal comms → CEO/Chair issue joint statement → Investor relations contacts key stakeholders',
        approvedBy: 'board_001',
        approvedDate: '2024-01-15',
        lastUpdated: '2024-11-01',
        lastTestedDate: '2024-06-01',
        nextTestDate: '2025-06-01',
        isActive: true,
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-11-01T14:30:00Z',
    },
    {
        id: 'emerg_002',
        criticalPositionId: 'pos_002',
        criticalPositionTitle: 'Chief Financial Officer',
        triggerEvents: [
            'Sudden departure or resignation',
            'Extended medical leave',
            'Death or permanent disability',
        ],
        emergencySuccessors: [
            {
                priority: 1,
                employeeId: 'emp_008',
                employeeName: 'Thomas Brown',
                currentPosition: 'Director of Financial Planning',
                readinessLevel: 'ready_1_year',
                contactInfo: 'tbrown@company.com, +1-555-0108',
                expectedDuration: 'Up to 12 months',
            },
            {
                priority: 2,
                employeeId: 'emp_016',
                employeeName: 'Amanda Foster',
                currentPosition: 'Controller',
                readinessLevel: 'ready_2_3_years',
                contactInfo: 'afoster@company.com, +1-555-0116',
                limitationsOnRole: 'Limited FP&A and strategic planning experience',
                expectedDuration: 'Interim only (3-6 months)',
            },
        ],
        interimActions: [
            'Notify CEO immediately',
            'Activate interim CFO per priority list',
            'Brief on month-end close status',
            'Transfer signing authorities',
            'Notify external auditors',
            'Arrange transition of banking relationships',
            'Update board finance committee',
        ],
        communicationPlan: 'CEO notifies executive team → CHRO coordinates internal comms → Finance team briefed → External stakeholders notified (banks, auditors)',
        approvedBy: 'emp_001',
        approvedDate: '2024-02-01',
        lastUpdated: '2024-10-15',
        lastTestedDate: '2024-07-01',
        nextTestDate: '2025-07-01',
        isActive: true,
        createdAt: '2024-02-01T10:00:00Z',
        updatedAt: '2024-10-15T11:20:00Z',
    },
    {
        id: 'emerg_003',
        criticalPositionId: 'pos_003',
        criticalPositionTitle: 'Chief Technology Officer',
        triggerEvents: [
            'Sudden departure or resignation',
            'Extended medical leave',
            'Death or permanent disability',
        ],
        emergencySuccessors: [
            {
                priority: 1,
                employeeId: 'emp_005',
                employeeName: 'James Wilson',
                currentPosition: 'VP Engineering',
                readinessLevel: 'ready_1_year',
                contactInfo: 'jwilson@company.com, +1-555-0105',
                expectedDuration: 'Up to 12 months',
            },
            {
                priority: 2,
                employeeId: 'emp_010',
                employeeName: 'Kevin Patel',
                currentPosition: 'Director of Product Management',
                readinessLevel: 'ready_2_3_years',
                contactInfo: 'kpatel@company.com, +1-555-0110',
                limitationsOnRole: 'Limited infrastructure and operations experience',
                expectedDuration: 'Interim only (3-6 months)',
            },
        ],
        interimActions: [
            'Notify CEO immediately',
            'Activate interim CTO per priority list',
            'Brief on critical ongoing projects',
            'Transfer vendor relationships',
            'Review technology roadmap',
            'Notify key technology partners',
            'Assess critical technology risks',
        ],
        communicationPlan: 'CEO notifies executive team → Engineering/Product teams briefed → External technology partners notified',
        approvedBy: 'emp_001',
        approvedDate: '2024-03-01',
        lastUpdated: '2024-11-20',
        isActive: true,
        createdAt: '2024-03-01T10:00:00Z',
        updatedAt: '2024-11-20T09:15:00Z',
    },
    {
        id: 'emerg_004',
        criticalPositionId: 'pos_006',
        criticalPositionTitle: 'VP Sales',
        triggerEvents: [
            'Sudden departure or resignation',
            'Extended medical leave',
            'Death or permanent disability',
        ],
        emergencySuccessors: [
            {
                priority: 1,
                employeeId: 'emp_018',
                employeeName: 'Marcus Johnson',
                currentPosition: 'Senior Sales Director',
                readinessLevel: 'ready_now',
                contactInfo: 'mjohnson@company.com, +1-555-0118',
                expectedDuration: 'Permanent replacement',
            },
        ],
        interimActions: [
            'Notify CEO immediately',
            'Activate interim VP Sales',
            'Review sales pipeline and forecasts',
            'Notify key customer accounts',
            'Transfer account relationships',
            'Brief sales team',
            'Review compensation plans and quotas',
        ],
        communicationPlan: 'CEO notifies executive team → Sales team briefed → Key customers contacted personally',
        approvedBy: 'emp_001',
        approvedDate: '2024-06-01',
        lastUpdated: '2024-11-15',
        lastTestedDate: '2024-08-01',
        nextTestDate: '2025-08-01',
        isActive: true,
        createdAt: '2024-06-01T10:00:00Z',
        updatedAt: '2024-11-15T10:00:00Z',
    },
];

// Succession Metrics
export const sampleSuccessionMetrics: SuccessionMetrics = {
    totalCriticalPositions: 15,
    positionsWithSuccessors: 12,
    positionsCoverage: 80, // 12/15 = 80%
    readyNowSuccessors: 3,
    avgSuccessionDepth: 1.5,
    highRiskPositions: 3,
    avgTimeToReadiness: 18, // months
    developmentPlansActive: 20,
    talentPoolSize: 45,
    retentionRiskCount: 5,
};

// Succession Risk Analysis
export const sampleSuccessionRiskAnalysis: SuccessionRiskAnalysis[] = [
    {
        positionId: 'pos_003',
        positionTitle: 'Chief Technology Officer',
        riskScore: 85,
        riskLevel: 'high',
        factors: [
            {
                factor: 'Expected Vacancy',
                impact: 'high',
                likelihood: 'high',
                description: 'CTO planning departure in August 2025',
            },
            {
                factor: 'Limited Succession Depth',
                impact: 'high',
                likelihood: 'high',
                description: 'Only 1 ready successor identified',
            },
            {
                factor: 'External Market Demand',
                impact: 'high',
                likelihood: 'medium',
                description: 'High demand for technology executives in market',
            },
        ],
        mitigationActions: [
            'Accelerate Alex Thompson development plan',
            'Identify external candidates as backup',
            'Consider retention package for current CTO',
            'Develop Sarah Mitchell as longer-term backup',
        ],
        lastAssessed: '2024-11-20',
    },
    {
        positionId: 'pos_012',
        positionTitle: 'Regional Sales Manager - West',
        riskScore: 90,
        riskLevel: 'high',
        factors: [
            {
                factor: 'Confirmed Departure',
                impact: 'high',
                likelihood: 'high',
                description: 'Manager departing June 2025',
            },
            {
                factor: 'No Succession Plan',
                impact: 'high',
                likelihood: 'high',
                description: 'Zero ready successors identified',
            },
            {
                factor: 'Revenue Impact',
                impact: 'high',
                likelihood: 'high',
                description: 'Manages significant regional revenue',
            },
        ],
        mitigationActions: [
            'Immediate internal candidate identification',
            'Launch external recruitment',
            'Knowledge transfer plan',
            'Customer relationship transition plan',
        ],
        lastAssessed: '2024-11-25',
    },
    {
        positionId: 'pos_014',
        positionTitle: 'Data Science Team Lead',
        riskScore: 75,
        riskLevel: 'high',
        factors: [
            {
                factor: 'Position Vacant',
                impact: 'high',
                likelihood: 'high',
                description: 'Position currently unfilled',
            },
            {
                factor: 'Critical for AI/ML Initiatives',
                impact: 'high',
                likelihood: 'high',
                description: 'Blocking strategic initiatives',
            },
        ],
        mitigationActions: [
            'Promote Chris Anderson immediately',
            'Fast-track hiring approval',
            'Interim consulting support if needed',
        ],
        lastAssessed: '2024-11-01',
    },
];

// Succession Settings
export const sampleSuccessionSettings: SuccessionSettings = {
    reviewFrequency: 'quarterly',
    mandatorySuccessionDepth: 2,
    retirementNoticeMonths: 12,
    talentReviewCalendar: ['2025-02-15', '2025-05-15', '2025-08-15', '2025-11-15'],
    nineBoxEnabled: true,
    emergencyPlanRequired: true,
    autoNotifications: {
        vacancyRiskAlert: true,
        developmentPlanDue: true,
        talentReviewReminder: true,
        readinessDateApproaching: true,
        retirementAlert: true,
    },
};
