/**
 * Workforce Planning Module - Sample Data
 * Comprehensive sample data for strategic workforce planning
 */

import type { DemandForecast, SupplyAnalysis, GapAnalysis, ScenarioModel, SuccessionReadiness, TalentAcquisitionPlan } from './types';

// ============================================================================
// Sample Demand Forecasts
// ============================================================================

export const sampleDemandForecasts: DemandForecast[] = [
  {
    id: 'forecast-001',
    forecastCode: 'FC-2024-001',
    forecastName: '2024-2026 Workforce Demand Forecast',
    status: 'active',
    description: 'Three-year demand forecast based on strategic business plan and growth initiatives',
    timeHorizon: 'medium_term',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2026-12-31T23:59:59Z',
    forecastPeriods: [
      {
        id: 'period-2024',
        periodName: '2024',
        startDate: '2024-01-01T00:00:00Z',
        endDate: '2024-12-31T23:59:59Z',
        sequence: 1,
        assumptions: ['15% revenue growth', '2 new product launches', 'Expansion to 3 new markets'],
      },
      {
        id: 'period-2025',
        periodName: '2025',
        startDate: '2025-01-01T00:00:00Z',
        endDate: '2025-12-31T23:59:59Z',
        sequence: 2,
        assumptions: ['20% revenue growth', 'AI automation in customer service', 'New distribution center'],
      },
      {
        id: 'period-2026',
        periodName: '2026',
        startDate: '2026-01-01T00:00:00Z',
        endDate: '2026-12-31T23:59:59Z',
        sequence: 3,
        assumptions: ['18% revenue growth', 'International expansion', 'Advanced analytics implementation'],
      },
    ],
    forecastMethod: 'hybrid',
    assumptions: [
      {
        id: 'assump-001',
        assumptionType: 'growth',
        description: 'Company revenue growth averaging 17-18% annually',
        value: 17.5,
        unit: 'percentage',
        impact: 'increase',
        confidence: 'high',
      },
      {
        id: 'assump-002',
        assumptionType: 'attrition',
        description: 'Employee attrition rate stable at 12%',
        value: 12,
        unit: 'percentage',
        impact: 'neutral',
        confidence: 'medium',
      },
      {
        id: 'assump-003',
        assumptionType: 'productivity',
        description: 'Technology improvements increase productivity by 8%',
        value: 8,
        unit: 'percentage',
        impact: 'decrease',
        confidence: 'medium',
      },
    ],
    businessDrivers: [
      {
        id: 'driver-001',
        driverName: 'Revenue Growth',
        driverType: 'revenue',
        description: 'Projected revenue growth from $500M to $750M over 3 years',
        baselineValue: 500,
        forecastedValue: 750,
        changePercentage: 50,
        impactOnHeadcount: 125,
        impactDescription: 'Need additional sales, support, and operations staff',
      },
      {
        id: 'driver-002',
        driverName: 'New Product Launches',
        driverType: 'projects',
        description: '5 major product launches requiring R&D and marketing support',
        baselineValue: 2,
        forecastedValue: 7,
        changePercentage: 250,
        impactOnHeadcount: 35,
        impactDescription: 'Engineering, product management, and marketing roles',
      },
    ],
    departments: ['Engineering', 'Sales', 'Customer Success', 'Operations', 'Marketing'],
    locations: ['San Francisco', 'New York', 'Austin', 'Remote'],
    jobFamilies: ['Engineering', 'Sales', 'Customer Success', 'Operations', 'Marketing', 'Finance', 'HR'],
    roleDemand: [
      {
        id: 'role-001',
        jobFamily: 'Engineering',
        jobTitle: 'Software Engineer',
        jobLevel: 'IC3',
        department: 'Engineering',
        location: 'San Francisco',
        currentHeadcount: 85,
        filledPositions: 82,
        vacantPositions: 3,
        forecastedHeadcount: 120,
        demandChange: 35,
        demandChangePercentage: 41.2,
        periodDemand: [
          {
            periodId: 'period-2024',
            periodName: '2024',
            headcount: 95,
            newHires: 12,
            promotions: 2,
            transfers: 1,
            attrition: 10,
          },
          {
            periodId: 'period-2025',
            periodName: '2025',
            headcount: 108,
            newHires: 15,
            promotions: 3,
            transfers: 0,
            attrition: 13,
          },
          {
            periodId: 'period-2026',
            periodName: '2026',
            headcount: 120,
            newHires: 14,
            promotions: 2,
            transfers: 1,
            attrition: 12,
          },
        ],
        drivers: ['New product development', 'Platform scalability', 'Technical debt reduction'],
        assumptions: ['15% attrition rate', 'Strong hiring market', 'Remote work options increase talent pool'],
        notes: 'Focus on hiring senior engineers with cloud architecture experience',
        priority: 'high',
        criticality: 'high',
      },
      {
        id: 'role-002',
        jobFamily: 'Sales',
        jobTitle: 'Account Executive',
        jobLevel: 'IC2',
        department: 'Sales',
        location: 'Multiple',
        currentHeadcount: 42,
        filledPositions: 38,
        vacantPositions: 4,
        forecastedHeadcount: 65,
        demandChange: 23,
        demandChangePercentage: 54.8,
        periodDemand: [
          {
            periodId: 'period-2024',
            periodName: '2024',
            headcount: 50,
            newHires: 10,
            promotions: 1,
            transfers: 0,
            attrition: 8,
          },
          {
            periodId: 'period-2025',
            periodName: '2025',
            headcount: 58,
            newHires: 10,
            promotions: 2,
            transfers: 0,
            attrition: 7,
          },
          {
            periodId: 'period-2026',
            periodName: '2026',
            headcount: 65,
            newHires: 9,
            promotions: 1,
            transfers: 0,
            attrition: 7,
          },
        ],
        drivers: ['Market expansion', 'Customer acquisition targets', 'New product lines'],
        assumptions: ['20% quota attainment', 'High turnover in first year', 'Ramping period of 6 months'],
        priority: 'high',
        criticality: 'medium',
      },
    ],
    totalCurrentHeadcount: 500,
    totalForecastedHeadcount: 625,
    totalHeadcountChange: 125,
    totalHeadcountChangePercentage: 25,
    approvalStatus: 'approved',
    approvedBy: 'CFO',
    approvedDate: '2024-01-15T00:00:00Z',
    createdBy: 'workforce-planning',
    createdByName: 'Workforce Planning Team',
    createdDate: '2023-12-01T00:00:00Z',
    lastModified: '2024-01-15T00:00:00Z',
    version: '1.0',
  },
];

// ============================================================================
// Sample Supply Analyses
// ============================================================================

export const sampleSupplyAnalyses: SupplyAnalysis[] = [
  {
    id: 'supply-001',
    analysisCode: 'SA-2024-001',
    analysisName: 'Current Workforce Supply Analysis',
    status: 'completed',
    description: 'Comprehensive analysis of current workforce supply as of January 2024',
    asOfDate: '2024-01-01T00:00:00Z',
    departments: ['Engineering', 'Sales', 'Customer Success', 'Operations', 'Marketing'],
    locations: ['San Francisco', 'New York', 'Austin', 'Remote'],
    jobFamilies: ['Engineering', 'Sales', 'Customer Success', 'Operations', 'Marketing', 'Finance', 'HR'],
    totalHeadcount: 500,
    totalFTE: 485.5,
    supplyByRole: [
      {
        id: 'supply-role-001',
        jobFamily: 'Engineering',
        jobTitle: 'Software Engineer',
        jobLevel: 'IC3',
        department: 'Engineering',
        location: 'San Francisco',
        headcount: 85,
        fte: 84.2,
        averageTenure: 3.2,
        averageAge: 32,
        averagePerformanceRating: 4.1,
        promotionReady: 12,
        lateralMoveReady: 8,
        retirementEligible: 0,
        flightRisk: 5,
        criticalSkillsCoverage: 78,
        skillGaps: [
          {
            skillName: 'Cloud Architecture (AWS)',
            requiredCount: 25,
            currentCount: 18,
            gap: 7,
            impactOnBusiness: 'high',
          },
        ],
      },
    ],
    demographics: {
      ageDistribution: [
        { ageRange: '20-29', count: 125, percentage: 25 },
        { ageRange: '30-39', count: 225, percentage: 45 },
        { ageRange: '40-49', count: 100, percentage: 20 },
        { ageRange: '50-59', count: 40, percentage: 8 },
        { ageRange: '60+', count: 10, percentage: 2 },
      ],
      genderDistribution: {
        male: 280,
        female: 200,
        nonBinary: 15,
        notSpecified: 5,
      },
      diversityMetrics: {
        underrepresentedMinorities: 145,
        underrepresentedMinoritiesPercentage: 29,
        veterans: 25,
        veteransPercentage: 5,
        disabilities: 18,
        disabilitiesPercentage: 3.6,
      },
      generationDistribution: {
        babyBoomers: 15,
        genX: 110,
        millennials: 280,
        genZ: 95,
      },
    },
    tenure: {
      averageTenure: 3.8,
      medianTenure: 2.5,
      tenureDistribution: [
        { tenureRange: '0-1 years', count: 120, percentage: 24 },
        { tenureRange: '1-3 years', count: 180, percentage: 36 },
        { tenureRange: '3-5 years', count: 125, percentage: 25 },
        { tenureRange: '5-10 years', count: 60, percentage: 12 },
        { tenureRange: '10+ years', count: 15, percentage: 3 },
      ],
      newHiresLast12Months: 125,
    },
    skills: {
      totalSkills: 850,
      criticalSkills: [
        {
          skillName: 'React/TypeScript',
          skillCategory: 'Frontend Development',
          requiredProficiency: 4,
          currentCoverage: 65,
          averageProficiency: 3.8,
          gap: -5,
          priority: 'high',
        },
        {
          skillName: 'AWS Cloud',
          skillCategory: 'Infrastructure',
          requiredProficiency: 4,
          currentCoverage: 42,
          averageProficiency: 3.5,
          gap: 8,
          priority: 'critical',
        },
      ],
      emergingSkills: [],
      skillGaps: [],
      overallSkillCoverage: 82.5,
    },
    performance: {
      topPerformers: 20,
      solidPerformers: 65,
      needsImprovement: 10,
      newEmployees: 5,
      averageRating: 3.9,
    },
    internalMobility: {
      promotionReadyCount: 85,
      lateralMoveReadyCount: 45,
      mobilityRate: 12.5,
      averageTimeToPromote: 28,
      successorsCovered: 65,
    },
    retirementEligibility: {
      eligibleNow: 8,
      eligibleIn1Year: 12,
      eligibleIn3Years: 28,
      eligibleIn5Years: 45,
      retirementRisk: 'low',
    },
    attritionRisk: {
      totalAttrition12Months: 60,
      attritionRate: 12,
      voluntaryAttrition: 52,
      involuntaryAttrition: 8,
      highRiskEmployees: 35,
      criticalRoleAttrition: 8,
      predictedAttritionNext12Months: 58,
    },
    pipeline: {
      activeCandidates: 145,
      offersPending: 12,
      hiresPending: 8,
      internsPipeline: 15,
      returnBoomerangs: 5,
      alumnniNetwork: 250,
    },
    createdBy: 'hr-analytics',
    createdDate: '2024-01-05T00:00:00Z',
    lastModified: '2024-01-05T00:00:00Z',
  },
];

// ============================================================================
// Sample Gap Analyses
// ============================================================================

export const sampleGapAnalyses: GapAnalysis[] = [
  {
    id: 'gap-001',
    analysisCode: 'GA-2024-001',
    analysisName: '2024-2026 Workforce Gap Analysis',
    status: 'completed',
    description: 'Gap analysis comparing demand forecast with current supply',
    demandForecastId: 'forecast-001',
    supplyAnalysisId: 'supply-001',
    analysisDate: '2024-01-10T00:00:00Z',
    forecastPeriodIds: ['period-2024', 'period-2025', 'period-2026'],
    totalDemand: 625,
    totalSupply: 500,
    totalGap: 125,
    gapPercentage: 25,
    periodGaps: [
      {
        periodId: 'period-2024',
        periodName: '2024',
        demand: 550,
        supply: 500,
        gap: 50,
        gapType: 'shortage',
        severity: 'medium',
      },
      {
        periodId: 'period-2025',
        periodName: '2025',
        demand: 590,
        supply: 550,
        gap: 40,
        gapType: 'shortage',
        severity: 'medium',
      },
      {
        periodId: 'period-2026',
        periodName: '2026',
        demand: 625,
        supply: 590,
        gap: 35,
        gapType: 'shortage',
        severity: 'low',
      },
    ],
    roleGaps: [
      {
        id: 'role-gap-001',
        jobFamily: 'Engineering',
        jobTitle: 'Software Engineer',
        jobLevel: 'IC3',
        department: 'Engineering',
        location: 'San Francisco',
        demand: 120,
        supply: 85,
        gap: 35,
        gapType: 'shortage',
        businessImpact: 'high',
        urgency: 'high',
        difficulty: 'moderate',
        recommendedActions: [
          'Accelerate campus recruiting',
          'Increase referral bonuses',
          'Expand remote hiring',
          'Partner with coding bootcamps',
        ],
        estimatedTimeToClose: 18,
        estimatedCost: 175000,
      },
    ],
    quantitativeGaps: [],
    qualitativeGaps: [],
    closureStrategies: [
      {
        id: 'strategy-001',
        strategyType: 'external_hire',
        description: 'Aggressive external hiring campaign for software engineers',
        targetRoles: ['Software Engineer IC3', 'Software Engineer IC4'],
        estimatedImpact: 35,
        timeline: 18,
        estimatedCost: 175000,
        feasibility: 'high',
        priority: 'high',
        owner: 'Recruiting Team',
        status: 'in_progress',
      },
    ],
    closureConfidence: 'high',
    createdBy: 'workforce-planning',
    createdDate: '2024-01-10T00:00:00Z',
    lastModified: '2024-01-10T00:00:00Z',
  },
];

// ============================================================================
// Sample Scenarios
// ============================================================================

export const sampleScenarios: ScenarioModel[] = [
  {
    id: 'scenario-001',
    scenarioCode: 'SC-BASELINE-2024',
    scenarioName: 'Baseline Growth Scenario',
    scenarioType: 'baseline',
    status: 'completed',
    description: 'Conservative baseline scenario assuming moderate growth and stable attrition',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2026-12-31T23:59:59Z',
    modelingPeriods: ['2024', '2025', '2026'],
    variables: [
      {
        id: 'var-001',
        variableName: 'Revenue Growth Rate',
        variableType: 'growth_rate',
        baselineValue: 17.5,
        scenarioValue: 15.0,
        unit: 'percentage',
        description: 'Annual revenue growth rate',
        impactDescription: 'Lower growth reduces hiring needs by approximately 15%',
      },
      {
        id: 'var-002',
        variableName: 'Attrition Rate',
        variableType: 'attrition_rate',
        baselineValue: 12,
        scenarioValue: 12,
        unit: 'percentage',
        description: 'Annual employee attrition rate',
        impactDescription: 'Stable attrition maintains replacement hiring needs',
      },
    ],
    headcountProjection: [],
    costProjection: [],
    totalHeadcountEnd: 600,
    totalCostEnd: 75000000,
    totalHeadcountChange: 100,
    totalCostChange: 15000000,
    createdBy: 'workforce-planning',
    createdDate: '2024-01-12T00:00:00Z',
    lastModified: '2024-01-12T00:00:00Z',
    version: '1.0',
  },
];

// ============================================================================
// Sample Succession Readiness
// ============================================================================

export const sampleSuccessionReadiness: SuccessionReadiness[] = [
  {
    id: 'succession-001',
    assessmentCode: 'SR-2024-001',
    assessmentName: '2024 Executive Succession Assessment',
    status: 'completed',
    description: 'Annual assessment of succession readiness for critical executive positions',
    assessmentDate: '2024-01-15T00:00:00Z',
    criticalPositions: [
      {
        id: 'pos-001',
        positionTitle: 'VP of Engineering',
        department: 'Engineering',
        location: 'San Francisco',
        currentIncumbent: 'John Smith',
        currentIncumbentId: 'emp-001',
        businessImpact: 'critical',
        difficultyToReplace: 'very_difficult',
        vacancyRisk: 'medium',
        successors: [
          {
            id: 'succ-001',
            employeeId: 'emp-102',
            employeeName: 'Sarah Johnson',
            currentPosition: 'Director of Engineering',
            currentDepartment: 'Engineering',
            readinessLevel: 'ready_1_to_2_years',
            readinessPercentage: 75,
            readinessAssessment: {
              technicalSkills: 90,
              leadershipSkills: 75,
              businessAcumen: 70,
              culturalFit: 85,
              overallReadiness: 80,
              assessmentDate: '2024-01-10T00:00:00Z',
              assessedBy: 'CEO',
              notes: 'Strong technical leader, needs more exposure to business strategy',
            },
            developmentNeeds: ['Executive leadership program', 'Board presentation experience', 'P&L management'],
            developmentPlan: 'Enroll in executive MBA program, assign as acting VP during Q2',
            mentorAssigned: 'CTO',
            performanceRating: 4.5,
            potentialRating: 4,
            is9BoxHiPo: true,
            retentionRisk: 'low',
            careerAspiration: 'VP/C-level role within 2 years',
          },
        ],
        successionDepth: 1,
        readinessLevel: 'medium',
        incumbentRetirementEligible: false,
        incumbentFlightRisk: 'low',
        incumbentTenure: 6.5,
        developmentActions: ['Cross-functional rotation', 'Executive coaching', 'Strategic planning involvement'],
      },
    ],
    totalCriticalPositions: 15,
    positionsWithSuccessors: 12,
    successionCoverageRate: 80,
    averageReadyNow: 3,
    averageReady1to2Years: 6,
    averageReady3to5Years: 3,
    highRiskPositions: 3,
    mediumRiskPositions: 7,
    lowRiskPositions: 5,
    developmentNeeds: [],
    accelerationPrograms: [],
    createdBy: 'talent-management',
    createdDate: '2024-01-15T00:00:00Z',
    lastModified: '2024-01-15T00:00:00Z',
  },
];

// ============================================================================
// Sample Talent Acquisition Plans
// ============================================================================

export const sampleTalentAcquisitionPlans: TalentAcquisitionPlan[] = [
  {
    id: 'plan-001',
    planCode: 'TAP-2024',
    planName: '2024 Talent Acquisition Plan',
    status: 'active',
    description: '2024 hiring plan to address workforce gaps identified in gap analysis',
    gapAnalysisId: 'gap-001',
    planYear: 2024,
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-12-31T23:59:59Z',
    totalHiringTarget: 125,
    hiringByRole: [],
    hiringByPeriod: [
      {
        periodId: 'q1-2024',
        periodName: 'Q1 2024',
        startDate: '2024-01-01T00:00:00Z',
        endDate: '2024-03-31T23:59:59Z',
        targetHires: 25,
        actualHires: 28,
        progress: 112,
      },
      {
        periodId: 'q2-2024',
        periodName: 'Q2 2024',
        startDate: '2024-04-01T00:00:00Z',
        endDate: '2024-06-30T23:59:59Z',
        targetHires: 30,
        actualHires: 15,
        progress: 50,
      },
    ],
    sourcingChannels: [
      {
        channelName: 'Employee Referrals',
        channelType: 'referral',
        targetHires: 40,
        actualHires: 18,
        costPerHire: 2500,
        timeToHire: 28,
        qualityScore: 4.5,
        diversityScore: 42,
      },
      {
        channelName: 'LinkedIn',
        channelType: 'social',
        targetHires: 35,
        actualHires: 12,
        costPerHire: 3500,
        timeToHire: 35,
        qualityScore: 4.0,
        diversityScore: 38,
      },
    ],
    diversityTargets: [
      {
        diversityCategory: 'Gender Diversity',
        targetPercentage: 50,
        currentPercentage: 40,
        gap: 10,
        actions: ['Partner with women in tech organizations', 'Bias training for hiring managers'],
      },
    ],
    totalRecruitingBudget: 625000,
    budgetByCategory: [
      {
        categoryName: 'External Recruiting Fees',
        allocatedBudget: 250000,
        spentBudget: 125000,
        remainingBudget: 125000,
        utilizationRate: 50,
      },
    ],
    milestones: [],
    actualHires: 43,
    hiringProgress: 34.4,
    budgetSpent: 215000,
    budgetRemaining: 410000,
    createdBy: 'recruiting',
    createdDate: '2023-12-15T00:00:00Z',
    lastModified: '2024-06-15T00:00:00Z',
  },
];
