"use client";

import React, { useState, useEffect } from 'react';
import { Download, FileText, Table as TableIcon, Image, Settings } from 'lucide-react';
import { ReportExportService } from '../services';

export default function ExportOptionsPage() {
    const [exports, setExports] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchExports();
    }, []);

    const fetchExports = async () => {
        try {
            // Export service doesn't have a getAll method, but we can prepare for future use
            setExports([]);
        } catch {
                    } finally {
            setLoading(false);
        }
    };

    const handleExport = async (reportId: string, format: string) => {
        try {
            await ReportExportService.exportReport(reportId, format);
        } catch {
                    }
    };
    return (
        <div className="p-6 space-y-8 min-h-screen">
            <div>
                <h1 className="text-3xl font-bold flex items-center gap-3 text-slate-900 dark:text-slate-100">
                    <Download className="w-8 h-8 text-indigo-500" />
                    Export Management
                </h1>
                <p className="text-slate-500 mt-2 text-lg">Configure default export formats, branding, and templates.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {[
                    { title: 'PDF Settings', icon: FileText, color: 'text-red-500', desc: 'Layout, Page Size, Branding' },
                    { title: 'Excel / CSV', icon: TableIcon, color: 'text-emerald-500', desc: 'Delimiter, Encoding, Headers' },
                    { title: 'Image Export', icon: Image, color: 'text-purple-500', desc: 'Resolution, Format (PNG/JPG)' },
                ].map((opt, i) => (
                    <div key={i} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 hover:shadow-lg transition-all cursor-pointer group">
                        <div className="flex justify-between items-start mb-4">
                            <div className={`p-4 rounded-xl bg-slate-50 dark:bg-slate-800 ${opt.color}`}>
                                <opt.icon className="w-8 h-8" />
                            </div>
                            <Settings className="w-5 h-5 text-slate-400 group-hover:text-indigo-500 transition-colors" />
                        </div>
                        <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100 mb-2">{opt.title}</h3>
                        <p className="text-slate-500 text-sm">{opt.desc}</p>
                    </div>
                ))}
            </div>

            <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-8">
                <h3 className="text-lg font-bold mb-6">Default Branding for Reports</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Company Logo</label>
                            <div className="border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-xl p-8 flex flex-col items-center justify-center text-center">
                                <Image className="w-8 h-8 text-slate-300 mb-2" />
                                <span className="text-sm font-bold text-indigo-600">Upload New Logo</span>
                                <span className="text-xs text-slate-400">PNG, JPG up to 2MB</span>
                            </div>
                        </div>
                    </div>
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Footer Text</label>
                            <input type="text" className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-xl p-3 text-sm" defaultValue="Confidential - Internal Use Only - Generated by AuraOS" />
                        </div>
                        <div>
                            <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Primary Color Hex</label>
                            <div className="flex items-center gap-2">
                                <div className="w-10 h-10 rounded-lg bg-indigo-600 shadow-sm"></div>
                                <input type="text" className="bg-slate-50 dark:bg-slate-800 border-none rounded-xl p-3 text-sm font-mono" defaultValue="#4F46E5" />
                            </div>
                        </div>
                    </div>
                </div>
                <div className="mt-8 flex justify-end">
                    <button className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-6 rounded-xl shadow-lg shadow-indigo-500/20">
                        Save Preferences
                    </button>
                </div>
            </div>
        </div>
    );
}
