/**
 * @module CountriesSeed
 * @description Seed data for countries
 * @project AURA HCM Platform
 * @reference docs/aura-master-instructions.md
 */

import { Country } from '@aura/types';

export const countriesSeed: Omit<Country, 'id' | 'createdAt' | 'updatedAt' | 'isDeleted'>[] = [
  {
    code: 'IN',
    code3: 'IND',
    name: 'India',
    nativeName: 'भारत',
    phoneCode: '+91',
    currencyCode: 'INR',
    timezones: ['Asia/Kolkata'],
    region: 'Asia',
    subregion: 'Southern Asia',
    flag: '🇮🇳',
    emoji: '🇮🇳',
    isActive: true,
  },
  {
    code: 'US',
    code3: 'USA',
    name: 'United States',
    nativeName: 'United States',
    phoneCode: '+1',
    currencyCode: 'USD',
    timezones: [
      'America/New_York',
      'America/Chicago',
      'America/Denver',
      'America/Los_Angeles',
      'America/Anchorage',
      'Pacific/Honolulu',
    ],
    region: 'Americas',
    subregion: 'Northern America',
    flag: '🇺🇸',
    emoji: '🇺🇸',
    isActive: true,
  },
  {
    code: 'GB',
    code3: 'GBR',
    name: 'United Kingdom',
    nativeName: 'United Kingdom',
    phoneCode: '+44',
    currencyCode: 'GBP',
    timezones: ['Europe/London'],
    region: 'Europe',
    subregion: 'Northern Europe',
    flag: '🇬🇧',
    emoji: '🇬🇧',
    isActive: true,
  },
  {
    code: 'CA',
    code3: 'CAN',
    name: 'Canada',
    nativeName: 'Canada',
    phoneCode: '+1',
    currencyCode: 'CAD',
    timezones: [
      'America/Toronto',
      'America/Winnipeg',
      'America/Edmonton',
      'America/Vancouver',
      'America/Halifax',
    ],
    region: 'Americas',
    subregion: 'Northern America',
    flag: '🇨🇦',
    emoji: '🇨🇦',
    isActive: true,
  },
  {
    code: 'AU',
    code3: 'AUS',
    name: 'Australia',
    nativeName: 'Australia',
    phoneCode: '+61',
    currencyCode: 'AUD',
    timezones: [
      'Australia/Sydney',
      'Australia/Melbourne',
      'Australia/Brisbane',
      'Australia/Perth',
      'Australia/Adelaide',
    ],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    flag: '🇦🇺',
    emoji: '🇦🇺',
    isActive: true,
  },
  {
    code: 'SG',
    code3: 'SGP',
    name: 'Singapore',
    nativeName: 'Singapore',
    phoneCode: '+65',
    currencyCode: 'SGD',
    timezones: ['Asia/Singapore'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    flag: '🇸🇬',
    emoji: '🇸🇬',
    isActive: true,
  },
  {
    code: 'AE',
    code3: 'ARE',
    name: 'United Arab Emirates',
    nativeName: 'الإمارات العربية المتحدة',
    phoneCode: '+971',
    currencyCode: 'AED',
    timezones: ['Asia/Dubai'],
    region: 'Asia',
    subregion: 'Western Asia',
    flag: '🇦🇪',
    emoji: '🇦🇪',
    isActive: true,
  },
  {
    code: 'DE',
    code3: 'DEU',
    name: 'Germany',
    nativeName: 'Deutschland',
    phoneCode: '+49',
    currencyCode: 'EUR',
    timezones: ['Europe/Berlin'],
    region: 'Europe',
    subregion: 'Western Europe',
    flag: '🇩🇪',
    emoji: '🇩🇪',
    isActive: true,
  },
  {
    code: 'FR',
    code3: 'FRA',
    name: 'France',
    nativeName: 'France',
    phoneCode: '+33',
    currencyCode: 'EUR',
    timezones: ['Europe/Paris'],
    region: 'Europe',
    subregion: 'Western Europe',
    flag: '🇫🇷',
    emoji: '🇫🇷',
    isActive: true,
  },
  {
    code: 'JP',
    code3: 'JPN',
    name: 'Japan',
    nativeName: '日本',
    phoneCode: '+81',
    currencyCode: 'JPY',
    timezones: ['Asia/Tokyo'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    flag: '🇯🇵',
    emoji: '🇯🇵',
    isActive: true,
  },
  {
    code: 'CN',
    code3: 'CHN',
    name: 'China',
    nativeName: '中国',
    phoneCode: '+86',
    currencyCode: 'CNY',
    timezones: ['Asia/Shanghai'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    flag: '🇨🇳',
    emoji: '🇨🇳',
    isActive: true,
  },
  {
    code: 'BR',
    code3: 'BRA',
    name: 'Brazil',
    nativeName: 'Brasil',
    phoneCode: '+55',
    currencyCode: 'BRL',
    timezones: ['America/Sao_Paulo', 'America/Manaus', 'America/Recife'],
    region: 'Americas',
    subregion: 'South America',
    flag: '🇧🇷',
    emoji: '🇧🇷',
    isActive: true,
  },
  {
    code: 'MX',
    code3: 'MEX',
    name: 'Mexico',
    nativeName: 'México',
    phoneCode: '+52',
    currencyCode: 'MXN',
    timezones: ['America/Mexico_City', 'America/Tijuana', 'America/Cancun'],
    region: 'Americas',
    subregion: 'Central America',
    flag: '🇲🇽',
    emoji: '🇲🇽',
    isActive: true,
  },
];
