/**
 * @module CurrenciesSeed
 * @description Seed data for currencies
 * @project AURA HCM Platform
 * @reference docs/aura-master-instructions.md
 */

export interface CurrencySeed {
  code: string;
  name: string;
  symbol: string;
  decimalPlaces: number;
  countries: string[];
  isActive: boolean;
  symbolPosition: 'before' | 'after';
  thousandsSeparator: ',' | '.' | ' ';
  decimalSeparator: '.' | ',';
  referenceRateToUSD: number;
}

export const currenciesSeed: CurrencySeed[] = [
  // ─── Major World Currencies ────────────────────────────────────────────────
  {
    code: 'USD',
    name: 'United States Dollar',
    symbol: '$',
    decimalPlaces: 2,
    countries: ['US'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 1.0,
  },
  {
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    decimalPlaces: 2,
    countries: ['DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'AT', 'PT', 'IE', 'FI'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 0.92,
  },
  {
    code: 'GBP',
    name: 'British Pound Sterling',
    symbol: '£',
    decimalPlaces: 2,
    countries: ['GB'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 0.79,
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    decimalPlaces: 0,
    countries: ['JP'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 149.5,
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    symbol: 'CHF',
    decimalPlaces: 2,
    countries: ['CH'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ' ',
    decimalSeparator: '.',
    referenceRateToUSD: 0.88,
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: 'C$',
    decimalPlaces: 2,
    countries: ['CA'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 1.36,
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: 'A$',
    decimalPlaces: 2,
    countries: ['AU'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 1.53,
  },
  {
    code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: 'NZ$',
    decimalPlaces: 2,
    countries: ['NZ'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 1.63,
  },
  {
    code: 'CNY',
    name: 'Chinese Yuan',
    symbol: '¥',
    decimalPlaces: 2,
    countries: ['CN'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 7.24,
  },
  {
    code: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: 'HK$',
    decimalPlaces: 2,
    countries: ['HK'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 7.82,
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar',
    symbol: 'S$',
    decimalPlaces: 2,
    countries: ['SG'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 1.34,
  },

  // ─── South Asian Currencies ────────────────────────────────────────────────
  {
    code: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    decimalPlaces: 2,
    countries: ['IN'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 83.12,
  },
  {
    code: 'PKR',
    name: 'Pakistani Rupee',
    symbol: '₨',
    decimalPlaces: 2,
    countries: ['PK'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 280.0,
  },
  {
    code: 'BDT',
    name: 'Bangladeshi Taka',
    symbol: '৳',
    decimalPlaces: 2,
    countries: ['BD'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 110.0,
  },
  {
    code: 'LKR',
    name: 'Sri Lankan Rupee',
    symbol: 'Rs',
    decimalPlaces: 2,
    countries: ['LK'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 320.0,
  },

  // ─── East & Southeast Asian Currencies ─────────────────────────────────────
  {
    code: 'KRW',
    name: 'South Korean Won',
    symbol: '₩',
    decimalPlaces: 0,
    countries: ['KR'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 1320.0,
  },
  {
    code: 'TWD',
    name: 'New Taiwan Dollar',
    symbol: 'NT$',
    decimalPlaces: 2,
    countries: ['TW'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 31.5,
  },
  {
    code: 'THB',
    name: 'Thai Baht',
    symbol: '฿',
    decimalPlaces: 2,
    countries: ['TH'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 35.5,
  },
  {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    decimalPlaces: 2,
    countries: ['MY'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 4.72,
  },
  {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    decimalPlaces: 0,
    countries: ['ID'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 15650.0,
  },
  {
    code: 'PHP',
    name: 'Philippine Peso',
    symbol: '₱',
    decimalPlaces: 2,
    countries: ['PH'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 56.2,
  },
  {
    code: 'VND',
    name: 'Vietnamese Dong',
    symbol: '₫',
    decimalPlaces: 0,
    countries: ['VN'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 24500.0,
  },

  // ─── Middle Eastern Currencies ─────────────────────────────────────────────
  {
    code: 'AED',
    name: 'United Arab Emirates Dirham',
    symbol: 'د.إ',
    decimalPlaces: 2,
    countries: ['AE'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 3.673,
  },
  {
    code: 'SAR',
    name: 'Saudi Riyal',
    symbol: '﷼',
    decimalPlaces: 2,
    countries: ['SA'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 3.75,
  },
  {
    code: 'QAR',
    name: 'Qatari Riyal',
    symbol: '﷼',
    decimalPlaces: 2,
    countries: ['QA'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 3.64,
  },
  {
    code: 'BHD',
    name: 'Bahraini Dinar',
    symbol: '.د.ب',
    decimalPlaces: 3,
    countries: ['BH'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 0.376,
  },
  {
    code: 'OMR',
    name: 'Omani Rial',
    symbol: '﷼',
    decimalPlaces: 3,
    countries: ['OM'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 0.385,
  },
  {
    code: 'KWD',
    name: 'Kuwaiti Dinar',
    symbol: 'د.ك',
    decimalPlaces: 3,
    countries: ['KW'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 0.308,
  },
  {
    code: 'JOD',
    name: 'Jordanian Dinar',
    symbol: 'د.ا',
    decimalPlaces: 3,
    countries: ['JO'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 0.709,
  },
  {
    code: 'ILS',
    name: 'Israeli New Shekel',
    symbol: '₪',
    decimalPlaces: 2,
    countries: ['IL'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 3.7,
  },
  {
    code: 'EGP',
    name: 'Egyptian Pound',
    symbol: 'E£',
    decimalPlaces: 2,
    countries: ['EG'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 30.9,
  },

  // ─── European Currencies (Non-Euro) ───────────────────────────────────────
  {
    code: 'SEK',
    name: 'Swedish Krona',
    symbol: 'kr',
    decimalPlaces: 2,
    countries: ['SE'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 10.5,
  },
  {
    code: 'NOK',
    name: 'Norwegian Krone',
    symbol: 'kr',
    decimalPlaces: 2,
    countries: ['NO'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 10.6,
  },
  {
    code: 'DKK',
    name: 'Danish Krone',
    symbol: 'kr',
    decimalPlaces: 2,
    countries: ['DK'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 6.88,
  },
  {
    code: 'PLN',
    name: 'Polish Zloty',
    symbol: 'zł',
    decimalPlaces: 2,
    countries: ['PL'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 4.02,
  },
  {
    code: 'CZK',
    name: 'Czech Koruna',
    symbol: 'Kč',
    decimalPlaces: 2,
    countries: ['CZ'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 22.8,
  },
  {
    code: 'HUF',
    name: 'Hungarian Forint',
    symbol: 'Ft',
    decimalPlaces: 0,
    countries: ['HU'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 356.0,
  },
  {
    code: 'RON',
    name: 'Romanian Leu',
    symbol: 'lei',
    decimalPlaces: 2,
    countries: ['RO'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 4.57,
  },
  {
    code: 'BGN',
    name: 'Bulgarian Lev',
    symbol: 'лв',
    decimalPlaces: 2,
    countries: ['BG'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 1.8,
  },
  {
    code: 'HRK',
    name: 'Croatian Kuna',
    symbol: 'kn',
    decimalPlaces: 2,
    countries: ['HR'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 6.93,
  },
  {
    code: 'RUB',
    name: 'Russian Ruble',
    symbol: '₽',
    decimalPlaces: 2,
    countries: ['RU'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 92.0,
  },
  {
    code: 'UAH',
    name: 'Ukrainian Hryvnia',
    symbol: '₴',
    decimalPlaces: 2,
    countries: ['UA'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: ' ',
    decimalSeparator: ',',
    referenceRateToUSD: 37.5,
  },
  {
    code: 'ISK',
    name: 'Icelandic Krona',
    symbol: 'kr',
    decimalPlaces: 0,
    countries: ['IS'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 138.0,
  },
  {
    code: 'TRY',
    name: 'Turkish Lira',
    symbol: '₺',
    decimalPlaces: 2,
    countries: ['TR'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 29.0,
  },

  // ─── Latin American Currencies ─────────────────────────────────────────────
  {
    code: 'BRL',
    name: 'Brazilian Real',
    symbol: 'R$',
    decimalPlaces: 2,
    countries: ['BR'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 4.97,
  },
  {
    code: 'MXN',
    name: 'Mexican Peso',
    symbol: '$',
    decimalPlaces: 2,
    countries: ['MX'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 17.15,
  },
  {
    code: 'ARS',
    name: 'Argentine Peso',
    symbol: '$',
    decimalPlaces: 2,
    countries: ['AR'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 830.0,
  },
  {
    code: 'COP',
    name: 'Colombian Peso',
    symbol: '$',
    decimalPlaces: 0,
    countries: ['CO'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 3950.0,
  },
  {
    code: 'CLP',
    name: 'Chilean Peso',
    symbol: '$',
    decimalPlaces: 0,
    countries: ['CL'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 880.0,
  },
  {
    code: 'PEN',
    name: 'Peruvian Sol',
    symbol: 'S/',
    decimalPlaces: 2,
    countries: ['PE'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 3.72,
  },

  // ─── African Currencies ────────────────────────────────────────────────────
  {
    code: 'ZAR',
    name: 'South African Rand',
    symbol: 'R',
    decimalPlaces: 2,
    countries: ['ZA'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ' ',
    decimalSeparator: '.',
    referenceRateToUSD: 18.5,
  },
  {
    code: 'NGN',
    name: 'Nigerian Naira',
    symbol: '₦',
    decimalPlaces: 2,
    countries: ['NG'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 780.0,
  },
  {
    code: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'KSh',
    decimalPlaces: 2,
    countries: ['KE'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 153.0,
  },
  {
    code: 'GHS',
    name: 'Ghanaian Cedi',
    symbol: 'GH₵',
    decimalPlaces: 2,
    countries: ['GH'],
    isActive: true,
    symbolPosition: 'before',
    thousandsSeparator: ',',
    decimalSeparator: '.',
    referenceRateToUSD: 12.5,
  },
  {
    code: 'MAD',
    name: 'Moroccan Dirham',
    symbol: 'د.م.',
    decimalPlaces: 2,
    countries: ['MA'],
    isActive: true,
    symbolPosition: 'after',
    thousandsSeparator: '.',
    decimalSeparator: ',',
    referenceRateToUSD: 10.0,
  },
];
