/**
 * @module LeaveTypesSeed
 * @description Seed data for common leave types
 * @project AURA HCM Platform
 * @reference docs/aura-master-instructions.md
 */


export const leaveTypesSeed = [
  {
    code: 'PL',
    name: 'Paid Leave',
    description: 'Annual paid leave for all employees',
    category: 'paid',
    isPaid: true,
    isCarryForward: true,
    maxCarryForward: 10,
    isEncashable: true,
    maxEncashment: 15,
    accrualType: 'monthly',
    accrualAmount: 1.5,
    maxBalance: 30,
    minServicePeriod: 0,
    requiresApproval: true,
    requiresDocument: false,
    gender: 'all',
    applicableAfter: 0,
    allowNegativeBalance: false,
    proration: true,
    isActive: true,
  },
  {
    code: 'SL',
    name: 'Sick Leave',
    description: 'Leave for medical emergencies',
    category: 'sick',
    isPaid: true,
    isCarryForward: true,
    maxCarryForward: 5,
    isEncashable: false,
    accrualType: 'monthly',
    accrualAmount: 0.67,
    maxBalance: 12,
    minServicePeriod: 0,
    requiresApproval: true,
    requiresDocument: true,
    gender: 'all',
    applicableAfter: 0,
    allowNegativeBalance: false,
    proration: true,
    isActive: true,
  },
  {
    code: 'CL',
    name: 'Casual Leave',
    description: 'Short-term casual leave',
    category: 'casual',
    isPaid: true,
    isCarryForward: false,
    isEncashable: false,
    accrualType: 'yearly',
    accrualAmount: 10,
    maxBalance: 10,
    minServicePeriod: 0,
    requiresApproval: true,
    requiresDocument: false,
    gender: 'all',
    applicableAfter: 0,
    allowNegativeBalance: false,
    proration: true,
    isActive: true,
  },
  {
    code: 'ML',
    name: 'Maternity Leave',
    description: 'Maternity leave for female employees',
    category: 'maternity',
    isPaid: true,
    isCarryForward: false,
    isEncashable: false,
    accrualType: 'manual',
    maxBalance: 180,
    minServicePeriod: 6,
    requiresApproval: true,
    requiresDocument: true,
    gender: 'female',
    applicableAfter: 6,
    allowNegativeBalance: false,
    proration: false,
    isActive: true,
  },
  {
    code: 'PTL',
    name: 'Paternity Leave',
    description: 'Paternity leave for male employees',
    category: 'paternity',
    isPaid: true,
    isCarryForward: false,
    isEncashable: false,
    accrualType: 'manual',
    maxBalance: 15,
    minServicePeriod: 6,
    requiresApproval: true,
    requiresDocument: true,
    gender: 'male',
    applicableAfter: 6,
    allowNegativeBalance: false,
    proration: false,
    isActive: true,
  },
  {
    code: 'CO',
    name: 'Compensatory Off',
    description: 'Compensatory leave for overtime work',
    category: 'compensatory',
    isPaid: true,
    isCarryForward: true,
    maxCarryForward: 5,
    isEncashable: true,
    maxEncashment: 10,
    accrualType: 'manual',
    maxBalance: 20,
    minServicePeriod: 0,
    requiresApproval: true,
    requiresDocument: false,
    gender: 'all',
    applicableAfter: 0,
    allowNegativeBalance: false,
    proration: false,
    isActive: true,
  },
  {
    code: 'LWP',
    name: 'Leave Without Pay',
    description: 'Leave without salary',
    category: 'unpaid',
    isPaid: false,
    isCarryForward: false,
    isEncashable: false,
    accrualType: 'manual',
    requiresApproval: true,
    requiresDocument: false,
    gender: 'all',
    applicableAfter: 0,
    allowNegativeBalance: true,
    maxNegativeBalance: 30,
    proration: false,
    isActive: true,
  },
  {
    code: 'BL',
    name: 'Bereavement Leave',
    description: 'Leave for death of immediate family member',
    category: 'other',
    isPaid: true,
    isCarryForward: false,
    isEncashable: false,
    accrualType: 'manual',
    maxBalance: 5,
    requiresApproval: true,
    requiresDocument: true,
    gender: 'all',
    applicableAfter: 0,
    allowNegativeBalance: false,
    proration: false,
    isActive: true,
  },
  {
    code: 'HAJJ',
    name: 'Hajj Leave',
    description: 'Pilgrimage leave for Hajj',
    category: 'other',
    isPaid: true,
    isCarryForward: false,
    isEncashable: false,
    accrualType: 'one_time', // Assuming schema supports this or falls back to 'manual'
    maxBalance: 15,
    minServicePeriod: 12,
    requiresApproval: true,
    requiresDocument: true,
    gender: 'all',
    applicableAfter: 12,
    allowNegativeBalance: false,
    proration: false,
    isActive: true,
  },
];
