/**
 * @module EmploymentTypesSeed
 * @description Seed data for employment types
 * @project AURA HCM Platform
 * @reference docs/aura-master-instructions.md
 */


export const employmentTypesSeed = [
  {
    code: 'FULL_TIME',
    name: 'Full Time',
    description: 'Full-time permanent employment',
    isPermanent: true,
    isFullTime: true,
    benefitsEligible: true,
    probationPeriod: 3,
    noticePeriod: 60,
    isActive: true,
  },
  {
    code: 'PART_TIME',
    name: 'Part Time',
    description: 'Part-time employment',
    isPermanent: true,
    isFullTime: false,
    benefitsEligible: false,
    probationPeriod: 2,
    noticePeriod: 30,
    isActive: true,
  },
  {
    code: 'CONTRACT',
    name: 'Contract',
    description: 'Contract-based employment',
    isPermanent: false,
    isFullTime: true,
    benefitsEligible: false,
    probationPeriod: 0,
    noticePeriod: 15,
    isActive: true,
  },
  {
    code: 'TEMPORARY',
    name: 'Temporary',
    description: 'Temporary employment',
    isPermanent: false,
    isFullTime: true,
    benefitsEligible: false,
    probationPeriod: 0,
    noticePeriod: 7,
    isActive: true,
  },
  {
    code: 'INTERN',
    name: 'Intern',
    description: 'Internship program',
    isPermanent: false,
    isFullTime: true,
    benefitsEligible: false,
    probationPeriod: 0,
    noticePeriod: 7,
    isActive: true,
  },
  {
    code: 'CONSULTANT',
    name: 'Consultant',
    description: 'Consultant engagement',
    isPermanent: false,
    isFullTime: false,
    benefitsEligible: false,
    probationPeriod: 0,
    noticePeriod: 15,
    isActive: true,
  },
  {
    code: 'FREELANCE',
    name: 'Freelance',
    description: 'Freelance engagement',
    isPermanent: false,
    isFullTime: false,
    benefitsEligible: false,
    probationPeriod: 0,
    noticePeriod: 0,
    isActive: true,
  },
];

export const employmentStatusesSeed = [
  {
    code: 'ACTIVE',
    name: 'Active',
    description: 'Actively employed',
    category: 'active',
    isPayrollEligible: true,
    isBenefitsEligible: true,
    isActive: true,
  },
  {
    code: 'PROBATION',
    name: 'Probation',
    description: 'On probation period',
    category: 'active',
    isPayrollEligible: true,
    isBenefitsEligible: false,
    isActive: true,
  },
  {
    code: 'NOTICE_PERIOD',
    name: 'Notice Period',
    description: 'Serving notice period',
    category: 'active',
    isPayrollEligible: true,
    isBenefitsEligible: true,
    isActive: true,
  },
  {
    code: 'ON_LEAVE',
    name: 'On Leave',
    description: 'On extended leave',
    category: 'on_hold',
    isPayrollEligible: true,
    isBenefitsEligible: true,
    isActive: true,
  },
  {
    code: 'SUSPENDED',
    name: 'Suspended',
    description: 'Temporarily suspended',
    category: 'suspended',
    isPayrollEligible: false,
    isBenefitsEligible: false,
    isActive: true,
  },
  {
    code: 'TERMINATED',
    name: 'Terminated',
    description: 'Employment terminated',
    category: 'terminated',
    isPayrollEligible: false,
    isBenefitsEligible: false,
    isActive: true,
  },
  {
    code: 'RESIGNED',
    name: 'Resigned',
    description: 'Employee resigned',
    category: 'terminated',
    isPayrollEligible: false,
    isBenefitsEligible: false,
    isActive: true,
  },
  {
    code: 'RETIRED',
    name: 'Retired',
    description: 'Retired from service',
    category: 'terminated',
    isPayrollEligible: false,
    isBenefitsEligible: false,
    isActive: true,
  },
];
