/**
 * @module GeoMastersSeed
 * @description Seed data for States and Cities (Global coverage - US, India, UK, Canada, and major countries)
 * @project AURA HCM Platform
 */

export const statesSeed = [
    // ─── United States (50 states + DC + 5 territories) ───────────────────────
    { code: 'US_AL', name: 'Alabama', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_AK', name: 'Alaska', countryCode: 'US', timezone: 'America/Anchorage' },
    { code: 'US_AZ', name: 'Arizona', countryCode: 'US', timezone: 'America/Phoenix' },
    { code: 'US_AR', name: 'Arkansas', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_CA', name: 'California', countryCode: 'US', timezone: 'America/Los_Angeles' },
    { code: 'US_CO', name: 'Colorado', countryCode: 'US', timezone: 'America/Denver' },
    { code: 'US_CT', name: 'Connecticut', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_DE', name: 'Delaware', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_FL', name: 'Florida', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_GA', name: 'Georgia', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_HI', name: 'Hawaii', countryCode: 'US', timezone: 'Pacific/Honolulu' },
    { code: 'US_ID', name: 'Idaho', countryCode: 'US', timezone: 'America/Boise' },
    { code: 'US_IL', name: 'Illinois', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_IN', name: 'Indiana', countryCode: 'US', timezone: 'America/Indiana/Indianapolis' },
    { code: 'US_IA', name: 'Iowa', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_KS', name: 'Kansas', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_KY', name: 'Kentucky', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_LA', name: 'Louisiana', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_ME', name: 'Maine', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_MD', name: 'Maryland', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_MA', name: 'Massachusetts', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_MI', name: 'Michigan', countryCode: 'US', timezone: 'America/Detroit' },
    { code: 'US_MN', name: 'Minnesota', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_MS', name: 'Mississippi', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_MO', name: 'Missouri', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_MT', name: 'Montana', countryCode: 'US', timezone: 'America/Denver' },
    { code: 'US_NE', name: 'Nebraska', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_NV', name: 'Nevada', countryCode: 'US', timezone: 'America/Los_Angeles' },
    { code: 'US_NH', name: 'New Hampshire', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_NJ', name: 'New Jersey', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_NM', name: 'New Mexico', countryCode: 'US', timezone: 'America/Denver' },
    { code: 'US_NY', name: 'New York', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_NC', name: 'North Carolina', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_ND', name: 'North Dakota', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_OH', name: 'Ohio', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_OK', name: 'Oklahoma', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_OR', name: 'Oregon', countryCode: 'US', timezone: 'America/Los_Angeles' },
    { code: 'US_PA', name: 'Pennsylvania', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_RI', name: 'Rhode Island', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_SC', name: 'South Carolina', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_SD', name: 'South Dakota', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_TN', name: 'Tennessee', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_TX', name: 'Texas', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_UT', name: 'Utah', countryCode: 'US', timezone: 'America/Denver' },
    { code: 'US_VT', name: 'Vermont', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_VA', name: 'Virginia', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_WA', name: 'Washington', countryCode: 'US', timezone: 'America/Los_Angeles' },
    { code: 'US_WV', name: 'West Virginia', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_WI', name: 'Wisconsin', countryCode: 'US', timezone: 'America/Chicago' },
    { code: 'US_WY', name: 'Wyoming', countryCode: 'US', timezone: 'America/Denver' },
    { code: 'US_DC', name: 'District of Columbia', countryCode: 'US', timezone: 'America/New_York' },
    { code: 'US_PR', name: 'Puerto Rico', countryCode: 'US', timezone: 'America/Puerto_Rico' },
    { code: 'US_GU', name: 'Guam', countryCode: 'US', timezone: 'Pacific/Guam' },
    { code: 'US_VI', name: 'U.S. Virgin Islands', countryCode: 'US', timezone: 'America/Virgin' },
    { code: 'US_AS', name: 'American Samoa', countryCode: 'US', timezone: 'Pacific/Pago_Pago' },
    { code: 'US_MP', name: 'Northern Mariana Islands', countryCode: 'US', timezone: 'Pacific/Guam' },

    // ─── India (28 states + 8 union territories) ─────────────────────────────
    { code: 'IN_AP', name: 'Andhra Pradesh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_AR', name: 'Arunachal Pradesh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_AS', name: 'Assam', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_BR', name: 'Bihar', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_CG', name: 'Chhattisgarh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_GA', name: 'Goa', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_GJ', name: 'Gujarat', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_HR', name: 'Haryana', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_HP', name: 'Himachal Pradesh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_JH', name: 'Jharkhand', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_KA', name: 'Karnataka', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_KL', name: 'Kerala', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_MP', name: 'Madhya Pradesh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_MH', name: 'Maharashtra', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_MN', name: 'Manipur', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_ML', name: 'Meghalaya', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_MZ', name: 'Mizoram', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_NL', name: 'Nagaland', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_OD', name: 'Odisha', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_PB', name: 'Punjab', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_RJ', name: 'Rajasthan', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_SK', name: 'Sikkim', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_TN', name: 'Tamil Nadu', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_TS', name: 'Telangana', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_TR', name: 'Tripura', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_UP', name: 'Uttar Pradesh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_UK', name: 'Uttarakhand', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_WB', name: 'West Bengal', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    // India Union Territories
    { code: 'IN_AN', name: 'Andaman and Nicobar Islands', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_CH', name: 'Chandigarh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_DD', name: 'Dadra and Nagar Haveli and Daman and Diu', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_DL', name: 'Delhi', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_JK', name: 'Jammu and Kashmir', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_LA', name: 'Ladakh', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_LD', name: 'Lakshadweep', countryCode: 'IN', timezone: 'Asia/Kolkata' },
    { code: 'IN_PY', name: 'Puducherry', countryCode: 'IN', timezone: 'Asia/Kolkata' },

    // ─── United Kingdom (England regions + Scotland, Wales, Northern Ireland) ─
    { code: 'GB_LDN', name: 'Greater London', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_SEE', name: 'South East England', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_SWE', name: 'South West England', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_WMD', name: 'West Midlands', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_EMD', name: 'East Midlands', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_EOE', name: 'East of England', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_YHU', name: 'Yorkshire and the Humber', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_NWE', name: 'North West England', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_NEE', name: 'North East England', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_SCT', name: 'Scotland', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_WLS', name: 'Wales', countryCode: 'GB', timezone: 'Europe/London' },
    { code: 'GB_NIR', name: 'Northern Ireland', countryCode: 'GB', timezone: 'Europe/London' },

    // ─── Canada (10 provinces + 3 territories) ───────────────────────────────
    { code: 'CA_ON', name: 'Ontario', countryCode: 'CA', timezone: 'America/Toronto' },
    { code: 'CA_QC', name: 'Quebec', countryCode: 'CA', timezone: 'America/Toronto' },
    { code: 'CA_BC', name: 'British Columbia', countryCode: 'CA', timezone: 'America/Vancouver' },
    { code: 'CA_AB', name: 'Alberta', countryCode: 'CA', timezone: 'America/Edmonton' },
    { code: 'CA_MB', name: 'Manitoba', countryCode: 'CA', timezone: 'America/Winnipeg' },
    { code: 'CA_SK', name: 'Saskatchewan', countryCode: 'CA', timezone: 'America/Regina' },
    { code: 'CA_NS', name: 'Nova Scotia', countryCode: 'CA', timezone: 'America/Halifax' },
    { code: 'CA_NB', name: 'New Brunswick', countryCode: 'CA', timezone: 'America/Moncton' },
    { code: 'CA_NL', name: 'Newfoundland and Labrador', countryCode: 'CA', timezone: 'America/St_Johns' },
    { code: 'CA_PE', name: 'Prince Edward Island', countryCode: 'CA', timezone: 'America/Halifax' },
    { code: 'CA_NT', name: 'Northwest Territories', countryCode: 'CA', timezone: 'America/Yellowknife' },
    { code: 'CA_YT', name: 'Yukon', countryCode: 'CA', timezone: 'America/Whitehorse' },
    { code: 'CA_NU', name: 'Nunavut', countryCode: 'CA', timezone: 'America/Iqaluit' },

    // ─── Australia (6 states + 2 territories) ────────────────────────────────
    { code: 'AU_NSW', name: 'New South Wales', countryCode: 'AU', timezone: 'Australia/Sydney' },
    { code: 'AU_VIC', name: 'Victoria', countryCode: 'AU', timezone: 'Australia/Melbourne' },
    { code: 'AU_QLD', name: 'Queensland', countryCode: 'AU', timezone: 'Australia/Brisbane' },
    { code: 'AU_WA', name: 'Western Australia', countryCode: 'AU', timezone: 'Australia/Perth' },
    { code: 'AU_SA', name: 'South Australia', countryCode: 'AU', timezone: 'Australia/Adelaide' },
    { code: 'AU_TAS', name: 'Tasmania', countryCode: 'AU', timezone: 'Australia/Hobart' },
    { code: 'AU_ACT', name: 'Australian Capital Territory', countryCode: 'AU', timezone: 'Australia/Sydney' },
    { code: 'AU_NT', name: 'Northern Territory', countryCode: 'AU', timezone: 'Australia/Darwin' },

    // ─── Singapore ────────────────────────────────────────────────────────────
    { code: 'SG_SG', name: 'Singapore', countryCode: 'SG', timezone: 'Asia/Singapore' },

    // ─── United Arab Emirates ─────────────────────────────────────────────────
    { code: 'AE_DU', name: 'Dubai', countryCode: 'AE', timezone: 'Asia/Dubai' },
    { code: 'AE_AB', name: 'Abu Dhabi', countryCode: 'AE', timezone: 'Asia/Dubai' },
    { code: 'AE_SH', name: 'Sharjah', countryCode: 'AE', timezone: 'Asia/Dubai' },
    { code: 'AE_AJ', name: 'Ajman', countryCode: 'AE', timezone: 'Asia/Dubai' },
    { code: 'AE_RK', name: 'Ras Al Khaimah', countryCode: 'AE', timezone: 'Asia/Dubai' },
    { code: 'AE_FU', name: 'Fujairah', countryCode: 'AE', timezone: 'Asia/Dubai' },
    { code: 'AE_UQ', name: 'Umm Al Quwain', countryCode: 'AE', timezone: 'Asia/Dubai' },

    // ─── Germany ──────────────────────────────────────────────────────────────
    { code: 'DE_BW', name: 'Baden-Wurttemberg', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_BY', name: 'Bavaria', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_BE', name: 'Berlin', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_BB', name: 'Brandenburg', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_HB', name: 'Bremen', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_HH', name: 'Hamburg', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_HE', name: 'Hesse', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_NI', name: 'Lower Saxony', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_MV', name: 'Mecklenburg-Vorpommern', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_NW', name: 'North Rhine-Westphalia', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_RP', name: 'Rhineland-Palatinate', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_SL', name: 'Saarland', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_SN', name: 'Saxony', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_ST', name: 'Saxony-Anhalt', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_SH', name: 'Schleswig-Holstein', countryCode: 'DE', timezone: 'Europe/Berlin' },
    { code: 'DE_TH', name: 'Thuringia', countryCode: 'DE', timezone: 'Europe/Berlin' },

    // ─── France ───────────────────────────────────────────────────────────────
    { code: 'FR_IDF', name: 'Ile-de-France', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_PAC', name: 'Provence-Alpes-Cote d\'Azur', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_ARA', name: 'Auvergne-Rhone-Alpes', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_OCC', name: 'Occitanie', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_NAQ', name: 'Nouvelle-Aquitaine', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_HDF', name: 'Hauts-de-France', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_GES', name: 'Grand Est', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_BRE', name: 'Brittany', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_NOR', name: 'Normandy', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_PDL', name: 'Pays de la Loire', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_CVL', name: 'Centre-Val de Loire', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_BFC', name: 'Bourgogne-Franche-Comte', countryCode: 'FR', timezone: 'Europe/Paris' },
    { code: 'FR_COR', name: 'Corsica', countryCode: 'FR', timezone: 'Europe/Paris' },

    // ─── Japan ────────────────────────────────────────────────────────────────
    { code: 'JP_TK', name: 'Tokyo', countryCode: 'JP', timezone: 'Asia/Tokyo' },
    { code: 'JP_OS', name: 'Osaka', countryCode: 'JP', timezone: 'Asia/Tokyo' },
    { code: 'JP_AI', name: 'Aichi', countryCode: 'JP', timezone: 'Asia/Tokyo' },
    { code: 'JP_FK', name: 'Fukuoka', countryCode: 'JP', timezone: 'Asia/Tokyo' },
    { code: 'JP_HK', name: 'Hokkaido', countryCode: 'JP', timezone: 'Asia/Tokyo' },
    { code: 'JP_KN', name: 'Kanagawa', countryCode: 'JP', timezone: 'Asia/Tokyo' },
    { code: 'JP_KY', name: 'Kyoto', countryCode: 'JP', timezone: 'Asia/Tokyo' },
    { code: 'JP_HG', name: 'Hyogo', countryCode: 'JP', timezone: 'Asia/Tokyo' },

    // ─── China ────────────────────────────────────────────────────────────────
    { code: 'CN_BJ', name: 'Beijing', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_SH', name: 'Shanghai', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_GD', name: 'Guangdong', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_JS', name: 'Jiangsu', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_ZJ', name: 'Zhejiang', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_SC', name: 'Sichuan', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_HB', name: 'Hubei', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_SD', name: 'Shandong', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_TJ', name: 'Tianjin', countryCode: 'CN', timezone: 'Asia/Shanghai' },
    { code: 'CN_CQ', name: 'Chongqing', countryCode: 'CN', timezone: 'Asia/Shanghai' },

    // ─── Brazil ───────────────────────────────────────────────────────────────
    { code: 'BR_SP', name: 'Sao Paulo', countryCode: 'BR', timezone: 'America/Sao_Paulo' },
    { code: 'BR_RJ', name: 'Rio de Janeiro', countryCode: 'BR', timezone: 'America/Sao_Paulo' },
    { code: 'BR_MG', name: 'Minas Gerais', countryCode: 'BR', timezone: 'America/Sao_Paulo' },
    { code: 'BR_BA', name: 'Bahia', countryCode: 'BR', timezone: 'America/Bahia' },
    { code: 'BR_RS', name: 'Rio Grande do Sul', countryCode: 'BR', timezone: 'America/Sao_Paulo' },
    { code: 'BR_PR', name: 'Parana', countryCode: 'BR', timezone: 'America/Sao_Paulo' },
    { code: 'BR_PE', name: 'Pernambuco', countryCode: 'BR', timezone: 'America/Recife' },
    { code: 'BR_DF', name: 'Distrito Federal', countryCode: 'BR', timezone: 'America/Sao_Paulo' },

    // ─── Mexico ───────────────────────────────────────────────────────────────
    { code: 'MX_CMX', name: 'Ciudad de Mexico', countryCode: 'MX', timezone: 'America/Mexico_City' },
    { code: 'MX_JAL', name: 'Jalisco', countryCode: 'MX', timezone: 'America/Mexico_City' },
    { code: 'MX_NLE', name: 'Nuevo Leon', countryCode: 'MX', timezone: 'America/Monterrey' },
    { code: 'MX_PUE', name: 'Puebla', countryCode: 'MX', timezone: 'America/Mexico_City' },
    { code: 'MX_GUA', name: 'Guanajuato', countryCode: 'MX', timezone: 'America/Mexico_City' },
    { code: 'MX_MEX', name: 'State of Mexico', countryCode: 'MX', timezone: 'America/Mexico_City' },
    { code: 'MX_QUE', name: 'Queretaro', countryCode: 'MX', timezone: 'America/Mexico_City' },

    // ─── Saudi Arabia ─────────────────────────────────────────────────────────
    { code: 'SA_RI', name: 'Riyadh Region', countryCode: 'SA', timezone: 'Asia/Riyadh' },
    { code: 'SA_MK', name: 'Makkah Region', countryCode: 'SA', timezone: 'Asia/Riyadh' },
    { code: 'SA_EP', name: 'Eastern Province', countryCode: 'SA', timezone: 'Asia/Riyadh' },
    { code: 'SA_MD', name: 'Madinah Region', countryCode: 'SA', timezone: 'Asia/Riyadh' },
    { code: 'SA_QS', name: 'Qassim Region', countryCode: 'SA', timezone: 'Asia/Riyadh' },

    // ─── New Zealand ──────────────────────────────────────────────────────────
    { code: 'NZ_AUK', name: 'Auckland', countryCode: 'NZ', timezone: 'Pacific/Auckland' },
    { code: 'NZ_WGN', name: 'Wellington', countryCode: 'NZ', timezone: 'Pacific/Auckland' },
    { code: 'NZ_CAN', name: 'Canterbury', countryCode: 'NZ', timezone: 'Pacific/Auckland' },
    { code: 'NZ_WKO', name: 'Waikato', countryCode: 'NZ', timezone: 'Pacific/Auckland' },
    { code: 'NZ_BOP', name: 'Bay of Plenty', countryCode: 'NZ', timezone: 'Pacific/Auckland' },
    { code: 'NZ_OTA', name: 'Otago', countryCode: 'NZ', timezone: 'Pacific/Auckland' },

    // ─── South Africa ─────────────────────────────────────────────────────────
    { code: 'ZA_GP', name: 'Gauteng', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_WC', name: 'Western Cape', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_KZN', name: 'KwaZulu-Natal', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_EC', name: 'Eastern Cape', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_LP', name: 'Limpopo', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_MP', name: 'Mpumalanga', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_NW', name: 'North West', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_FS', name: 'Free State', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },
    { code: 'ZA_NC', name: 'Northern Cape', countryCode: 'ZA', timezone: 'Africa/Johannesburg' },

    // ─── South Korea ──────────────────────────────────────────────────────────
    { code: 'KR_SE', name: 'Seoul', countryCode: 'KR', timezone: 'Asia/Seoul' },
    { code: 'KR_BS', name: 'Busan', countryCode: 'KR', timezone: 'Asia/Seoul' },
    { code: 'KR_DG', name: 'Daegu', countryCode: 'KR', timezone: 'Asia/Seoul' },
    { code: 'KR_IC', name: 'Incheon', countryCode: 'KR', timezone: 'Asia/Seoul' },
    { code: 'KR_GG', name: 'Gyeonggi', countryCode: 'KR', timezone: 'Asia/Seoul' },
    { code: 'KR_DJ', name: 'Daejeon', countryCode: 'KR', timezone: 'Asia/Seoul' },

    // ─── Italy ────────────────────────────────────────────────────────────────
    { code: 'IT_LZ', name: 'Lazio', countryCode: 'IT', timezone: 'Europe/Rome' },
    { code: 'IT_LO', name: 'Lombardy', countryCode: 'IT', timezone: 'Europe/Rome' },
    { code: 'IT_VN', name: 'Veneto', countryCode: 'IT', timezone: 'Europe/Rome' },
    { code: 'IT_CP', name: 'Campania', countryCode: 'IT', timezone: 'Europe/Rome' },
    { code: 'IT_ER', name: 'Emilia-Romagna', countryCode: 'IT', timezone: 'Europe/Rome' },
    { code: 'IT_PM', name: 'Piedmont', countryCode: 'IT', timezone: 'Europe/Rome' },
    { code: 'IT_TC', name: 'Tuscany', countryCode: 'IT', timezone: 'Europe/Rome' },
    { code: 'IT_SC', name: 'Sicily', countryCode: 'IT', timezone: 'Europe/Rome' },

    // ─── Spain ────────────────────────────────────────────────────────────────
    { code: 'ES_MD', name: 'Community of Madrid', countryCode: 'ES', timezone: 'Europe/Madrid' },
    { code: 'ES_CT', name: 'Catalonia', countryCode: 'ES', timezone: 'Europe/Madrid' },
    { code: 'ES_AN', name: 'Andalusia', countryCode: 'ES', timezone: 'Europe/Madrid' },
    { code: 'ES_VC', name: 'Valencian Community', countryCode: 'ES', timezone: 'Europe/Madrid' },
    { code: 'ES_GA', name: 'Galicia', countryCode: 'ES', timezone: 'Europe/Madrid' },
    { code: 'ES_PV', name: 'Basque Country', countryCode: 'ES', timezone: 'Europe/Madrid' },
    { code: 'ES_CN', name: 'Canary Islands', countryCode: 'ES', timezone: 'Atlantic/Canary' },

    // ─── Netherlands ──────────────────────────────────────────────────────────
    { code: 'NL_NH', name: 'North Holland', countryCode: 'NL', timezone: 'Europe/Amsterdam' },
    { code: 'NL_ZH', name: 'South Holland', countryCode: 'NL', timezone: 'Europe/Amsterdam' },
    { code: 'NL_NB', name: 'North Brabant', countryCode: 'NL', timezone: 'Europe/Amsterdam' },
    { code: 'NL_GE', name: 'Gelderland', countryCode: 'NL', timezone: 'Europe/Amsterdam' },
    { code: 'NL_UT', name: 'Utrecht', countryCode: 'NL', timezone: 'Europe/Amsterdam' },
    { code: 'NL_LI', name: 'Limburg', countryCode: 'NL', timezone: 'Europe/Amsterdam' },

    // ─── Qatar ────────────────────────────────────────────────────────────────
    { code: 'QA_DA', name: 'Doha', countryCode: 'QA', timezone: 'Asia/Qatar' },

    // ─── Bahrain ──────────────────────────────────────────────────────────────
    { code: 'BH_CA', name: 'Capital Governorate', countryCode: 'BH', timezone: 'Asia/Bahrain' },

    // ─── Oman ─────────────────────────────────────────────────────────────────
    { code: 'OM_MU', name: 'Muscat Governorate', countryCode: 'OM', timezone: 'Asia/Muscat' },
];

export const citiesSeed = [
    // ─── United States ────────────────────────────────────────────────────────
    { name: 'New York City', stateCode: 'US_NY' },
    { name: 'Buffalo', stateCode: 'US_NY' },
    { name: 'Albany', stateCode: 'US_NY' },
    { name: 'Rochester', stateCode: 'US_NY' },
    { name: 'Los Angeles', stateCode: 'US_CA' },
    { name: 'San Francisco', stateCode: 'US_CA' },
    { name: 'San Diego', stateCode: 'US_CA' },
    { name: 'San Jose', stateCode: 'US_CA' },
    { name: 'Sacramento', stateCode: 'US_CA' },
    { name: 'Chicago', stateCode: 'US_IL' },
    { name: 'Springfield', stateCode: 'US_IL' },
    { name: 'Aurora', stateCode: 'US_IL' },
    { name: 'Houston', stateCode: 'US_TX' },
    { name: 'Dallas', stateCode: 'US_TX' },
    { name: 'Austin', stateCode: 'US_TX' },
    { name: 'San Antonio', stateCode: 'US_TX' },
    { name: 'Fort Worth', stateCode: 'US_TX' },
    { name: 'Phoenix', stateCode: 'US_AZ' },
    { name: 'Tucson', stateCode: 'US_AZ' },
    { name: 'Mesa', stateCode: 'US_AZ' },
    { name: 'Philadelphia', stateCode: 'US_PA' },
    { name: 'Pittsburgh', stateCode: 'US_PA' },
    { name: 'Harrisburg', stateCode: 'US_PA' },
    { name: 'Jacksonville', stateCode: 'US_FL' },
    { name: 'Miami', stateCode: 'US_FL' },
    { name: 'Tampa', stateCode: 'US_FL' },
    { name: 'Orlando', stateCode: 'US_FL' },
    { name: 'Columbus', stateCode: 'US_OH' },
    { name: 'Cleveland', stateCode: 'US_OH' },
    { name: 'Cincinnati', stateCode: 'US_OH' },
    { name: 'Indianapolis', stateCode: 'US_IN' },
    { name: 'Fort Wayne', stateCode: 'US_IN' },
    { name: 'Charlotte', stateCode: 'US_NC' },
    { name: 'Raleigh', stateCode: 'US_NC' },
    { name: 'Durham', stateCode: 'US_NC' },
    { name: 'Seattle', stateCode: 'US_WA' },
    { name: 'Spokane', stateCode: 'US_WA' },
    { name: 'Tacoma', stateCode: 'US_WA' },
    { name: 'Denver', stateCode: 'US_CO' },
    { name: 'Colorado Springs', stateCode: 'US_CO' },
    { name: 'Boulder', stateCode: 'US_CO' },
    { name: 'Washington', stateCode: 'US_DC' },
    { name: 'Boston', stateCode: 'US_MA' },
    { name: 'Cambridge', stateCode: 'US_MA' },
    { name: 'Worcester', stateCode: 'US_MA' },
    { name: 'Nashville', stateCode: 'US_TN' },
    { name: 'Memphis', stateCode: 'US_TN' },
    { name: 'Knoxville', stateCode: 'US_TN' },
    { name: 'Detroit', stateCode: 'US_MI' },
    { name: 'Grand Rapids', stateCode: 'US_MI' },
    { name: 'Ann Arbor', stateCode: 'US_MI' },
    { name: 'Baltimore', stateCode: 'US_MD' },
    { name: 'Atlanta', stateCode: 'US_GA' },
    { name: 'Savannah', stateCode: 'US_GA' },
    { name: 'Minneapolis', stateCode: 'US_MN' },
    { name: 'Saint Paul', stateCode: 'US_MN' },
    { name: 'Kansas City', stateCode: 'US_MO' },
    { name: 'Saint Louis', stateCode: 'US_MO' },
    { name: 'Las Vegas', stateCode: 'US_NV' },
    { name: 'Reno', stateCode: 'US_NV' },
    { name: 'Portland', stateCode: 'US_OR' },
    { name: 'Eugene', stateCode: 'US_OR' },
    { name: 'New Orleans', stateCode: 'US_LA' },
    { name: 'Baton Rouge', stateCode: 'US_LA' },
    { name: 'Salt Lake City', stateCode: 'US_UT' },
    { name: 'Provo', stateCode: 'US_UT' },
    { name: 'Milwaukee', stateCode: 'US_WI' },
    { name: 'Madison', stateCode: 'US_WI' },
    { name: 'Birmingham', stateCode: 'US_AL' },
    { name: 'Montgomery', stateCode: 'US_AL' },
    { name: 'Anchorage', stateCode: 'US_AK' },
    { name: 'Little Rock', stateCode: 'US_AR' },
    { name: 'Hartford', stateCode: 'US_CT' },
    { name: 'Wilmington', stateCode: 'US_DE' },
    { name: 'Honolulu', stateCode: 'US_HI' },
    { name: 'Boise', stateCode: 'US_ID' },
    { name: 'Des Moines', stateCode: 'US_IA' },
    { name: 'Wichita', stateCode: 'US_KS' },
    { name: 'Louisville', stateCode: 'US_KY' },
    { name: 'Lexington', stateCode: 'US_KY' },
    { name: 'Portland', stateCode: 'US_ME' },
    { name: 'Jackson', stateCode: 'US_MS' },
    { name: 'Billings', stateCode: 'US_MT' },
    { name: 'Omaha', stateCode: 'US_NE' },
    { name: 'Lincoln', stateCode: 'US_NE' },
    { name: 'Manchester', stateCode: 'US_NH' },
    { name: 'Newark', stateCode: 'US_NJ' },
    { name: 'Jersey City', stateCode: 'US_NJ' },
    { name: 'Albuquerque', stateCode: 'US_NM' },
    { name: 'Santa Fe', stateCode: 'US_NM' },
    { name: 'Fargo', stateCode: 'US_ND' },
    { name: 'Oklahoma City', stateCode: 'US_OK' },
    { name: 'Tulsa', stateCode: 'US_OK' },
    { name: 'Providence', stateCode: 'US_RI' },
    { name: 'Charleston', stateCode: 'US_SC' },
    { name: 'Columbia', stateCode: 'US_SC' },
    { name: 'Sioux Falls', stateCode: 'US_SD' },
    { name: 'Burlington', stateCode: 'US_VT' },
    { name: 'Virginia Beach', stateCode: 'US_VA' },
    { name: 'Richmond', stateCode: 'US_VA' },
    { name: 'Norfolk', stateCode: 'US_VA' },
    { name: 'Charleston', stateCode: 'US_WV' },
    { name: 'Cheyenne', stateCode: 'US_WY' },
    { name: 'San Juan', stateCode: 'US_PR' },
    { name: 'Hagatna', stateCode: 'US_GU' },
    { name: 'Charlotte Amalie', stateCode: 'US_VI' },
    { name: 'Pago Pago', stateCode: 'US_AS' },
    { name: 'Saipan', stateCode: 'US_MP' },

    // ─── India ────────────────────────────────────────────────────────────────
    { name: 'Bangalore', stateCode: 'IN_KA' },
    { name: 'Mysore', stateCode: 'IN_KA' },
    { name: 'Hubli', stateCode: 'IN_KA' },
    { name: 'Mangalore', stateCode: 'IN_KA' },
    { name: 'Mumbai', stateCode: 'IN_MH' },
    { name: 'Pune', stateCode: 'IN_MH' },
    { name: 'Nagpur', stateCode: 'IN_MH' },
    { name: 'Nashik', stateCode: 'IN_MH' },
    { name: 'Thane', stateCode: 'IN_MH' },
    { name: 'New Delhi', stateCode: 'IN_DL' },
    { name: 'Chennai', stateCode: 'IN_TN' },
    { name: 'Coimbatore', stateCode: 'IN_TN' },
    { name: 'Madurai', stateCode: 'IN_TN' },
    { name: 'Salem', stateCode: 'IN_TN' },
    { name: 'Hyderabad', stateCode: 'IN_TS' },
    { name: 'Warangal', stateCode: 'IN_TS' },
    { name: 'Secunderabad', stateCode: 'IN_TS' },
    { name: 'Kolkata', stateCode: 'IN_WB' },
    { name: 'Howrah', stateCode: 'IN_WB' },
    { name: 'Durgapur', stateCode: 'IN_WB' },
    { name: 'Ahmedabad', stateCode: 'IN_GJ' },
    { name: 'Surat', stateCode: 'IN_GJ' },
    { name: 'Vadodara', stateCode: 'IN_GJ' },
    { name: 'Rajkot', stateCode: 'IN_GJ' },
    { name: 'Jaipur', stateCode: 'IN_RJ' },
    { name: 'Jodhpur', stateCode: 'IN_RJ' },
    { name: 'Udaipur', stateCode: 'IN_RJ' },
    { name: 'Lucknow', stateCode: 'IN_UP' },
    { name: 'Kanpur', stateCode: 'IN_UP' },
    { name: 'Agra', stateCode: 'IN_UP' },
    { name: 'Varanasi', stateCode: 'IN_UP' },
    { name: 'Noida', stateCode: 'IN_UP' },
    { name: 'Patna', stateCode: 'IN_BR' },
    { name: 'Gaya', stateCode: 'IN_BR' },
    { name: 'Bhopal', stateCode: 'IN_MP' },
    { name: 'Indore', stateCode: 'IN_MP' },
    { name: 'Jabalpur', stateCode: 'IN_MP' },
    { name: 'Kochi', stateCode: 'IN_KL' },
    { name: 'Thiruvananthapuram', stateCode: 'IN_KL' },
    { name: 'Kozhikode', stateCode: 'IN_KL' },
    { name: 'Chandigarh', stateCode: 'IN_CH' },
    { name: 'Gurgaon', stateCode: 'IN_HR' },
    { name: 'Faridabad', stateCode: 'IN_HR' },
    { name: 'Ludhiana', stateCode: 'IN_PB' },
    { name: 'Amritsar', stateCode: 'IN_PB' },
    { name: 'Jalandhar', stateCode: 'IN_PB' },
    { name: 'Visakhapatnam', stateCode: 'IN_AP' },
    { name: 'Vijayawada', stateCode: 'IN_AP' },
    { name: 'Tirupati', stateCode: 'IN_AP' },
    { name: 'Bhubaneswar', stateCode: 'IN_OD' },
    { name: 'Cuttack', stateCode: 'IN_OD' },
    { name: 'Ranchi', stateCode: 'IN_JH' },
    { name: 'Jamshedpur', stateCode: 'IN_JH' },
    { name: 'Raipur', stateCode: 'IN_CG' },
    { name: 'Dehradun', stateCode: 'IN_UK' },
    { name: 'Haridwar', stateCode: 'IN_UK' },
    { name: 'Panaji', stateCode: 'IN_GA' },
    { name: 'Margao', stateCode: 'IN_GA' },
    { name: 'Guwahati', stateCode: 'IN_AS' },
    { name: 'Shimla', stateCode: 'IN_HP' },
    { name: 'Gangtok', stateCode: 'IN_SK' },
    { name: 'Imphal', stateCode: 'IN_MN' },
    { name: 'Shillong', stateCode: 'IN_ML' },
    { name: 'Aizawl', stateCode: 'IN_MZ' },
    { name: 'Kohima', stateCode: 'IN_NL' },
    { name: 'Agartala', stateCode: 'IN_TR' },
    { name: 'Itanagar', stateCode: 'IN_AR' },
    { name: 'Srinagar', stateCode: 'IN_JK' },
    { name: 'Jammu', stateCode: 'IN_JK' },
    { name: 'Leh', stateCode: 'IN_LA' },
    { name: 'Puducherry', stateCode: 'IN_PY' },
    { name: 'Port Blair', stateCode: 'IN_AN' },

    // ─── United Kingdom ───────────────────────────────────────────────────────
    { name: 'London', stateCode: 'GB_LDN' },
    { name: 'Westminster', stateCode: 'GB_LDN' },
    { name: 'Croydon', stateCode: 'GB_LDN' },
    { name: 'Bromley', stateCode: 'GB_LDN' },
    { name: 'Manchester', stateCode: 'GB_NWE' },
    { name: 'Liverpool', stateCode: 'GB_NWE' },
    { name: 'Preston', stateCode: 'GB_NWE' },
    { name: 'Chester', stateCode: 'GB_NWE' },
    { name: 'Birmingham', stateCode: 'GB_WMD' },
    { name: 'Coventry', stateCode: 'GB_WMD' },
    { name: 'Wolverhampton', stateCode: 'GB_WMD' },
    { name: 'Leeds', stateCode: 'GB_YHU' },
    { name: 'Sheffield', stateCode: 'GB_YHU' },
    { name: 'Bradford', stateCode: 'GB_YHU' },
    { name: 'York', stateCode: 'GB_YHU' },
    { name: 'Bristol', stateCode: 'GB_SWE' },
    { name: 'Plymouth', stateCode: 'GB_SWE' },
    { name: 'Bath', stateCode: 'GB_SWE' },
    { name: 'Exeter', stateCode: 'GB_SWE' },
    { name: 'Brighton', stateCode: 'GB_SEE' },
    { name: 'Oxford', stateCode: 'GB_SEE' },
    { name: 'Reading', stateCode: 'GB_SEE' },
    { name: 'Southampton', stateCode: 'GB_SEE' },
    { name: 'Nottingham', stateCode: 'GB_EMD' },
    { name: 'Leicester', stateCode: 'GB_EMD' },
    { name: 'Derby', stateCode: 'GB_EMD' },
    { name: 'Cambridge', stateCode: 'GB_EOE' },
    { name: 'Norwich', stateCode: 'GB_EOE' },
    { name: 'Ipswich', stateCode: 'GB_EOE' },
    { name: 'Newcastle upon Tyne', stateCode: 'GB_NEE' },
    { name: 'Sunderland', stateCode: 'GB_NEE' },
    { name: 'Durham', stateCode: 'GB_NEE' },
    { name: 'Edinburgh', stateCode: 'GB_SCT' },
    { name: 'Glasgow', stateCode: 'GB_SCT' },
    { name: 'Aberdeen', stateCode: 'GB_SCT' },
    { name: 'Dundee', stateCode: 'GB_SCT' },
    { name: 'Inverness', stateCode: 'GB_SCT' },
    { name: 'Cardiff', stateCode: 'GB_WLS' },
    { name: 'Swansea', stateCode: 'GB_WLS' },
    { name: 'Newport', stateCode: 'GB_WLS' },
    { name: 'Belfast', stateCode: 'GB_NIR' },
    { name: 'Londonderry', stateCode: 'GB_NIR' },
    { name: 'Lisburn', stateCode: 'GB_NIR' },

    // ─── Canada ───────────────────────────────────────────────────────────────
    { name: 'Toronto', stateCode: 'CA_ON' },
    { name: 'Ottawa', stateCode: 'CA_ON' },
    { name: 'Mississauga', stateCode: 'CA_ON' },
    { name: 'Hamilton', stateCode: 'CA_ON' },
    { name: 'London', stateCode: 'CA_ON' },
    { name: 'Montreal', stateCode: 'CA_QC' },
    { name: 'Quebec City', stateCode: 'CA_QC' },
    { name: 'Laval', stateCode: 'CA_QC' },
    { name: 'Gatineau', stateCode: 'CA_QC' },
    { name: 'Vancouver', stateCode: 'CA_BC' },
    { name: 'Victoria', stateCode: 'CA_BC' },
    { name: 'Surrey', stateCode: 'CA_BC' },
    { name: 'Burnaby', stateCode: 'CA_BC' },
    { name: 'Kelowna', stateCode: 'CA_BC' },
    { name: 'Calgary', stateCode: 'CA_AB' },
    { name: 'Edmonton', stateCode: 'CA_AB' },
    { name: 'Red Deer', stateCode: 'CA_AB' },
    { name: 'Lethbridge', stateCode: 'CA_AB' },
    { name: 'Winnipeg', stateCode: 'CA_MB' },
    { name: 'Brandon', stateCode: 'CA_MB' },
    { name: 'Saskatoon', stateCode: 'CA_SK' },
    { name: 'Regina', stateCode: 'CA_SK' },
    { name: 'Halifax', stateCode: 'CA_NS' },
    { name: 'Dartmouth', stateCode: 'CA_NS' },
    { name: 'Fredericton', stateCode: 'CA_NB' },
    { name: 'Saint John', stateCode: 'CA_NB' },
    { name: 'Moncton', stateCode: 'CA_NB' },
    { name: 'St. John\'s', stateCode: 'CA_NL' },
    { name: 'Charlottetown', stateCode: 'CA_PE' },
    { name: 'Yellowknife', stateCode: 'CA_NT' },
    { name: 'Whitehorse', stateCode: 'CA_YT' },
    { name: 'Iqaluit', stateCode: 'CA_NU' },

    // ─── Australia ────────────────────────────────────────────────────────────
    { name: 'Sydney', stateCode: 'AU_NSW' },
    { name: 'Newcastle', stateCode: 'AU_NSW' },
    { name: 'Wollongong', stateCode: 'AU_NSW' },
    { name: 'Melbourne', stateCode: 'AU_VIC' },
    { name: 'Geelong', stateCode: 'AU_VIC' },
    { name: 'Ballarat', stateCode: 'AU_VIC' },
    { name: 'Brisbane', stateCode: 'AU_QLD' },
    { name: 'Gold Coast', stateCode: 'AU_QLD' },
    { name: 'Cairns', stateCode: 'AU_QLD' },
    { name: 'Townsville', stateCode: 'AU_QLD' },
    { name: 'Perth', stateCode: 'AU_WA' },
    { name: 'Fremantle', stateCode: 'AU_WA' },
    { name: 'Bunbury', stateCode: 'AU_WA' },
    { name: 'Adelaide', stateCode: 'AU_SA' },
    { name: 'Mount Gambier', stateCode: 'AU_SA' },
    { name: 'Hobart', stateCode: 'AU_TAS' },
    { name: 'Launceston', stateCode: 'AU_TAS' },
    { name: 'Canberra', stateCode: 'AU_ACT' },
    { name: 'Darwin', stateCode: 'AU_NT' },
    { name: 'Alice Springs', stateCode: 'AU_NT' },

    // ─── Singapore ────────────────────────────────────────────────────────────
    { name: 'Singapore', stateCode: 'SG_SG' },
    { name: 'Jurong East', stateCode: 'SG_SG' },
    { name: 'Tampines', stateCode: 'SG_SG' },
    { name: 'Woodlands', stateCode: 'SG_SG' },
    { name: 'Changi', stateCode: 'SG_SG' },

    // ─── United Arab Emirates ─────────────────────────────────────────────────
    { name: 'Dubai', stateCode: 'AE_DU' },
    { name: 'Jebel Ali', stateCode: 'AE_DU' },
    { name: 'Deira', stateCode: 'AE_DU' },
    { name: 'Abu Dhabi', stateCode: 'AE_AB' },
    { name: 'Al Ain', stateCode: 'AE_AB' },
    { name: 'Sharjah', stateCode: 'AE_SH' },
    { name: 'Ajman', stateCode: 'AE_AJ' },
    { name: 'Ras Al Khaimah', stateCode: 'AE_RK' },
    { name: 'Fujairah', stateCode: 'AE_FU' },

    // ─── Germany ──────────────────────────────────────────────────────────────
    { name: 'Berlin', stateCode: 'DE_BE' },
    { name: 'Munich', stateCode: 'DE_BY' },
    { name: 'Nuremberg', stateCode: 'DE_BY' },
    { name: 'Augsburg', stateCode: 'DE_BY' },
    { name: 'Hamburg', stateCode: 'DE_HH' },
    { name: 'Frankfurt', stateCode: 'DE_HE' },
    { name: 'Wiesbaden', stateCode: 'DE_HE' },
    { name: 'Cologne', stateCode: 'DE_NW' },
    { name: 'Dusseldorf', stateCode: 'DE_NW' },
    { name: 'Dortmund', stateCode: 'DE_NW' },
    { name: 'Essen', stateCode: 'DE_NW' },
    { name: 'Stuttgart', stateCode: 'DE_BW' },
    { name: 'Karlsruhe', stateCode: 'DE_BW' },
    { name: 'Mannheim', stateCode: 'DE_BW' },
    { name: 'Hanover', stateCode: 'DE_NI' },
    { name: 'Dresden', stateCode: 'DE_SN' },
    { name: 'Leipzig', stateCode: 'DE_SN' },
    { name: 'Bremen', stateCode: 'DE_HB' },

    // ─── France ───────────────────────────────────────────────────────────────
    { name: 'Paris', stateCode: 'FR_IDF' },
    { name: 'Versailles', stateCode: 'FR_IDF' },
    { name: 'Boulogne-Billancourt', stateCode: 'FR_IDF' },
    { name: 'Marseille', stateCode: 'FR_PAC' },
    { name: 'Nice', stateCode: 'FR_PAC' },
    { name: 'Toulon', stateCode: 'FR_PAC' },
    { name: 'Lyon', stateCode: 'FR_ARA' },
    { name: 'Grenoble', stateCode: 'FR_ARA' },
    { name: 'Saint-Etienne', stateCode: 'FR_ARA' },
    { name: 'Toulouse', stateCode: 'FR_OCC' },
    { name: 'Montpellier', stateCode: 'FR_OCC' },
    { name: 'Bordeaux', stateCode: 'FR_NAQ' },
    { name: 'Limoges', stateCode: 'FR_NAQ' },
    { name: 'Lille', stateCode: 'FR_HDF' },
    { name: 'Strasbourg', stateCode: 'FR_GES' },
    { name: 'Rennes', stateCode: 'FR_BRE' },
    { name: 'Brest', stateCode: 'FR_BRE' },
    { name: 'Rouen', stateCode: 'FR_NOR' },
    { name: 'Nantes', stateCode: 'FR_PDL' },

    // ─── Japan ────────────────────────────────────────────────────────────────
    { name: 'Tokyo', stateCode: 'JP_TK' },
    { name: 'Shibuya', stateCode: 'JP_TK' },
    { name: 'Shinjuku', stateCode: 'JP_TK' },
    { name: 'Osaka', stateCode: 'JP_OS' },
    { name: 'Sakai', stateCode: 'JP_OS' },
    { name: 'Nagoya', stateCode: 'JP_AI' },
    { name: 'Toyota', stateCode: 'JP_AI' },
    { name: 'Fukuoka', stateCode: 'JP_FK' },
    { name: 'Kitakyushu', stateCode: 'JP_FK' },
    { name: 'Sapporo', stateCode: 'JP_HK' },
    { name: 'Asahikawa', stateCode: 'JP_HK' },
    { name: 'Yokohama', stateCode: 'JP_KN' },
    { name: 'Kawasaki', stateCode: 'JP_KN' },
    { name: 'Kyoto', stateCode: 'JP_KY' },
    { name: 'Kobe', stateCode: 'JP_HG' },

    // ─── China ────────────────────────────────────────────────────────────────
    { name: 'Beijing', stateCode: 'CN_BJ' },
    { name: 'Shanghai', stateCode: 'CN_SH' },
    { name: 'Guangzhou', stateCode: 'CN_GD' },
    { name: 'Shenzhen', stateCode: 'CN_GD' },
    { name: 'Dongguan', stateCode: 'CN_GD' },
    { name: 'Foshan', stateCode: 'CN_GD' },
    { name: 'Nanjing', stateCode: 'CN_JS' },
    { name: 'Suzhou', stateCode: 'CN_JS' },
    { name: 'Wuxi', stateCode: 'CN_JS' },
    { name: 'Hangzhou', stateCode: 'CN_ZJ' },
    { name: 'Ningbo', stateCode: 'CN_ZJ' },
    { name: 'Wenzhou', stateCode: 'CN_ZJ' },
    { name: 'Chengdu', stateCode: 'CN_SC' },
    { name: 'Wuhan', stateCode: 'CN_HB' },
    { name: 'Qingdao', stateCode: 'CN_SD' },
    { name: 'Jinan', stateCode: 'CN_SD' },
    { name: 'Tianjin', stateCode: 'CN_TJ' },
    { name: 'Chongqing', stateCode: 'CN_CQ' },

    // ─── Brazil ───────────────────────────────────────────────────────────────
    { name: 'Sao Paulo', stateCode: 'BR_SP' },
    { name: 'Campinas', stateCode: 'BR_SP' },
    { name: 'Santos', stateCode: 'BR_SP' },
    { name: 'Guarulhos', stateCode: 'BR_SP' },
    { name: 'Rio de Janeiro', stateCode: 'BR_RJ' },
    { name: 'Niteroi', stateCode: 'BR_RJ' },
    { name: 'Belo Horizonte', stateCode: 'BR_MG' },
    { name: 'Uberlandia', stateCode: 'BR_MG' },
    { name: 'Salvador', stateCode: 'BR_BA' },
    { name: 'Porto Alegre', stateCode: 'BR_RS' },
    { name: 'Curitiba', stateCode: 'BR_PR' },
    { name: 'Recife', stateCode: 'BR_PE' },
    { name: 'Brasilia', stateCode: 'BR_DF' },

    // ─── Mexico ───────────────────────────────────────────────────────────────
    { name: 'Mexico City', stateCode: 'MX_CMX' },
    { name: 'Coyoacan', stateCode: 'MX_CMX' },
    { name: 'Guadalajara', stateCode: 'MX_JAL' },
    { name: 'Zapopan', stateCode: 'MX_JAL' },
    { name: 'Monterrey', stateCode: 'MX_NLE' },
    { name: 'San Nicolas de los Garza', stateCode: 'MX_NLE' },
    { name: 'Puebla', stateCode: 'MX_PUE' },
    { name: 'Leon', stateCode: 'MX_GUA' },
    { name: 'Irapuato', stateCode: 'MX_GUA' },
    { name: 'Toluca', stateCode: 'MX_MEX' },
    { name: 'Ecatepec', stateCode: 'MX_MEX' },
    { name: 'Queretaro', stateCode: 'MX_QUE' },

    // ─── Saudi Arabia ─────────────────────────────────────────────────────────
    { name: 'Riyadh', stateCode: 'SA_RI' },
    { name: 'Jeddah', stateCode: 'SA_MK' },
    { name: 'Mecca', stateCode: 'SA_MK' },
    { name: 'Dammam', stateCode: 'SA_EP' },
    { name: 'Dhahran', stateCode: 'SA_EP' },
    { name: 'Al Khobar', stateCode: 'SA_EP' },
    { name: 'Medina', stateCode: 'SA_MD' },
    { name: 'Buraidah', stateCode: 'SA_QS' },

    // ─── New Zealand ──────────────────────────────────────────────────────────
    { name: 'Auckland', stateCode: 'NZ_AUK' },
    { name: 'Manukau', stateCode: 'NZ_AUK' },
    { name: 'North Shore', stateCode: 'NZ_AUK' },
    { name: 'Wellington', stateCode: 'NZ_WGN' },
    { name: 'Lower Hutt', stateCode: 'NZ_WGN' },
    { name: 'Christchurch', stateCode: 'NZ_CAN' },
    { name: 'Timaru', stateCode: 'NZ_CAN' },
    { name: 'Hamilton', stateCode: 'NZ_WKO' },
    { name: 'Tauranga', stateCode: 'NZ_BOP' },
    { name: 'Dunedin', stateCode: 'NZ_OTA' },
    { name: 'Queenstown', stateCode: 'NZ_OTA' },

    // ─── South Africa ─────────────────────────────────────────────────────────
    { name: 'Johannesburg', stateCode: 'ZA_GP' },
    { name: 'Pretoria', stateCode: 'ZA_GP' },
    { name: 'Soweto', stateCode: 'ZA_GP' },
    { name: 'Sandton', stateCode: 'ZA_GP' },
    { name: 'Cape Town', stateCode: 'ZA_WC' },
    { name: 'Stellenbosch', stateCode: 'ZA_WC' },
    { name: 'Durban', stateCode: 'ZA_KZN' },
    { name: 'Pietermaritzburg', stateCode: 'ZA_KZN' },
    { name: 'Port Elizabeth', stateCode: 'ZA_EC' },
    { name: 'East London', stateCode: 'ZA_EC' },
    { name: 'Polokwane', stateCode: 'ZA_LP' },
    { name: 'Nelspruit', stateCode: 'ZA_MP' },
    { name: 'Rustenburg', stateCode: 'ZA_NW' },
    { name: 'Bloemfontein', stateCode: 'ZA_FS' },
    { name: 'Kimberley', stateCode: 'ZA_NC' },

    // ─── South Korea ──────────────────────────────────────────────────────────
    { name: 'Seoul', stateCode: 'KR_SE' },
    { name: 'Gangnam', stateCode: 'KR_SE' },
    { name: 'Busan', stateCode: 'KR_BS' },
    { name: 'Haeundae', stateCode: 'KR_BS' },
    { name: 'Daegu', stateCode: 'KR_DG' },
    { name: 'Incheon', stateCode: 'KR_IC' },
    { name: 'Suwon', stateCode: 'KR_GG' },
    { name: 'Seongnam', stateCode: 'KR_GG' },
    { name: 'Goyang', stateCode: 'KR_GG' },
    { name: 'Yongin', stateCode: 'KR_GG' },
    { name: 'Daejeon', stateCode: 'KR_DJ' },

    // ─── Italy ────────────────────────────────────────────────────────────────
    { name: 'Rome', stateCode: 'IT_LZ' },
    { name: 'Latina', stateCode: 'IT_LZ' },
    { name: 'Milan', stateCode: 'IT_LO' },
    { name: 'Bergamo', stateCode: 'IT_LO' },
    { name: 'Brescia', stateCode: 'IT_LO' },
    { name: 'Venice', stateCode: 'IT_VN' },
    { name: 'Verona', stateCode: 'IT_VN' },
    { name: 'Padua', stateCode: 'IT_VN' },
    { name: 'Naples', stateCode: 'IT_CP' },
    { name: 'Salerno', stateCode: 'IT_CP' },
    { name: 'Bologna', stateCode: 'IT_ER' },
    { name: 'Parma', stateCode: 'IT_ER' },
    { name: 'Turin', stateCode: 'IT_PM' },
    { name: 'Florence', stateCode: 'IT_TC' },
    { name: 'Pisa', stateCode: 'IT_TC' },
    { name: 'Palermo', stateCode: 'IT_SC' },
    { name: 'Catania', stateCode: 'IT_SC' },

    // ─── Spain ────────────────────────────────────────────────────────────────
    { name: 'Madrid', stateCode: 'ES_MD' },
    { name: 'Alcala de Henares', stateCode: 'ES_MD' },
    { name: 'Getafe', stateCode: 'ES_MD' },
    { name: 'Barcelona', stateCode: 'ES_CT' },
    { name: 'Girona', stateCode: 'ES_CT' },
    { name: 'Tarragona', stateCode: 'ES_CT' },
    { name: 'Seville', stateCode: 'ES_AN' },
    { name: 'Malaga', stateCode: 'ES_AN' },
    { name: 'Granada', stateCode: 'ES_AN' },
    { name: 'Cordoba', stateCode: 'ES_AN' },
    { name: 'Valencia', stateCode: 'ES_VC' },
    { name: 'Alicante', stateCode: 'ES_VC' },
    { name: 'Vigo', stateCode: 'ES_GA' },
    { name: 'A Coruna', stateCode: 'ES_GA' },
    { name: 'Bilbao', stateCode: 'ES_PV' },
    { name: 'San Sebastian', stateCode: 'ES_PV' },
    { name: 'Las Palmas', stateCode: 'ES_CN' },
    { name: 'Santa Cruz de Tenerife', stateCode: 'ES_CN' },

    // ─── Netherlands ──────────────────────────────────────────────────────────
    { name: 'Amsterdam', stateCode: 'NL_NH' },
    { name: 'Haarlem', stateCode: 'NL_NH' },
    { name: 'Rotterdam', stateCode: 'NL_ZH' },
    { name: 'The Hague', stateCode: 'NL_ZH' },
    { name: 'Leiden', stateCode: 'NL_ZH' },
    { name: 'Eindhoven', stateCode: 'NL_NB' },
    { name: 'Tilburg', stateCode: 'NL_NB' },
    { name: 'Breda', stateCode: 'NL_NB' },
    { name: 'Arnhem', stateCode: 'NL_GE' },
    { name: 'Nijmegen', stateCode: 'NL_GE' },
    { name: 'Utrecht', stateCode: 'NL_UT' },
    { name: 'Amersfoort', stateCode: 'NL_UT' },
    { name: 'Maastricht', stateCode: 'NL_LI' },

    // ─── Qatar ────────────────────────────────────────────────────────────────
    { name: 'Doha', stateCode: 'QA_DA' },
    { name: 'Al Wakrah', stateCode: 'QA_DA' },
    { name: 'Lusail', stateCode: 'QA_DA' },

    // ─── Bahrain ──────────────────────────────────────────────────────────────
    { name: 'Manama', stateCode: 'BH_CA' },
    { name: 'Muharraq', stateCode: 'BH_CA' },

    // ─── Oman ─────────────────────────────────────────────────────────────────
    { name: 'Muscat', stateCode: 'OM_MU' },
    { name: 'Seeb', stateCode: 'OM_MU' },
    { name: 'Muttrah', stateCode: 'OM_MU' },
];
