/**
 * @seed Employment History
 * @description Sample employment history records
 * @project AURA HCM Platform
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedEmploymentHistory() {
  console.log('🌱 Seeding Employment History...');

  // Note: This seed data assumes employees, departments, job profiles, grades, and locations exist
  // In production, employment history is typically auto-generated when employee data changes

  const sampleRecords = [
    {
      changeType: 'NEW_HIRE',
      effectiveDate: new Date('2022-01-15'),
      reason: 'Joined as Senior Engineer',
      status: 'COMPLETED',
      isAutoGenerated: false,
    },
    {
      changeType: 'PROMOTION',
      effectiveDate: new Date('2023-06-01'),
      reason: 'Promoted to Lead Engineer for outstanding performance',
      status: 'COMPLETED',
      isAutoGenerated: false,
    },
    {
      changeType: 'TRANSFER',
      effectiveDate: new Date('2024-03-15'),
      reason: 'Transferred to New York office',
      status: 'COMPLETED',
      isAutoGenerated: false,
    },
  ];

  console.log('✅ Sample employment history seed data prepared');
  console.log('Note: Actual seeding requires employee IDs. Use employee update workflows to generate real history.');
}

// Run if executed directly
if (require.main === module) {
  seedEmploymentHistory()
    .catch((e) => {
      console.error('❌ Error seeding employment history:', e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
