import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { withEnhancedAuth } from '@/lib/auth';
import { prisma } from '@aura/database';

// Alumni events are stored in the aura_alumni_event table (new model, accessed
// via (prisma as any) until the generated client is regenerated by the orchestrator).
const db = prisma as any;

function mapEvent(e: any) {
  return {
    eventId: e.id,
    eventName: e.eventName,
    eventType: e.eventType,
    eventFormat: e.eventFormat,
    description: e.description || '',
    eventDate: e.eventDate,
    eventTime: e.eventTime || '',
    endDate: e.endDate,
    venue: e.location ? { venueName: e.location } : undefined,
    virtualLink: e.virtualLink || undefined,
    eventStatus: e.status,
    maxAttendees: e.maxAttendees ?? undefined,
    currentAttendees: e.currentAttendees ?? 0,
    isFree: e.isFree,
    ticketPrice: e.ticketPrice ? Number(e.ticketPrice) : undefined,
    currency: e.currency || undefined,
    organizer: e.organizerName
      ? { organizerName: e.organizerName, organizerRole: 'Organizer' }
      : undefined,
    isReunion: e.isReunion,
    batchYear: e.batchYear ?? undefined,
    tags: e.tags || [],
    rsvpCount: e.currentAttendees ?? 0,
    location: e.location || '',
    createdDate: e.createdAt,
    lastUpdatedDate: e.updatedAt,
  };
}

export const GET = withEnhancedAuth(async (_request: NextRequest, context) => {
  try {
    const { user } = context;
    const events = await db.alumniEvent.findMany({
      where: { tenantId: user.tenantId, isReunion: false },
      orderBy: { eventDate: 'asc' },
    });
    return NextResponse.json(events.map(mapEvent), { status: 200 });
  } catch (error) {
    console.error('Error fetching alumni events:', error);
    return NextResponse.json(
      { message: 'Failed to fetch events', messageAr: 'فشل في جلب الفعاليات' },
      { status: 500 }
    );
  }
});

export const POST = withEnhancedAuth(async (request: NextRequest, context) => {
  try {
    const { user } = context;
    const body = await request.json();

    if (!body.eventName || !body.eventDate) {
      return NextResponse.json(
        {
          message: 'eventName and eventDate are required',
          messageAr: 'اسم الفعالية وتاريخها مطلوبان',
        },
        { status: 400 }
      );
    }

    const created = await db.alumniEvent.create({
      data: {
        tenantId: user.tenantId,
        eventName: body.eventName,
        eventType: body.eventType || 'networking',
        eventFormat: body.eventFormat || 'in_person',
        description: body.description || null,
        eventDate: new Date(body.eventDate),
        eventTime: body.eventTime || null,
        endDate: body.endDate ? new Date(body.endDate) : null,
        location: body.location || body.venue?.venueName || null,
        virtualLink: body.virtualLink || null,
        status: body.status || body.eventStatus || 'published',
        maxAttendees: body.maxAttendees ?? null,
        isFree: body.isFree ?? true,
        ticketPrice: body.ticketPrice ?? null,
        currency: body.currency || null,
        organizerName: body.organizerName || body.organizer?.organizerName || null,
        isReunion: Boolean(body.isReunion),
        batchYear: body.batchYear ?? null,
        tags: Array.isArray(body.tags) ? body.tags : [],
        createdBy: context.employeeId ?? user.userId,
      },
    });

    return NextResponse.json(mapEvent(created), { status: 201 });
  } catch (error) {
    console.error('Error creating alumni event:', error);
    return NextResponse.json(
      { message: 'Failed to create event', messageAr: 'فشل في إنشاء الفعالية' },
      { status: 500 }
    );
  }
});
