// @ts-nocheck — Dev/demo seed data, intentionally loose-typed.
/**
 * Recruitment Module - Sample Data
 */

import type {
    JobRequisition,
    JobPosting,
    CandidateApplication,
    Interview,
    InterviewFeedback,
    JobOffer,
    BackgroundCheck,
    HiringPipeline,
    RecruitmentSettings,
} from './types';

export const generateSampleJobRequisitions = (): JobRequisition[] => [
    {
        id: 'req_001',
        requisitionNumber: 'REQ-2025-001',
        jobTitle: 'Senior Software Engineer',
        departmentId: 'dept_engineering',
        departmentName: 'Engineering',
        locationId: 'loc_sf',
        locationName: 'San Francisco, CA',
        hiringManagerId: 'mgr_001',
        hiringManagerName: 'Sarah Johnson',
        recruiterId: 'rec_001',
        recruiterName: 'Mike Chen',
        jobType: 'full_time',
        experienceLevel: 'senior_level',
        employmentMode: 'hybrid',
        numberOfPositions: 2,
        positionsFilled: 0,
        status: 'open',
        priority: 'high',
        jobDescription: 'We are seeking an experienced Senior Software Engineer to join our platform team.',
        responsibilities: [
            'Design and implement scalable backend systems',
            'Lead technical discussions and architecture decisions',
            'Mentor junior engineers',
            'Collaborate with product and design teams',
        ],
        qualifications: [
            '5+ years of software engineering experience',
            'Strong experience with TypeScript/Node.js',
            'Experience with cloud platforms (AWS/GCP)',
            'Excellent communication skills',
        ],
        preferredQualifications: [
            'Experience with microservices architecture',
            'Open source contributions',
            'Leadership experience',
        ],
        skills: ['TypeScript', 'Node.js', 'React', 'AWS', 'PostgreSQL', 'GraphQL'],
        salaryRange: {
            min: 150000,
            max: 200000,
            currency: 'USD',
        },
        benefits: ['Health insurance', '401k matching', 'Stock options', 'Remote work'],
        targetStartDate: '2025-03-01',
        requestedDate: '2025-01-05T00:00:00Z',
        approvedDate: '2025-01-10T00:00:00Z',
        approvedBy: 'director_001',
        createdAt: '2025-01-05T00:00:00Z',
        updatedAt: '2025-01-10T00:00:00Z',
    },
    {
        id: 'req_002',
        requisitionNumber: 'REQ-2025-002',
        jobTitle: 'Product Designer',
        departmentId: 'dept_design',
        departmentName: 'Design',
        locationId: 'loc_ny',
        locationName: 'New York, NY',
        hiringManagerId: 'mgr_002',
        hiringManagerName: 'Alex Martinez',
        jobType: 'full_time',
        experienceLevel: 'mid_level',
        employmentMode: 'remote',
        numberOfPositions: 1,
        positionsFilled: 0,
        status: 'approved',
        priority: 'medium',
        jobDescription: 'Join our design team to create beautiful, user-centric product experiences.',
        responsibilities: [
            'Design user interfaces and experiences',
            'Create prototypes and mockups',
            'Conduct user research',
            'Collaborate with engineering team',
        ],
        qualifications: [
            '3+ years of product design experience',
            'Strong portfolio demonstrating UX/UI skills',
            'Experience with Figma or similar tools',
            'Understanding of design systems',
        ],
        skills: ['Figma', 'Sketch', 'Prototyping', 'User Research', 'Design Systems'],
        salaryRange: {
            min: 100000,
            max: 140000,
            currency: 'USD',
        },
        benefits: ['Health insurance', '401k', 'Professional development budget'],
        requestedDate: '2025-01-08T00:00:00Z',
        approvedDate: '2025-01-12T00:00:00Z',
        approvedBy: 'director_002',
        createdAt: '2025-01-08T00:00:00Z',
        updatedAt: '2025-01-12T00:00:00Z',
    },
];

export const generateSampleJobPostings = (): JobPosting[] => [
    {
        id: 'post_001',
        requisitionId: 'req_001',
        jobTitle: 'Senior Software Engineer',
        departmentName: 'Engineering',
        locationName: 'San Francisco, CA',
        jobType: 'full_time',
        experienceLevel: 'senior_level',
        employmentMode: 'hybrid',
        description: 'We are seeking an experienced Senior Software Engineer to join our platform team.',
        responsibilities: [
            'Design and implement scalable backend systems',
            'Lead technical discussions and architecture decisions',
            'Mentor junior engineers',
        ],
        qualifications: [
            '5+ years of software engineering experience',
            'Strong experience with TypeScript/Node.js',
            'Experience with cloud platforms (AWS/GCP)',
        ],
        skills: ['TypeScript', 'Node.js', 'React', 'AWS', 'PostgreSQL'],
        salaryRange: {
            min: 150000,
            max: 200000,
            currency: 'USD',
            displaySalary: true,
        },
        benefits: ['Health insurance', '401k matching', 'Stock options'],
        publishedDate: '2025-01-15T00:00:00Z',
        expiryDate: '2025-03-15T00:00:00Z',
        isActive: true,
        isExternal: true,
        externalBoards: ['LinkedIn', 'Indeed', 'Glassdoor'],
        applicationCount: 15,
        viewCount: 250,
        createdAt: '2025-01-15T00:00:00Z',
        updatedAt: '2025-01-15T00:00:00Z',
    },
];

export const generateSampleApplications = (): CandidateApplication[] => [
    {
        id: 'app_001',
        applicationNumber: 'APP-2025-001',
        jobPostingId: 'post_001',
        jobTitle: 'Senior Software Engineer',
        candidateId: 'cand_001',
        firstName: 'Emily',
        lastName: 'Chen',
        email: 'emily.chen@email.com',
        phone: '+1-555-0101',
        location: 'San Francisco, CA',
        resumeUrl: '/files/resumes/emily_chen_resume.pdf',
        linkedInUrl: 'https://linkedin.com/in/emilychen',
        source: 'linkedin',
        status: 'interview',
        currentStage: 'Technical Interview',
        rating: 4,
        experience: 7,
        currentCompany: 'Tech Corp',
        currentTitle: 'Software Engineer',
        expectedSalary: 175000,
        noticePeriod: 30,
        skills: ['TypeScript', 'Node.js', 'React', 'AWS', 'PostgreSQL', 'GraphQL'],
        education: [{
            id: 'edu_001',
            degree: 'BS Computer Science',
            field: 'Computer Science',
            institution: 'Stanford University',
            graduationYear: 2018,
            gpa: 3.8,
        }],
        workExperience: [{
            id: 'exp_001',
            title: 'Software Engineer',
            company: 'Tech Corp',
            startDate: '2018-07-01',
            endDate: undefined,
            isCurrent: true,
            description: 'Building scalable web applications using React and Node.js',
        }],
        appliedDate: '2025-01-16T00:00:00Z',
        lastActivityDate: '2025-01-20T00:00:00Z',
        tags: ['strong-candidate', 'local'],
        createdAt: '2025-01-16T00:00:00Z',
        updatedAt: '2025-01-20T00:00:00Z',
    },
    {
        id: 'app_002',
        applicationNumber: 'APP-2025-002',
        jobPostingId: 'post_001',
        jobTitle: 'Senior Software Engineer',
        candidateId: 'cand_002',
        firstName: 'Michael',
        lastName: 'Rodriguez',
        email: 'michael.r@email.com',
        phone: '+1-555-0102',
        location: 'Austin, TX',
        resumeUrl: '/files/resumes/michael_rodriguez_resume.pdf',
        source: 'referral',
        referredBy: 'John Doe (emp_001)',
        status: 'screening',
        currentStage: 'Phone Screen',
        rating: 5,
        experience: 8,
        currentCompany: 'Innovation Labs',
        currentTitle: 'Senior Engineer',
        expectedSalary: 180000,
        noticePeriod: 14,
        skills: ['TypeScript', 'Node.js', 'Python', 'AWS', 'Kubernetes', 'GraphQL'],
        education: [{
            id: 'edu_002',
            degree: 'MS Computer Science',
            field: 'Computer Science',
            institution: 'MIT',
            graduationYear: 2017,
            gpa: 3.9,
        }],
        workExperience: [{
            id: 'exp_002',
            title: 'Senior Engineer',
            company: 'Innovation Labs',
            startDate: '2020-03-01',
            endDate: undefined,
            isCurrent: true,
            description: 'Leading backend architecture and infrastructure initiatives',
        }],
        appliedDate: '2025-01-17T00:00:00Z',
        lastActivityDate: '2025-01-18T00:00:00Z',
        tags: ['referral', 'strong-candidate', 'relocation'],
        createdAt: '2025-01-17T00:00:00Z',
        updatedAt: '2025-01-18T00:00:00Z',
    },
];

export const generateSampleInterviews = (): Interview[] => [
    {
        id: 'int_001',
        applicationId: 'app_001',
        candidateName: 'Emily Chen',
        jobTitle: 'Senior Software Engineer',
        type: 'technical',
        status: 'completed',
        scheduledDate: '2025-01-22T14:00:00Z',
        duration: 60,
        meetingLink: 'https://zoom.us/j/123456789',
        interviewers: [
            {
                id: 'int_001_1',
                name: 'Sarah Johnson',
                email: 'sarah.j@company.com',
                role: 'Engineering Manager',
                isPrimary: true,
            },
            {
                id: 'int_001_2',
                name: 'David Lee',
                email: 'david.l@company.com',
                role: 'Senior Engineer',
                isPrimary: false,
            },
        ],
        feedback: [],
        createdAt: '2025-01-20T00:00:00Z',
        updatedAt: '2025-01-22T15:00:00Z',
    },
];

export const generateSampleInterviewFeedback = (): InterviewFeedback[] => [
    {
        id: 'fb_001',
        interviewId: 'int_001',
        interviewerId: 'int_001_1',
        interviewerName: 'Sarah Johnson',
        rating: 'strong_yes',
        technicalSkills: 5,
        communicationSkills: 5,
        problemSolving: 4,
        cultureFit: 5,
        strengths: 'Excellent problem-solving skills, strong technical knowledge, great communication',
        concerns: 'None significant',
        recommendation: 'hire',
        notes: 'Strong candidate, would be a great addition to the team',
        submittedDate: '2025-01-22T16:00:00Z',
    },
];

export const generateSampleJobOffers = (): JobOffer[] => [
    {
        id: 'offer_001',
        offerNumber: 'OFFER-2025-001',
        applicationId: 'app_001',
        candidateName: 'Emily Chen',
        jobTitle: 'Senior Software Engineer',
        departmentName: 'Engineering',
        status: 'sent',
        jobType: 'full_time',
        startDate: '2025-03-01',
        salary: 175000,
        currency: 'USD',
        bonus: 25000,
        equity: '0.15% stock options',
        benefits: ['Health insurance', '401k matching 6%', 'Stock options', 'Remote work flexibility'],
        relocationAssistance: false,
        signingBonus: 10000,
        probationPeriod: 3,
        sentDate: '2025-01-25T00:00:00Z',
        expiryDate: '2025-02-08T00:00:00Z',
        approvedBy: 'director_001',
        approvedDate: '2025-01-24T00:00:00Z',
        notes: 'Competitive offer based on market research and candidate expectations',
        createdAt: '2025-01-24T00:00:00Z',
        updatedAt: '2025-01-25T00:00:00Z',
    },
];

export const generateSampleBackgroundChecks = (): BackgroundCheck[] => [
    {
        id: 'bg_001',
        applicationId: 'app_001',
        candidateName: 'Emily Chen',
        status: 'in_progress',
        checks: [
            {
                id: 'bgc_001',
                type: 'criminal',
                status: 'in_progress',
            },
            {
                id: 'bgc_002',
                type: 'employment',
                status: 'in_progress',
            },
            {
                id: 'bgc_003',
                type: 'education',
                status: 'clear',
                result: 'Verified: BS Computer Science, Stanford University, 2018',
            },
        ],
        vendorName: 'CheckRight',
        requestedDate: '2025-01-26T00:00:00Z',
        createdAt: '2025-01-26T00:00:00Z',
        updatedAt: '2025-01-26T00:00:00Z',
    },
];

export const generateSampleHiringPipelines = (): HiringPipeline[] => [
    {
        id: 'pipeline_001',
        name: 'Standard Hiring Pipeline',
        stages: [
            { id: 'stage_001', name: 'Application Review', order: 1, isRequired: true, averageDuration: 2 },
            { id: 'stage_002', name: 'Phone Screen', order: 2, isRequired: true, averageDuration: 3 },
            { id: 'stage_003', name: 'Technical Interview', order: 3, isRequired: true, averageDuration: 7 },
            { id: 'stage_004', name: 'Behavioral Interview', order: 4, isRequired: true, averageDuration: 5 },
            { id: 'stage_005', name: 'Final Interview', order: 5, isRequired: true, averageDuration: 5 },
            { id: 'stage_006', name: 'Offer', order: 6, isRequired: true, averageDuration: 3 },
            { id: 'stage_007', name: 'Background Check', order: 7, isRequired: true, averageDuration: 7 },
            { id: 'stage_008', name: 'Hired', order: 8, isRequired: true, averageDuration: 0 },
        ],
        isDefault: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];

export const generateSampleRecruitmentSettings = (): RecruitmentSettings => ({
    defaultPipelineId: 'pipeline_001',
    applicationExpiryDays: 90,
    offerExpiryDays: 14,
    requireBackgroundCheck: true,
    requireReferenceCheck: true,
    autoRejectAfterDays: 30,
    emailTemplates: [
        {
            id: 'tmpl_001',
            name: 'Application Received',
            subject: 'Thank you for your application',
            body: 'Dear {{firstName}},\n\nThank you for applying to {{jobTitle}}. We have received your application and will review it shortly.',
            type: 'application_received',
        },
        {
            id: 'tmpl_002',
            name: 'Interview Invitation',
            subject: 'Interview Invitation - {{jobTitle}}',
            body: 'Dear {{firstName}},\n\nWe would like to invite you for an interview for the {{jobTitle}} position.',
            type: 'interview_scheduled',
        },
    ],
    screeningQuestions: [
        {
            id: 'sq_001',
            question: 'Are you legally authorized to work in the United States?',
            isRequired: true,
            isDisqualifying: true,
            expectedAnswer: 'Yes',
        },
        {
            id: 'sq_002',
            question: 'What is your expected salary range?',
            isRequired: true,
            isDisqualifying: false,
        },
    ],
});
