import type { ContentRights, BandwidthMetrics, AudienceMetrics, NetworkOperations, MediaSettings } from './types';

export const sampleContentRights: ContentRights[] = [{ rightsId: 'rights-001', contentId: 'content-001', contentTitle: 'Premium Sports Event 2024', contentType: 'video', rightsHolder: 'Global Sports Media Inc.', licenseType: 'Exclusive Broadcast Rights', territory: ['United States', 'Canada'], exclusivity: true, startDate: '2024-01-01', endDate: '2026-12-31', usageRights: { broadcast: true, streaming: true, digital: false, physical: false, derivative: false }, royalties: { royaltyType: 'hybrid', fixedAmount: 1000000, percentageRate: 15, minimumGuarantee: 500000, currency: 'USD', paymentSchedule: 'Quarterly' }, restrictions: ['No sublicensing to competitors'], sublicensing: false, status: 'active', createdAt: '2024-01-01T00:00:00Z' }];

export const sampleBandwidthMetrics: BandwidthMetrics[] = [{ metricId: 'bw-001', period: { startDate: '2024-12-01', endDate: '2024-12-13' }, totalBandwidth: 5000, averageBandwidth: 385, peakBandwidth: 1250, peakTime: '2024-12-10T20:00:00Z', dataTransferred: 125, unit: 'TB', costPerUnit: 0.15, totalCost: 18.75, utilizationRate: 77, trendData: [] }];

export const sampleAudienceMetrics: AudienceMetrics[] = [{ metricId: 'aud-001', period: { startDate: '2024-12-01', endDate: '2024-12-13' }, totalViews: 1500000, uniqueViewers: 850000, avgWatchTime: 1800, completionRate: 72, engagementRate: 65, demographics: { ageGroups: [{ ageRange: '18-24', percentage: 22 }, { ageRange: '25-34', percentage: 35 }, { ageRange: '35-44', percentage: 25 }], gender: { male: 58, female: 40, other: 2 } }, geography: [{ country: 'United States', views: 750000, uniqueViewers: 425000, percentage: 50 }], devices: [{ deviceType: 'Mobile', views: 600000, percentage: 40 }, { deviceType: 'Desktop', views: 525000, percentage: 35 }], sources: [{ source: 'Direct', views: 450000, percentage: 30 }, { source: 'Social Media', views: 600000, percentage: 40 }] }];

export const sampleNetworkOperations: NetworkOperations[] = [{ operationId: 'netop-001', operationType: 'maintenance', facilityId: 'facility-001', facilityName: 'Primary Data Center', equipment: [{ equipmentId: 'eq-001', equipmentType: 'Core Router', manufacturer: 'Cisco', model: 'ASR 9000', serialNumber: 'SN123456', location: 'Rack A-05', status: 'active' }], scheduledStart: '2024-12-15T02:00:00Z', scheduledEnd: '2024-12-15T06:00:00Z', technicians: [{ technicianId: 'tech-001', technicianName: 'John Network Engineer', specialization: 'Routing & Switching', certifications: ['CCNP', 'JNCIP'] }], status: 'scheduled', impact: { severity: 'low', affectedServices: ['Secondary streaming routes'], estimatedDowntime: 0, customerImpact: 0 }, createdAt: '2024-12-01T00:00:00Z' }];

export const sampleMediaSettings: MediaSettings = { settingsId: 'settings-001', organizationId: 'org-001', contentSettings: { rightsExpiryWarningDays: 90, autoRenewalEnabled: false }, bandwidthSettings: { alertThreshold: 85, costTrackingEnabled: true }, audienceSettings: { metricsUpdateFrequency: 3600, retentionPeriodDays: 365 }, networkSettings: { maintenanceWindowEnabled: true, incidentResponseTime: 15 }, notifications: { rightsExpiring: true, bandwidthAlert: true, networkIncident: true }, updatedAt: '2024-01-01T00:00:00Z' };
