"use client";
import { useState, useEffect, useCallback } from 'react';
import type { AuditLog, RolePermission, SecuritySettings, SecurityAlert } from '../types';
import { AuditLogService, RoleService, SecuritySettingsService, SecurityAlertService } from '../services';
import { sampleAuditLogs, sampleRoles, sampleSecuritySettings } from '../data';
interface Toast { type: 'success' | 'error' | 'info'; message: string; }
export const useSecurity = () => { const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]); const [roles, setRoles] = useState<RolePermission[]>([]); const [settings, setSettings] = useState<SecuritySettings | null>(null); const [alerts, setAlerts] = useState<SecurityAlert[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [toasts, setToasts] = useState<Toast[]>([]);
const addToast = useCallback((toast: Toast) => { setToasts(prev => [...prev, toast]); setTimeout(() => setToasts(prev => prev.slice(1)), 5000); }, []);
const loadAllData = useCallback(async () => { setLoading(true); try { const [logsData, rolesData, settingsData, alertsData] = await Promise.all([AuditLogService.getAll(), RoleService.getAll(), SecuritySettingsService.get(), SecurityAlertService.getAll()]); if (logsData.length === 0) { for (const l of sampleAuditLogs) await AuditLogService.create(l); setAuditLogs(sampleAuditLogs); } else setAuditLogs(logsData); if (rolesData.length === 0) { for (const r of sampleRoles) await RoleService.create(r); setRoles(sampleRoles); } else setRoles(rolesData); if (!settingsData) { await SecuritySettingsService.update(sampleSecuritySettings); setSettings(sampleSecuritySettings); } else setSettings(settingsData); setAlerts(alertsData); } catch (error) { setError(error instanceof Error ? error.message : 'Failed to load data'); addToast({ type: 'error', message: 'Failed to load security data' }); } finally { setLoading(false); } }, [addToast]);
useEffect(() => { loadAllData(); }, [loadAllData]);
const createAuditLog = async (data: Partial<AuditLog>) => { setLoading(true); try { const log = await AuditLogService.create(data); setAuditLogs(await AuditLogService.getAll()); return log; } catch (error) { addToast({ type: 'error', message: 'Failed to create audit log' }); throw error; } finally { setLoading(false); } };
const createRole = async (data: Partial<RolePermission>) => { setLoading(true); try { const role = await RoleService.create(data); setRoles(await RoleService.getAll()); addToast({ type: 'success', message: 'Role created' }); return role; } catch (error) { addToast({ type: 'error', message: 'Failed to create role' }); throw error; } finally { setLoading(false); } };
const updateRole = async (id: string, updates: Partial<RolePermission>) => { setLoading(true); try { const role = await RoleService.update(id, updates); setRoles(await RoleService.getAll()); addToast({ type: 'success', message: 'Role updated' }); return role; } catch (error) { addToast({ type: 'error', message: 'Failed to update role' }); throw error; } finally { setLoading(false); } };
const createAlert = async (data: Partial<SecurityAlert>) => { setLoading(true); try { const alert = await SecurityAlertService.create(data); setAlerts(await SecurityAlertService.getAll()); addToast({ type: 'success', message: 'Alert created' }); return alert; } catch (error) { addToast({ type: 'error', message: 'Failed to create alert' }); throw error; } finally { setLoading(false); } };
return { auditLogs, roles, settings, alerts, loading, error, toasts, createAuditLog, createRole, updateRole, createAlert, loadAllData }; };
