// @ts-nocheck — Dev/demo seed data, intentionally loose-typed.
/**
 * Finance & Budget Management Module - Sample Data
 * Comprehensive sample data for immediate testing
 */

import type { Budget, BudgetTemplate, BudgetScenario, Vendor, VendorContract, PettyCashFund, FinancialAsset } from './types';

// ============================================================================
// Sample Budgets
// ============================================================================

export const sampleBudgets: Budget[] = [
  {
    id: 'budget-001',
    budgetCode: 'BG-2024-ENG',
    budgetName: '2024 Engineering Department Budget',
    budgetType: 'department',
    status: 'approved',
    description: 'Annual operating budget for Engineering department covering salaries, tools, and operations',
    fiscalYear: 2024,
    period: 'annual',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-12-31T23:59:59Z',
    department: 'Engineering',
    costCenter: 'CC-100',
    lines: [
      {
        id: 'line-001',
        lineNumber: 1,
        category: 'Salaries & Benefits',
        subcategory: 'Base Salaries',
        description: 'Engineering team base salaries for 85 employees',
        budgetAmount: 12750000,
        allocatedAmount: 12750000,
        committedAmount: 10625000,
        actualAmount: 9562500,
        remainingAmount: 3187500,
        headcountBudget: {
          budgetedHeadcount: 95,
          currentHeadcount: 85,
          plannedHires: 15,
          plannedAttrition: 5,
          endingHeadcount: 95,
          averageSalary: 150000,
          totalSalaryCost: 12750000,
          benefitsCost: 3825000,
          totalCompensationCost: 16575000,
        },
      },
      {
        id: 'line-002',
        lineNumber: 2,
        category: 'Salaries & Benefits',
        subcategory: 'Benefits',
        description: 'Health insurance, 401k matching, and other benefits',
        budgetAmount: 3825000,
        allocatedAmount: 3825000,
        committedAmount: 3187500,
        actualAmount: 2868750,
        remainingAmount: 956250,
      },
      {
        id: 'line-003',
        lineNumber: 3,
        category: 'Technology & Tools',
        subcategory: 'Cloud Infrastructure',
        description: 'AWS, Azure, and other cloud services',
        budgetAmount: 1200000,
        allocatedAmount: 1200000,
        committedAmount: 900000,
        actualAmount: 825000,
        remainingAmount: 375000,
        periodBreakdown: [
          {
            period: '2024-Q1',
            startDate: '2024-01-01T00:00:00Z',
            endDate: '2024-03-31T23:59:59Z',
            budgetAmount: 300000,
            actualAmount: 285000,
            variance: 15000,
            variancePercentage: 5,
          },
          {
            period: '2024-Q2',
            startDate: '2024-04-01T00:00:00Z',
            endDate: '2024-06-30T23:59:59Z',
            budgetAmount: 300000,
            actualAmount: 290000,
            variance: 10000,
            variancePercentage: 3.33,
          },
          {
            period: '2024-Q3',
            startDate: '2024-07-01T00:00:00Z',
            endDate: '2024-09-30T23:59:59Z',
            budgetAmount: 300000,
            actualAmount: 250000,
            variance: 50000,
            variancePercentage: 16.67,
          },
        ],
        topExpenses: [
          {
            id: 'exp-001',
            date: '2024-03-15T00:00:00Z',
            description: 'AWS Monthly Bill - March',
            amount: 95000,
            vendor: 'Amazon Web Services',
            category: 'Cloud Infrastructure',
          },
          {
            id: 'exp-002',
            date: '2024-04-15T00:00:00Z',
            description: 'AWS Monthly Bill - April',
            amount: 98000,
            vendor: 'Amazon Web Services',
            category: 'Cloud Infrastructure',
          },
        ],
      },
      {
        id: 'line-004',
        lineNumber: 4,
        category: 'Technology & Tools',
        subcategory: 'Software Licenses',
        description: 'Development tools, IDEs, and productivity software',
        budgetAmount: 450000,
        allocatedAmount: 450000,
        committedAmount: 337500,
        actualAmount: 303750,
        remainingAmount: 146250,
      },
      {
        id: 'line-005',
        lineNumber: 5,
        category: 'Operations',
        subcategory: 'Recruiting',
        description: 'Recruiting fees, job postings, and candidate travel',
        budgetAmount: 300000,
        allocatedAmount: 300000,
        committedAmount: 150000,
        actualAmount: 135000,
        remainingAmount: 165000,
      },
      {
        id: 'line-006',
        lineNumber: 6,
        category: 'Operations',
        subcategory: 'Training & Development',
        description: 'Conferences, courses, and professional development',
        budgetAmount: 250000,
        allocatedAmount: 250000,
        committedAmount: 125000,
        actualAmount: 112500,
        remainingAmount: 137500,
      },
    ],
    totalBudget: 18775000,
    totalAllocated: 18775000,
    totalSpent: 13807500,
    totalRemaining: 4967500,
    utilizationRate: 73.5,
    approvalStatus: 'approved',
    approvedBy: 'CFO',
    approvedDate: '2023-12-15T00:00:00Z',
    version: '1.1',
    revisionHistory: [
      {
        id: 'rev-001',
        version: '1.1',
        revisionDate: '2024-03-01T00:00:00Z',
        revisedBy: 'budget-manager',
        revisedByName: 'Budget Manager',
        reason: 'Increased cloud infrastructure budget due to product expansion',
        changes: [
          {
            lineId: 'line-003',
            lineName: 'Cloud Infrastructure',
            fieldChanged: 'budgetAmount',
            oldValue: 1000000,
            newValue: 1200000,
            difference: 200000,
          },
        ],
        totalImpact: 200000,
      },
    ],
    createdBy: 'finance-team',
    createdByName: 'Finance Team',
    createdDate: '2023-11-01T00:00:00Z',
    lastModified: '2024-03-01T00:00:00Z',
    tags: ['engineering', 'department', '2024'],
  },
];

// ============================================================================
// Sample Budget Templates
// ============================================================================

export const sampleBudgetTemplates: BudgetTemplate[] = [
  {
    id: 'template-001',
    templateCode: 'TMPL-DEPT-STANDARD',
    templateName: 'Standard Department Budget Template',
    templateType: 'department',
    status: 'active',
    description: 'Standard template for departmental budgets including salaries, operations, and technology',
    templateLines: [
      {
        id: 'tl-001',
        lineNumber: 1,
        category: 'Salaries & Benefits',
        subcategory: 'Base Salaries',
        description: 'Employee base salaries',
        required: true,
        allowOverride: true,
        notes: 'Calculate based on headcount plan and average salary',
      },
      {
        id: 'tl-002',
        lineNumber: 2,
        category: 'Salaries & Benefits',
        subcategory: 'Benefits',
        description: 'Healthcare, 401k, and other benefits',
        defaultAmount: 0,
        calculationFormula: 'BaseSalaries * 0.30',
        required: true,
        allowOverride: true,
        notes: 'Typically 30% of base salaries',
      },
      {
        id: 'tl-003',
        lineNumber: 3,
        category: 'Technology & Tools',
        subcategory: 'Software & Licenses',
        description: 'Software licenses and tools',
        required: true,
        allowOverride: true,
      },
      {
        id: 'tl-004',
        lineNumber: 4,
        category: 'Operations',
        subcategory: 'Travel & Entertainment',
        description: 'Business travel, client entertainment, and events',
        required: false,
        allowOverride: true,
      },
      {
        id: 'tl-005',
        lineNumber: 5,
        category: 'Operations',
        subcategory: 'Training & Development',
        description: 'Employee training, conferences, and certifications',
        required: false,
        allowOverride: true,
      },
      {
        id: 'tl-006',
        lineNumber: 6,
        category: 'Operations',
        subcategory: 'Recruiting',
        description: 'Hiring costs including fees, postings, and relocation',
        required: false,
        allowOverride: true,
      },
    ],
    defaultPeriod: 'annual',
    defaultCurrency: 'USD',
    includeHeadcount: true,
    includeContingency: true,
    contingencyPercentage: 5,
    usageCount: 15,
    lastUsedDate: '2024-01-15T00:00:00Z',
    allowedDepartments: [],
    allowedRoles: ['finance', 'department_manager', 'executive'],
    createdBy: 'finance-team',
    createdDate: '2023-01-01T00:00:00Z',
    lastModified: '2023-06-15T00:00:00Z',
  },
];

// ============================================================================
// Sample Budget Scenarios
// ============================================================================

export const sampleBudgetScenarios: BudgetScenario[] = [
  {
    id: 'scenario-001',
    scenarioCode: 'SC-2024-OPTIMISTIC',
    scenarioName: '2024 Optimistic Growth Scenario',
    scenarioType: 'optimistic',
    status: 'active',
    description: 'Optimistic scenario with 25% revenue growth and aggressive hiring',
    baseBudgetId: 'budget-001',
    baseBudgetName: '2024 Engineering Department Budget',
    assumptions: [
      {
        id: 'assump-001',
        assumptionType: 'salary_increase',
        description: 'Average salary increase of 5%',
        baselineValue: 3,
        scenarioValue: 5,
        unit: 'percentage',
        impactDescription: 'Higher merit increases to retain top talent',
        affectedCategories: ['Salaries & Benefits'],
      },
      {
        id: 'assump-002',
        assumptionType: 'headcount_change',
        description: 'Aggressive hiring plan - 25 new hires',
        baselineValue: 10,
        scenarioValue: 25,
        unit: 'headcount',
        impactDescription: 'Accelerated growth to meet market demand',
        affectedCategories: ['Salaries & Benefits', 'Operations'],
      },
    ],
    adjustedLines: [],
    totalAdjustedBudget: 22100000,
    totalVarianceFromBase: 3325000,
    variancePercentage: 17.7,
    headcountImpact: {
      baselineHeadcount: 95,
      scenarioHeadcount: 110,
      headcountChange: 15,
      averageSalaryChange: 7500,
      totalCompensationChange: 2250000,
    },
    createdBy: 'finance-team',
    createdDate: '2024-01-20T00:00:00Z',
    lastModified: '2024-01-20T00:00:00Z',
  },
];

// ============================================================================
// Sample Vendors
// ============================================================================

export const sampleVendors: Vendor[] = [
  {
    id: 'vendor-001',
    vendorCode: 'VND-001',
    vendorName: 'CloudTech Solutions Inc.',
    vendorType: 'company',
    status: 'active',
    primaryContact: {
      name: 'John Smith',
      title: 'Account Manager',
      email: 'john.smith@cloudtech.com',
      phone: '+1-555-0123',
      mobile: '+1-555-0124',
    },
    email: 'accounts@cloudtech.com',
    phone: '+1-555-0100',
    website: 'https://www.cloudtech.com',
    billingAddress: {
      line1: '123 Tech Boulevard',
      line2: 'Suite 400',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      country: 'USA',
    },
    taxId: '12-3456789',
    businessRegistrationNumber: 'BRN-123456',
    insuranceCertificate: 'INS-2024-001',
    insuranceExpiryDate: '2025-12-31T23:59:59Z',
    paymentTerms: 'net_30',
    bankDetails: {
      bankName: 'Wells Fargo',
      accountName: 'CloudTech Solutions Inc.',
      accountNumber: '****5678',
      routingNumber: '121000248',
    },
    preferredPaymentMethod: 'bank_transfer',
    w9OnFile: true,
    backgroundCheckCompleted: true,
    contractOnFile: true,
    contractExpiryDate: '2025-06-30T23:59:59Z',
    categories: ['Cloud Services', 'Infrastructure', 'Technology'],
    servicesProvided: ['Cloud Infrastructure', 'Managed Services', 'Security Services'],
    performanceRating: 4.5,
    totalTransactions: 48,
    totalSpend: 1200000,
    averageInvoiceAmount: 25000,
    onTimePaymentRate: 98,
    qualityScore: 4.7,
    documents: [
      {
        id: 'doc-001',
        documentType: 'w9',
        documentName: 'W9 Form 2024',
        fileUrl: '/documents/vendor-001-w9.pdf',
        uploadedDate: '2024-01-05T00:00:00Z',
        status: 'current',
      },
      {
        id: 'doc-002',
        documentType: 'insurance',
        documentName: 'General Liability Insurance',
        fileUrl: '/documents/vendor-001-insurance.pdf',
        uploadedDate: '2024-01-05T00:00:00Z',
        expiryDate: '2025-12-31T23:59:59Z',
        status: 'current',
      },
    ],
    approvalStatus: 'approved',
    approvedBy: 'CFO',
    approvedDate: '2024-01-10T00:00:00Z',
    createdBy: 'procurement',
    createdDate: '2024-01-05T00:00:00Z',
    lastModified: '2024-01-10T00:00:00Z',
    lastTransactionDate: '2024-09-15T00:00:00Z',
    notes: 'Preferred vendor for cloud infrastructure. Excellent service record.',
  },
];

// ============================================================================
// Sample Vendor Contracts
// ============================================================================

export const sampleVendorContracts: VendorContract[] = [
  {
    id: 'contract-001',
    contractCode: 'CNT-2024-001',
    contractName: 'Cloud Infrastructure Services Agreement',
    vendorId: 'vendor-001',
    vendorName: 'CloudTech Solutions Inc.',
    contractType: 'time_and_materials',
    status: 'active',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-12-31T23:59:59Z',
    autoRenew: true,
    renewalNoticeDays: 60,
    totalContractValue: 1200000,
    currency: 'USD',
    paymentTerms: 'net_30',
    paymentSchedule: [
      {
        id: 'ps-001',
        milestoneDescription: 'Q1 2024 Services',
        dueDate: '2024-04-15T00:00:00Z',
        amount: 300000,
        paid: true,
        paidDate: '2024-04-10T00:00:00Z',
        invoiceNumber: 'INV-2024-Q1',
      },
      {
        id: 'ps-002',
        milestoneDescription: 'Q2 2024 Services',
        dueDate: '2024-07-15T00:00:00Z',
        amount: 300000,
        paid: true,
        paidDate: '2024-07-12T00:00:00Z',
        invoiceNumber: 'INV-2024-Q2',
      },
      {
        id: 'ps-003',
        milestoneDescription: 'Q3 2024 Services',
        dueDate: '2024-10-15T00:00:00Z',
        amount: 300000,
        paid: false,
      },
      {
        id: 'ps-004',
        milestoneDescription: 'Q4 2024 Services',
        dueDate: '2025-01-15T00:00:00Z',
        amount: 300000,
        paid: false,
      },
    ],
    servicesIncluded: [
      'Cloud infrastructure management',
      'Security monitoring',
      'Backup and disaster recovery',
      'Performance optimization',
      '24/7 technical support',
    ],
    deliverables: [
      {
        id: 'del-001',
        deliverableName: 'Monthly Service Report',
        description: 'Detailed monthly report on infrastructure performance and incidents',
        dueDate: '2024-01-31T00:00:00Z',
        completed: true,
        completionDate: '2024-01-28T00:00:00Z',
        acceptanceStatus: 'accepted',
      },
    ],
    kpis: [
      {
        id: 'kpi-001',
        kpiName: 'Uptime',
        targetValue: 99.9,
        actualValue: 99.95,
        unit: 'percentage',
        measurementFrequency: 'monthly',
      },
      {
        id: 'kpi-002',
        kpiName: 'Average Response Time',
        targetValue: 15,
        actualValue: 12,
        unit: 'minutes',
        measurementFrequency: 'monthly',
      },
    ],
    confidentialityClause: true,
    nonCompeteClause: false,
    terminationClause: 'Either party may terminate with 90 days written notice',
    disputeResolution: 'Binding arbitration in San Francisco, CA',
    totalSpent: 600000,
    remainingValue: 600000,
    utilizationRate: 50,
    amendments: [],
    createdBy: 'procurement',
    createdDate: '2023-11-15T00:00:00Z',
    lastModified: '2024-07-12T00:00:00Z',
  },
];

// ============================================================================
// Sample Petty Cash Funds
// ============================================================================

export const samplePettyCashFunds: PettyCashFund[] = [
  {
    id: 'fund-001',
    fundCode: 'PC-SF-001',
    fundName: 'San Francisco Office Petty Cash',
    status: 'active',
    department: 'Operations',
    location: 'San Francisco HQ',
    custodian: 'emp-001',
    custodianName: 'Jane Doe',
    initialBalance: 5000,
    currentBalance: 3250,
    totalDisbursed: 4750,
    totalReplenished: 3000,
    fundLimit: 5000,
    transactionLimit: 500,
    minimumBalance: 1000,
    transactions: [],
    lastReconciledDate: '2024-09-01T00:00:00Z',
    lastReconciledBy: 'finance-team',
    nextReconciliationDue: '2024-10-01T00:00:00Z',
    requireReceipt: true,
    requireApproval: true,
    approvalThreshold: 200,
    createdDate: '2024-01-01T00:00:00Z',
    lastModified: '2024-09-15T00:00:00Z',
  },
];

// ============================================================================
// Sample Financial Assets
// ============================================================================

export const sampleFinancialAssets: FinancialAsset[] = [
  {
    id: 'asset-001',
    assetCode: 'AST-2023-001',
    assetName: 'Dell PowerEdge R750 Server',
    assetType: 'it_equipment',
    status: 'active',
    description: 'Production database server for main application',
    purchasePrice: 15000,
    currentValue: 12000,
    depreciationMethod: 'straight_line',
    usefulLife: 5,
    salvageValue: 1500,
    accumulatedDepreciation: 3000,
    purchaseDate: '2023-01-15T00:00:00Z',
    vendor: 'Dell Technologies',
    invoiceNumber: 'DELL-2023-12345',
    warrantyExpiryDate: '2026-01-15T23:59:59Z',
    assignedTo: 'emp-tech-001',
    assignedToName: 'IT Department',
    department: 'IT',
    costCenter: 'CC-200',
    location: 'San Francisco Data Center',
    maintenanceSchedule: {
      frequency: 'quarterly',
      lastMaintenanceDate: '2024-07-15T00:00:00Z',
      nextMaintenanceDate: '2024-10-15T00:00:00Z',
      estimatedCost: 500,
    },
    maintenanceHistory: [
      {
        id: 'maint-001',
        maintenanceDate: '2024-07-15T00:00:00Z',
        maintenanceType: 'preventive',
        description: 'Quarterly maintenance check, firmware updates',
        cost: 450,
        performedBy: 'Dell Support',
        nextScheduledDate: '2024-10-15T00:00:00Z',
        notes: 'All systems operational, no issues found',
      },
    ],
    createdDate: '2023-01-15T00:00:00Z',
    lastModified: '2024-07-15T00:00:00Z',
    notes: 'Critical asset for production database. Handle with priority.',
  },
];
