import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const startDate = searchParams.get('startDate') || '2026-01-01';
  const endDate = searchParams.get('endDate') || '2026-01-23';
  const format = searchParams.get('format') || 'json';

  const auditLogExport = {
    exportId: 'audit-export-' + Date.now(),
    generatedAt: new Date().toISOString(),
    dateRange: { startDate, endDate },
    format,
    totalEntries: 2847,
    filters: {
      startDate,
      endDate,
      actions: searchParams.get('actions')?.split(',') || ['all'],
      users: searchParams.get('users')?.split(',') || ['all'],
      modules: searchParams.get('modules')?.split(',') || ['all'],
    },
    summary: {
      totalEvents: 2847,
      byAction: [
        { action: 'login', count: 1245 },
        { action: 'data_view', count: 634 },
        { action: 'data_update', count: 412 },
        { action: 'data_create', count: 234 },
        { action: 'data_delete', count: 45 },
        { action: 'permission_change', count: 23 },
        { action: 'settings_update', count: 67 },
        { action: 'export', count: 89 },
        { action: 'failed_login', count: 56 },
        { action: 'password_reset', count: 42 },
      ],
      byModule: [
        { module: 'Authentication', count: 1343 },
        { module: 'Employee Management', count: 523 },
        { module: 'Leave Management', count: 312 },
        { module: 'Payroll', count: 245 },
        { module: 'Admin Settings', count: 189 },
        { module: 'Analytics', count: 156 },
        { module: 'Learning', count: 79 },
      ],
      uniqueUsers: 456,
      suspiciousActivities: 3,
    },
    entries: [
      {
        id: 'log-001',
        timestamp: '2026-01-23T09:15:32Z',
        userId: 'user-042',
        userName: 'John Smith',
        action: 'data_update',
        module: 'Employee Management',
        resource: 'employee/emp-156',
        details: 'Updated salary field',
        ipAddress: '192.168.1.45',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        status: 'success',
        changes: { field: 'salary', before: '120000', after: '130000' },
      },
      {
        id: 'log-002',
        timestamp: '2026-01-23T09:12:18Z',
        userId: 'user-089',
        userName: 'Sarah Johnson',
        action: 'login',
        module: 'Authentication',
        resource: 'auth/session',
        details: 'Successful login via SSO',
        ipAddress: '10.0.5.23',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        status: 'success',
        changes: null,
      },
      {
        id: 'log-003',
        timestamp: '2026-01-23T08:45:01Z',
        userId: 'unknown',
        userName: null,
        action: 'failed_login',
        module: 'Authentication',
        resource: 'auth/login',
        details: 'Failed login attempt - invalid credentials',
        ipAddress: '203.45.67.89',
        userAgent: 'Mozilla/5.0 (Linux; Android 12)',
        status: 'failed',
        changes: null,
        flagged: true,
        flagReason: 'Multiple failed attempts from same IP',
      },
      {
        id: 'log-004',
        timestamp: '2026-01-23T08:30:00Z',
        userId: 'admin-001',
        userName: 'Admin User',
        action: 'permission_change',
        module: 'Admin Settings',
        resource: 'permissions/role-004',
        details: 'Updated Department Manager permissions',
        ipAddress: '192.168.1.10',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        status: 'success',
        changes: { role: 'Department Manager', added: ['analytics:export'], removed: [] },
      },
      {
        id: 'log-005',
        timestamp: '2026-01-23T08:15:45Z',
        userId: 'user-156',
        userName: 'Mike Chen',
        action: 'export',
        module: 'Analytics',
        resource: 'reports/rpt-001',
        details: 'Exported Monthly Headcount Summary report',
        ipAddress: '10.0.3.78',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        status: 'success',
        changes: null,
      },
    ],
    downloadUrl: format !== 'json' ? `/api/v1/admin/audit-log/export/download?id=audit-export-001&format=${format}` : null,
    retentionPolicy: {
      currentRetention: '365 days',
      oldestEntry: '2025-01-23T00:00:00Z',
      complianceStandard: 'SOC2',
    },
  };

  return NextResponse.json({ success: true, data: auditLogExport });
}
