export type StoreStatus = 'open' | 'closed' | 'limited_hours';
export type CommissionStatus = 'pending' | 'approved' | 'paid' | 'disputed';
export type HireStatus = 'applied' | 'screening' | 'interviewing' | 'offered' | 'hired' | 'rejected';

export interface Store { storeId: string; storeNumber: string; storeName: string; location: { address: string; city: string; state: string; zipCode: string; }; manager: string; employees: number; status: StoreStatus; operatingHours: { weekday: { open: string; close: string; }; weekend: { open: string; close: string; }; }; performance: StorePerformance; createdAt: string; updatedAt?: string; }
export interface StorePerformance { dailySales: number; monthlySales: number; salesTarget: number; targetAchievement: number; footTraffic: number; conversionRate: number; averageTransaction: number; topPerformers: TopPerformer[]; }
export interface TopPerformer { employeeId: string; employeeName: string; salesAmount: number; transactions: number; }
export interface CommissionPlan { planId: string; planName: string; planType: 'tiered' | 'flat' | 'progressive'; applicableRoles: string[]; tiers: CommissionTier[]; bonus: BonusStructure; effectiveDate: string; expiryDate?: string; status: 'active' | 'inactive'; createdAt: string; }
export interface CommissionTier { tierLevel: number; minSales: number; maxSales?: number; commissionRate: number; }
export interface BonusStructure { bonusType: 'monthly' | 'quarterly' | 'annual'; targetSales: number; bonusAmount: number; conditions: string[]; }
export interface SalesCommission { commissionId: string; employeeId: string; employeeName: string; period: { startDate: string; endDate: string; }; totalSales: number; commissionableAmount: number; commissionRate: number; commissionEarned: number; bonusEarned: number; totalEarnings: number; status: CommissionStatus; approvedBy?: string; approvalDate?: string; paidDate?: string; createdAt: string; }
export interface SeasonalHire { hireId: string; applicantName: string; email: string; phone: string; position: string; storeId: string; storeName: string; seasonPeriod: { startDate: string; endDate: string; }; availability: string[]; experience: number; interviewDate?: string; interviewScore?: number; status: HireStatus; hireDate?: string; terminationDate?: string; performance?: SeasonalPerformance; createdAt: string; updatedAt?: string; }
export interface SeasonalPerformance { attendanceRate: number; salesPerShift: number; customerRating: number; productKnowledge: number; overallRating: number; rehireEligible: boolean; }
export interface RetailSettings { settingsId: string; organizationId: string; storeSettings: { targetSalesGrowth: number; minStaffPerShift: number; maxOvertimeHours: number; }; commissionSettings: { paymentFrequency: 'weekly' | 'bi_weekly' | 'monthly'; approvalRequired: boolean; disputeWindow: number; }; seasonalSettings: { advanceRecruitmentDays: number; trainingHours: number; probationPeriod: number; }; notifications: { salesAlerts: boolean; commissionReady: boolean; applicationReceived: boolean; }; updatedAt: string; }
export interface RetailAlert { alertId: string; alertType: 'store_performance' | 'commission' | 'seasonal_hiring'; severity: 'low' | 'medium' | 'high'; title: string; message: string; status: 'active' | 'acknowledged' | 'resolved'; createdAt: string; }
