// @ts-nocheck — Dev/demo seed data, intentionally loose-typed.
import type {
  OnboardingProgram,
  OnboardingInstance,
  OnboardingTask,
  OnboardingDocument,
  OnboardingEquipment,
  OnboardingAccess,
  OnboardingTraining,
  BuddyAssignment,
  Day30_60_90Plan,
  OnboardingSurvey,
  Feedback,
  PreBoardingPackage,
  OnboardingMetrics,
  OnboardingSettings,
  OnboardingPhaseConfig,
  ChecklistTemplate,
  DocumentRequirement,
  EquipmentRequirement,
  SurveySchedule,
  PreBoardingMaterial,
  PreBoardingForm,
  FirstDayInformation,
  PlanMilestone,
} from './types';

// ============================================================================
// ONBOARDING PROGRAMS
// ============================================================================

export const sampleOnboardingPrograms: OnboardingProgram[] = [
  {
    id: 'prog_001',
    programCode: 'OB-ENG-001',
    programName: 'Software Engineer Onboarding',
    description: 'Comprehensive onboarding program for software engineers',
    departmentId: 'dept_engineering',
    departmentName: 'Engineering',
    jobLevelId: 'level_mid',
    jobLevelName: 'Mid-Level',
    isActive: true,
    duration: 90,
    phases: [
      {
        phaseName: 'pre_boarding',
        displayName: 'Pre-boarding',
        startDay: -7,
        endDay: 0,
        description: 'Pre-boarding activities before first day',
        tasks: [
          {
            taskName: 'Complete background verification',
            description: 'Submit required documents for background check',
            assignedTo: 'employee',
            dueInDays: -5,
            estimatedHours: 1,
            isMandatory: true,
          },
          {
            taskName: 'Review welcome package',
            description: 'Read through welcome materials and company handbook',
            assignedTo: 'employee',
            dueInDays: -3,
            estimatedHours: 2,
            isMandatory: true,
          },
          {
            taskName: 'Complete I-9 verification',
            description: 'Submit employment eligibility documents',
            assignedTo: 'hr',
            dueInDays: -2,
            estimatedHours: 0.5,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: 'All pre-boarding documents submitted',
            dueDay: -1,
          },
        ],
      },
      {
        phaseName: 'day_1',
        displayName: 'Day 1',
        startDay: 1,
        endDay: 1,
        description: 'First day orientation and setup',
        tasks: [
          {
            taskName: 'Workspace setup',
            description: 'Set up desk, chair, and workstation',
            assignedTo: 'it',
            dueInDays: 1,
            estimatedHours: 1,
            isMandatory: true,
          },
          {
            taskName: 'Welcome orientation',
            description: 'Company overview and culture presentation',
            assignedTo: 'hr',
            dueInDays: 1,
            estimatedHours: 2,
            isMandatory: true,
          },
          {
            taskName: 'Team introduction',
            description: 'Meet the team members and manager',
            assignedTo: 'manager',
            dueInDays: 1,
            estimatedHours: 1,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: 'First day checklist completed',
            dueDay: 1,
          },
        ],
      },
      {
        phaseName: 'week_1',
        displayName: 'Week 1',
        startDay: 2,
        endDay: 7,
        description: 'First week training and setup',
        tasks: [
          {
            taskName: 'Complete IT security training',
            description: 'Mandatory security awareness training',
            assignedTo: 'employee',
            dueInDays: 5,
            estimatedHours: 3,
            isMandatory: true,
          },
          {
            taskName: 'Set up development environment',
            description: 'Install required tools and access repositories',
            assignedTo: 'buddy',
            dueInDays: 7,
            estimatedHours: 4,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: 'Development environment ready',
            dueDay: 7,
          },
        ],
      },
      {
        phaseName: 'month_1',
        displayName: 'Month 1',
        startDay: 8,
        endDay: 30,
        description: 'First month learning and initial contributions',
        tasks: [
          {
            taskName: 'Complete product training',
            description: 'Learn about company products and architecture',
            assignedTo: 'employee',
            dueInDays: 20,
            estimatedHours: 16,
            isMandatory: true,
          },
          {
            taskName: 'First code contribution',
            description: 'Submit first pull request',
            assignedTo: 'employee',
            dueInDays: 25,
            estimatedHours: 8,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: 'First PR merged',
            dueDay: 30,
          },
        ],
      },
      {
        phaseName: 'month_2_3',
        displayName: 'Months 2-3',
        startDay: 31,
        endDay: 90,
        description: 'Continued learning and increasing responsibility',
        tasks: [
          {
            taskName: 'Lead a small project',
            description: 'Take ownership of a feature or bug fix',
            assignedTo: 'employee',
            dueInDays: 60,
            estimatedHours: 40,
            isMandatory: false,
          },
          {
            taskName: 'Complete 90-day review',
            description: 'Review progress with manager',
            assignedTo: 'manager',
            dueInDays: 90,
            estimatedHours: 1,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: '90-day review completed',
            dueDay: 90,
          },
        ],
      },
    ],
    checklistTemplate: {
      id: 'checklist_eng_001',
      templateName: 'Engineering Onboarding Checklist',
      sections: [
        {
          sectionName: 'IT Setup',
          items: [
            {
              itemName: 'Laptop and peripherals received',
              isRequired: true,
              assignedRole: 'it',
            },
            {
              itemName: 'Email and accounts configured',
              isRequired: true,
              assignedRole: 'it',
            },
            {
              itemName: 'VPN access granted',
              isRequired: true,
              assignedRole: 'it',
            },
          ],
        },
        {
          sectionName: 'Access & Permissions',
          items: [
            {
              itemName: 'GitHub access',
              isRequired: true,
              assignedRole: 'it',
            },
            {
              itemName: 'AWS console access',
              isRequired: true,
              assignedRole: 'it',
            },
            {
              itemName: 'Jira/project management tools',
              isRequired: true,
              assignedRole: 'manager',
            },
          ],
        },
      ],
    },
    documentsRequired: [
      {
        documentType: 'identity_proof',
        documentName: 'Government-issued ID',
        isMandatory: true,
        dueInDays: -2,
        description: 'Passport or driver license',
      },
      {
        documentType: 'tax_form',
        documentName: 'W-4 Form',
        isMandatory: true,
        dueInDays: 1,
        description: 'Federal tax withholding form',
      },
      {
        documentType: 'bank_details',
        documentName: 'Direct Deposit Form',
        isMandatory: true,
        dueInDays: 5,
        description: 'Bank account information for payroll',
      },
      {
        documentType: 'confidentiality_agreement',
        documentName: 'NDA',
        isMandatory: true,
        dueInDays: 1,
        description: 'Non-disclosure agreement',
      },
    ],
    equipmentRequired: [
      {
        equipmentType: 'laptop',
        equipmentName: 'MacBook Pro 16"',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: -1,
        specifications: {
          processor: 'M3 Pro',
          ram: '32GB',
          storage: '1TB SSD',
        },
      },
      {
        equipmentType: 'monitor',
        equipmentName: 'External Monitor 27"',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: 1,
        specifications: {
          resolution: '4K',
          brand: 'Dell',
        },
      },
      {
        equipmentType: 'keyboard',
        equipmentName: 'Mechanical Keyboard',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: 1,
      },
      {
        equipmentType: 'mouse',
        equipmentName: 'Wireless Mouse',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: 1,
      },
      {
        equipmentType: 'headphones',
        equipmentName: 'Noise-canceling Headphones',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: 1,
      },
    ],
    buddyRequired: true,
    buddyDuration: 90,
    surveySchedule: [
      {
        surveyName: 'Day 1 Feedback',
        triggerDay: 1,
        surveyType: 'experience',
        isRequired: true,
      },
      {
        surveyName: '30-day Check-in',
        triggerDay: 30,
        surveyType: 'progress',
        isRequired: true,
      },
      {
        surveyName: '90-day Review',
        triggerDay: 90,
        surveyType: 'completion',
        isRequired: true,
      },
    ],
    createdBy: 'Sarah Chen',
    createdDate: '2024-01-15T10:00:00Z',
    lastModified: '2024-03-20T14:30:00Z',
    successCount: 45,
  },
  {
    id: 'prog_002',
    programCode: 'OB-SALES-001',
    programName: 'Sales Representative Onboarding',
    description: 'Onboarding program for sales team members',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    jobLevelId: 'level_entry',
    jobLevelName: 'Entry Level',
    isActive: true,
    duration: 60,
    phases: [
      {
        phaseName: 'pre_boarding',
        displayName: 'Pre-boarding',
        startDay: -5,
        endDay: 0,
        description: 'Pre-boarding preparation',
        tasks: [
          {
            taskName: 'Review sales methodology',
            description: 'Study company sales approach',
            assignedTo: 'employee',
            dueInDays: -2,
            estimatedHours: 3,
            isMandatory: true,
          },
        ],
        milestones: [],
      },
      {
        phaseName: 'week_1',
        displayName: 'Week 1',
        startDay: 1,
        endDay: 7,
        description: 'Sales training bootcamp',
        tasks: [
          {
            taskName: 'Product knowledge training',
            description: 'Deep dive into product features and benefits',
            assignedTo: 'employee',
            dueInDays: 5,
            estimatedHours: 16,
            isMandatory: true,
          },
          {
            taskName: 'CRM training',
            description: 'Learn Salesforce and sales tools',
            assignedTo: 'employee',
            dueInDays: 7,
            estimatedHours: 4,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: 'Sales bootcamp completed',
            dueDay: 7,
          },
        ],
      },
      {
        phaseName: 'month_1',
        displayName: 'Month 1',
        startDay: 8,
        endDay: 30,
        description: 'Shadowing and first calls',
        tasks: [
          {
            taskName: 'Shadow senior rep',
            description: 'Observe 10 sales calls',
            assignedTo: 'employee',
            dueInDays: 20,
            estimatedHours: 20,
            isMandatory: true,
          },
          {
            taskName: 'First discovery call',
            description: 'Conduct first customer call',
            assignedTo: 'employee',
            dueInDays: 30,
            estimatedHours: 1,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: 'First call completed',
            dueDay: 30,
          },
        ],
      },
      {
        phaseName: 'month_2',
        displayName: 'Month 2',
        startDay: 31,
        endDay: 60,
        description: 'Independent selling',
        tasks: [
          {
            taskName: 'Build pipeline',
            description: 'Create pipeline of 20 opportunities',
            assignedTo: 'employee',
            dueInDays: 60,
            estimatedHours: 40,
            isMandatory: true,
          },
        ],
        milestones: [
          {
            milestoneName: '60-day review completed',
            dueDay: 60,
          },
        ],
      },
    ],
    checklistTemplate: {
      id: 'checklist_sales_001',
      templateName: 'Sales Onboarding Checklist',
      sections: [
        {
          sectionName: 'Tools & Access',
          items: [
            {
              itemName: 'Salesforce access',
              isRequired: true,
              assignedRole: 'it',
            },
            {
              itemName: 'Phone system setup',
              isRequired: true,
              assignedRole: 'it',
            },
          ],
        },
      ],
    },
    documentsRequired: [
      {
        documentType: 'tax_form',
        documentName: 'W-4 Form',
        isMandatory: true,
        dueInDays: 1,
      },
      {
        documentType: 'commission_agreement',
        documentName: 'Sales Commission Plan',
        isMandatory: true,
        dueInDays: 1,
        description: 'Commission structure and terms',
      },
    ],
    equipmentRequired: [
      {
        equipmentType: 'laptop',
        equipmentName: 'Business Laptop',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: -1,
      },
      {
        equipmentType: 'mobile_phone',
        equipmentName: 'iPhone',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: 1,
      },
    ],
    buddyRequired: true,
    buddyDuration: 60,
    surveySchedule: [
      {
        surveyName: 'Week 1 Feedback',
        triggerDay: 7,
        surveyType: 'experience',
        isRequired: true,
      },
      {
        surveyName: '60-day Review',
        triggerDay: 60,
        surveyType: 'completion',
        isRequired: true,
      },
    ],
    createdBy: 'Michael Rodriguez',
    createdDate: '2024-02-01T09:00:00Z',
    lastModified: '2024-03-15T16:00:00Z',
    successCount: 28,
  },
  {
    id: 'prog_003',
    programCode: 'OB-HR-001',
    programName: 'HR Specialist Onboarding',
    description: 'Onboarding program for HR department',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources',
    jobLevelId: 'level_mid',
    jobLevelName: 'Mid-Level',
    isActive: true,
    duration: 90,
    phases: [
      {
        phaseName: 'pre_boarding',
        displayName: 'Pre-boarding',
        startDay: -7,
        endDay: 0,
        description: 'Pre-boarding activities',
        tasks: [
          {
            taskName: 'Review HR policies',
            description: 'Study employee handbook and policies',
            assignedTo: 'employee',
            dueInDays: -3,
            estimatedHours: 4,
            isMandatory: true,
          },
        ],
        milestones: [],
      },
      {
        phaseName: 'week_1',
        displayName: 'Week 1',
        startDay: 1,
        endDay: 7,
        description: 'HR systems training',
        tasks: [
          {
            taskName: 'HRIS training',
            description: 'Learn HR information system',
            assignedTo: 'employee',
            dueInDays: 7,
            estimatedHours: 8,
            isMandatory: true,
          },
        ],
        milestones: [],
      },
      {
        phaseName: 'month_1',
        displayName: 'Month 1',
        startDay: 8,
        endDay: 30,
        description: 'HR function overview',
        tasks: [
          {
            taskName: 'Understand all HR functions',
            description: 'Overview of recruitment, benefits, payroll, compliance',
            assignedTo: 'employee',
            dueInDays: 30,
            estimatedHours: 20,
            isMandatory: true,
          },
        ],
        milestones: [],
      },
      {
        phaseName: 'month_2_3',
        displayName: 'Months 2-3',
        startDay: 31,
        endDay: 90,
        description: 'Specialized training',
        tasks: [
          {
            taskName: 'Handle first cases independently',
            description: 'Manage employee cases with supervision',
            assignedTo: 'employee',
            dueInDays: 90,
            estimatedHours: 60,
            isMandatory: true,
          },
        ],
        milestones: [],
      },
    ],
    checklistTemplate: {
      id: 'checklist_hr_001',
      templateName: 'HR Onboarding Checklist',
      sections: [
        {
          sectionName: 'System Access',
          items: [
            {
              itemName: 'HRIS access',
              isRequired: true,
              assignedRole: 'it',
            },
            {
              itemName: 'Payroll system access',
              isRequired: true,
              assignedRole: 'it',
            },
          ],
        },
      ],
    },
    documentsRequired: [
      {
        documentType: 'confidentiality_agreement',
        documentName: 'Confidentiality Agreement',
        isMandatory: true,
        dueInDays: 1,
        description: 'HR data confidentiality',
      },
    ],
    equipmentRequired: [
      {
        equipmentType: 'laptop',
        equipmentName: 'Business Laptop',
        isProvided: true,
        provisionedBy: 'it',
        dueInDays: -1,
      },
    ],
    buddyRequired: true,
    buddyDuration: 90,
    surveySchedule: [
      {
        surveyName: '30-day Check-in',
        triggerDay: 30,
        surveyType: 'progress',
        isRequired: true,
      },
      {
        surveyName: '90-day Review',
        triggerDay: 90,
        surveyType: 'completion',
        isRequired: true,
      },
    ],
    createdBy: 'Emily Watson',
    createdDate: '2024-01-20T11:00:00Z',
    lastModified: '2024-03-10T10:00:00Z',
    successCount: 12,
  },
];

// ============================================================================
// ONBOARDING INSTANCES
// ============================================================================

export const sampleOnboardingInstances: OnboardingInstance[] = [
  {
    id: 'inst_001',
    onboardingCode: 'OB-2024-001',
    programId: 'prog_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    departmentId: 'dept_engineering',
    departmentName: 'Engineering',
    positionId: 'pos_eng_001',
    positionTitle: 'Senior Software Engineer',
    managerId: 'emp_mgr_001',
    managerName: 'Sarah Chen',
    buddyId: 'emp_buddy_001',
    buddyName: 'David Park',
    hireDate: '2024-03-01',
    startDate: '2024-03-01',
    expectedEndDate: '2024-05-30',
    status: 'in_progress',
    currentPhase: 'month_1',
    progress: 65,
    completedTasks: 13,
    totalTasks: 20,
    overdueTasks: 1,
    tasks: [
      {
        id: 'task_001',
        taskName: 'Complete background verification',
        description: 'Submit required documents for background check',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'Alex Johnson',
        dueDate: '2024-02-25',
        phase: 'pre_boarding',
        status: 'completed',
        priority: 'high',
        estimatedHours: 1,
        actualHours: 0.5,
        isMandatory: true,
        completedDate: '2024-02-24T15:00:00Z',
        completedBy: 'Alex Johnson',
      },
      {
        id: 'task_002',
        taskName: 'Review welcome package',
        description: 'Read through welcome materials and company handbook',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'Alex Johnson',
        dueDate: '2024-02-27',
        phase: 'pre_boarding',
        status: 'completed',
        priority: 'medium',
        estimatedHours: 2,
        actualHours: 2,
        isMandatory: true,
        completedDate: '2024-02-27T10:00:00Z',
        completedBy: 'Alex Johnson',
      },
      {
        id: 'task_003',
        taskName: 'Complete product training',
        description: 'Learn about company products and architecture',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'Alex Johnson',
        dueDate: '2024-03-21',
        phase: 'month_1',
        status: 'in_progress',
        priority: 'high',
        estimatedHours: 16,
        actualHours: 10,
        isMandatory: true,
        notes: 'Making good progress, 60% complete',
      },
      {
        id: 'task_004',
        taskName: 'First code contribution',
        description: 'Submit first pull request',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'Alex Johnson',
        dueDate: '2024-03-26',
        phase: 'month_1',
        status: 'pending',
        priority: 'high',
        estimatedHours: 8,
        isMandatory: true,
      },
      {
        id: 'task_005',
        taskName: 'Set up development environment',
        description: 'Install required tools and access repositories',
        assignedTo: 'buddy',
        assignedRole: 'buddy',
        assignedPerson: 'David Park',
        dueDate: '2024-03-08',
        phase: 'week_1',
        status: 'completed',
        priority: 'critical',
        estimatedHours: 4,
        actualHours: 5,
        isMandatory: true,
        completedDate: '2024-03-07T16:00:00Z',
        completedBy: 'David Park',
      },
    ],
    documents: [
      {
        id: 'doc_001',
        documentType: 'identity_proof',
        documentName: 'Passport',
        uploadedBy: 'Alex Johnson',
        uploadedDate: '2024-02-20T14:00:00Z',
        status: 'approved',
        approvedBy: 'HR Admin',
        approvedDate: '2024-02-21T09:00:00Z',
        fileUrl: '/documents/passport_alex.pdf',
        fileSize: 2048000,
        isMandatory: true,
        expiryDate: '2030-05-15',
      },
      {
        id: 'doc_002',
        documentType: 'tax_form',
        documentName: 'W-4 Form',
        uploadedBy: 'Alex Johnson',
        uploadedDate: '2024-03-01T10:00:00Z',
        status: 'approved',
        approvedBy: 'HR Admin',
        approvedDate: '2024-03-01T14:00:00Z',
        fileUrl: '/documents/w4_alex.pdf',
        fileSize: 512000,
        isMandatory: true,
      },
      {
        id: 'doc_003',
        documentType: 'bank_details',
        documentName: 'Direct Deposit Form',
        uploadedBy: 'Alex Johnson',
        uploadedDate: '2024-03-05T11:00:00Z',
        status: 'pending',
        fileUrl: '/documents/bank_alex.pdf',
        fileSize: 256000,
        isMandatory: true,
      },
    ],
    equipment: [
      {
        id: 'equip_001',
        equipmentType: 'laptop',
        equipmentName: 'MacBook Pro 16"',
        serialNumber: 'MBP-2024-001',
        assetTag: 'ASSET-001',
        assignedDate: '2024-02-28',
        provisionedBy: 'IT Admin',
        status: 'assigned',
        condition: 'new',
        returnRequired: true,
        specifications: {
          processor: 'M3 Pro',
          ram: '32GB',
          storage: '1TB SSD',
        },
      },
      {
        id: 'equip_002',
        equipmentType: 'monitor',
        equipmentName: 'Dell 27" 4K Monitor',
        serialNumber: 'DELL-MON-001',
        assetTag: 'ASSET-002',
        assignedDate: '2024-03-01',
        provisionedBy: 'IT Admin',
        status: 'assigned',
        condition: 'new',
        returnRequired: true,
      },
      {
        id: 'equip_003',
        equipmentType: 'keyboard',
        equipmentName: 'Mechanical Keyboard',
        serialNumber: 'KB-001',
        assetTag: 'ASSET-003',
        assignedDate: '2024-03-01',
        provisionedBy: 'IT Admin',
        status: 'assigned',
        condition: 'new',
        returnRequired: true,
      },
    ],
    access: [
      {
        id: 'access_001',
        accessType: 'email',
        systemName: 'Corporate Email',
        accountId: 'alex.johnson@company.com',
        requestedDate: '2024-02-28',
        grantedDate: '2024-02-28T14:00:00Z',
        grantedBy: 'IT Admin',
        status: 'active',
        isPermanent: true,
      },
      {
        id: 'access_002',
        accessType: 'vcs',
        systemName: 'GitHub',
        accountId: 'alexj-dev',
        requestedDate: '2024-03-01',
        grantedDate: '2024-03-01T10:00:00Z',
        grantedBy: 'IT Admin',
        status: 'active',
        isPermanent: true,
        permissions: ['read', 'write', 'admin'],
      },
      {
        id: 'access_003',
        accessType: 'cloud_platform',
        systemName: 'AWS Console',
        accountId: 'alex.johnson',
        requestedDate: '2024-03-05',
        grantedDate: '2024-03-06T09:00:00Z',
        grantedBy: 'DevOps Lead',
        status: 'active',
        isPermanent: false,
        expiryDate: '2025-03-06',
        permissions: ['developer'],
      },
    ],
    training: [
      {
        id: 'training_001',
        trainingName: 'Security Awareness Training',
        trainingType: 'compliance',
        provider: 'Internal',
        scheduledDate: '2024-03-04',
        duration: 3,
        status: 'completed',
        completedDate: '2024-03-04T16:00:00Z',
        score: 95,
        certificateUrl: '/certificates/security_alex.pdf',
        isMandatory: true,
      },
      {
        id: 'training_002',
        trainingName: 'Product Architecture Overview',
        trainingType: 'product',
        provider: 'Internal',
        scheduledDate: '2024-03-11',
        duration: 4,
        status: 'completed',
        completedDate: '2024-03-11T17:00:00Z',
        score: 88,
        isMandatory: true,
      },
      {
        id: 'training_003',
        trainingName: 'Advanced TypeScript',
        trainingType: 'technical',
        provider: 'Frontend Masters',
        scheduledDate: '2024-03-18',
        duration: 8,
        status: 'in_progress',
        isMandatory: false,
      },
    ],
    surveys: [
      {
        id: 'survey_001',
        surveyName: 'Day 1 Feedback',
        surveyType: 'experience',
        scheduledDate: '2024-03-01',
        completedDate: '2024-03-01T18:00:00Z',
        status: 'completed',
        score: 9,
        maxScore: 10,
        feedback: 'Great first day! Team was very welcoming.',
      },
    ],
    createdBy: 'HR Admin',
    createdDate: '2024-02-15T10:00:00Z',
    lastModified: '2024-03-15T14:30:00Z',
  },
  {
    id: 'inst_002',
    onboardingCode: 'OB-2024-002',
    programId: 'prog_002',
    employeeId: 'emp_new_002',
    employeeName: 'Maria Garcia',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    positionId: 'pos_sales_001',
    positionTitle: 'Sales Representative',
    managerId: 'emp_mgr_002',
    managerName: 'Michael Rodriguez',
    buddyId: 'emp_buddy_002',
    buddyName: 'Jennifer Lee',
    hireDate: '2024-03-11',
    startDate: '2024-03-11',
    expectedEndDate: '2024-05-10',
    status: 'in_progress',
    currentPhase: 'week_1',
    progress: 35,
    completedTasks: 7,
    totalTasks: 20,
    overdueTasks: 0,
    tasks: [
      {
        id: 'task_201',
        taskName: 'Review sales methodology',
        description: 'Study company sales approach',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'Maria Garcia',
        dueDate: '2024-03-09',
        phase: 'pre_boarding',
        status: 'completed',
        priority: 'high',
        estimatedHours: 3,
        actualHours: 3,
        isMandatory: true,
        completedDate: '2024-03-08T16:00:00Z',
        completedBy: 'Maria Garcia',
      },
      {
        id: 'task_202',
        taskName: 'Product knowledge training',
        description: 'Deep dive into product features and benefits',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'Maria Garcia',
        dueDate: '2024-03-16',
        phase: 'week_1',
        status: 'in_progress',
        priority: 'high',
        estimatedHours: 16,
        actualHours: 8,
        isMandatory: true,
      },
    ],
    documents: [
      {
        id: 'doc_201',
        documentType: 'tax_form',
        documentName: 'W-4 Form',
        uploadedBy: 'Maria Garcia',
        uploadedDate: '2024-03-11T10:00:00Z',
        status: 'approved',
        approvedBy: 'HR Admin',
        approvedDate: '2024-03-11T14:00:00Z',
        fileUrl: '/documents/w4_maria.pdf',
        fileSize: 512000,
        isMandatory: true,
      },
    ],
    equipment: [
      {
        id: 'equip_201',
        equipmentType: 'laptop',
        equipmentName: 'Business Laptop',
        serialNumber: 'LAP-2024-002',
        assetTag: 'ASSET-101',
        assignedDate: '2024-03-10',
        provisionedBy: 'IT Admin',
        status: 'assigned',
        condition: 'new',
        returnRequired: true,
      },
      {
        id: 'equip_202',
        equipmentType: 'mobile_phone',
        equipmentName: 'iPhone 15',
        serialNumber: 'IP-2024-002',
        assetTag: 'ASSET-102',
        assignedDate: '2024-03-11',
        provisionedBy: 'IT Admin',
        status: 'assigned',
        condition: 'new',
        returnRequired: true,
      },
    ],
    access: [
      {
        id: 'access_201',
        accessType: 'email',
        systemName: 'Corporate Email',
        accountId: 'maria.garcia@company.com',
        requestedDate: '2024-03-10',
        grantedDate: '2024-03-10T14:00:00Z',
        grantedBy: 'IT Admin',
        status: 'active',
        isPermanent: true,
      },
      {
        id: 'access_202',
        accessType: 'crm',
        systemName: 'Salesforce',
        accountId: 'mgarcia',
        requestedDate: '2024-03-11',
        grantedDate: '2024-03-11T10:00:00Z',
        grantedBy: 'Sales Ops',
        status: 'active',
        isPermanent: true,
        permissions: ['sales_rep'],
      },
    ],
    training: [
      {
        id: 'training_201',
        trainingName: 'Sales Bootcamp',
        trainingType: 'sales',
        provider: 'Internal',
        scheduledDate: '2024-03-12',
        duration: 16,
        status: 'in_progress',
        isMandatory: true,
      },
    ],
    surveys: [],
    createdBy: 'HR Admin',
    createdDate: '2024-03-01T10:00:00Z',
    lastModified: '2024-03-14T11:00:00Z',
  },
  {
    id: 'inst_003',
    onboardingCode: 'OB-2024-003',
    programId: 'prog_001',
    employeeId: 'emp_new_003',
    employeeName: 'Raj Patel',
    departmentId: 'dept_engineering',
    departmentName: 'Engineering',
    positionId: 'pos_eng_002',
    positionTitle: 'Frontend Developer',
    managerId: 'emp_mgr_001',
    managerName: 'Sarah Chen',
    buddyId: 'emp_buddy_003',
    buddyName: 'Lisa Wong',
    hireDate: '2024-04-01',
    startDate: '2024-04-01',
    expectedEndDate: '2024-06-30',
    status: 'not_started',
    currentPhase: 'pre_boarding',
    progress: 0,
    completedTasks: 0,
    totalTasks: 20,
    overdueTasks: 0,
    tasks: [],
    documents: [],
    equipment: [],
    access: [],
    training: [],
    surveys: [],
    createdBy: 'HR Admin',
    createdDate: '2024-03-15T09:00:00Z',
    lastModified: '2024-03-15T09:00:00Z',
  },
];

// ============================================================================
// BUDDY ASSIGNMENTS
// ============================================================================

export const sampleBuddyAssignments: BuddyAssignment[] = [
  {
    id: 'buddy_001',
    onboardingId: 'inst_001',
    newEmployeeId: 'emp_new_001',
    newEmployeeName: 'Alex Johnson',
    buddyId: 'emp_buddy_001',
    buddyName: 'David Park',
    buddyEmail: 'david.park@company.com',
    buddyDepartment: 'Engineering',
    assignedDate: '2024-02-20',
    startDate: '2024-03-01',
    endDate: '2024-05-30',
    status: 'active',
    meetingFrequency: 'weekly',
    nextMeetingDate: '2024-03-18',
    checkIns: [
      {
        date: '2024-03-04',
        notes: 'Helped with dev environment setup. Alex is picking things up quickly.',
        duration: 2,
        topics: ['Development environment', 'Git workflow', 'Code review process'],
      },
      {
        date: '2024-03-11',
        notes: 'Reviewed architecture and discussed first project assignment.',
        duration: 1.5,
        topics: ['System architecture', 'Project planning', 'Testing strategy'],
      },
    ],
    feedback: {
      buddyRating: 5,
      buddyComments: 'Alex is a quick learner and asks great questions.',
      newEmployeeRating: 5,
      newEmployeeComments: 'David has been incredibly helpful and patient.',
    },
  },
  {
    id: 'buddy_002',
    onboardingId: 'inst_002',
    newEmployeeId: 'emp_new_002',
    newEmployeeName: 'Maria Garcia',
    buddyId: 'emp_buddy_002',
    buddyName: 'Jennifer Lee',
    buddyEmail: 'jennifer.lee@company.com',
    buddyDepartment: 'Sales',
    assignedDate: '2024-03-05',
    startDate: '2024-03-11',
    endDate: '2024-05-10',
    status: 'active',
    meetingFrequency: 'weekly',
    nextMeetingDate: '2024-03-18',
    checkIns: [
      {
        date: '2024-03-11',
        notes: 'Introduction meeting. Discussed sales process and tools.',
        duration: 1,
        topics: ['CRM introduction', 'Sales methodology', 'Team structure'],
      },
    ],
  },
  {
    id: 'buddy_003',
    onboardingId: 'inst_003',
    newEmployeeId: 'emp_new_003',
    newEmployeeName: 'Raj Patel',
    buddyId: 'emp_buddy_003',
    buddyName: 'Lisa Wong',
    buddyEmail: 'lisa.wong@company.com',
    buddyDepartment: 'Engineering',
    assignedDate: '2024-03-15',
    startDate: '2024-04-01',
    endDate: '2024-06-30',
    status: 'assigned',
    meetingFrequency: 'weekly',
    checkIns: [],
  },
];

// ============================================================================
// 30-60-90 DAY PLANS
// ============================================================================

export const sampleDay30_60_90Plans: Day30_60_90Plan[] = [
  {
    id: 'plan_001',
    onboardingId: 'inst_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    positionTitle: 'Senior Software Engineer',
    managerId: 'emp_mgr_001',
    managerName: 'Sarah Chen',
    day30Goals: {
      milestones: [
        {
          description: 'Complete all onboarding training modules',
          dueDate: '2024-03-30',
          status: 'completed',
          completedDate: '2024-03-28T15:00:00Z',
        },
        {
          description: 'Submit first pull request',
          dueDate: '2024-03-30',
          status: 'completed',
          completedDate: '2024-03-26T14:00:00Z',
        },
        {
          description: 'Understand team processes and workflows',
          dueDate: '2024-03-30',
          status: 'completed',
          completedDate: '2024-03-25T10:00:00Z',
        },
      ],
      learningObjectives: [
        'Understand product architecture',
        'Learn development workflow and tools',
        'Build relationships with team members',
      ],
      successMetrics: [
        'Training completion: 100%',
        'First PR merged',
        'Met all team members',
      ],
      managerNotes: 'Alex is exceeding expectations. Very engaged and proactive.',
      employeeReflection: 'Great first month! Team has been super supportive.',
    },
    day60Goals: {
      milestones: [
        {
          description: 'Take ownership of a feature',
          dueDate: '2024-04-30',
          status: 'in_progress',
        },
        {
          description: 'Participate in architecture discussions',
          dueDate: '2024-04-30',
          status: 'in_progress',
        },
        {
          description: 'Contribute to code reviews',
          dueDate: '2024-04-30',
          status: 'pending',
        },
      ],
      learningObjectives: [
        'Deep dive into specific product areas',
        'Understand technical debt and improvement opportunities',
        'Learn best practices for our stack',
      ],
      successMetrics: [
        'Own and deliver a complete feature',
        'Active participation in team discussions',
        'Conduct 5+ code reviews',
      ],
    },
    day90Goals: {
      milestones: [
        {
          description: 'Lead a project independently',
          dueDate: '2024-05-30',
          status: 'pending',
        },
        {
          description: 'Mentor a junior developer',
          dueDate: '2024-05-30',
          status: 'pending',
        },
        {
          description: 'Propose technical improvements',
          dueDate: '2024-05-30',
          status: 'pending',
        },
      ],
      learningObjectives: [
        'Develop expertise in core systems',
        'Understand business impact of technical decisions',
        'Build cross-functional relationships',
      ],
      successMetrics: [
        'Successfully deliver independent project',
        'Positive feedback from mentee',
        'Improvement proposal accepted by team',
      ],
    },
    status: 'in_progress',
    currentPhase: 'day_60',
    createdBy: 'Sarah Chen',
    createdDate: '2024-03-01T09:00:00Z',
    lastModified: '2024-03-30T16:00:00Z',
  },
  {
    id: 'plan_002',
    onboardingId: 'inst_002',
    employeeId: 'emp_new_002',
    employeeName: 'Maria Garcia',
    positionTitle: 'Sales Representative',
    managerId: 'emp_mgr_002',
    managerName: 'Michael Rodriguez',
    day30Goals: {
      milestones: [
        {
          description: 'Complete sales training bootcamp',
          dueDate: '2024-04-10',
          status: 'in_progress',
        },
        {
          description: 'Shadow 10 sales calls',
          dueDate: '2024-04-10',
          status: 'in_progress',
        },
        {
          description: 'Learn CRM and sales tools',
          dueDate: '2024-04-10',
          status: 'completed',
          completedDate: '2024-03-15T14:00:00Z',
        },
      ],
      learningObjectives: [
        'Understand product value proposition',
        'Learn sales methodology',
        'Know target customer profiles',
      ],
      successMetrics: [
        'Pass product knowledge assessment',
        'Complete all training modules',
        'CRM proficiency demonstrated',
      ],
    },
    day60Goals: {
      milestones: [
        {
          description: 'Conduct 5 independent discovery calls',
          dueDate: '2024-05-10',
          status: 'pending',
        },
        {
          description: 'Build pipeline of 20 opportunities',
          dueDate: '2024-05-10',
          status: 'pending',
        },
      ],
      learningObjectives: [
        'Master discovery call framework',
        'Understand objection handling',
        'Learn proposal creation',
      ],
      successMetrics: [
        '20+ qualified opportunities in pipeline',
        '5+ successful discovery calls',
      ],
    },
    day90Goals: {
      milestones: [
        {
          description: 'Close first deal',
          dueDate: '2024-06-10',
          status: 'pending',
        },
      ],
      learningObjectives: [
        'Navigate full sales cycle',
        'Build strong customer relationships',
      ],
      successMetrics: [
        'First deal closed',
        'Pipeline value of $100K+',
      ],
    },
    status: 'in_progress',
    currentPhase: 'day_30',
    createdBy: 'Michael Rodriguez',
    createdDate: '2024-03-11T10:00:00Z',
    lastModified: '2024-03-15T14:00:00Z',
  },
];

// ============================================================================
// PRE-BOARDING PACKAGES
// ============================================================================

export const samplePreBoardingPackages: PreBoardingPackage[] = [
  {
    id: 'preboard_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    hireDate: '2024-03-01',
    status: 'completed',
    sentDate: '2024-02-20T10:00:00Z',
    completedDate: '2024-02-28T16:00:00Z',
    welcomeMessage: 'Welcome to the team, Alex! We\'re excited to have you join us as a Senior Software Engineer. This package contains everything you need to prepare for your first day.',
    materials: [
      {
        materialType: 'handbook',
        title: 'Employee Handbook',
        description: 'Company policies, benefits, and culture guide',
        url: '/preboarding/handbook.pdf',
        isRequired: true,
        status: 'viewed',
        viewedDate: '2024-02-22T14:00:00Z',
      },
      {
        materialType: 'video',
        title: 'CEO Welcome Video',
        description: 'Welcome message from our CEO',
        url: '/preboarding/ceo_welcome.mp4',
        isRequired: false,
        status: 'viewed',
        viewedDate: '2024-02-23T10:00:00Z',
      },
      {
        materialType: 'document',
        title: 'Engineering Team Guide',
        description: 'Overview of engineering practices and culture',
        url: '/preboarding/eng_guide.pdf',
        isRequired: true,
        status: 'viewed',
        viewedDate: '2024-02-24T15:00:00Z',
      },
      {
        materialType: 'link',
        title: 'Tech Stack Overview',
        description: 'Technologies we use',
        url: 'https://wiki.company.com/tech-stack',
        isRequired: false,
        status: 'viewed',
        viewedDate: '2024-02-25T09:00:00Z',
      },
    ],
    forms: [
      {
        formType: 'emergency_contact',
        formName: 'Emergency Contact Form',
        description: 'Provide emergency contact information',
        isRequired: true,
        dueDate: '2024-02-28',
        status: 'submitted',
        submittedDate: '2024-02-26T11:00:00Z',
      },
      {
        formType: 'i9',
        formName: 'I-9 Employment Eligibility',
        description: 'Verify employment eligibility',
        isRequired: true,
        dueDate: '2024-02-28',
        status: 'submitted',
        submittedDate: '2024-02-27T14:00:00Z',
      },
      {
        formType: 'tax',
        formName: 'W-4 Tax Withholding',
        description: 'Federal tax withholding form',
        isRequired: true,
        dueDate: '2024-03-01',
        status: 'submitted',
        submittedDate: '2024-02-28T10:00:00Z',
      },
      {
        formType: 'direct_deposit',
        formName: 'Direct Deposit Authorization',
        description: 'Bank account details for payroll',
        isRequired: true,
        dueDate: '2024-03-05',
        status: 'submitted',
        submittedDate: '2024-02-28T10:30:00Z',
      },
    ],
    firstDayInfo: {
      reportingTime: '09:00 AM',
      reportingLocation: '123 Tech Street, Building A, 5th Floor',
      parkingInfo: 'Visitor parking available in Lot B. Bring this email to reception for a parking pass.',
      dressCode: 'Business casual',
      whatToBring: [
        'Government-issued photo ID',
        'Completed I-9 documents',
        'Voided check for direct deposit (if not submitted online)',
      ],
      contactPerson: 'Sarah Chen',
      contactEmail: 'sarah.chen@company.com',
      contactPhone: '+1-555-0100',
      agendaItems: [
        {
          time: '09:00 AM',
          activity: 'Arrive and check in at reception',
          location: 'Main Lobby',
        },
        {
          time: '09:30 AM',
          activity: 'HR Orientation',
          location: 'Conference Room A',
        },
        {
          time: '11:00 AM',
          activity: 'IT Setup and Equipment',
          location: 'IT Department',
        },
        {
          time: '12:00 PM',
          activity: 'Lunch with your buddy (David Park)',
          location: 'Company Cafeteria',
        },
        {
          time: '01:00 PM',
          activity: 'Meet your manager and team',
          location: 'Engineering Area',
        },
        {
          time: '03:00 PM',
          activity: 'Workspace setup and initial training',
          location: 'Your Desk',
        },
      ],
    },
    createdBy: 'HR Admin',
    createdDate: '2024-02-15T10:00:00Z',
  },
  {
    id: 'preboard_002',
    employeeId: 'emp_new_002',
    employeeName: 'Maria Garcia',
    hireDate: '2024-03-11',
    status: 'sent',
    sentDate: '2024-03-01T09:00:00Z',
    welcomeMessage: 'Welcome to the Sales team, Maria! We can\'t wait for you to start on March 11th.',
    materials: [
      {
        materialType: 'handbook',
        title: 'Employee Handbook',
        description: 'Company policies, benefits, and culture guide',
        url: '/preboarding/handbook.pdf',
        isRequired: true,
        status: 'viewed',
        viewedDate: '2024-03-02T10:00:00Z',
      },
      {
        materialType: 'document',
        title: 'Sales Playbook',
        description: 'Our sales methodology and processes',
        url: '/preboarding/sales_playbook.pdf',
        isRequired: true,
        status: 'viewed',
        viewedDate: '2024-03-03T14:00:00Z',
      },
    ],
    forms: [
      {
        formType: 'emergency_contact',
        formName: 'Emergency Contact Form',
        description: 'Provide emergency contact information',
        isRequired: true,
        dueDate: '2024-03-08',
        status: 'submitted',
        submittedDate: '2024-03-05T11:00:00Z',
      },
      {
        formType: 'tax',
        formName: 'W-4 Tax Withholding',
        description: 'Federal tax withholding form',
        isRequired: true,
        dueDate: '2024-03-11',
        status: 'pending',
      },
    ],
    firstDayInfo: {
      reportingTime: '09:00 AM',
      reportingLocation: '123 Tech Street, Building B, 3rd Floor',
      parkingInfo: 'Visitor parking in Lot B',
      dressCode: 'Business professional for first week',
      whatToBring: [
        'Government-issued photo ID',
        'Completed forms',
      ],
      contactPerson: 'Michael Rodriguez',
      contactEmail: 'michael.rodriguez@company.com',
      contactPhone: '+1-555-0200',
      agendaItems: [
        {
          time: '09:00 AM',
          activity: 'Check in and HR orientation',
          location: 'Main Lobby',
        },
        {
          time: '11:00 AM',
          activity: 'Sales team meeting',
          location: 'Sales Floor',
        },
        {
          time: '12:00 PM',
          activity: 'Team lunch',
          location: 'Nearby Restaurant',
        },
      ],
    },
    createdBy: 'HR Admin',
    createdDate: '2024-03-01T09:00:00Z',
  },
  {
    id: 'preboard_003',
    employeeId: 'emp_new_003',
    employeeName: 'Raj Patel',
    hireDate: '2024-04-01',
    status: 'draft',
    welcomeMessage: 'Welcome aboard, Raj! We\'re preparing your onboarding package.',
    materials: [],
    forms: [],
    firstDayInfo: {
      reportingTime: '09:00 AM',
      reportingLocation: '123 Tech Street, Building A, 5th Floor',
      parkingInfo: 'TBD',
      dressCode: 'Business casual',
      whatToBring: [],
      contactPerson: 'Sarah Chen',
      contactEmail: 'sarah.chen@company.com',
      contactPhone: '+1-555-0100',
      agendaItems: [],
    },
    createdBy: 'HR Admin',
    createdDate: '2024-03-15T09:00:00Z',
  },
];

// ============================================================================
// SURVEYS
// ============================================================================

export const sampleOnboardingSurveys: OnboardingSurvey[] = [
  {
    id: 'survey_001',
    onboardingId: 'inst_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    surveyName: 'Day 1 Feedback',
    surveyType: 'experience',
    scheduledDate: '2024-03-01',
    completedDate: '2024-03-01T18:00:00Z',
    status: 'completed',
    questions: [
      {
        question: 'How would you rate your first day experience?',
        answer: '9/10',
        questionType: 'rating',
      },
      {
        question: 'Was your workspace ready?',
        answer: 'Yes',
        questionType: 'yes_no',
      },
      {
        question: 'Did you receive all necessary equipment?',
        answer: 'Yes',
        questionType: 'yes_no',
      },
      {
        question: 'What went well today?',
        answer: 'Everyone was very welcoming. My buddy David was great and helped me get set up quickly. The orientation was informative.',
        questionType: 'text',
      },
      {
        question: 'What could be improved?',
        answer: 'The lunch break was a bit short. Maybe extend it by 15 minutes for the first day?',
        questionType: 'text',
      },
    ],
    score: 9,
    maxScore: 10,
    feedback: 'Great first day! Team was very welcoming.',
  },
  {
    id: 'survey_002',
    onboardingId: 'inst_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    surveyName: '30-day Check-in',
    surveyType: 'progress',
    scheduledDate: '2024-03-30',
    status: 'pending',
    questions: [
      {
        question: 'How would you rate your onboarding experience so far?',
        questionType: 'rating',
      },
      {
        question: 'Do you feel you have the tools and resources needed to do your job?',
        questionType: 'yes_no',
      },
      {
        question: 'How well do you understand your role and responsibilities?',
        questionType: 'rating',
      },
      {
        question: 'What has been most helpful during your first 30 days?',
        questionType: 'text',
      },
      {
        question: 'What additional support would you like?',
        questionType: 'text',
      },
    ],
  },
];

// ============================================================================
// FEEDBACK
// ============================================================================

export const sampleFeedback: Feedback[] = [
  {
    id: 'feedback_001',
    onboardingId: 'inst_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    feedbackType: 'employee',
    providedBy: 'Alex Johnson',
    providedDate: '2024-03-15T14:00:00Z',
    category: 'process',
    rating: 9,
    comments: 'The onboarding process has been excellent. I particularly appreciate having a dedicated buddy who has been very helpful. The training materials are comprehensive and well-organized.',
    suggestions: 'It would be helpful to have a centralized dashboard showing all onboarding tasks and their deadlines. Also, maybe schedule a team social event in the first week.',
    isAnonymous: false,
  },
  {
    id: 'feedback_002',
    onboardingId: 'inst_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    feedbackType: 'manager',
    providedBy: 'Sarah Chen',
    providedDate: '2024-03-20T10:00:00Z',
    category: 'performance',
    rating: 10,
    comments: 'Alex is exceeding expectations. Very quick learner, asks great questions, and has already started contributing meaningfully to the team. The first PR was high quality.',
    actionItems: [
      'Continue current trajectory',
      'Consider giving more challenging tasks',
      'Include in architecture discussions',
    ],
    isAnonymous: false,
  },
  {
    id: 'feedback_003',
    onboardingId: 'inst_001',
    employeeId: 'emp_new_001',
    employeeName: 'Alex Johnson',
    feedbackType: 'buddy',
    providedBy: 'David Park',
    providedDate: '2024-03-18T15:00:00Z',
    category: 'experience',
    rating: 9,
    comments: 'Alex is a pleasure to work with. Very proactive and doesn\'t hesitate to ask questions. Our weekly check-ins have been productive.',
    isAnonymous: false,
  },
  {
    id: 'feedback_004',
    onboardingId: 'inst_002',
    employeeId: 'emp_new_002',
    employeeName: 'Maria Garcia',
    feedbackType: 'employee',
    providedBy: 'Maria Garcia',
    providedDate: '2024-03-14T16:00:00Z',
    category: 'training',
    rating: 8,
    comments: 'The sales training has been comprehensive. The product knowledge sessions are especially valuable.',
    suggestions: 'Would love more hands-on practice with objection handling scenarios.',
    isAnonymous: false,
  },
];

// ============================================================================
// ANALYTICS & METRICS
// ============================================================================

export const sampleOnboardingMetrics: OnboardingMetrics = {
  totalOnboarding: 15,
  activeOnboarding: 8,
  completedOnboarding: 5,
  notStartedOnboarding: 2,
  averageCompletionRate: 78,
  averageTimeToProductivity: 45,
  averageSatisfactionScore: 8.5,
  timeToProductivityByDept: [
    {
      departmentId: 'dept_engineering',
      departmentName: 'Engineering',
      averageDays: 52,
      count: 6,
    },
    {
      departmentId: 'dept_sales',
      departmentName: 'Sales',
      averageDays: 38,
      count: 4,
    },
    {
      departmentId: 'dept_hr',
      departmentName: 'Human Resources',
      averageDays: 42,
      count: 2,
    },
  ],
  completionRateByProgram: [
    {
      programId: 'prog_001',
      programName: 'Software Engineer Onboarding',
      completionRate: 82,
      count: 6,
    },
    {
      programId: 'prog_002',
      programName: 'Sales Representative Onboarding',
      completionRate: 75,
      count: 4,
    },
    {
      programId: 'prog_003',
      programName: 'HR Specialist Onboarding',
      completionRate: 70,
      count: 2,
    },
  ],
  satisfactionByPhase: [
    {
      phase: 'pre_boarding',
      averageScore: 8.8,
      responseCount: 12,
    },
    {
      phase: 'day_1',
      averageScore: 9.2,
      responseCount: 12,
    },
    {
      phase: 'week_1',
      averageScore: 8.5,
      responseCount: 10,
    },
    {
      phase: 'month_1',
      averageScore: 8.3,
      responseCount: 8,
    },
    {
      phase: 'month_2_3',
      averageScore: 8.0,
      responseCount: 5,
    },
  ],
  taskCompletionTrends: [
    {
      month: '2024-01',
      onTimeCompletion: 85,
      lateCompletion: 12,
      notCompleted: 3,
    },
    {
      month: '2024-02',
      onTimeCompletion: 88,
      lateCompletion: 10,
      notCompleted: 2,
    },
    {
      month: '2024-03',
      onTimeCompletion: 90,
      lateCompletion: 8,
      notCompleted: 2,
    },
  ],
  retentionRate90Days: 95,
  retentionRate180Days: 92,
  retentionRate365Days: 88,
  commonIssues: [
    {
      issue: 'IT equipment delays',
      frequency: 8,
      averageImpact: 'medium',
    },
    {
      issue: 'Access provisioning delays',
      frequency: 12,
      averageImpact: 'high',
    },
    {
      issue: 'Training material outdated',
      frequency: 5,
      averageImpact: 'low',
    },
  ],
  topPerformingBuddies: [
    {
      buddyId: 'emp_buddy_001',
      buddyName: 'David Park',
      assignmentsCompleted: 5,
      averageRating: 9.2,
    },
    {
      buddyId: 'emp_buddy_002',
      buddyName: 'Jennifer Lee',
      assignmentsCompleted: 4,
      averageRating: 8.8,
    },
  ],
};

// ============================================================================
// SETTINGS
// ============================================================================

export const sampleOnboardingSettings: OnboardingSettings = {
  defaultDuration: 90,
  defaultBuddyDuration: 90,
  autoAssignBuddy: true,
  requireManagerApproval: true,
  sendReminderNotifications: true,
  reminderFrequency: 'daily',
  enablePreBoarding: true,
  preBoardingLeadTime: 7,
  enable30_60_90Plans: true,
  requireSurveyCompletion: true,
  defaultSurveySchedule: [
    {
      day: 1,
      surveyType: 'experience',
      surveyName: 'Day 1 Feedback',
    },
    {
      day: 7,
      surveyType: 'experience',
      surveyName: 'Week 1 Check-in',
    },
    {
      day: 30,
      surveyType: 'progress',
      surveyName: '30-day Review',
    },
    {
      day: 60,
      surveyType: 'progress',
      surveyName: '60-day Review',
    },
    {
      day: 90,
      surveyType: 'completion',
      surveyName: '90-day Review',
    },
  ],
  documentRetentionDays: 2555,
  equipmentReturnReminder: 7,
  itProvisioningLeadTime: 2,
  hrNotificationEmail: 'hr@company.com',
  itNotificationEmail: 'it@company.com',
  managerNotificationEmail: '',
  customFields: [
    {
      fieldName: 'shirt_size',
      fieldLabel: 'T-Shirt Size',
      fieldType: 'select',
      isRequired: false,
      options: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    },
    {
      fieldName: 'dietary_restrictions',
      fieldLabel: 'Dietary Restrictions',
      fieldType: 'text',
      isRequired: false,
    },
  ],
};
