// @ts-nocheck — Dev/demo seed data, intentionally loose-typed.
/**
 * Benefits Management Module - Sample Data
 *
 * Comprehensive sample data for testing and development including:
 * - Benefit Plans (Health, Dental, Vision)
 * - Enrollment Windows
 * - Benefit Enrollments
 * - Dependents
 * - Claims
 * - Healthcare Providers
 * - Qualifying Events
 * - Premium Deductions
 * - Settings
 */

import type {
    BenefitPlan,
    BenefitEnrollment,
    EnrollmentWindow,
    Dependent,
    BenefitClaim,
    HealthcareProvider,
    QualifyingEvent,
    PremiumDeduction,
    BenefitSettings,
} from './types';

// ============================================================================
// BENEFIT PLANS
// ============================================================================

export const generateSampleBenefitPlans = (): BenefitPlan[] => [
    // Health Insurance Plans
    {
        id: 'bp_health_basic',
        planCode: 'HLT-BAS-2025',
        name: 'Essential Care',
        description: 'Basic health coverage for major medical events and preventive care',
        category: 'health_insurance',
        tier: 'basic',
        carrierName: 'Blue Cross Blue Shield',
        carrierId: 'carrier_bcbs',
        policyNumber: 'POL-12345-2025',
        groupNumber: 'GRP-ABC-001',
        coverageLevels: ['employee_only', 'employee_spouse', 'employee_children', 'family'],
        annualCoverageLimit: 1000000,
        deductible: {
            individual: 5000,
            family: 10000,
            inNetwork: 5000,
            outOfNetwork: 7500,
        },
        outOfPocketMax: {
            individual: 8000,
            family: 16000,
        },
        coinsurance: {
            inNetwork: 20,
            outOfNetwork: 40,
        },
        copay: {
            primaryCare: 30,
            specialist: 60,
            urgentCare: 100,
            emergencyRoom: 250,
            genericDrug: 10,
            brandDrug: 40,
        },
        premiumRates: [
            {
                id: 'pr_health_basic_ee',
                benefitPlanId: 'bp_health_basic',
                coverageLevel: 'employee_only',
                employeeContribution: 0,
                employerContribution: 450,
                totalPremium: 450,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
            {
                id: 'pr_health_basic_family',
                benefitPlanId: 'bp_health_basic',
                coverageLevel: 'family',
                employeeContribution: 200,
                employerContribution: 1000,
                totalPremium: 1200,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
        ],
        eligibilityRules: [
            {
                id: 'er_health_basic_1',
                name: 'Full-Time Employees',
                description: 'Available to all full-time employees',
                employmentType: ['full_time'],
                minTenure: 0,
                minHoursPerWeek: 30,
                isActive: true,
                priority: 1,
            },
        ],
        waitingPeriod: 0,
        features: [
            '100% Preventive Care',
            '$5,000 Deductible',
            '20% Co-insurance',
            'Telemedicine Included',
            'Prescription Drug Coverage',
        ],
        exclusions: ['Cosmetic Procedures', 'Experimental Treatments'],
        networkProviders: ['Blue Cross Blue Shield Network'],
        documents: [
            {
                id: 'doc_health_basic_spd',
                name: 'Summary Plan Description',
                type: 'summary_plan_description',
                url: '/documents/health-basic-spd.pdf',
                uploadedDate: '2024-12-01T00:00:00Z',
                fileSize: 1024000,
            },
        ],
        planYear: '2025',
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        isRecommended: false,
        displayOrder: 1,
        createdAt: '2024-11-01T00:00:00Z',
        updatedAt: '2024-11-01T00:00:00Z',
        createdBy: 'admin@company.com',
    },
    {
        id: 'bp_health_gold',
        planCode: 'HLT-GLD-2025',
        name: 'Balanced Choice',
        description: 'Lower deductibles and copays for regular visits',
        category: 'health_insurance',
        tier: 'gold',
        carrierName: 'Blue Cross Blue Shield',
        carrierId: 'carrier_bcbs',
        policyNumber: 'POL-12346-2025',
        groupNumber: 'GRP-ABC-002',
        coverageLevels: ['employee_only', 'employee_spouse', 'employee_children', 'family'],
        annualCoverageLimit: 2000000,
        deductible: {
            individual: 1500,
            family: 3000,
            inNetwork: 1500,
            outOfNetwork: 3000,
        },
        outOfPocketMax: {
            individual: 5000,
            family: 10000,
        },
        coinsurance: {
            inNetwork: 10,
            outOfNetwork: 30,
        },
        copay: {
            primaryCare: 20,
            specialist: 40,
            urgentCare: 75,
            emergencyRoom: 150,
            genericDrug: 5,
            brandDrug: 25,
        },
        premiumRates: [
            {
                id: 'pr_health_gold_ee',
                benefitPlanId: 'bp_health_gold',
                coverageLevel: 'employee_only',
                employeeContribution: 120,
                employerContribution: 550,
                totalPremium: 670,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
            {
                id: 'pr_health_gold_family',
                benefitPlanId: 'bp_health_gold',
                coverageLevel: 'family',
                employeeContribution: 400,
                employerContribution: 1200,
                totalPremium: 1600,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
        ],
        eligibilityRules: [
            {
                id: 'er_health_gold_1',
                name: 'Full-Time Employees',
                description: 'Available to all full-time employees',
                employmentType: ['full_time'],
                minTenure: 0,
                minHoursPerWeek: 30,
                isActive: true,
                priority: 1,
            },
        ],
        waitingPeriod: 0,
        features: [
            '100% Preventive Care',
            '$1,500 Deductible',
            '$20 Copay (PCP)',
            'Specialist Referrals Not Required',
            'Enhanced Prescription Coverage',
            'Mental Health Services',
        ],
        exclusions: ['Cosmetic Procedures'],
        networkProviders: ['Blue Cross Blue Shield Preferred Network'],
        documents: [],
        planYear: '2025',
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        isRecommended: true,
        displayOrder: 2,
        createdAt: '2024-11-01T00:00:00Z',
        updatedAt: '2024-11-01T00:00:00Z',
        createdBy: 'admin@company.com',
    },
    {
        id: 'bp_health_platinum',
        planCode: 'HLT-PLT-2025',
        name: 'Premium Health',
        description: 'Maximum coverage with minimal out-of-pocket costs',
        category: 'health_insurance',
        tier: 'platinum',
        carrierName: 'Blue Cross Blue Shield',
        carrierId: 'carrier_bcbs',
        policyNumber: 'POL-12347-2025',
        groupNumber: 'GRP-ABC-003',
        coverageLevels: ['employee_only', 'employee_spouse', 'employee_children', 'family'],
        annualCoverageLimit: 5000000,
        deductible: {
            individual: 500,
            family: 1000,
            inNetwork: 500,
            outOfNetwork: 1500,
        },
        outOfPocketMax: {
            individual: 3000,
            family: 6000,
        },
        coinsurance: {
            inNetwork: 5,
            outOfNetwork: 20,
        },
        copay: {
            primaryCare: 10,
            specialist: 25,
            urgentCare: 50,
            emergencyRoom: 100,
            genericDrug: 0,
            brandDrug: 15,
        },
        premiumRates: [
            {
                id: 'pr_health_platinum_ee',
                benefitPlanId: 'bp_health_platinum',
                coverageLevel: 'employee_only',
                employeeContribution: 280,
                employerContribution: 650,
                totalPremium: 930,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
        ],
        eligibilityRules: [
            {
                id: 'er_health_platinum_1',
                name: 'Full-Time Employees',
                description: 'Available to all full-time employees',
                employmentType: ['full_time'],
                minTenure: 0,
                minHoursPerWeek: 30,
                isActive: true,
                priority: 1,
            },
        ],
        waitingPeriod: 0,
        features: [
            '100% Preventive Care',
            '$500 Deductible',
            '$10 Copay (PCP)',
            'Out-of-Network Coverage',
            'Free Generic Drugs',
            'Worldwide Coverage',
        ],
        exclusions: [],
        networkProviders: ['Blue Cross Blue Shield Premium Network'],
        documents: [],
        planYear: '2025',
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        isRecommended: false,
        displayOrder: 3,
        createdAt: '2024-11-01T00:00:00Z',
        updatedAt: '2024-11-01T00:00:00Z',
        createdBy: 'admin@company.com',
    },
    // Dental Plans
    {
        id: 'bp_dental_basic',
        planCode: 'DNT-BAS-2025',
        name: 'Preventive Dental',
        description: 'Covers cleanings and exams',
        category: 'dental',
        tier: 'basic',
        carrierName: 'Delta Dental',
        carrierId: 'carrier_delta',
        policyNumber: 'POL-54321-2025',
        groupNumber: 'GRP-DNT-001',
        coverageLevels: ['employee_only', 'family'],
        deductible: {
            individual: 50,
            family: 150,
            inNetwork: 50,
            outOfNetwork: 100,
        },
        outOfPocketMax: {
            individual: 1500,
            family: 3000,
        },
        coinsurance: {
            inNetwork: 0,
            outOfNetwork: 20,
        },
        copay: {},
        premiumRates: [
            {
                id: 'pr_dental_basic_ee',
                benefitPlanId: 'bp_dental_basic',
                coverageLevel: 'employee_only',
                employeeContribution: 10,
                employerContribution: 30,
                totalPremium: 40,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
        ],
        eligibilityRules: [
            {
                id: 'er_dental_basic_1',
                name: 'All Employees',
                description: 'Available to all employees',
                employmentType: ['full_time', 'part_time'],
                minTenure: 0,
                isActive: true,
                priority: 1,
            },
        ],
        waitingPeriod: 0,
        features: ['2 Cleanings/Year', 'X-Rays Covered', 'No Orthodontia'],
        exclusions: ['Cosmetic Dentistry', 'Orthodontia'],
        networkProviders: ['Delta Dental PPO Network'],
        documents: [],
        planYear: '2025',
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        isRecommended: false,
        displayOrder: 1,
        createdAt: '2024-11-01T00:00:00Z',
        updatedAt: '2024-11-01T00:00:00Z',
        createdBy: 'admin@company.com',
    },
    {
        id: 'bp_dental_gold',
        planCode: 'DNT-GLD-2025',
        name: 'Comprehensive Dental',
        description: 'Includes fillings, basic surgery, and major work',
        category: 'dental',
        tier: 'gold',
        carrierName: 'Delta Dental',
        carrierId: 'carrier_delta',
        policyNumber: 'POL-54322-2025',
        groupNumber: 'GRP-DNT-002',
        coverageLevels: ['employee_only', 'family'],
        deductible: {
            individual: 0,
            family: 0,
            inNetwork: 0,
            outOfNetwork: 50,
        },
        outOfPocketMax: {
            individual: 2000,
            family: 4000,
        },
        coinsurance: {
            inNetwork: 20,
            outOfNetwork: 40,
        },
        copay: {},
        premiumRates: [
            {
                id: 'pr_dental_gold_ee',
                benefitPlanId: 'bp_dental_gold',
                coverageLevel: 'employee_only',
                employeeContribution: 35,
                employerContribution: 40,
                totalPremium: 75,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
        ],
        eligibilityRules: [
            {
                id: 'er_dental_gold_1',
                name: 'All Employees',
                description: 'Available to all employees',
                employmentType: ['full_time', 'part_time'],
                minTenure: 0,
                isActive: true,
                priority: 1,
            },
        ],
        waitingPeriod: 0,
        features: ['2 Cleanings/Year', '80% Fillings & Root Canals', '50% Major Work ($1500 max)', 'Orthodontia Coverage (50%, $1000 lifetime max)'],
        exclusions: ['Cosmetic Dentistry'],
        networkProviders: ['Delta Dental Premier Network'],
        documents: [],
        planYear: '2025',
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        isRecommended: true,
        displayOrder: 2,
        createdAt: '2024-11-01T00:00:00Z',
        updatedAt: '2024-11-01T00:00:00Z',
        createdBy: 'admin@company.com',
    },
    // Vision Plans
    {
        id: 'bp_vision_basic',
        planCode: 'VSN-BAS-2025',
        name: 'Standard Vision',
        description: 'Annual eye exam and discounts',
        category: 'vision',
        tier: 'basic',
        carrierName: 'VSP Vision Care',
        carrierId: 'carrier_vsp',
        policyNumber: 'POL-98765-2025',
        groupNumber: 'GRP-VSN-001',
        coverageLevels: ['employee_only', 'family'],
        deductible: {
            individual: 0,
            family: 0,
            inNetwork: 0,
            outOfNetwork: 0,
        },
        outOfPocketMax: {
            individual: 500,
            family: 1000,
        },
        coinsurance: {
            inNetwork: 0,
            outOfNetwork: 0,
        },
        copay: {
            primaryCare: 10,
        },
        premiumRates: [
            {
                id: 'pr_vision_basic_ee',
                benefitPlanId: 'bp_vision_basic',
                coverageLevel: 'employee_only',
                employeeContribution: 5,
                employerContribution: 15,
                totalPremium: 20,
                paymentFrequency: 'monthly',
                effectiveDate: '2025-01-01',
                expiryDate: '2025-12-31',
            },
        ],
        eligibilityRules: [
            {
                id: 'er_vision_basic_1',
                name: 'All Employees',
                description: 'Available to all employees',
                employmentType: ['full_time', 'part_time'],
                minTenure: 0,
                isActive: true,
                priority: 1,
            },
        ],
        waitingPeriod: 0,
        features: ['$10 Exam Copay', '$130 Frame Allowance', 'Lens Discounts', 'Contact Lens Allowance'],
        exclusions: [],
        networkProviders: ['VSP Network'],
        documents: [],
        planYear: '2025',
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        isRecommended: false,
        displayOrder: 1,
        createdAt: '2024-11-01T00:00:00Z',
        updatedAt: '2024-11-01T00:00:00Z',
        createdBy: 'admin@company.com',
    },
];

// ============================================================================
// ENROLLMENT WINDOWS
// ============================================================================

export const generateSampleEnrollmentWindows = (): EnrollmentWindow[] => [
    {
        id: 'ew_annual_2025',
        name: '2025 Annual Open Enrollment',
        type: 'annual',
        planYear: '2025',
        startDate: '2024-11-01T00:00:00Z',
        endDate: '2024-11-30T23:59:59Z',
        effectiveDate: '2025-01-01T00:00:00Z',
        eligibleEmployees: ['emp001', 'emp002', 'emp003', 'emp004', 'emp005'],
        allowedBenefitCategories: ['health_insurance', 'dental', 'vision', 'life_insurance', 'disability'],
        requiresDependentVerification: true,
        reminderSchedule: ['2024-11-05T09:00:00Z', '2024-11-15T09:00:00Z', '2024-11-25T09:00:00Z'],
        isActive: true,
        completionRate: 65,
        enrolledCount: 3,
        eligibleCount: 5,
        notificationsSent: 15,
        createdAt: '2024-10-01T00:00:00Z',
        updatedAt: '2024-11-15T00:00:00Z',
        createdBy: 'hr@company.com',
    },
];

// ============================================================================
// BENEFIT ENROLLMENTS
// ============================================================================

export const generateSampleEnrollments = (): BenefitEnrollment[] => [
    {
        id: 'enr_001',
        enrollmentNumber: 'ENR-2025-001',
        employeeId: 'emp001',
        employeeName: 'John Doe',
        employeeEmail: 'john.doe@company.com',
        enrollmentWindowId: 'ew_annual_2025',
        enrollmentType: 'annual',
        benefitPlanId: 'bp_health_gold',
        benefitPlanName: 'Balanced Choice Health Plan',
        coverageLevel: 'family',
        dependents: [
            {
                dependentId: 'dep_001',
                name: 'Jane Doe',
                relationship: 'spouse',
                dateOfBirth: '1988-05-15',
                isVerified: true,
            },
            {
                dependentId: 'dep_002',
                name: 'Jimmy Doe',
                relationship: 'child',
                dateOfBirth: '2015-03-20',
                isVerified: true,
            },
        ],
        employeeContribution: 400,
        employerContribution: 1200,
        totalPremium: 1600,
        annualCost: 19200,
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        submittedDate: '2024-11-10T14:30:00Z',
        confirmedDate: '2024-11-11T09:00:00Z',
        approvedBy: 'hr@company.com',
        approvedDate: '2024-11-11T09:00:00Z',
        requiresEOI: false,
        isWaived: false,
        documents: [],
        createdAt: '2024-11-10T14:30:00Z',
        updatedAt: '2024-11-11T09:00:00Z',
    },
    {
        id: 'enr_002',
        enrollmentNumber: 'ENR-2025-002',
        employeeId: 'emp002',
        employeeName: 'Sarah Smith',
        employeeEmail: 'sarah.smith@company.com',
        enrollmentWindowId: 'ew_annual_2025',
        enrollmentType: 'annual',
        benefitPlanId: 'bp_health_basic',
        benefitPlanName: 'Essential Care Health Plan',
        coverageLevel: 'employee_only',
        dependents: [],
        employeeContribution: 0,
        employerContribution: 450,
        totalPremium: 450,
        annualCost: 5400,
        effectiveDate: '2025-01-01',
        expiryDate: '2025-12-31',
        status: 'active',
        submittedDate: '2024-11-08T10:15:00Z',
        confirmedDate: '2024-11-08T16:00:00Z',
        approvedBy: 'hr@company.com',
        approvedDate: '2024-11-08T16:00:00Z',
        requiresEOI: false,
        isWaived: false,
        documents: [],
        createdAt: '2024-11-08T10:15:00Z',
        updatedAt: '2024-11-08T16:00:00Z',
    },
];

// ============================================================================
// DEPENDENTS
// ============================================================================

export const generateSampleDependents = (): Dependent[] => [
    {
        id: 'dep_001',
        employeeId: 'emp001',
        firstName: 'Jane',
        lastName: 'Doe',
        dateOfBirth: '1988-05-15',
        gender: 'female',
        relationship: 'spouse',
        isStudent: false,
        isDisabled: false,
        status: 'verified',
        verificationDocuments: [
            {
                id: 'doc_dep_001_marriage',
                type: 'marriage_certificate',
                name: 'Marriage Certificate',
                url: '/documents/marriage-cert-001.pdf',
                uploadedDate: '2024-11-10T14:30:00Z',
                isVerified: true,
                verifiedDate: '2024-11-11T09:00:00Z',
            },
        ],
        verifiedDate: '2024-11-11T09:00:00Z',
        verifiedBy: 'hr@company.com',
        enrolledPlans: ['bp_health_gold'],
        createdAt: '2024-11-10T14:30:00Z',
        updatedAt: '2024-11-11T09:00:00Z',
    },
    {
        id: 'dep_002',
        employeeId: 'emp001',
        firstName: 'Jimmy',
        lastName: 'Doe',
        dateOfBirth: '2015-03-20',
        gender: 'male',
        relationship: 'child',
        isStudent: true,
        studentInfo: {
            schoolName: 'Elementary School',
            expectedGraduation: '2033-06-15',
            isFullTime: true,
        },
        isDisabled: false,
        status: 'verified',
        verificationDocuments: [
            {
                id: 'doc_dep_002_birth',
                type: 'birth_certificate',
                name: 'Birth Certificate',
                url: '/documents/birth-cert-002.pdf',
                uploadedDate: '2024-11-10T14:30:00Z',
                isVerified: true,
                verifiedDate: '2024-11-11T09:00:00Z',
            },
        ],
        verifiedDate: '2024-11-11T09:00:00Z',
        verifiedBy: 'hr@company.com',
        enrolledPlans: ['bp_health_gold'],
        createdAt: '2024-11-10T14:30:00Z',
        updatedAt: '2024-11-11T09:00:00Z',
    },
];

// ============================================================================
// CLAIMS
// ============================================================================

export const generateSampleClaims = (): BenefitClaim[] => [
    {
        id: 'clm_001',
        claimNumber: 'CLM-2025-001',
        employeeId: 'emp001',
        employeeName: 'John Doe',
        enrollmentId: 'enr_001',
        benefitPlanId: 'bp_health_gold',
        benefitPlanName: 'Balanced Choice Health Plan',
        serviceDate: '2025-01-15T00:00:00Z',
        submittedDate: '2025-01-20T10:00:00Z',
        providerName: 'City Medical Center',
        providerId: 'prov_001',
        providerType: 'in_network',
        patientName: 'John Doe',
        patientRelationship: 'self',
        claimedAmount: 1500,
        approvedAmount: 1500,
        deductibleApplied: 150,
        coinsuranceApplied: 135,
        copayApplied: 20,
        paidAmount: 1195,
        patientResponsibility: 305,
        diagnosisCodes: ['Z00.00'],
        procedureCodes: ['99213'],
        treatmentDescription: 'Annual physical examination',
        status: 'paid',
        processedDate: '2025-01-25T14:00:00Z',
        processedBy: 'claims@bcbs.com',
        paymentDate: '2025-01-30T00:00:00Z',
        receipts: [
            {
                id: 'rec_clm_001',
                type: 'invoice',
                name: 'Medical Invoice',
                url: '/documents/invoice-clm-001.pdf',
                uploadedDate: '2025-01-20T10:00:00Z',
            },
        ],
        createdAt: '2025-01-20T10:00:00Z',
        updatedAt: '2025-01-30T00:00:00Z',
    },
];

// ============================================================================
// PROVIDERS
// ============================================================================

export const generateSampleProviders = (): HealthcareProvider[] => [
    {
        id: 'prov_001',
        name: 'City Medical Center',
        type: 'hospital',
        providerType: 'in_network',
        networkIds: ['net_bcbs_001'],
        acceptedBenefitPlanIds: ['bp_health_basic', 'bp_health_gold', 'bp_health_platinum'],
        phone: '555-0100',
        email: 'info@citymedical.com',
        website: 'https://citymedical.com',
        address: {
            street: '123 Main St',
            city: 'San Francisco',
            state: 'CA',
            zipCode: '94102',
            country: 'USA',
        },
        rating: 4.5,
        reviewCount: 245,
        acceptingNewPatients: true,
        wheelchairAccessible: true,
        isActive: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'prov_002',
        name: 'Bright Smile Dental',
        type: 'dental',
        specialty: 'General Dentistry',
        providerType: 'in_network',
        networkIds: ['net_delta_001'],
        acceptedBenefitPlanIds: ['bp_dental_basic', 'bp_dental_gold'],
        phone: '555-0200',
        website: 'https://brightsmile.com',
        address: {
            street: '456 Oak Ave',
            city: 'San Francisco',
            state: 'CA',
            zipCode: '94103',
            country: 'USA',
        },
        rating: 4.8,
        reviewCount: 189,
        acceptingNewPatients: true,
        wheelchairAccessible: true,
        isActive: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];

// ============================================================================
// QUALIFYING EVENTS
// ============================================================================

export const generateSampleQualifyingEvents = (): QualifyingEvent[] => [
    {
        id: 'qe_001',
        employeeId: 'emp003',
        employeeName: 'Mike Johnson',
        eventType: 'marriage',
        eventDate: '2025-02-14T00:00:00Z',
        description: 'Employee got married',
        specialEnrollmentWindowStart: '2025-02-14T00:00:00Z',
        specialEnrollmentWindowEnd: '2025-03-16T23:59:59Z',
        requiresDocumentation: true,
        documents: [
            {
                id: 'doc_qe_001',
                type: 'marriage_certificate',
                name: 'Marriage Certificate',
                url: '/documents/marriage-cert-qe-001.pdf',
                uploadedDate: '2025-02-20T10:00:00Z',
            },
        ],
        isVerified: true,
        verifiedDate: '2025-02-21T09:00:00Z',
        verifiedBy: 'hr@company.com',
        allowedChanges: ['add_dependent', 'change_coverage_level', 'enroll_in_plan'],
        enrollmentChanges: [],
        status: 'verified',
        reportedDate: '2025-02-20T10:00:00Z',
        createdAt: '2025-02-20T10:00:00Z',
        updatedAt: '2025-02-21T09:00:00Z',
    },
];

// ============================================================================
// PREMIUM DEDUCTIONS
// ============================================================================

export const generateSamplePremiumDeductions = (): PremiumDeduction[] => [
    {
        id: 'pd_001',
        employeeId: 'emp001',
        enrollmentId: 'enr_001',
        benefitPlanId: 'bp_health_gold',
        payrollPeriodStart: '2025-01-01',
        payrollPeriodEnd: '2025-01-15',
        payDate: '2025-01-15',
        employeeContribution: 200,
        employerContribution: 600,
        totalPremium: 800,
        isPreTax: true,
        taxSavings: 50,
        isAdjustment: false,
        status: 'processed',
        processedDate: '2025-01-15T12:00:00Z',
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-15T12:00:00Z',
    },
];

// ============================================================================
// SETTINGS
// ============================================================================

export const generateSampleSettings = (): BenefitSettings => ({
    id: 'settings_001',
    organizationId: 'org_001',
    defaultEnrollmentWindowDays: 30,
    requireDependentVerification: true,
    allowMidYearChanges: false,
    qualifyingEventWindowDays: 60,
    newHireEnrollmentPeriodDays: 30,
    newHireWaitingPeriodDays: 0,
    defaultPaymentFrequency: 'monthly',
    allowEmployerContributionVariance: true,
    requireACACompliance: true,
    requireCOBRANotifications: true,
    requireHIPAACompliance: true,
    sendEnrollmentReminders: true,
    reminderDaysBefore: [15, 7, 3, 1],
    sendCoverageChangeNotifications: true,
    enableProviderDirectory: true,
    requireInNetworkPreAuthorization: false,
    enableOnlineClaims: true,
    requireClaimReceipts: true,
    claimSubmissionDeadlineDays: 90,
    updatedAt: '2024-11-01T00:00:00Z',
    updatedBy: 'admin@company.com',
});
