export type FlightStatus = 'scheduled' | 'departed' | 'arrived' | 'delayed' | 'cancelled';
export type ShiftRotation = '2_1' | '4_3' | '8_6' | '14_7' | 'custom';

export interface FIFOWorker { workerId: string; employeeId: string; employeeName: string; position: string; site: string; rotation: ShiftRotation; currentStatus: 'on_site' | 'off_rotation' | 'in_transit'; flightDetails: FlightBooking[]; accommodation: AccommodationAssignment; swingSchedule: SwingSchedule; createdAt: string; }
export interface FlightBooking { bookingId: string; bookingReference: string; flightNumber: string; airline: string; departureAirport: string; arrivalAirport: string; departureTime: string; arrivalTime: string; bookingClass: string; status: FlightStatus; cost: number; currency: string; }
export interface AccommodationAssignment { assignmentId: string; campId: string; campName: string; roomNumber: string; roomType: 'single' | 'shared' | 'ensuite'; checkIn: string; checkOut: string; amenities: string[]; }
export interface SwingSchedule { scheduleId: string; rotationPattern: string; swingStartDate: string; swingEndDate: string; daysOn: number; daysOff: number; completedSwings: number; }
export interface CampFacility { facilityId: string; facilityName: string; location: string; capacity: number; currentOccupancy: number; facilities: CampAmenity[]; rooms: CampRoom[]; services: CampService[]; status: 'operational' | 'maintenance' | 'closed'; createdAt: string; }
export interface CampAmenity { amenityType: string; description: string; availability: '24/7' | 'scheduled'; }
export interface CampRoom { roomId: string; roomNumber: string; roomType: 'single' | 'shared' | 'ensuite'; capacity: number; occupied: number; assignedWorkers: string[]; }
export interface CampService { serviceType: string; provider: string; schedule: string; cost?: number; }
export interface HazardPayRule { ruleId: string; ruleName: string; hazardType: string; payMultiplier: number; eligibilityCriteria: string[]; applicableRoles: string[]; documentation: string[]; status: 'active' | 'inactive'; createdAt: string; }
export interface HazardPayment { paymentId: string; employeeId: string; employeeName: string; period: { startDate: string; endDate: string; }; hazardType: string; hoursWorked: number; baseRate: number; hazardMultiplier: number; totalAmount: number; approvedBy?: string; approvalDate?: string; paidDate?: string; status: 'pending' | 'approved' | 'paid'; createdAt: string; }
export interface MiningSettings { settingsId: string; organizationId: string; fifoSettings: { advanceBookingDays: number; preferredAirlines: string[]; accommodationStandard: string; }; campSettings: { minimumCapacity: number; maintenanceScheduleDays: number; }; hazardSettings: { autoCalculation: boolean; approvalRequired: boolean; documentationMandatory: boolean; }; notifications: { flightReminder: boolean; accommodationConfirmation: boolean; hazardPayApproval: boolean; }; updatedAt: string; }
export interface MiningAlert { alertId: string; alertType: 'fifo' | 'camp' | 'hazard'; severity: 'low' | 'medium' | 'high' | 'critical'; title: string; message: string; relatedEntity: { entityType: string; entityId: string; entityName: string; }; status: 'active' | 'acknowledged' | 'resolved'; createdAt: string; }
