import type {
  AlumniProfile,
  AlumniDirectory,
  AlumniEvent,
  Reunion,
  AlumniJob,
  AlumniNetworkAnalytics,
  AlumniNetworkSettings,
} from './types';

// Sample Alumni Profiles
export const sampleAlumniProfiles: AlumniProfile[] = [
  {
    alumniId: 'alumni-001',
    firstName: 'Sarah',
    lastName: 'Mitchell',
    fullName: 'Sarah Mitchell',
    email: 'sarah.mitchell@email.com',
    phone: '+1-415-555-0123',
    profilePicture: '/avatars/sarah-mitchell.jpg',
    dateJoined: new Date('2015-06-15'),
    dateLeft: new Date('2022-08-30'),
    tenure: 87, // months
    lastDesignation: 'Senior Software Engineer',
    lastDepartment: 'Engineering',
    lastLocation: 'San Francisco, CA',
    lastManager: 'James Wilson',
    reasonForLeaving: 'resignation',
    currentCompany: 'Tech Innovators Inc',
    currentDesignation: 'Lead Software Architect',
    currentLocation: 'Seattle, WA',
    currentIndustry: 'Technology',
    linkedInProfile: 'https://linkedin.com/in/sarah-mitchell',
    personalWebsite: 'https://sarahmitchell.dev',
    alumniStatus: 'active',
    membershipType: 'premium',
    joinedAlumniNetworkDate: new Date('2022-09-15'),
    lastActiveDate: new Date('2024-12-10'),
    profileVisibility: 'public',
    willingToMentor: true,
    openToOpportunities: false,
    openToReferrals: true,
    interests: ['Software Architecture', 'Cloud Computing', 'Mentorship', 'Public Speaking'],
    skills: ['Python', 'JavaScript', 'AWS', 'Kubernetes', 'System Design', 'Team Leadership'],
    eventsAttended: 8,
    jobsPosted: 3,
    referralsGiven: 12,
    mentoringSessions: 25,
    contactPreferences: {
      allowEmail: true,
      allowPhone: false,
      allowSMS: false,
      allowWhatsApp: true,
      newsletterSubscription: true,
      eventNotifications: true,
      jobAlerts: true,
    },
    address: {
      addressId: 'addr-001',
      addressLine1: '123 Tech Street',
      city: 'Seattle',
      state: 'Washington',
      country: 'United States',
      postalCode: '98101',
    },
    socialMedia: {
      linkedin: 'https://linkedin.com/in/sarah-mitchell',
      twitter: '@sarahcodes',
      github: 'https://github.com/sarahmitchell',
    },
    bio: 'Passionate software architect with 10+ years of experience building scalable systems. Love mentoring early-career engineers and contributing to open source.',
    achievements: [
      'Led architecture redesign that improved system performance by 300%',
      'Speaker at 5 major tech conferences',
      'Published author on cloud architecture',
    ],
    createdDate: new Date('2022-09-15'),
    createdBy: 'system',
    lastUpdatedDate: new Date('2024-12-10'),
    lastUpdatedBy: 'alumni-001',
    notes: 'Highly engaged alumni, excellent mentor',
  },
  {
    alumniId: 'alumni-002',
    firstName: 'Michael',
    lastName: 'Chen',
    fullName: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+1-212-555-0456',
    profilePicture: '/avatars/michael-chen.jpg',
    dateJoined: new Date('2017-03-10'),
    dateLeft: new Date('2023-06-15'),
    tenure: 75, // months
    lastDesignation: 'Product Manager',
    lastDepartment: 'Product',
    lastLocation: 'New York, NY',
    lastManager: 'Lisa Anderson',
    reasonForLeaving: 'resignation',
    currentCompany: 'Startup Ventures',
    currentDesignation: 'VP of Product',
    currentLocation: 'Austin, TX',
    currentIndustry: 'Technology',
    linkedInProfile: 'https://linkedin.com/in/michael-chen-pm',
    alumniStatus: 'active',
    membershipType: 'basic',
    joinedAlumniNetworkDate: new Date('2023-07-01'),
    lastActiveDate: new Date('2024-12-08'),
    profileVisibility: 'alumni_only',
    willingToMentor: true,
    openToOpportunities: true,
    openToReferrals: true,
    interests: ['Product Strategy', 'Startups', 'User Experience', 'Innovation'],
    skills: ['Product Management', 'User Research', 'Roadmap Planning', 'Agile', 'Data Analysis'],
    eventsAttended: 5,
    jobsPosted: 0,
    referralsGiven: 8,
    mentoringSessions: 15,
    contactPreferences: {
      allowEmail: true,
      allowPhone: true,
      allowSMS: false,
      allowWhatsApp: false,
      newsletterSubscription: true,
      eventNotifications: true,
      jobAlerts: true,
    },
    currentCompany: 'Startup Ventures',
    currentDesignation: 'VP of Product',
    currentLocation: 'Austin, TX',
    currentIndustry: 'Technology',
    bio: 'Product leader passionate about building products that solve real problems. Ex-FAANG, now helping startups scale.',
    createdDate: new Date('2023-07-01'),
    createdBy: 'system',
    lastUpdatedDate: new Date('2024-12-08'),
    lastUpdatedBy: 'alumni-002',
  },
  {
    alumniId: 'alumni-003',
    firstName: 'Jennifer',
    lastName: 'Rodriguez',
    fullName: 'Jennifer Rodriguez',
    email: 'jennifer.rodriguez@email.com',
    phone: '+1-617-555-0789',
    profilePicture: '/avatars/jennifer-rodriguez.jpg',
    dateJoined: new Date('2018-09-01'),
    dateLeft: new Date('2024-01-31'),
    tenure: 64, // months
    lastDesignation: 'Marketing Director',
    lastDepartment: 'Marketing',
    lastLocation: 'Boston, MA',
    lastManager: 'David Thompson',
    reasonForLeaving: 'resignation',
    currentCompany: 'Global Marketing Agency',
    currentDesignation: 'Chief Marketing Officer',
    currentLocation: 'Boston, MA',
    currentIndustry: 'Marketing',
    linkedInProfile: 'https://linkedin.com/in/jennifer-rodriguez-marketing',
    alumniStatus: 'active',
    membershipType: 'lifetime',
    joinedAlumniNetworkDate: new Date('2024-02-15'),
    lastActiveDate: new Date('2024-12-11'),
    profileVisibility: 'public',
    willingToMentor: true,
    openToOpportunities: false,
    openToReferrals: true,
    interests: ['Digital Marketing', 'Brand Strategy', 'Content Marketing', 'Leadership'],
    skills: ['Marketing Strategy', 'Brand Management', 'SEO/SEM', 'Analytics', 'Team Building'],
    eventsAttended: 6,
    jobsPosted: 2,
    referralsGiven: 15,
    mentoringSessions: 20,
    contactPreferences: {
      allowEmail: true,
      allowPhone: false,
      allowSMS: true,
      allowWhatsApp: true,
      newsletterSubscription: true,
      eventNotifications: true,
      jobAlerts: false,
    },
    bio: 'Award-winning marketer with expertise in digital transformation and brand growth. Passionate about empowering women in marketing.',
    achievements: [
      'Led rebranding that increased market share by 40%',
      'Winner of Marketing Excellence Award 2023',
      'Keynote speaker at MarketingCon',
    ],
    createdDate: new Date('2024-02-15'),
    createdBy: 'system',
    lastUpdatedDate: new Date('2024-12-11'),
    lastUpdatedBy: 'alumni-003',
  },
];

// Sample Alumni Directory
export const sampleAlumniDirectory: AlumniDirectory = {
  directoryId: 'dir-001',
  totalAlumni: 487,
  activeAlumni: 356,
  lastUpdatedDate: new Date('2024-12-13'),
  categories: [
    {
      categoryId: 'cat-001',
      categoryName: 'Engineering',
      categoryType: 'department',
      alumniCount: 145,
    },
    {
      categoryId: 'cat-002',
      categoryName: 'Product',
      categoryType: 'department',
      alumniCount: 78,
    },
    {
      categoryId: 'cat-003',
      categoryName: 'Marketing',
      categoryType: 'department',
      alumniCount: 62,
    },
    {
      categoryId: 'cat-004',
      categoryName: 'Sales',
      categoryType: 'department',
      alumniCount: 89,
    },
    {
      categoryId: 'cat-005',
      categoryName: 'Technology',
      categoryType: 'industry',
      alumniCount: 212,
    },
    {
      categoryId: 'cat-006',
      categoryName: '2020-2024',
      categoryType: 'year',
      alumniCount: 156,
    },
  ],
  featuredAlumni: ['alumni-001', 'alumni-003'],
};

// Sample Alumni Events
export const sampleAlumniEvents: AlumniEvent[] = [
  {
    eventId: 'event-001',
    eventName: 'Annual Alumni Reunion 2024',
    eventType: 'reunion',
    eventFormat: 'hybrid',
    description:
      'Join us for our annual alumni reunion! Reconnect with former colleagues, share stories, and network with fellow alumni. This hybrid event offers both in-person and virtual participation options.',
    eventDate: new Date('2024-12-20'),
    eventTime: '18:00',
    endDate: new Date('2024-12-20'),
    endTime: '22:00',
    venue: {
      venueId: 'venue-001',
      venueName: 'Grand Ballroom, Marriott Hotel',
      address: {
        addressId: 'venue-addr-001',
        addressLine1: '1234 Downtown Street',
        city: 'San Francisco',
        state: 'California',
        country: 'United States',
        postalCode: '94102',
      },
      capacity: 300,
      facilities: ['Audio/Visual Equipment', 'Catering', 'Parking', 'WiFi'],
      contactPerson: 'Emily White',
      contactPhone: '+1-415-555-1000',
      parkingAvailable: true,
      accessibilityFeatures: ['Wheelchair Access', 'Elevator', 'Accessible Restrooms'],
    },
    virtualLink: 'https://zoom.us/j/123456789',
    eventStatus: 'published',
    registrationOpen: true,
    registrationStartDate: new Date('2024-11-01'),
    registrationEndDate: new Date('2024-12-18'),
    maxAttendees: 300,
    currentAttendees: 187,
    waitlistEnabled: true,
    waitlistCount: 12,
    isFree: false,
    ticketPrice: 50,
    currency: 'USD',
    organizer: {
      organizerId: 'org-001',
      organizerName: 'Alumni Relations Team',
      organizerEmail: 'alumni@company.com',
      organizerPhone: '+1-415-555-2000',
      organizerRole: 'Alumni Coordinator',
    },
    coHosts: ['Jennifer Rodriguez', 'Michael Chen'],
    sponsors: [
      {
        sponsorId: 'sponsor-001',
        sponsorName: 'Tech Innovators Inc',
        sponsorLogo: '/logos/tech-innovators.png',
        sponsorLevel: 'platinum',
        sponsorshipAmount: 10000,
        sponsorWebsite: 'https://techinnovators.com',
      },
    ],
    agenda: [
      {
        agendaId: 'agenda-001',
        sessionName: 'Welcome & Registration',
        sessionDescription: 'Check-in and welcome drinks',
        startTime: '18:00',
        endTime: '18:30',
        location: 'Main Lobby',
      },
      {
        agendaId: 'agenda-002',
        sessionName: 'Keynote: The Journey Forward',
        sessionDescription: 'CEO shares company updates and vision',
        startTime: '18:30',
        endTime: '19:15',
        speaker: 'John Smith, CEO',
        location: 'Main Hall',
      },
      {
        agendaId: 'agenda-003',
        sessionName: 'Networking Dinner',
        sessionDescription: 'Enjoy dinner and reconnect with colleagues',
        startTime: '19:30',
        endTime: '21:00',
        location: 'Grand Ballroom',
      },
      {
        agendaId: 'agenda-004',
        sessionName: 'Awards & Recognition',
        sessionDescription: 'Honoring distinguished alumni',
        startTime: '21:00',
        endTime: '21:30',
        location: 'Main Hall',
      },
    ],
    speakers: [
      {
        speakerId: 'speaker-001',
        speakerName: 'John Smith',
        speakerTitle: 'CEO',
        speakerCompany: 'Company Inc',
        speakerBio: 'John has been leading the company for 10 years, driving innovation and growth.',
        speakerPhoto: '/speakers/john-smith.jpg',
        speakerTopic: 'The Journey Forward',
      },
    ],
    tags: ['reunion', 'networking', 'annual', '2024'],
    images: ['/events/reunion-2024-banner.jpg'],
    registrations: [
      {
        registrationId: 'reg-001',
        eventId: 'event-001',
        alumniId: 'alumni-001',
        alumniName: 'Sarah Mitchell',
        alumniEmail: 'sarah.mitchell@email.com',
        registrationDate: new Date('2024-11-05'),
        registrationStatus: 'confirmed',
        ticketType: 'In-Person',
        paymentStatus: 'paid',
        paymentAmount: 50,
        paymentDate: new Date('2024-11-05'),
        guestCount: 1,
        guestNames: ['John Mitchell'],
        dietaryRestrictions: 'Vegetarian',
        checkInStatus: 'not_checked_in',
      },
      {
        registrationId: 'reg-002',
        eventId: 'event-001',
        alumniId: 'alumni-002',
        alumniName: 'Michael Chen',
        alumniEmail: 'michael.chen@email.com',
        registrationDate: new Date('2024-11-10'),
        registrationStatus: 'confirmed',
        ticketType: 'Virtual',
        paymentStatus: 'paid',
        paymentAmount: 50,
        paymentDate: new Date('2024-11-10'),
        guestCount: 0,
        checkInStatus: 'not_checked_in',
      },
    ],
    attendanceList: [],
    rsvpCount: 187,
    attendedCount: 0,
    feedbackCount: 0,
    announcements: [
      {
        announcementId: 'ann-001',
        announcementTitle: 'Event Agenda Published',
        announcementMessage:
          'The detailed agenda for the Annual Alumni Reunion is now available. Check your email for the full schedule!',
        announcementDate: new Date('2024-12-01'),
        announcementType: 'update',
        targetAudience: 'registered',
        sentVia: ['email'],
      },
    ],
    reminders: [
      {
        reminderId: 'rem-001',
        reminderType: 'event_upcoming',
        scheduledDate: new Date('2024-12-13'),
        sent: true,
        sentDate: new Date('2024-12-13'),
        recipientCount: 187,
      },
    ],
    createdDate: new Date('2024-11-01'),
    createdBy: 'admin-001',
    createdByName: 'Admin User',
    lastUpdatedDate: new Date('2024-12-13'),
    lastUpdatedBy: 'admin-001',
    lastUpdatedByName: 'Admin User',
    notes: 'Largest alumni event of the year',
  },
  {
    eventId: 'event-002',
    eventName: 'Tech Talk: AI in Enterprise',
    eventType: 'webinar',
    eventFormat: 'virtual',
    description:
      'Join Sarah Mitchell, Lead Software Architect at Tech Innovators, for an insightful webinar on implementing AI solutions in enterprise environments.',
    eventDate: new Date('2025-01-15'),
    eventTime: '14:00',
    endDate: new Date('2025-01-15'),
    endTime: '15:30',
    virtualLink: 'https://zoom.us/j/987654321',
    eventStatus: 'published',
    registrationOpen: true,
    registrationStartDate: new Date('2024-12-01'),
    registrationEndDate: new Date('2025-01-14'),
    maxAttendees: 500,
    currentAttendees: 123,
    waitlistEnabled: false,
    waitlistCount: 0,
    isFree: true,
    organizer: {
      organizerId: 'org-002',
      organizerName: 'Sarah Mitchell',
      organizerEmail: 'sarah.mitchell@email.com',
      organizerRole: 'Alumni Volunteer',
    },
    coHosts: [],
    sponsors: [],
    agenda: [
      {
        agendaId: 'agenda-005',
        sessionName: 'Introduction',
        startTime: '14:00',
        endTime: '14:10',
        speaker: 'Sarah Mitchell',
      },
      {
        agendaId: 'agenda-006',
        sessionName: 'AI Implementation Strategies',
        sessionDescription: 'Best practices for enterprise AI adoption',
        startTime: '14:10',
        endTime: '14:50',
        speaker: 'Sarah Mitchell',
      },
      {
        agendaId: 'agenda-007',
        sessionName: 'Q&A Session',
        startTime: '14:50',
        endTime: '15:30',
      },
    ],
    speakers: [
      {
        speakerId: 'speaker-002',
        speakerName: 'Sarah Mitchell',
        speakerTitle: 'Lead Software Architect',
        speakerCompany: 'Tech Innovators Inc',
        speakerBio:
          'Sarah has 10+ years of experience in software architecture with focus on AI and cloud computing.',
        speakerPhoto: '/speakers/sarah-mitchell.jpg',
        speakerTopic: 'AI in Enterprise',
      },
    ],
    tags: ['tech', 'AI', 'webinar', 'education'],
    images: [],
    registrations: [],
    attendanceList: [],
    rsvpCount: 123,
    attendedCount: 0,
    feedbackCount: 0,
    announcements: [],
    reminders: [],
    createdDate: new Date('2024-12-01'),
    createdBy: 'alumni-001',
    createdByName: 'Sarah Mitchell',
    lastUpdatedDate: new Date('2024-12-10'),
    lastUpdatedBy: 'alumni-001',
    lastUpdatedByName: 'Sarah Mitchell',
  },
];

// Sample Reunions
export const sampleReunions: Reunion[] = [
  {
    reunionId: 'reunion-001',
    reunionName: 'Engineering Class of 2020 Reunion',
    batchYear: 2020,
    department: 'Engineering',
    location: 'San Francisco, CA',
    eventId: 'event-001',
    targetAudience: {
      yearRange: { start: 2019, end: 2021 },
      departments: ['Engineering', 'Product'],
    },
    expectedAttendees: 85,
    actualAttendees: 72,
    reunionCommittee: [
      {
        memberId: 'comm-001',
        memberName: 'Sarah Mitchell',
        role: 'Chair',
        email: 'sarah.mitchell@email.com',
        phone: '+1-415-555-0123',
      },
      {
        memberId: 'comm-002',
        memberName: 'Michael Chen',
        role: 'Communications Lead',
        email: 'michael.chen@email.com',
      },
    ],
    budget: {
      totalBudget: 15000,
      amountCollected: 12500,
      amountSpent: 8900,
      remainingBudget: 3600,
      expenses: [
        {
          expenseId: 'exp-001',
          expenseCategory: 'Venue',
          expenseDescription: 'Ballroom rental',
          plannedAmount: 5000,
          actualAmount: 4500,
          status: 'paid',
        },
        {
          expenseId: 'exp-002',
          expenseCategory: 'Catering',
          expenseDescription: 'Dinner for 200 people',
          plannedAmount: 6000,
          actualAmount: 5800,
          status: 'paid',
        },
        {
          expenseId: 'exp-003',
          expenseCategory: 'Entertainment',
          expenseDescription: 'Live band',
          plannedAmount: 2000,
          status: 'approved',
        },
      ],
    },
    activities: [
      {
        activityId: 'act-001',
        activityName: 'Photo Booth Session',
        activityType: 'photo_session',
        startTime: '18:30',
        endTime: '20:30',
        location: 'Lobby',
        responsible: 'Event Coordinator',
      },
      {
        activityId: 'act-002',
        activityName: 'Networking Games',
        activityType: 'ice_breaker',
        startTime: '19:00',
        endTime: '19:30',
        location: 'Main Hall',
        responsible: 'Sarah Mitchell',
      },
    ],
    memorabilia: ['Class Photo', 'Commemorative Badge', 'Reunion T-Shirt'],
  },
];

// Sample Alumni Jobs
export const sampleAlumniJobs: AlumniJob[] = [
  {
    jobId: 'job-001',
    jobTitle: 'Senior Software Engineer',
    jobType: 'full_time',
    jobLevel: 'senior',
    companyName: 'Tech Innovators Inc',
    companyLogo: '/logos/tech-innovators.png',
    companyWebsite: 'https://techinnovators.com',
    companySize: 'large',
    companyIndustry: 'Technology',
    jobDescription:
      'We are seeking an experienced Senior Software Engineer to join our platform engineering team. You will work on building scalable distributed systems that power our core product.',
    responsibilities: [
      'Design and implement scalable backend services',
      'Lead technical discussions and code reviews',
      'Mentor junior engineers',
      'Collaborate with product and design teams',
      'Optimize system performance and reliability',
    ],
    requirements: [
      '5+ years of software engineering experience',
      'Strong proficiency in Python or Java',
      'Experience with distributed systems',
      'Knowledge of cloud platforms (AWS/GCP/Azure)',
      'Excellent problem-solving skills',
    ],
    niceToHave: ['Experience with Kubernetes', 'Background in machine learning', 'Open source contributions'],
    workLocation: 'hybrid',
    locationCity: 'Seattle',
    locationCountry: 'United States',
    remotePolicy: 'hybrid',
    salaryRange: {
      min: 150000,
      max: 200000,
      currency: 'USD',
      period: 'yearly',
    },
    currency: 'USD',
    benefits: ['Health Insurance', '401(k) Matching', 'Unlimited PTO', 'Stock Options', 'Remote Work Flexibility'],
    experienceRequired: {
      min: 5,
      max: 10,
      unit: 'years',
    },
    educationRequired: ["Bachelor's in Computer Science or related field"],
    skillsRequired: ['Python', 'Java', 'AWS', 'Distributed Systems', 'System Design'],
    certificationsRequired: [],
    jobStatus: 'active',
    postedDate: new Date('2024-12-01'),
    applicationDeadline: new Date('2025-01-31'),
    startDate: new Date('2025-02-15'),
    applicationMethod: 'referral',
    applicationEmail: 'careers@techinnovators.com',
    referralContactName: 'Sarah Mitchell',
    referralContactEmail: 'sarah.mitchell@email.com',
    postedBy: 'alumni-001',
    postedByName: 'Sarah Mitchell',
    postedByEmail: 'sarah.mitchell@email.com',
    postedByCompany: 'Tech Innovators Inc',
    isReferralAvailable: true,
    viewCount: 245,
    applicationCount: 18,
    savedCount: 42,
    shareCount: 15,
    applications: [
      {
        applicationId: 'app-001',
        jobId: 'job-001',
        applicantId: 'alumni-002',
        applicantName: 'Michael Chen',
        applicantEmail: 'michael.chen@email.com',
        applicantPhone: '+1-212-555-0456',
        applicationDate: new Date('2024-12-05'),
        applicationStatus: 'shortlisted',
        resume: '/resumes/michael-chen.pdf',
        coverLetter: '/cover-letters/michael-chen.pdf',
        linkedInUrl: 'https://linkedin.com/in/michael-chen-pm',
        screeningQuestions: [],
        currentStage: 'phone_interview',
        stages: [
          {
            stageId: 'stage-001',
            stage: 'application_received',
            status: 'completed',
            startDate: new Date('2024-12-05'),
            completionDate: new Date('2024-12-05'),
          },
          {
            stageId: 'stage-002',
            stage: 'screening',
            status: 'completed',
            startDate: new Date('2024-12-06'),
            completionDate: new Date('2024-12-08'),
            notes: 'Strong technical background, good culture fit',
          },
          {
            stageId: 'stage-003',
            stage: 'phone_interview',
            status: 'in_progress',
            startDate: new Date('2024-12-10'),
          },
        ],
        isReferral: true,
        referredBy: 'alumni-001',
        referredByName: 'Sarah Mitchell',
        interviews: [],
        offerExtended: false,
        lastUpdatedDate: new Date('2024-12-10'),
      },
    ],
    featured: true,
    tags: ['engineering', 'backend', 'senior', 'referral'],
    category: 'Technology',
    createdDate: new Date('2024-12-01'),
    lastUpdatedDate: new Date('2024-12-13'),
    notes: 'Urgent hiring need, fast-track referrals',
  },
  {
    jobId: 'job-002',
    jobTitle: 'Marketing Manager',
    jobType: 'full_time',
    jobLevel: 'manager',
    companyName: 'Global Marketing Agency',
    companyWebsite: 'https://globalmarketingagency.com',
    companySize: 'medium',
    companyIndustry: 'Marketing',
    jobDescription:
      'Join our dynamic marketing team as a Marketing Manager. Lead campaigns, manage a team, and drive growth for our clients.',
    responsibilities: [
      'Develop and execute marketing strategies',
      'Manage a team of 5-7 marketers',
      'Oversee campaign performance and ROI',
      'Client relationship management',
      'Budget planning and management',
    ],
    requirements: [
      '5+ years in marketing',
      'Proven team management experience',
      'Strong analytical skills',
      'Excellent communication skills',
    ],
    niceToHave: ['Digital marketing certifications', 'Experience in B2B marketing'],
    workLocation: 'on_site',
    locationCity: 'Boston',
    locationCountry: 'United States',
    remotePolicy: 'flexible',
    salaryRange: {
      min: 90000,
      max: 120000,
      currency: 'USD',
      period: 'yearly',
    },
    currency: 'USD',
    benefits: ['Health Insurance', 'Dental Insurance', 'Retirement Plan', '3 weeks PTO'],
    experienceRequired: {
      min: 5,
      max: 8,
      unit: 'years',
    },
    educationRequired: ["Bachelor's in Marketing or related field"],
    skillsRequired: ['Marketing Strategy', 'Team Management', 'Analytics', 'Campaign Management'],
    jobStatus: 'active',
    postedDate: new Date('2024-11-15'),
    applicationDeadline: new Date('2025-01-15'),
    applicationMethod: 'email',
    applicationEmail: 'hr@globalmarketingagency.com',
    postedBy: 'alumni-003',
    postedByName: 'Jennifer Rodriguez',
    postedByEmail: 'jennifer.rodriguez@email.com',
    postedByCompany: 'Global Marketing Agency',
    isReferralAvailable: true,
    viewCount: 178,
    applicationCount: 12,
    savedCount: 28,
    shareCount: 8,
    applications: [],
    featured: false,
    tags: ['marketing', 'manager', 'b2b'],
    category: 'Marketing',
    createdDate: new Date('2024-11-15'),
    lastUpdatedDate: new Date('2024-12-10'),
  },
];

// Sample Alumni Network Analytics
export const sampleAlumniNetworkAnalytics: AlumniNetworkAnalytics = {
  totalAlumni: 487,
  activeAlumni: 356,
  newAlumniThisMonth: 12,
  alumniByDepartment: [
    { department: 'Engineering', count: 145 },
    { department: 'Sales', count: 89 },
    { department: 'Product', count: 78 },
    { department: 'Marketing', count: 62 },
    { department: 'Operations', count: 45 },
    { department: 'Finance', count: 38 },
    { department: 'HR', count: 30 },
  ],
  alumniByLocation: [
    { location: 'San Francisco, CA', count: 98 },
    { location: 'New York, NY', count: 76 },
    { location: 'Seattle, WA', count: 54 },
    { location: 'Austin, TX', count: 42 },
    { location: 'Boston, MA', count: 38 },
    { location: 'Remote/Other', count: 179 },
  ],
  alumniByYear: [
    { year: 2024, count: 15 },
    { year: 2023, count: 42 },
    { year: 2022, count: 58 },
    { year: 2021, count: 67 },
    { year: 2020, count: 72 },
    { year: 2019, count: 55 },
    { year: 2018, count: 48 },
    { year: 2017, count: 40 },
    { year: 2016, count: 35 },
    { year: 2015, count: 55 },
  ],
  alumniByCurrentIndustry: [
    { industry: 'Technology', count: 212 },
    { industry: 'Finance', count: 68 },
    { industry: 'Consulting', count: 52 },
    { industry: 'Healthcare', count: 45 },
    { industry: 'Education', count: 38 },
    { industry: 'Marketing', count: 35 },
    { industry: 'Other', count: 37 },
  ],
  totalEvents: 24,
  upcomingEvents: 3,
  totalAttendees: 1245,
  averageAttendanceRate: 78.5,
  eventsByType: [
    { type: 'Networking', count: 8 },
    { type: 'Reunion', count: 5 },
    { type: 'Webinar', count: 6 },
    { type: 'Workshop', count: 3 },
    { type: 'Social', count: 2 },
  ],
  topRatedEvents: [
    { eventId: 'event-001', eventName: 'Annual Alumni Reunion 2024', rating: 4.8 },
    { eventId: 'event-002', eventName: 'Tech Talk: AI in Enterprise', rating: 4.7 },
  ],
  totalJobs: 45,
  activeJobs: 28,
  totalApplications: 156,
  averageApplicationsPerJob: 5.6,
  jobsByType: [
    { type: 'Full-time', count: 32 },
    { type: 'Contract', count: 8 },
    { type: 'Part-time', count: 3 },
    { type: 'Internship', count: 2 },
  ],
  jobsByIndustry: [
    { industry: 'Technology', count: 25 },
    { industry: 'Finance', count: 8 },
    { industry: 'Marketing', count: 6 },
    { industry: 'Consulting', count: 4 },
    { industry: 'Other', count: 2 },
  ],
  placementRate: 32.5,
  activeUsers: 285,
  totalConnections: 1876,
  totalMentoringSessions: 342,
  totalReferrals: 487,
  engagementRate: 64.2,
  monthlyGrowth: [
    { month: 'Jul 2024', alumni: 8, events: 2, jobs: 3 },
    { month: 'Aug 2024', alumni: 10, events: 1, jobs: 4 },
    { month: 'Sep 2024', alumni: 12, events: 3, jobs: 5 },
    { month: 'Oct 2024', alumni: 15, events: 2, jobs: 6 },
    { month: 'Nov 2024', alumni: 18, events: 4, jobs: 7 },
    { month: 'Dec 2024', alumni: 12, events: 3, jobs: 5 },
  ],
};

// Sample Alumni Network Settings
export const sampleAlumniNetworkSettings: AlumniNetworkSettings = {
  settingsId: 'settings-001',
  networkName: 'Company Alumni Network',
  networkDescription: 'Connecting past and present to build a stronger community',
  networkLogo: '/logos/alumni-network.png',
  contactEmail: 'alumni@company.com',
  contactPhone: '+1-415-555-2000',
  directorySettings: {
    enablePublicDirectory: false,
    requireApprovalForMembership: true,
    allowSelfRegistration: true,
    defaultProfileVisibility: 'alumni_only',
    allowProfileEditing: true,
    mandatoryFields: ['firstName', 'lastName', 'email', 'lastDesignation', 'lastDepartment'],
  },
  eventsSettings: {
    enableEvents: true,
    requireEventApproval: true,
    allowAlumniToCreateEvents: true,
    defaultEventFormat: 'hybrid',
    enableEventPayments: true,
    paymentGateway: 'Stripe',
    enableWaitlist: true,
    sendEventReminders: true,
    reminderDaysBefore: [7, 3, 1],
  },
  jobsSettings: {
    enableJobs: true,
    requireJobApproval: true,
    allowAlumniToPostJobs: true,
    jobPostingDurationDays: 60,
    enableJobApplications: true,
    enableJobAlerts: true,
    moderateJobPosts: true,
  },
  communicationSettings: {
    enableEmailNotifications: true,
    enableSMSNotifications: true,
    enablePushNotifications: true,
    newsletterFrequency: 'monthly',
    allowDirectMessaging: true,
  },
  privacySettings: {
    dataRetentionPeriod: 7,
    allowDataExport: true,
    requireConsentForCommunication: true,
    gdprCompliant: true,
  },
  integrationSettings: {
    linkedInIntegration: true,
    emailMarketingIntegration: true,
    paymentGatewayIntegration: true,
    analyticsIntegration: true,
  },
  lastUpdatedDate: new Date('2024-11-01'),
  lastUpdatedBy: 'admin-001',
  lastUpdatedByName: 'System Administrator',
};
