// Automotive Module - Sample Data

import {
  Technician, TechnicianShift, RosterTemplate, ShiftSwapRequest, TimeOffRequest, WorkloadAnalysis,
  SalesCommission, VehicleSale, ServiceSale, CommissionStructure, CommissionReport, SalesPerson,
  Part, InventoryMovement, PurchaseOrder, StockAdjustment, InventoryAnalysis,
  AutomotiveSettings
} from './types';

// ============================================================================
// TECHNICIAN ROSTERING SAMPLE DATA
// ============================================================================

export const sampleTechnicians: Technician[] = [
  {
    technicianId: 'tech-001',
    employeeId: 'EMP-1001',
    firstName: 'Mike',
    lastName: 'Anderson',
    email: 'mike.anderson@dealership.com',
    phone: '555-0101',
    certifications: [
      {
        certificationId: 'cert-001',
        certificationName: 'ASE Master Technician',
        issuingOrganization: 'ASE',
        certificationNumber: 'ASE-12345',
        issueDate: new Date('2022-01-15'),
        expiryDate: new Date('2027-01-15'),
        isActive: true,
      },
      {
        certificationId: 'cert-002',
        certificationName: 'Ford Certified Technician',
        issuingOrganization: 'Ford Motor Company',
        certificationNumber: 'FORD-567',
        issueDate: new Date('2021-06-01'),
        expiryDate: new Date('2026-06-01'),
        isActive: true,
      },
    ],
    specializations: ['Engine Diagnostics', 'Electrical Systems', 'Transmission'],
    skillLevel: 'master',
    hourlyRate: 35.00,
    employmentType: 'full_time',
    availability: [
      { availabilityId: 'av-001', dayOfWeek: 'monday', startTime: '08:00', endTime: '17:00', isAvailable: true, preferredShift: 'morning' },
      { availabilityId: 'av-002', dayOfWeek: 'tuesday', startTime: '08:00', endTime: '17:00', isAvailable: true, preferredShift: 'morning' },
      { availabilityId: 'av-003', dayOfWeek: 'wednesday', startTime: '08:00', endTime: '17:00', isAvailable: true, preferredShift: 'morning' },
      { availabilityId: 'av-004', dayOfWeek: 'thursday', startTime: '08:00', endTime: '17:00', isAvailable: true, preferredShift: 'morning' },
      { availabilityId: 'av-005', dayOfWeek: 'friday', startTime: '08:00', endTime: '17:00', isAvailable: true, preferredShift: 'morning' },
    ],
    performanceMetrics: {
      averageJobTime: 125,
      jobsCompleted: 245,
      customerSatisfactionScore: 92,
      qualityScore: 95,
      efficiency: 88,
      comebackRate: 2.5,
      lastReviewDate: new Date('2024-11-01'),
    },
    status: 'active',
    hireDate: new Date('2018-03-15'),
    department: 'Service',
  },
  {
    technicianId: 'tech-002',
    employeeId: 'EMP-1002',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@dealership.com',
    phone: '555-0102',
    certifications: [
      {
        certificationId: 'cert-003',
        certificationName: 'ASE Brakes Certification',
        issuingOrganization: 'ASE',
        certificationNumber: 'ASE-45678',
        issueDate: new Date('2023-02-10'),
        expiryDate: new Date('2028-02-10'),
        isActive: true,
      },
    ],
    specializations: ['Brakes', 'Suspension', 'Alignments'],
    skillLevel: 'journeyman',
    hourlyRate: 28.00,
    employmentType: 'full_time',
    availability: [
      { availabilityId: 'av-006', dayOfWeek: 'monday', startTime: '10:00', endTime: '19:00', isAvailable: true, preferredShift: 'afternoon' },
      { availabilityId: 'av-007', dayOfWeek: 'tuesday', startTime: '10:00', endTime: '19:00', isAvailable: true, preferredShift: 'afternoon' },
      { availabilityId: 'av-008', dayOfWeek: 'wednesday', startTime: '10:00', endTime: '19:00', isAvailable: true, preferredShift: 'afternoon' },
      { availabilityId: 'av-009', dayOfWeek: 'thursday', startTime: '10:00', endTime: '19:00', isAvailable: true, preferredShift: 'afternoon' },
      { availabilityId: 'av-010', dayOfWeek: 'saturday', startTime: '08:00', endTime: '14:00', isAvailable: true, preferredShift: 'morning' },
    ],
    performanceMetrics: {
      averageJobTime: 95,
      jobsCompleted: 312,
      customerSatisfactionScore: 89,
      qualityScore: 91,
      efficiency: 92,
      comebackRate: 3.2,
      lastReviewDate: new Date('2024-10-15'),
    },
    status: 'active',
    hireDate: new Date('2020-07-20'),
    department: 'Service',
  },
];

export const sampleShifts: TechnicianShift[] = [
  {
    shiftId: 'shift-001',
    technicianId: 'tech-001',
    technicianName: 'Mike Anderson',
    date: new Date(),
    shiftType: 'morning',
    startTime: '08:00',
    endTime: '17:00',
    breakDuration: 60,
    location: 'Main Service Center',
    serviceAdvisor: 'John Smith',
    assignedJobs: ['JOB-101', 'JOB-102', 'JOB-103'],
    status: 'scheduled',
  },
  {
    shiftId: 'shift-002',
    technicianId: 'tech-002',
    technicianName: 'Sarah Johnson',
    date: new Date(),
    shiftType: 'afternoon',
    startTime: '10:00',
    endTime: '19:00',
    breakDuration: 60,
    location: 'Main Service Center',
    serviceAdvisor: 'Jane Doe',
    assignedJobs: ['JOB-104', 'JOB-105'],
    status: 'scheduled',
  },
];

export const sampleRosterTemplates: RosterTemplate[] = [
  {
    templateId: 'template-001',
    templateName: 'Standard Monday-Friday Coverage',
    description: 'Standard weekday coverage with morning and afternoon shifts',
    weekPattern: [
      {
        weekNumber: 1,
        shifts: [
          {
            dayOfWeek: 'monday',
            shiftType: 'morning',
            startTime: '08:00',
            endTime: '17:00',
            requiredTechnicians: 3,
            requiredSkillLevel: 'journeyman',
          },
          {
            dayOfWeek: 'monday',
            shiftType: 'afternoon',
            startTime: '10:00',
            endTime: '19:00',
            requiredTechnicians: 2,
          },
        ],
      },
    ],
    effectiveFrom: new Date('2025-01-01'),
    isActive: true,
    createdBy: 'admin',
    createdDate: new Date('2024-12-01'),
  },
];

export const sampleShiftSwapRequests: ShiftSwapRequest[] = [
  {
    requestId: 'swap-001',
    requestingTechnicianId: 'tech-001',
    requestingTechnicianName: 'Mike Anderson',
    originalShiftId: 'shift-001',
    targetTechnicianId: 'tech-002',
    targetTechnicianName: 'Sarah Johnson',
    proposedShiftId: 'shift-002',
    reason: 'Family emergency',
    requestDate: new Date('2024-12-10'),
    status: 'pending',
  },
];

export const sampleTimeOffRequests: TimeOffRequest[] = [
  {
    requestId: 'timeoff-001',
    technicianId: 'tech-002',
    technicianName: 'Sarah Johnson',
    startDate: new Date('2024-12-24'),
    endDate: new Date('2024-12-26'),
    requestType: 'vacation',
    reason: 'Holiday vacation',
    affectedShifts: ['shift-015', 'shift-016', 'shift-017'],
    coverageArranged: true,
    coverageTechnicianId: 'tech-001',
    requestDate: new Date('2024-11-15'),
    status: 'approved',
    approvedBy: 'manager',
    approvalDate: new Date('2024-11-16'),
  },
];

export const sampleWorkloadAnalysis: WorkloadAnalysis = {
  analysisId: 'analysis-001',
  period: { start: new Date('2024-11-01'), end: new Date('2024-11-30') },
  totalJobs: 487,
  totalHours: 1856,
  averageJobsPerTechnician: 81,
  averageHoursPerTechnician: 309,
  utilizationRate: 87,
  overtimeHours: 24,
  technicianWorkload: [
    {
      technicianId: 'tech-001',
      technicianName: 'Mike Anderson',
      scheduledHours: 160,
      actualHours: 168,
      jobsCompleted: 85,
      utilizationRate: 95,
      overtimeHours: 8,
      efficiency: 88,
    },
    {
      technicianId: 'tech-002',
      technicianName: 'Sarah Johnson',
      scheduledHours: 160,
      actualHours: 172,
      jobsCompleted: 92,
      utilizationRate: 98,
      overtimeHours: 12,
      efficiency: 92,
    },
  ],
  recommendations: [
    'Consider hiring additional technician for peak periods',
    'Review overtime patterns for tech-002',
    'Optimize job assignments to balance workload',
  ],
  generatedDate: new Date('2024-12-01'),
};

// ============================================================================
// SALES COMMISSIONS SAMPLE DATA
// ============================================================================

export const sampleSalesPeople: SalesPerson[] = [
  {
    salesPersonId: 'sp-001',
    employeeId: 'EMP-2001',
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david.martinez@dealership.com',
    phone: '555-0201',
    department: 'new_vehicles',
    hireDate: new Date('2019-04-01'),
    commissionStructureId: 'cs-001',
    performanceMetrics: {
      ytdSales: 2450000,
      ytdCommissions: 73500,
      ytdUnits: 98,
      mtdSales: 285000,
      mtdCommissions: 8550,
      mtdUnits: 12,
      averageDealSize: 25000,
      closingRate: 24,
      customerSatisfactionScore: 91,
      lastReviewDate: new Date('2024-10-01'),
    },
    status: 'active',
    yearlySalesTarget: 3000000,
    monthlySalesTarget: 250000,
  },
  {
    salesPersonId: 'sp-002',
    employeeId: 'EMP-2002',
    firstName: 'Lisa',
    lastName: 'Chen',
    email: 'lisa.chen@dealership.com',
    phone: '555-0202',
    department: 'used_vehicles',
    hireDate: new Date('2021-08-15'),
    commissionStructureId: 'cs-002',
    performanceMetrics: {
      ytdSales: 1850000,
      ytdCommissions: 55500,
      ytdUnits: 123,
      mtdSales: 195000,
      mtdCommissions: 5850,
      mtdUnits: 13,
      averageDealSize: 15000,
      closingRate: 28,
      customerSatisfactionScore: 94,
      lastReviewDate: new Date('2024-11-01'),
    },
    status: 'active',
    yearlySalesTarget: 2000000,
    monthlySalesTarget: 165000,
  },
];

export const sampleVehicleSales: VehicleSale[] = [
  {
    saleId: 'vs-001',
    vehicleId: 'VEH-001',
    vehicleMake: 'Ford',
    vehicleModel: 'F-150',
    vehicleYear: 2024,
    vin: '1FTFW1E84PKF12345',
    saleType: 'new',
    salePrice: 52500,
    cost: 45000,
    grossProfit: 7500,
    customerId: 'CUST-001',
    customerName: 'John Smith',
    saleDate: new Date('2024-12-05'),
    deliveryDate: new Date('2024-12-08'),
    financingType: 'finance',
    financeCommission: 500,
    addOnsCommission: 300,
    totalCommission: 1575,
    commissionRate: 3,
    invoiceNumber: 'INV-2024-1245',
    status: 'delivered',
  },
  {
    saleId: 'vs-002',
    vehicleId: 'VEH-002',
    vehicleMake: 'Honda',
    vehicleModel: 'Civic',
    vehicleYear: 2022,
    vin: '2HGFC2F59MH567890',
    saleType: 'used',
    salePrice: 22500,
    cost: 19000,
    grossProfit: 3500,
    customerId: 'CUST-002',
    customerName: 'Jane Doe',
    saleDate: new Date('2024-12-07'),
    deliveryDate: new Date('2024-12-07'),
    financingType: 'cash',
    totalCommission: 675,
    commissionRate: 3,
    invoiceNumber: 'INV-2024-1246',
    status: 'delivered',
  },
];

export const sampleServiceSales: ServiceSale[] = [
  {
    serviceId: 'ss-001',
    customerId: 'CUST-003',
    customerName: 'Bob Wilson',
    vehicleId: 'VEH-003',
    serviceType: 'maintenance',
    serviceDescription: 'Oil change, tire rotation, brake inspection',
    serviceDate: new Date('2024-12-06'),
    laborAmount: 120,
    partsAmount: 85,
    totalAmount: 205,
    commissionableAmount: 205,
    commissionRate: 5,
    commissionAmount: 10.25,
    serviceAdvisorId: 'sp-003',
    invoiceNumber: 'SVC-2024-3456',
    isPaid: true,
  },
  {
    serviceId: 'ss-002',
    customerId: 'CUST-004',
    customerName: 'Mary Taylor',
    vehicleId: 'VEH-004',
    serviceType: 'repair',
    serviceDescription: 'Brake pad replacement, rotor resurfacing',
    serviceDate: new Date('2024-12-08'),
    laborAmount: 280,
    partsAmount: 320,
    totalAmount: 600,
    commissionableAmount: 600,
    commissionRate: 5,
    commissionAmount: 30,
    serviceAdvisorId: 'sp-003',
    invoiceNumber: 'SVC-2024-3457',
    isPaid: true,
  },
];

export const sampleCommissionStructures: CommissionStructure[] = [
  {
    structureId: 'cs-001',
    structureName: 'New Vehicle Sales - Tiered',
    description: 'Tiered commission structure for new vehicle sales based on gross profit',
    applicableTo: 'vehicles',
    commissionType: 'tiered',
    tiers: [
      { tierId: 't1', tierName: 'Base', minAmount: 0, maxAmount: 3000, commissionRate: 20, flatBonus: 0 },
      { tierId: 't2', tierName: 'Standard', minAmount: 3001, maxAmount: 5000, commissionRate: 25, flatBonus: 100 },
      { tierId: 't3', tierName: 'Premium', minAmount: 5001, commissionRate: 30, flatBonus: 250 },
    ],
    bonusRules: [
      {
        ruleId: 'br-001',
        ruleName: 'Monthly Target Bonus',
        ruleType: 'target',
        criteria: { monthlyTarget: 10, unitType: 'vehicles' },
        bonusAmount: 1000,
        isActive: true,
      },
    ],
    effectiveFrom: new Date('2024-01-01'),
    isActive: true,
    createdBy: 'admin',
    createdDate: new Date('2023-12-01'),
  },
  {
    structureId: 'cs-002',
    structureName: 'Used Vehicle Sales - Percentage',
    description: 'Flat percentage of gross profit for used vehicle sales',
    applicableTo: 'vehicles',
    commissionType: 'percentage',
    baseRate: 30,
    effectiveFrom: new Date('2024-01-01'),
    isActive: true,
    createdBy: 'admin',
    createdDate: new Date('2023-12-01'),
  },
];

export const sampleCommissions: SalesCommission[] = [
  {
    commissionId: 'comm-001',
    salesPersonId: 'sp-001',
    salesPersonName: 'David Martinez',
    period: { start: new Date('2024-11-01'), end: new Date('2024-11-30') },
    vehicleSales: sampleVehicleSales.slice(0, 1),
    serviceSales: [],
    totalVehicleSales: 52500,
    totalServiceSales: 0,
    totalSalesAmount: 52500,
    baseCommission: 2250,
    bonuses: [
      {
        bonusId: 'bonus-001',
        bonusType: 'monthly_target',
        bonusDescription: 'Monthly target achieved - 12 units',
        bonusAmount: 1000,
        eligibilityCriteria: 'Sold 10+ vehicles in November',
        achievedDate: new Date('2024-11-30'),
      },
    ],
    totalBonuses: 1000,
    deductions: [],
    totalDeductions: 0,
    netCommission: 3250,
    commissionRate: 3,
    status: 'approved',
    calculatedDate: new Date('2024-12-01'),
    approvedBy: 'sales_manager',
    approvalDate: new Date('2024-12-02'),
    paymentDate: new Date('2024-12-15'),
  },
];

export const sampleCommissionReports: CommissionReport[] = [
  {
    reportId: 'report-001',
    reportType: 'team',
    period: { start: new Date('2024-11-01'), end: new Date('2024-11-30') },
    totalSales: 3500000,
    totalCommissions: 105000,
    averageCommissionRate: 3,
    topPerformers: [
      {
        rank: 1,
        salesPersonId: 'sp-001',
        salesPersonName: 'David Martinez',
        totalSales: 285000,
        totalCommissions: 8550,
        unitsold: 12,
        averageDealSize: 23750,
      },
      {
        rank: 2,
        salesPersonId: 'sp-002',
        salesPersonName: 'Lisa Chen',
        totalSales: 195000,
        totalCommissions: 5850,
        unitsold: 13,
        averageDealSize: 15000,
      },
    ],
    trends: [
      { period: 'Nov 2024', totalSales: 285000, totalCommissions: 8550, averageCommissionRate: 3, unitsold: 12 },
      { period: 'Oct 2024', totalSales: 265000, totalCommissions: 7950, averageCommissionRate: 3, unitsold: 11 },
      { period: 'Sep 2024', totalSales: 275000, totalCommissions: 8250, averageCommissionRate: 3, unitsold: 11 },
    ],
    generatedDate: new Date('2024-12-01'),
    generatedBy: 'sales_manager',
  },
];

// ============================================================================
// PARTS INVENTORY SAMPLE DATA
// ============================================================================

export const sampleParts: Part[] = [
  {
    partId: 'part-001',
    partNumber: 'FL-820S',
    partName: 'Motorcraft Oil Filter',
    description: 'Premium oil filter for Ford vehicles',
    category: 'Filters',
    subCategory: 'Oil Filters',
    manufacturer: 'Motorcraft',
    manufacturerPartNumber: 'FL-820S',
    applicableVehicles: [
      { make: 'Ford', model: 'F-150', yearStart: 2015, yearEnd: 2024, engine: '5.0L V8' },
      { make: 'Ford', model: 'Mustang', yearStart: 2015, yearEnd: 2024, engine: '5.0L V8' },
    ],
    unitOfMeasure: 'EA',
    cost: 8.50,
    retailPrice: 15.99,
    wholesalePrice: 12.00,
    markup: 88,
    quantityOnHand: 45,
    quantityOnOrder: 0,
    quantityReserved: 5,
    quantityAvailable: 40,
    reorderPoint: 20,
    reorderQuantity: 50,
    minStockLevel: 15,
    maxStockLevel: 100,
    leadTimeDays: 3,
    binLocation: 'A-12-03',
    shelf: 'A',
    weight: 0.8,
    dimensions: { length: 4, width: 4, height: 5 },
    isSerialized: false,
    isCore: false,
    warrantyDays: 90,
    supplier: {
      supplierId: 'SUP-001',
      supplierName: 'Ford Parts Direct',
      supplierPartNumber: 'FL-820S',
      contactPerson: 'Tom Wilson',
      phone: '555-0301',
      email: 'orders@fordpartsdirect.com',
      leadTimeDays: 3,
      minOrderQuantity: 25,
      lastOrderDate: new Date('2024-11-15'),
      preferredSupplier: true,
    },
    status: 'in_stock',
    lastOrderDate: new Date('2024-11-15'),
    lastSaleDate: new Date('2024-12-08'),
    createdDate: new Date('2023-01-10'),
    updatedDate: new Date('2024-12-08'),
  },
  {
    partId: 'part-002',
    partNumber: 'BRF-1234',
    partName: 'Premium Brake Pad Set - Front',
    description: 'Ceramic brake pads for superior stopping power and low dust',
    category: 'Brakes',
    subCategory: 'Brake Pads',
    manufacturer: 'Raybestos',
    manufacturerPartNumber: 'EHT1234',
    applicableVehicles: [
      { make: 'Honda', model: 'Civic', yearStart: 2016, yearEnd: 2021 },
      { make: 'Honda', model: 'Accord', yearStart: 2018, yearEnd: 2022 },
    ],
    unitOfMeasure: 'SET',
    cost: 42.00,
    retailPrice: 89.99,
    wholesalePrice: 65.00,
    markup: 114,
    quantityOnHand: 12,
    quantityOnOrder: 20,
    quantityReserved: 2,
    quantityAvailable: 10,
    reorderPoint: 8,
    reorderQuantity: 20,
    minStockLevel: 6,
    maxStockLevel: 40,
    leadTimeDays: 5,
    binLocation: 'B-05-12',
    shelf: 'B',
    weight: 3.2,
    dimensions: { length: 8, width: 6, height: 3 },
    isSerialized: false,
    isCore: false,
    warrantyDays: 365,
    supplier: {
      supplierId: 'SUP-002',
      supplierName: 'Auto Parts Warehouse',
      supplierPartNumber: 'EHT1234',
      contactPerson: 'Sarah Lee',
      phone: '555-0302',
      email: 'sales@autopartswarehouse.com',
      leadTimeDays: 5,
      minOrderQuantity: 10,
      lastOrderDate: new Date('2024-11-20'),
      preferredSupplier: true,
    },
    status: 'in_stock',
    lastOrderDate: new Date('2024-11-20'),
    lastSaleDate: new Date('2024-12-07'),
    createdDate: new Date('2023-02-15'),
    updatedDate: new Date('2024-12-07'),
  },
];

export const sampleInventoryMovements: InventoryMovement[] = [
  {
    movementId: 'move-001',
    partId: 'part-001',
    partNumber: 'FL-820S',
    partName: 'Motorcraft Oil Filter',
    movementType: 'receipt',
    quantity: 50,
    unitCost: 8.50,
    totalCost: 425.00,
    referenceNumber: 'PO-2024-1156',
    referenceType: 'purchase_order',
    toLocation: 'A-12-03',
    performedBy: 'warehouse_clerk',
    movementDate: new Date('2024-11-15'),
    notes: 'Regular stock replenishment',
  },
  {
    movementId: 'move-002',
    partId: 'part-001',
    partNumber: 'FL-820S',
    partName: 'Motorcraft Oil Filter',
    movementType: 'sale',
    quantity: -1,
    referenceNumber: 'SVC-2024-3456',
    referenceType: 'work_order',
    fromLocation: 'A-12-03',
    performedBy: 'tech-001',
    movementDate: new Date('2024-12-06'),
  },
];

export const samplePurchaseOrders: PurchaseOrder[] = [
  {
    purchaseOrderId: 'po-001',
    poNumber: 'PO-2024-1156',
    supplierId: 'SUP-001',
    supplierName: 'Ford Parts Direct',
    orderDate: new Date('2024-11-10'),
    expectedDeliveryDate: new Date('2024-11-15'),
    actualDeliveryDate: new Date('2024-11-15'),
    items: [
      {
        itemId: 'poi-001',
        partId: 'part-001',
        partNumber: 'FL-820S',
        partName: 'Motorcraft Oil Filter',
        quantityOrdered: 50,
        quantityReceived: 50,
        quantityBackordered: 0,
        unitCost: 8.50,
        totalCost: 425.00,
        expectedDeliveryDate: new Date('2024-11-15'),
        actualDeliveryDate: new Date('2024-11-15'),
        status: 'received',
      },
    ],
    subtotal: 425.00,
    tax: 34.00,
    shipping: 15.00,
    total: 474.00,
    status: 'received',
    createdBy: 'parts_manager',
    approvedBy: 'service_director',
    approvalDate: new Date('2024-11-10'),
    receivedBy: 'warehouse_clerk',
    notes: 'Regular stock order',
  },
];

export const sampleStockAdjustments: StockAdjustment[] = [
  {
    adjustmentId: 'adj-001',
    adjustmentDate: new Date('2024-12-01'),
    adjustmentType: 'physical_count',
    items: [
      {
        itemId: 'adji-001',
        partId: 'part-001',
        partNumber: 'FL-820S',
        partName: 'Motorcraft Oil Filter',
        systemQuantity: 48,
        physicalQuantity: 45,
        adjustmentQuantity: -3,
        unitCost: 8.50,
        adjustmentValue: -25.50,
        binLocation: 'A-12-03',
        reason: 'Physical count variance',
      },
    ],
    reason: 'Monthly physical inventory count',
    totalValue: -25.50,
    performedBy: 'inventory_clerk',
    approvedBy: 'parts_manager',
    approvalDate: new Date('2024-12-01'),
    notes: 'Minor variance found during monthly count',
    status: 'approved',
  },
];

export const sampleInventoryAnalysis: InventoryAnalysis = {
  analysisId: 'analysis-002',
  period: { start: new Date('2024-11-01'), end: new Date('2024-11-30') },
  totalParts: 1245,
  totalValue: 185750,
  turnoverRate: 4.2,
  slowMovingParts: [
    {
      partId: 'part-050',
      partNumber: 'RARE-001',
      partName: 'Specialty Part - Discontinued Model',
      quantityOnHand: 5,
      value: 425,
      daysSinceLastSale: 180,
      turnoverRate: 0.2,
      recommendation: 'Consider markdown or return to supplier',
    },
  ],
  fastMovingParts: [
    {
      partId: 'part-001',
      partNumber: 'FL-820S',
      partName: 'Motorcraft Oil Filter',
      quantityOnHand: 45,
      quantitySold: 125,
      turnoverRate: 12.5,
      daysOfSupply: 10,
      recommendation: 'Maintain current stock levels',
    },
  ],
  stockoutParts: [],
  overstockedParts: [],
  deadStock: [],
  reorderRecommendations: [
    {
      partId: 'part-002',
      partNumber: 'BRF-1234',
      partName: 'Premium Brake Pad Set - Front',
      currentStock: 12,
      reorderPoint: 8,
      recommendedOrderQuantity: 20,
      estimatedCost: 840,
      priority: 'medium',
      supplier: 'Auto Parts Warehouse',
      leadTimeDays: 5,
    },
  ],
  generatedDate: new Date('2024-12-01'),
};

// ============================================================================
// SETTINGS SAMPLE DATA
// ============================================================================

export const sampleAutomotiveSettings: AutomotiveSettings = {
  settingsId: 'settings-001',
  defaultRosterTemplate: 'template-001',
  defaultShiftDuration: 8,
  overtimeThreshold: 40,
  commissionPaymentSchedule: 'monthly',
  inventoryValuationMethod: 'FIFO',
  autoReorderEnabled: false,
  lowStockAlertThreshold: 20,
  defaultMarkupPercentage: 30,
  enableShiftSwaps: true,
  maxShiftSwapsPerMonth: 4,
  requireManagerApproval: true,
  lastUpdatedDate: new Date('2024-11-01'),
  lastUpdatedBy: 'admin',
};
