import type {
  ResignationLetter,
  TerminationNotice,
  OffboardingInstance,
  KnowledgeTransfer,
  ExitInterview,
  ExitSurvey,
  FinalSettlement,
  AlumniRecord,
  OffboardingMetrics,
  OffboardingSettings,
} from './types';

// ============================================================================
// RESIGNATIONS
// ============================================================================

export const sampleResignations: ResignationLetter[] = [
  {
    id: 'resign_001',
    employeeId: 'emp_101',
    employeeName: 'John Smith',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    positionId: 'pos_senior_dev',
    positionTitle: 'Senior Software Developer',
    managerId: 'emp_mgr_001',
    managerName: 'Sarah Chen',
    submittedDate: '2024-12-01',
    lastWorkingDate: '2024-12-31',
    noticePeriodDays: 30,
    resignationType: 'resignation',
    reason: 'Better career opportunity',
    reasonCategory: 'better_opportunity',
    detailedReason: 'Accepted a senior engineering position at a tech startup with better growth potential and equity compensation.',
    newEmployer: 'TechStart Inc.',
    status: 'accepted',
    reviewedBy: 'Sarah Chen',
    reviewedDate: '2024-12-02',
    reviewComments: 'Regret to see John go. He has been an excellent performer.',
    counterOfferMade: true,
    counterOfferDetails: 'Offered 20% raise and promotion to Lead Developer',
    counterOfferResponse: 'declined',
    acceptedBy: 'HR Manager',
    acceptedDate: '2024-12-03',
    createdBy: 'John Smith',
    createdDate: '2024-12-01T10:00:00Z',
    lastModified: '2024-12-03T14:00:00Z',
  },
  {
    id: 'resign_002',
    employeeId: 'emp_102',
    employeeName: 'Emily Watson',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    positionId: 'pos_sales_mgr',
    positionTitle: 'Sales Manager',
    managerId: 'emp_mgr_002',
    managerName: 'Michael Rodriguez',
    submittedDate: '2024-11-15',
    lastWorkingDate: '2024-12-15',
    noticePeriodDays: 30,
    resignationType: 'resignation',
    reason: 'Relocation',
    reasonCategory: 'relocation',
    detailedReason: 'Moving to another state due to family reasons.',
    status: 'accepted',
    reviewedBy: 'Michael Rodriguez',
    reviewedDate: '2024-11-16',
    acceptedBy: 'HR Manager',
    acceptedDate: '2024-11-16',
    createdBy: 'Emily Watson',
    createdDate: '2024-11-15T09:00:00Z',
    lastModified: '2024-11-16T11:00:00Z',
  },
];

// ============================================================================
// TERMINATIONS
// ============================================================================

export const sampleTerminations: TerminationNotice[] = [
  {
    id: 'term_001',
    employeeId: 'emp_103',
    employeeName: 'Robert Taylor',
    departmentId: 'dept_ops',
    departmentName: 'Operations',
    positionId: 'pos_ops_coord',
    positionTitle: 'Operations Coordinator',
    terminationType: 'termination',
    terminationDate: '2024-11-20',
    effectiveDate: '2024-11-20',
    noticePeriodDays: 0,
    issuedBy: 'HR Director',
    issuedDate: '2024-11-20',
    reason: 'Performance issues',
    reasonCategory: 'performance',
    detailedJustification: 'Despite multiple warnings and performance improvement plans over 6 months, employee failed to meet minimum performance standards.',
    severancePay: 5000,
    severanceDetails: '1 month base salary',
    legalReview: true,
    legalReviewedBy: 'Legal Counsel',
    legalReviewDate: '2024-11-19',
    legalComments: 'Termination is legally compliant. All documentation in order.',
    approvedBy: 'CEO',
    approvedDate: '2024-11-19',
    communicatedToEmployee: true,
    communicationDate: '2024-11-20',
    employeeAcknowledgement: true,
    acknowledgementDate: '2024-11-20',
    appealAllowed: false,
    createdBy: 'HR Director',
    createdDate: '2024-11-19T14:00:00Z',
  },
];

// ============================================================================
// OFFBOARDING INSTANCES
// ============================================================================

export const sampleOffboardingInstances: OffboardingInstance[] = [
  {
    id: 'off_001',
    offboardingCode: 'OFF-2024-001',
    employeeId: 'emp_101',
    employeeName: 'John Smith',
    employeeEmail: 'john.smith@company.com',
    departmentId: 'dept_eng',
    departmentName: 'Engineering',
    positionId: 'pos_senior_dev',
    positionTitle: 'Senior Software Developer',
    managerId: 'emp_mgr_001',
    managerName: 'Sarah Chen',
    hrContactId: 'emp_hr_001',
    hrContactName: 'Lisa Anderson',
    offboardingType: 'resignation',
    initiatedDate: '2024-12-01',
    lastWorkingDate: '2024-12-31',
    noticePeriodDays: 30,
    status: 'in_progress',
    currentPhase: 'knowledge_transfer',
    progress: 60,
    resignationId: 'resign_001',
    tasks: [
      {
        id: 'task_001',
        taskName: 'Complete handover documentation',
        description: 'Document all ongoing projects and responsibilities',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'John Smith',
        dueDate: '2024-12-20',
        phase: 'knowledge_transfer',
        status: 'in_progress',
        priority: 'critical',
        estimatedHours: 16,
        actualHours: 10,
        isMandatory: true,
      },
      {
        id: 'task_002',
        taskName: 'Conduct knowledge transfer sessions',
        description: 'Train replacement on key projects and processes',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'John Smith',
        dueDate: '2024-12-25',
        phase: 'knowledge_transfer',
        status: 'in_progress',
        priority: 'high',
        estimatedHours: 20,
        isMandatory: true,
      },
      {
        id: 'task_003',
        taskName: 'Return company laptop',
        description: 'Return MacBook Pro and accessories to IT',
        assignedTo: 'employee',
        assignedRole: 'employee',
        assignedPerson: 'John Smith',
        dueDate: '2024-12-31',
        phase: 'exit_formalities',
        status: 'pending',
        priority: 'critical',
        estimatedHours: 1,
        isMandatory: true,
      },
      {
        id: 'task_004',
        taskName: 'Complete exit interview',
        description: 'Schedule and complete exit interview with HR',
        assignedTo: 'hr',
        assignedRole: 'hr',
        assignedPerson: 'Lisa Anderson',
        dueDate: '2024-12-30',
        phase: 'exit_formalities',
        status: 'pending',
        priority: 'high',
        estimatedHours: 1,
        isMandatory: true,
      },
    ],
    completedTasks: 6,
    totalTasks: 10,
    overdueTasks: 0,
    equipmentReturns: [
      {
        id: 'equip_001',
        offboardingId: 'off_001',
        equipmentId: 'equip_laptop_001',
        equipmentType: 'laptop',
        equipmentName: 'MacBook Pro 16"',
        serialNumber: 'MBP-2023-001',
        assetTag: 'ASSET-1001',
        assignedDate: '2023-01-15',
        dueReturnDate: '2024-12-31',
        status: 'pending',
        location: 'Employee possession',
      },
      {
        id: 'equip_002',
        offboardingId: 'off_001',
        equipmentId: 'equip_monitor_001',
        equipmentType: 'monitor',
        equipmentName: 'Dell 27" 4K Monitor',
        assetTag: 'ASSET-1002',
        assignedDate: '2023-01-15',
        dueReturnDate: '2024-12-31',
        status: 'pending',
      },
    ],
    accessRevocations: [
      {
        id: 'access_001',
        offboardingId: 'off_001',
        accessId: 'acc_email_001',
        accessType: 'email',
        systemName: 'Corporate Email',
        accountId: 'john.smith@company.com',
        grantedDate: '2023-01-15',
        scheduledRevocationDate: '2024-12-31',
        status: 'pending',
      },
      {
        id: 'access_002',
        offboardingId: 'off_001',
        accessId: 'acc_github_001',
        accessType: 'vcs',
        systemName: 'GitHub',
        accountId: 'johnsmith-dev',
        grantedDate: '2023-01-15',
        scheduledRevocationDate: '2024-12-31',
        status: 'pending',
      },
    ],
    clearances: [
      {
        id: 'clear_001',
        offboardingId: 'off_001',
        departmentId: 'dept_it',
        departmentName: 'IT Department',
        clearanceType: 'it',
        assignedTo: 'emp_it_001',
        assignedToName: 'IT Manager',
        dueDate: '2024-12-31',
        status: 'pending',
      },
      {
        id: 'clear_002',
        offboardingId: 'off_001',
        departmentId: 'dept_hr',
        departmentName: 'HR Department',
        clearanceType: 'hr',
        assignedTo: 'emp_hr_001',
        assignedToName: 'Lisa Anderson',
        dueDate: '2024-12-31',
        status: 'pending',
      },
      {
        id: 'clear_003',
        offboardingId: 'off_001',
        departmentId: 'dept_finance',
        departmentName: 'Finance Department',
        clearanceType: 'finance',
        assignedTo: 'emp_fin_001',
        assignedToName: 'Finance Manager',
        dueDate: '2024-12-31',
        status: 'pending',
      },
    ],
    rehireEligibility: 'eligible',
    rehireNotes: 'Excellent performer. Resigned for better opportunity. Eligible for rehire.',
    createdBy: 'HR System',
    createdDate: '2024-12-01T10:30:00Z',
    lastModified: '2024-12-13T09:00:00Z',
  },
  {
    id: 'off_002',
    offboardingCode: 'OFF-2024-002',
    employeeId: 'emp_102',
    employeeName: 'Emily Watson',
    employeeEmail: 'emily.watson@company.com',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    positionId: 'pos_sales_mgr',
    positionTitle: 'Sales Manager',
    managerId: 'emp_mgr_002',
    managerName: 'Michael Rodriguez',
    hrContactId: 'emp_hr_001',
    hrContactName: 'Lisa Anderson',
    offboardingType: 'resignation',
    initiatedDate: '2024-11-15',
    lastWorkingDate: '2024-12-15',
    noticePeriodDays: 30,
    status: 'completed',
    currentPhase: 'post_exit',
    progress: 100,
    resignationId: 'resign_002',
    tasks: [],
    completedTasks: 12,
    totalTasks: 12,
    overdueTasks: 0,
    equipmentReturns: [],
    accessRevocations: [],
    clearances: [],
    rehireEligibility: 'eligible',
    createdBy: 'HR System',
    createdDate: '2024-11-15T09:30:00Z',
    lastModified: '2024-12-15T17:00:00Z',
  },
];

// ============================================================================
// KNOWLEDGE TRANSFERS
// ============================================================================

export const sampleKnowledgeTransfers: KnowledgeTransfer[] = [
  {
    id: 'kt_001',
    offboardingId: 'off_001',
    employeeId: 'emp_101',
    employeeName: 'John Smith',
    successorId: 'emp_201',
    successorName: 'Alex Kumar',
    managerId: 'emp_mgr_001',
    managerName: 'Sarah Chen',
    startDate: '2024-12-05',
    targetCompletionDate: '2024-12-25',
    status: 'in_progress',
    progress: 65,
    sessions: [
      {
        id: 'session_001',
        sessionDate: '2024-12-05',
        duration: 2,
        topics: ['Project A overview', 'Codebase structure', 'Development workflow'],
        attendees: ['John Smith', 'Alex Kumar', 'Sarah Chen'],
        keyPoints: 'Covered high-level architecture and current sprint status',
        actionItems: ['Alex to review documentation', 'Schedule deep-dive on authentication module'],
        nextSessionDate: '2024-12-08',
        completedBy: 'John Smith',
      },
      {
        id: 'session_002',
        sessionDate: '2024-12-08',
        duration: 3,
        topics: ['Authentication module', 'API integration', 'Database schema'],
        attendees: ['John Smith', 'Alex Kumar'],
        keyPoints: 'Detailed walkthrough of auth flow and database relationships',
        actionItems: ['Alex to set up local environment', 'Review API documentation'],
        nextSessionDate: '2024-12-12',
        completedBy: 'John Smith',
      },
    ],
    documentation: [
      {
        id: 'doc_001',
        documentType: 'process_doc',
        title: 'Deployment Process Guide',
        description: 'Step-by-step guide for deploying to production',
        fileUrl: '/docs/deployment-guide.pdf',
        createdDate: '2024-12-06',
        reviewedBy: 'Alex Kumar',
        reviewedDate: '2024-12-07',
        status: 'approved',
      },
      {
        id: 'doc_002',
        documentType: 'contact_list',
        title: 'Key Stakeholder Contacts',
        description: 'List of important contacts for each project',
        fileUrl: '/docs/contacts.xlsx',
        createdDate: '2024-12-07',
        status: 'reviewed',
      },
    ],
    handoverChecklist: [
      {
        id: 'item_001',
        category: 'projects',
        itemName: 'Project A - User Authentication',
        description: 'Complete ownership transfer of authentication module',
        handoverTo: 'emp_201',
        handoverToName: 'Alex Kumar',
        priority: 'critical',
        status: 'completed',
        completedDate: '2024-12-10',
      },
      {
        id: 'item_002',
        category: 'projects',
        itemName: 'Project B - Payment Gateway',
        description: 'Transfer payment integration knowledge',
        handoverTo: 'emp_201',
        handoverToName: 'Alex Kumar',
        priority: 'high',
        status: 'in_progress',
      },
      {
        id: 'item_003',
        category: 'responsibilities',
        itemName: 'Code review responsibilities',
        description: 'Transfer code review ownership for team PRs',
        handoverTo: 'emp_201',
        handoverToName: 'Alex Kumar',
        priority: 'medium',
        status: 'pending',
      },
    ],
    completedItems: 7,
    totalItems: 12,
  },
];

// ============================================================================
// EXIT INTERVIEWS
// ============================================================================

export const sampleExitInterviews: ExitInterview[] = [
  {
    id: 'exit_int_001',
    offboardingId: 'off_002',
    employeeId: 'emp_102',
    employeeName: 'Emily Watson',
    scheduledDate: '2024-12-14',
    conductedDate: '2024-12-14T14:00:00Z',
    conductedBy: 'emp_hr_001',
    conductedByName: 'Lisa Anderson',
    interviewType: 'in_person',
    status: 'completed',
    duration: 45,
    questions: [
      {
        question: 'What is your primary reason for leaving?',
        questionType: 'text',
        answer: 'Relocating to another state for family reasons',
        category: 'other',
      },
      {
        question: 'How satisfied were you with your role?',
        questionType: 'rating',
        answer: '8/10',
        rating: 8,
        category: 'job_satisfaction',
      },
      {
        question: 'How would you rate your manager?',
        questionType: 'rating',
        answer: '9/10',
        rating: 9,
        category: 'management',
      },
      {
        question: 'Were you satisfied with your compensation?',
        questionType: 'yes_no',
        answer: 'Yes',
        category: 'compensation',
      },
      {
        question: 'What could we have done better?',
        questionType: 'text',
        answer: 'More remote work flexibility would have been helpful',
        category: 'work_life_balance',
      },
    ],
    overallSentiment: 'positive',
    wouldRecommend: true,
    recommendationScore: 9,
    openToRehire: true,
    keyTakeaways: [
      'Employee leaving for personal reasons, not company-related',
      'Highly satisfied with management and team',
      'Desires more remote work flexibility',
    ],
    actionItems: ['Review remote work policy for sales team'],
    confidential: false,
    notes: 'Great employee. Regret to lose due to relocation.',
  },
];

// ============================================================================
// EXIT SURVEYS
// ============================================================================

export const sampleExitSurveys: ExitSurvey[] = [
  {
    id: 'exit_survey_001',
    offboardingId: 'off_002',
    employeeId: 'emp_102',
    employeeName: 'Emily Watson',
    sentDate: '2024-12-15',
    completedDate: '2024-12-16T10:00:00Z',
    status: 'completed',
    surveyType: 'standard',
    isAnonymous: false,
    questions: [
      {
        questionId: 'q1',
        question: 'Overall, how satisfied were you working at our company?',
        questionType: 'rating',
        category: 'overall',
        rating: 8,
      },
      {
        questionId: 'q2',
        question: 'How likely are you to recommend our company as a great place to work?',
        questionType: 'scale',
        category: 'nps',
        rating: 9,
      },
      {
        questionId: 'q3',
        question: 'Would you consider returning to work here in the future?',
        questionType: 'yes_no',
        category: 'rehire',
        answer: 'Yes',
      },
    ],
    overallRating: 8,
    wouldReturn: true,
    wouldRecommend: true,
    npsScore: 9,
    comments: 'Great company and team. Would love to return if circumstances change.',
  },
];

// ============================================================================
// FINAL SETTLEMENTS
// ============================================================================

export const sampleFinalSettlements: FinalSettlement[] = [
  {
    id: 'settlement_001',
    offboardingId: 'off_002',
    employeeId: 'emp_102',
    employeeName: 'Emily Watson',
    employeeBankAccount: '****5678',
    calculationDate: '2024-12-10',
    paymentDueDate: '2024-12-20',
    paymentDate: '2024-12-20',
    status: 'paid',
    components: [],
    earnings: [
      {
        earningType: 'salary',
        description: 'Salary for December (pro-rated)',
        amount: 3500,
        isTaxable: true,
        calculation: 'Monthly salary $7000 / 30 days * 15 days',
      },
      {
        earningType: 'leave_encashment',
        description: 'Unused leave balance encashment',
        amount: 1200,
        isTaxable: true,
        calculation: '6 days * $200 per day',
      },
      {
        earningType: 'bonus',
        description: 'Pro-rated Q4 bonus',
        amount: 2000,
        isTaxable: true,
        calculation: 'Quarterly bonus $4000 * 50%',
      },
    ],
    deductions: [
      {
        deductionType: 'tax',
        description: 'Income tax',
        amount: 1350,
        calculation: '20% of taxable earnings',
      },
    ],
    totalEarnings: 6700,
    totalDeductions: 1350,
    netPayable: 5350,
    paymentMethod: 'bank_transfer',
    paymentReference: 'TXN-2024-1220-001',
    calculatedBy: 'Finance Team',
    approvedBy: 'Finance Manager',
    approvedDate: '2024-12-15',
    paidBy: 'Finance Team',
    notes: 'All calculations verified. Payment processed successfully.',
  },
];

// ============================================================================
// ALUMNI RECORDS
// ============================================================================

export const sampleAlumniRecords: AlumniRecord[] = [
  {
    id: 'alumni_001',
    employeeId: 'emp_102',
    employeeName: 'Emily Watson',
    employeeEmail: 'emily.watson@company.com',
    personalEmail: 'emily.watson.personal@gmail.com',
    phoneNumber: '+1-555-0102',
    linkedInProfile: 'https://linkedin.com/in/emilywatson',
    departmentId: 'dept_sales',
    departmentName: 'Sales',
    lastPosition: 'Sales Manager',
    joinDate: '2022-03-01',
    exitDate: '2024-12-15',
    tenure: 33,
    exitReason: 'resignation',
    status: 'active',
    optedInDate: '2024-12-15',
    willingToMentor: true,
    willingToRefer: true,
    interestedInReturning: true,
    lastContactDate: '2024-12-15',
    events: [
      {
        eventType: 'contact',
        eventDate: '2024-12-15',
        description: 'Initial alumni opt-in',
        participated: true,
        notes: 'Expressed interest in staying connected',
      },
    ],
  },
];

// ============================================================================
// ANALYTICS & METRICS
// ============================================================================

export const sampleOffboardingMetrics: OffboardingMetrics = {
  totalOffboarding: 25,
  activeOffboarding: 8,
  completedOffboarding: 15,
  averageCompletionTime: 32,
  averageNoticePeriod: 28,
  offboardingByType: [
    { type: 'resignation', count: 15, percentage: 60 },
    { type: 'termination', count: 5, percentage: 20 },
    { type: 'retirement', count: 3, percentage: 12 },
    { type: 'contract_end', count: 2, percentage: 8 },
  ],
  offboardingByDepartment: [
    { departmentId: 'dept_sales', departmentName: 'Sales', offboardingCount: 8, turnoverRate: 15, avgTenure: 24 },
    { departmentId: 'dept_eng', departmentName: 'Engineering', offboardingCount: 6, turnoverRate: 10, avgTenure: 36 },
    { departmentId: 'dept_hr', departmentName: 'HR', offboardingCount: 3, turnoverRate: 8, avgTenure: 42 },
  ],
  turnoverRate: 12.5,
  voluntaryTurnover: 60,
  involuntaryTurnover: 20,
  retirementRate: 12,
  avgTenure: 32,
  topExitReasons: [
    { reason: 'Better opportunity', count: 8, percentage: 32, trend: 'increasing' },
    { reason: 'Career growth', count: 5, percentage: 20, trend: 'stable' },
    { reason: 'Compensation', count: 4, percentage: 16, trend: 'decreasing' },
    { reason: 'Work-life balance', count: 3, percentage: 12, trend: 'stable' },
    { reason: 'Relocation', count: 2, percentage: 8, trend: 'stable' },
  ],
  rehireEligibilityStats: {
    eligible: 18,
    notEligible: 4,
    restricted: 2,
    underReview: 1,
  },
  exitInterviewParticipation: 88,
  exitSurveyResponse: 76,
  averageExitRating: 7.8,
  npsScore: 42,
  equipmentReturnRate: 96,
  clearanceCompletionRate: 92,
  knowledgeTransferCompletionRate: 85,
  alumniEngagementRate: 68,
  costPerOffboarding: 2500,
  retentionRiskDepartments: ['Sales', 'Engineering'],
};

// ============================================================================
// SETTINGS
// ============================================================================

export const sampleOffboardingSettings: OffboardingSettings = {
  defaultNoticePeriod: 30,
  autoInitiateOffboarding: true,
  requireExitInterview: true,
  requireExitSurvey: true,
  exitSurveyAnonymous: false,
  exitSurveyExpiry: 30,
  sendExitSurveyAfter: 0,
  requireKnowledgeTransfer: true,
  knowledgeTransferDuration: 14,
  autoRevokeAccessOnExit: true,
  accessRevocationLeadTime: 0,
  autoCreateAlumniRecord: true,
  alumniOptInRequired: false,
  equipmentReturnReminder: 7,
  clearanceReminderFrequency: 'weekly',
  finalSettlementDays: 45,
  allowCounterOffer: true,
  counterOfferApprovalRequired: true,
  notificationEmail: 'hr@company.com',
  hrNotificationEmail: 'hr@company.com',
  itNotificationEmail: 'it@company.com',
  financeNotificationEmail: 'finance@company.com',
  customFields: [
    {
      fieldName: 'exit_reason_detail',
      fieldLabel: 'Detailed Exit Reason',
      fieldType: 'textarea',
      isRequired: false,
    },
  ],
};
