"use client";
import { useState, useEffect, useCallback } from 'react';
import { Volunteer, FieldMission, Donor, NonprofitSettings, NonprofitAlert } from '../types';
import { VolunteerService, MissionService, DonorService, NonprofitSettingsService, AlertsService } from '../services';
import { sampleVolunteers, sampleMissions, sampleDonors, sampleNonprofitSettings } from '../data';
interface Toast { type: 'success' | 'error' | 'info'; message: string; }
export const useNonprofit = () => { const [volunteers, setVolunteers] = useState<Volunteer[]>([]); const [missions, setMissions] = useState<FieldMission[]>([]); const [donors, setDonors] = useState<Donor[]>([]); const [settings, setSettings] = useState<NonprofitSettings | null>(null); const [alerts, setAlerts] = useState<NonprofitAlert[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [toasts, setToasts] = useState<Toast[]>([]);
const addToast = useCallback((toast: Toast) => { setToasts(prev => [...prev, toast]); setTimeout(() => setToasts(prev => prev.slice(1)), 5000); }, []);
const loadAllData = useCallback(async () => { setLoading(true); try { const [volData, missionData, donorData, settingsData] = await Promise.all([VolunteerService.getAll(), MissionService.getAll(), DonorService.getAll(), NonprofitSettingsService.get()]); if (volData.length === 0) { for (const v of sampleVolunteers) await VolunteerService.create(v); setVolunteers(sampleVolunteers); } else setVolunteers(volData); if (missionData.length === 0) { for (const m of sampleMissions) await MissionService.create(m); setMissions(sampleMissions); } else setMissions(missionData); if (donorData.length === 0) { for (const d of sampleDonors) await DonorService.create(d); setDonors(sampleDonors); } else setDonors(donorData); if (!settingsData) { await NonprofitSettingsService.update(sampleNonprofitSettings); setSettings(sampleNonprofitSettings); } else setSettings(settingsData); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to load data'); addToast({ type: 'error', message: 'Failed to load nonprofit data' }); } finally { setLoading(false); } }, [addToast]);
useEffect(() => { loadAllData(); }, [loadAllData]);
const createVolunteer = async (data: Partial<Volunteer>) => { setLoading(true); try { const vol = await VolunteerService.create(data); setVolunteers(await VolunteerService.getAll()); addToast({ type: 'success', message: 'Volunteer created' }); return vol; } catch (err) { addToast({ type: 'error', message: 'Failed to create volunteer' }); throw err; } finally { setLoading(false); } };
const createMission = async (data: Partial<FieldMission>) => { setLoading(true); try { const mission = await MissionService.create(data); setMissions(await MissionService.getAll()); addToast({ type: 'success', message: 'Mission created' }); return mission; } catch (err) { addToast({ type: 'error', message: 'Failed to create mission' }); throw err; } finally { setLoading(false); } };
const createDonor = async (data: Partial<Donor>) => { setLoading(true); try { const donor = await DonorService.create(data); setDonors(await DonorService.getAll()); addToast({ type: 'success', message: 'Donor created' }); return donor; } catch (err) { addToast({ type: 'error', message: 'Failed to create donor' }); throw err; } finally { setLoading(false); } };
return { volunteers, missions, donors, settings, alerts, loading, error, toasts, createVolunteer, createMission, createDonor, loadAllData }; };
