// @ts-nocheck — Dev/demo seed data, intentionally loose-typed.
import type {
  MobileAppConfig,
  PushNotification,
  OfflineConfig,
  BiometricConfig,
  GPSAttendanceConfig,
  MobileApproval,
  MobileTimesheet,
  QuickAction,
  VoiceCommandConfig,
  MobileAnalytics,
  ChatConversation,
  MobileUserProfile,
  MobileAppSettings,
} from './types';

// Sample Mobile App Configuration
export const sampleMobileAppConfig: MobileAppConfig = {
  configId: 'config-001',
  appName: 'AuraOS Mobile',
  appVersion: '2.5.0',
  minimumSupportedVersion: '2.0.0',
  platforms: [
    {
      platform: 'ios',
      enabled: true,
      appStoreUrl: 'https://apps.apple.com/app/auraos',
      bundleId: 'com.auraos.mobile',
      currentVersion: '2.5.0',
      minimumVersion: '2.0.0',
      buildNumber: 250,
    },
    {
      platform: 'android',
      enabled: true,
      appStoreUrl: 'https://play.google.com/store/apps/details?id=com.auraos.mobile',
      bundleId: 'com.auraos.mobile',
      currentVersion: '2.5.0',
      minimumVersion: '2.0.0',
      buildNumber: 250,
    },
  ],
  features: [
    {
      featureId: 'feature-001',
      featureName: 'Biometric Login',
      enabled: true,
      platforms: ['ios', 'android'],
      rolloutPercentage: 100,
      enabledDate: new Date('2024-01-15'),
    },
    {
      featureId: 'feature-002',
      featureName: 'Offline Mode',
      enabled: true,
      platforms: ['ios', 'android'],
      rolloutPercentage: 100,
      enabledDate: new Date('2024-02-01'),
    },
    {
      featureId: 'feature-003',
      featureName: 'Voice Commands',
      enabled: true,
      platforms: ['ios', 'android'],
      rolloutPercentage: 50,
      enabledDate: new Date('2024-11-01'),
    },
  ],
  maintenanceMode: false,
  forceUpdateRequired: false,
  createdDate: new Date('2023-01-01'),
  lastUpdatedDate: new Date('2024-12-01'),
  lastUpdatedBy: 'admin',
};

// Sample Push Notifications
export const samplePushNotifications: PushNotification[] = [
  {
    notificationId: 'notif-001',
    notificationType: 'leave_approval',
    title: 'Leave Request Pending',
    body: 'You have 3 leave requests pending approval',
    priority: 'high',
    targetType: 'user',
    targetIds: ['manager-001', 'manager-002'],
    sendImmediately: false,
    scheduledDate: new Date('2024-12-14T09:00:00'),
    platforms: ['ios', 'android'],
    iosConfig: {
      badge: 3,
      sound: 'default',
      category: 'APPROVAL_REQUEST',
    },
    androidConfig: {
      channelId: 'approvals',
      sound: 'notification',
      icon: 'ic_notification',
      color: '#4F46E5',
      vibrate: true,
    },
    data: {
      screen: 'approvals',
      type: 'leave',
    },
    actionButtons: [
      {
        actionId: 'approve_all',
        actionTitle: 'Approve All',
        actionType: 'deep_link',
        actionData: 'auraos://approvals/bulk-approve',
      },
      {
        actionId: 'view',
        actionTitle: 'View',
        actionType: 'deep_link',
        actionData: 'auraos://approvals',
      },
    ],
    sentCount: 0,
    deliveredCount: 0,
    openedCount: 0,
    openRate: 0,
    status: 'scheduled',
    createdBy: 'system',
    createdByName: 'System',
    createdDate: new Date('2024-12-13'),
  },
  {
    notificationId: 'notif-002',
    notificationType: 'payslip',
    title: 'December Payslip Available',
    body: 'Your payslip for December 2024 is now available',
    priority: 'medium',
    targetType: 'all',
    sendImmediately: false,
    scheduledDate: new Date('2024-12-31T10:00:00'),
    platforms: ['ios', 'android'],
    sentCount: 1250,
    deliveredCount: 1198,
    openedCount: 856,
    openRate: 71.5,
    status: 'sent',
    sentDate: new Date('2024-11-30T10:00:00'),
    createdBy: 'system',
    createdByName: 'System',
    createdDate: new Date('2024-11-29'),
  },
  {
    notificationId: 'notif-003',
    notificationType: 'event_reminder',
    title: 'Team Meeting in 30 Minutes',
    body: 'Quarterly Planning Meeting starts at 2:00 PM',
    priority: 'high',
    targetType: 'department',
    targetIds: ['engineering', 'product'],
    sendImmediately: true,
    platforms: ['ios', 'android'],
    imageUrl: '/events/quarterly-planning.jpg',
    sentCount: 45,
    deliveredCount: 44,
    openedCount: 38,
    openRate: 86.4,
    status: 'sent',
    sentDate: new Date('2024-12-13T13:30:00'),
    createdBy: 'admin-001',
    createdByName: 'Sarah Wilson',
    createdDate: new Date('2024-12-13T13:30:00'),
  },
];

// Sample Offline Configuration
export const sampleOfflineConfig: OfflineConfig = {
  configId: 'offline-001',
  offlineModeEnabled: true,
  syncStrategy: 'on_wifi',
  maxOfflineDuration: 72,
  enabledModules: [
    {
      moduleId: 'module-001',
      moduleName: 'Timesheets',
      enabled: true,
      dataTypes: ['timesheet_entries', 'projects', 'tasks'],
      maxCacheAge: 24,
    },
    {
      moduleId: 'module-002',
      moduleName: 'Expenses',
      enabled: true,
      dataTypes: ['expense_claims', 'receipts'],
      maxCacheAge: 48,
    },
    {
      moduleId: 'module-003',
      moduleName: 'Attendance',
      enabled: true,
      dataTypes: ['check_ins', 'check_outs'],
      maxCacheAge: 12,
    },
    {
      moduleId: 'module-004',
      moduleName: 'Leave',
      enabled: true,
      dataTypes: ['leave_balance', 'leave_applications'],
      maxCacheAge: 24,
    },
  ],
  cacheSize: 100,
  autoSync: true,
  syncOnWifi: true,
  conflictResolution: 'latest_wins',
};

// Sample Biometric Configuration
export const sampleBiometricConfig: BiometricConfig = {
  configId: 'bio-001',
  biometricEnabled: true,
  supportedMethods: ['fingerprint', 'face_id'],
  fallbackToPassword: true,
  maxAttempts: 3,
  lockoutDuration: 5,
  requireBiometricOnAppLaunch: true,
  requireBiometricForSensitiveActions: true,
};

// Sample GPS Attendance Configuration
export const sampleGPSAttendanceConfig: GPSAttendanceConfig = {
  configId: 'gps-001',
  gpsEnabled: true,
  requireGPS: true,
  geofencingEnabled: true,
  locations: [
    {
      locationId: 'loc-001',
      locationName: 'Headquarters',
      address: '123 Corporate Blvd, San Francisco, CA 94105',
      latitude: 37.7749,
      longitude: -122.4194,
      radius: 200,
      isActive: true,
    },
    {
      locationId: 'loc-002',
      locationName: 'East Coast Office',
      address: '456 Business Ave, New York, NY 10001',
      latitude: 40.7128,
      longitude: -74.006,
      radius: 150,
      isActive: true,
    },
    {
      locationId: 'loc-003',
      locationName: 'Austin Branch',
      address: '789 Tech Street, Austin, TX 78701',
      latitude: 30.2672,
      longitude: -97.7431,
      radius: 100,
      isActive: true,
    },
  ],
  accuracyThreshold: 50,
  mockLocationDetection: true,
  allowCheckInOutsideGeofence: false,
};

// Sample Mobile Approvals
export const sampleMobileApprovals: MobileApproval[] = [
  {
    approvalId: 'approval-001',
    approvalType: 'leave',
    requestId: 'leave-req-145',
    requestTitle: 'Annual Leave - 5 days',
    requestedBy: 'emp-123',
    requestedByName: 'John Smith',
    requestedByPhoto: '/avatars/john-smith.jpg',
    requestDate: new Date('2024-12-10'),
    priority: 'medium',
    status: 'pending',
    approverId: 'manager-001',
    approverName: 'Sarah Wilson',
    dueDate: new Date('2024-12-15'),
    summary: 'Annual leave from Dec 20-24, 2024',
    duration: '5 days',
    canApprove: true,
    canReject: true,
    canEscalate: false,
    requiresComment: false,
    workflowStage: 1,
    totalStages: 1,
    metadata: {
      leaveType: 'Annual Leave',
      startDate: '2024-12-20',
      endDate: '2024-12-24',
      reason: 'Family vacation',
    },
  },
  {
    approvalId: 'approval-002',
    approvalType: 'expense',
    requestId: 'expense-req-289',
    requestTitle: 'Business Travel Expenses',
    requestedBy: 'emp-456',
    requestedByName: 'Emily Chen',
    requestedByPhoto: '/avatars/emily-chen.jpg',
    requestDate: new Date('2024-12-11'),
    priority: 'high',
    status: 'pending',
    approverId: 'manager-001',
    approverName: 'Sarah Wilson',
    dueDate: new Date('2024-12-14'),
    summary: 'Client meeting expenses in New York',
    amount: 1250.75,
    currency: 'USD',
    canApprove: true,
    canReject: true,
    canEscalate: true,
    requiresComment: false,
    workflowStage: 1,
    totalStages: 2,
    metadata: {
      category: 'Travel',
      items: 5,
      hasReceipts: true,
    },
  },
  {
    approvalId: 'approval-003',
    approvalType: 'timesheet',
    requestId: 'timesheet-req-342',
    requestTitle: 'Weekly Timesheet',
    requestedBy: 'emp-789',
    requestedByName: 'Michael Rodriguez',
    requestedByPhoto: '/avatars/michael-rodriguez.jpg',
    requestDate: new Date('2024-12-13'),
    priority: 'medium',
    status: 'pending',
    approverId: 'manager-001',
    approverName: 'Sarah Wilson',
    dueDate: new Date('2024-12-16'),
    summary: 'Week of Dec 9-15, 2024',
    duration: '42 hours',
    canApprove: true,
    canReject: true,
    canEscalate: false,
    requiresComment: false,
    workflowStage: 1,
    totalStages: 1,
    metadata: {
      regularHours: 40,
      overtimeHours: 2,
      projects: 3,
    },
  },
];

// Sample Mobile Timesheets
export const sampleMobileTimesheets: MobileTimesheet[] = [
  {
    timesheetId: 'timesheet-001',
    userId: 'emp-001',
    userName: 'Current User',
    periodStart: new Date('2024-12-09'),
    periodEnd: new Date('2024-12-15'),
    status: 'draft',
    entries: [
      {
        entryId: 'entry-001',
        date: new Date('2024-12-09'),
        projectId: 'proj-001',
        projectName: 'Mobile App Enhancement',
        taskId: 'task-001',
        taskName: 'Push Notifications',
        hours: 8,
        isOvertime: false,
        description: 'Implemented push notification system',
      },
      {
        entryId: 'entry-002',
        date: new Date('2024-12-10'),
        projectId: 'proj-001',
        projectName: 'Mobile App Enhancement',
        taskId: 'task-002',
        taskName: 'Offline Mode',
        hours: 8,
        isOvertime: false,
        description: 'Developed offline sync functionality',
      },
      {
        entryId: 'entry-003',
        date: new Date('2024-12-11'),
        projectId: 'proj-002',
        projectName: 'Client Portal',
        taskId: 'task-003',
        taskName: 'Dashboard',
        hours: 8,
        isOvertime: false,
        description: 'Built analytics dashboard',
      },
      {
        entryId: 'entry-004',
        date: new Date('2024-12-12'),
        projectId: 'proj-001',
        projectName: 'Mobile App Enhancement',
        taskId: 'task-004',
        taskName: 'Testing',
        hours: 10,
        isOvertime: true,
        description: 'End-to-end testing',
      },
    ],
    totalHours: 42,
    regularHours: 40,
    overtimeHours: 2,
    canEdit: true,
    canSubmit: true,
  },
];

// Sample Quick Actions
export const sampleQuickActions: QuickAction[] = [
  {
    actionId: 'action-001',
    actionName: 'Check In',
    actionType: 'check_in',
    icon: 'clock-in',
    color: '#10B981',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'attendance/check-in',
    deepLink: 'auraos://attendance/check-in',
    order: 1,
    platforms: ['ios', 'android'],
    requiredPermissions: ['location'],
  },
  {
    actionId: 'action-002',
    actionName: 'Check Out',
    actionType: 'check_out',
    icon: 'clock-out',
    color: '#EF4444',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'attendance/check-out',
    deepLink: 'auraos://attendance/check-out',
    order: 2,
    platforms: ['ios', 'android'],
    requiredPermissions: ['location'],
  },
  {
    actionId: 'action-003',
    actionName: 'Apply Leave',
    actionType: 'apply_leave',
    icon: 'calendar',
    color: '#3B82F6',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'leave/apply',
    deepLink: 'auraos://leave/apply',
    order: 3,
    platforms: ['ios', 'android'],
  },
  {
    actionId: 'action-004',
    actionName: 'Expense Claim',
    actionType: 'expense_claim',
    icon: 'receipt',
    color: '#F59E0B',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'expenses/new',
    deepLink: 'auraos://expenses/new',
    order: 4,
    platforms: ['ios', 'android'],
    requiredPermissions: ['camera', 'storage'],
  },
  {
    actionId: 'action-005',
    actionName: 'View Payslip',
    actionType: 'view_payslip',
    icon: 'dollar',
    color: '#8B5CF6',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'payroll/payslips',
    deepLink: 'auraos://payroll/payslips',
    order: 5,
    platforms: ['ios', 'android'],
  },
  {
    actionId: 'action-006',
    actionName: 'Timesheet',
    actionType: 'timesheet',
    icon: 'clock',
    color: '#06B6D4',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'timesheets/current',
    deepLink: 'auraos://timesheets/current',
    order: 6,
    platforms: ['ios', 'android'],
  },
  {
    actionId: 'action-007',
    actionName: 'Directory',
    actionType: 'directory',
    icon: 'users',
    color: '#EC4899',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'directory',
    deepLink: 'auraos://directory',
    order: 7,
    platforms: ['ios', 'android'],
  },
  {
    actionId: 'action-008',
    actionName: 'Approvals',
    actionType: 'approvals',
    icon: 'check-circle',
    color: '#14B8A6',
    enabled: true,
    requiresAuth: true,
    targetScreen: 'approvals',
    deepLink: 'auraos://approvals',
    order: 8,
    platforms: ['ios', 'android'],
  },
];

// Sample Voice Command Configuration
export const sampleVoiceCommandConfig: VoiceCommandConfig = {
  configId: 'voice-001',
  voiceEnabled: true,
  supportedLanguages: ['en-US', 'en-GB', 'es-ES', 'fr-FR', 'de-DE'],
  wakeWord: 'Hey AuraOS',
  confidenceThreshold: 0.7,
  enabledCommands: [
    {
      commandId: 'cmd-001',
      commandName: 'Check In',
      commandPhrases: ['check in', 'clock in', 'start work'],
      action: 'attendance/check-in',
      requiresConfirmation: true,
      enabled: true,
    },
    {
      commandId: 'cmd-002',
      commandName: 'Check Out',
      commandPhrases: ['check out', 'clock out', 'end work'],
      action: 'attendance/check-out',
      requiresConfirmation: true,
      enabled: true,
    },
    {
      commandId: 'cmd-003',
      commandName: 'Apply Leave',
      commandPhrases: ['apply leave', 'request leave', 'take time off'],
      action: 'leave/apply',
      requiresConfirmation: false,
      enabled: true,
    },
    {
      commandId: 'cmd-004',
      commandName: 'View Payslip',
      commandPhrases: ['show payslip', 'view payslip', 'my salary'],
      action: 'payroll/payslips',
      requiresConfirmation: false,
      enabled: true,
    },
  ],
};

// Sample Mobile Analytics
export const sampleMobileAnalytics: MobileAnalytics = {
  totalUsers: 1250,
  activeUsers: 985,
  dailyActiveUsers: 756,
  monthlyActiveUsers: 1180,
  platformDistribution: [
    { platform: 'ios', count: 625, percentage: 50 },
    { platform: 'android', count: 600, percentage: 48 },
    { platform: 'web', count: 25, percentage: 2 },
  ],
  versionDistribution: [
    { version: '2.5.0', count: 850, percentage: 68 },
    { version: '2.4.0', count: 280, percentage: 22.4 },
    { version: '2.3.0', count: 95, percentage: 7.6 },
    { version: '2.2.0', count: 25, percentage: 2 },
  ],
  featureUsage: [
    { feature: 'GPS Attendance', usageCount: 15420, uniqueUsers: 756 },
    { feature: 'Mobile Approvals', usageCount: 8934, uniqueUsers: 445 },
    { feature: 'Expense Claims', usageCount: 6785, uniqueUsers: 623 },
    { feature: 'Timesheets', usageCount: 5623, uniqueUsers: 512 },
    { feature: 'Leave Applications', usageCount: 4567, uniqueUsers: 892 },
    { feature: 'Payslip Access', usageCount: 3456, uniqueUsers: 1050 },
  ],
  averageSessionDuration: 8.5,
  crashRate: 0.15,
  appLoadTime: 1.2,
  apiResponseTime: 450,
  pushNotificationOpenRate: 68.5,
  biometricAdoptionRate: 78.3,
  offlineModeUsage: 45.2,
  topQuickActions: [
    { action: 'Check In', count: 8945 },
    { action: 'Check Out', count: 8723 },
    { action: 'Apply Leave', count: 4567 },
    { action: 'View Payslip', count: 3456 },
    { action: 'Approvals', count: 2890 },
  ],
  errorRate: 0.8,
  topErrors: [
    { error: 'Network timeout', count: 234 },
    { error: 'GPS unavailable', count: 156 },
    { error: 'Sync failed', count: 89 },
    { error: 'Image upload failed', count: 67 },
  ],
};

// Sample Chat Conversations
export const sampleChatConversations: ChatConversation[] = [
  {
    conversationId: 'conv-001',
    conversationType: 'direct',
    participants: [
      {
        userId: 'user-001',
        userName: 'Current User',
        isOnline: true,
      },
      {
        userId: 'user-002',
        userName: 'Sarah Wilson',
        userPhoto: '/avatars/sarah-wilson.jpg',
        isOnline: true,
        lastSeen: new Date('2024-12-13T14:30:00'),
      },
    ],
    lastMessage: {
      messageId: 'msg-001',
      conversationId: 'conv-001',
      senderId: 'user-002',
      senderName: 'Sarah Wilson',
      messageType: 'text',
      content: 'Thanks for the update! I approved your leave request.',
      timestamp: new Date('2024-12-13T14:30:00'),
      isEdited: false,
      readBy: ['user-001'],
      deliveredTo: ['user-001'],
    },
    unreadCount: 0,
    isPinned: true,
    isMuted: false,
    createdDate: new Date('2024-11-01'),
    lastActivityDate: new Date('2024-12-13T14:30:00'),
  },
  {
    conversationId: 'conv-002',
    conversationType: 'group',
    participants: [
      {
        userId: 'user-001',
        userName: 'Current User',
        isOnline: true,
      },
      {
        userId: 'user-003',
        userName: 'Engineering Team',
        isOnline: false,
        role: 'admin',
      },
    ],
    lastMessage: {
      messageId: 'msg-002',
      conversationId: 'conv-002',
      senderId: 'user-004',
      senderName: 'John Smith',
      messageType: 'text',
      content: 'Sprint planning meeting at 3 PM today',
      timestamp: new Date('2024-12-13T10:15:00'),
      isEdited: false,
      readBy: ['user-001'],
      deliveredTo: ['user-001', 'user-003', 'user-004'],
    },
    unreadCount: 3,
    isPinned: false,
    isMuted: false,
    createdDate: new Date('2024-09-01'),
    lastActivityDate: new Date('2024-12-13T10:15:00'),
  },
];

// Sample Mobile User Profile
export const sampleMobileUserProfile: MobileUserProfile = {
  userId: 'user-001',
  employeeId: 'EMP-001',
  firstName: 'John',
  lastName: 'Doe',
  fullName: 'John Doe',
  email: 'john.doe@company.com',
  phone: '+1-415-555-0100',
  profilePhoto: '/avatars/john-doe.jpg',
  designation: 'Senior Software Engineer',
  department: 'Engineering',
  location: 'San Francisco, CA',
  manager: 'manager-001',
  managerName: 'Sarah Wilson',
  preferences: {
    language: 'en-US',
    theme: 'auto',
    biometricEnabled: true,
    offlineModeEnabled: true,
    dataUsageMode: 'wifi_only',
    defaultView: 'dashboard',
    quickActions: ['check_in', 'check_out', 'apply_leave', 'expense_claim'],
  },
  notificationSettings: {
    pushEnabled: true,
    emailEnabled: true,
    smsEnabled: false,
    notificationTypes: {
      announcement: true,
      leave_approval: true,
      expense_approval: true,
      timesheet_reminder: true,
      attendance_alert: true,
      payslip: true,
      birthday: true,
      task_assignment: true,
      event_reminder: true,
      general: true,
    },
    quietHoursEnabled: true,
    quietHoursStart: '22:00',
    quietHoursEnd: '07:00',
  },
  privacySettings: {
    profileVisibility: 'colleagues',
    showOnlineStatus: true,
    showLastSeen: true,
    allowDirectMessages: true,
    shareLocation: false,
  },
  registeredDevices: [
    {
      deviceId: 'device-001',
      deviceName: 'iPhone 13 Pro',
      platform: 'ios',
      osVersion: '16.0',
      appVersion: '2.5.0',
      model: 'iPhone 13 Pro',
      manufacturer: 'Apple',
    },
  ],
};

// Sample Mobile App Settings
export const sampleMobileAppSettings: MobileAppSettings = {
  settingsId: 'settings-001',
  appConfig: sampleMobileAppConfig,
  pushNotificationConfig: {
    enabled: true,
    providers: [
      { provider: 'firebase', apiKey: 'firebase-api-key' },
      { provider: 'apns', apiKey: 'apns-api-key' },
    ],
    dailyLimit: 50,
  },
  offlineConfig: sampleOfflineConfig,
  biometricConfig: sampleBiometricConfig,
  gpsAttendanceConfig: sampleGPSAttendanceConfig,
  documentUploadConfig: {
    configId: 'doc-001',
    maxFileSize: 10,
    allowedFileTypes: ['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'],
    compressionEnabled: true,
    compressionQuality: 0.8,
    uploadOnWifiOnly: false,
    enableOCR: true,
  },
  voiceCommandConfig: sampleVoiceCommandConfig,
  chatConfig: {
    configId: 'chat-001',
    chatEnabled: true,
    allowDirectMessages: true,
    allowGroupChats: true,
    allowFileSharing: true,
    maxGroupSize: 100,
    messageRetentionDays: 90,
    enableReadReceipts: true,
    enableTypingIndicators: true,
    enablePushNotifications: true,
  },
  securitySettings: {
    sessionTimeout: 30,
    requirePasswordChange: true,
    passwordChangeDays: 90,
    allowScreenshots: false,
    allowCopyPaste: true,
    requireDeviceEncryption: true,
  },
  lastUpdatedDate: new Date('2024-12-01'),
  lastUpdatedBy: 'admin-001',
  lastUpdatedByName: 'System Administrator',
};
