'use client';

/**
 * @page Employment History
 * @description Track employee career progression with timeline view
 * @project AURA HCM Platform
 */

import React, { useState, useEffect } from 'react';
import { DataPage } from '@aura/ui';
import {
  History,
  TrendingUp,
  TrendingDown,
  ArrowRightLeft,
  User,
  Calendar,
  MapPin,
  Briefcase,
  Building,
  Award,
  DollarSign,
  CheckCircle,
  Clock,
  XCircle,
  Eye,
  Edit,
  Trash2,
  ThumbsUp,
  ThumbsDown,
  Plus,
} from 'lucide-react';
import { toast } from 'sonner';

// ========================================
// TYPES
// ========================================

interface EmploymentHistory {
  id: string;
  employeeId: string;
  changeType: 'PROMOTION' | 'DEMOTION' | 'TRANSFER' | 'LATERAL_MOVE' | 'NEW_HIRE' | 'TERMINATION' | 'REHIRE';
  effectiveDate: string;
  reason?: string;
  notes?: string;

  previousDepartment?: { id: string; name: string };
  previousJobProfile?: { id: string; title: string };
  previousGrade?: { id: string; name: string };
  previousLocation?: { id: string; name: string };
  previousManagerId?: string;
  previousSalary?: number;
  previousEmploymentType?: string;

  newDepartment?: { id: string; name: string };
  newJobProfile?: { id: string; title: string };
  newGrade?: { id: string; name: string };
  newLocation?: { id: string; name: string };
  newManagerId?: string;
  newSalary?: number;
  newEmploymentType?: string;

  requestedBy?: string;
  approvedBy?: string;
  approvedAt?: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'COMPLETED';
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

interface Stats {
  totalChanges: number;
  promotions: number;
  demotions: number;
  transfers: number;
  lateralMoves: number;
  newHires: number;
  terminations: number;
}

// ========================================
// CONSTANTS
// ========================================

const CHANGE_TYPES = [
  { value: 'PROMOTION', label: 'Promotion', icon: TrendingUp, color: 'bg-emerald-100 text-emerald-700 border-emerald-500' },
  { value: 'DEMOTION', label: 'Demotion', icon: TrendingDown, color: 'bg-red-100 text-red-700 border-red-500' },
  { value: 'TRANSFER', label: 'Transfer', icon: ArrowRightLeft, color: 'bg-blue-100 text-blue-700 border-blue-500' },
  { value: 'LATERAL_MOVE', label: 'Lateral Move', icon: ArrowRightLeft, color: 'bg-purple-100 text-purple-700 border-purple-500' },
  { value: 'NEW_HIRE', label: 'New Hire', icon: User, color: 'bg-green-100 text-green-700 border-green-500' },
  { value: 'TERMINATION', label: 'Termination', icon: XCircle, color: 'bg-gray-100 text-gray-700 border-gray-500' },
  { value: 'REHIRE', label: 'Rehire', icon: CheckCircle, color: 'bg-indigo-100 text-indigo-700 border-indigo-500' },
];

const STATUS_CONFIG = [
  { value: 'PENDING', label: 'Pending', color: 'bg-amber-100 text-amber-700', icon: Clock },
  { value: 'APPROVED', label: 'Approved', color: 'bg-green-100 text-green-700', icon: CheckCircle },
  { value: 'REJECTED', label: 'Rejected', color: 'bg-red-100 text-red-700', icon: XCircle },
  { value: 'COMPLETED', label: 'Completed', color: 'bg-blue-100 text-blue-700', icon: CheckCircle },
];

// ========================================
// MAIN COMPONENT
// ========================================

export default function EmploymentHistoryPage() {
  const [stats, setStats] = useState<Stats | null>(null);
  const [selectedChangeType, setSelectedChangeType] = useState<string | null>(null);
  const [selectedEmployee, setSelectedEmployee] = useState<string | null>(null);
  const [timelineView, setTimelineView] = useState(false);

  // ========================================
  // STATS CARDS
  // ========================================

  const StatsCards = () => {
    if (!stats) return null;

    return (
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-4 mb-6">
        {/* Total Changes */}
        <div className="bg-gradient-to-br from-indigo-500 to-indigo-600 rounded-xl p-4 text-white shadow-lg">
          <div className="text-xs font-medium opacity-90 mb-1">Total Changes</div>
          <div className="text-2xl font-bold">{stats.totalChanges}</div>
        </div>

        {/* Promotions */}
        <div className="bg-gradient-to-br from-emerald-500 to-emerald-600 rounded-xl p-4 text-white shadow-lg">
          <div className="text-xs font-medium opacity-90 mb-1">Promotions</div>
          <div className="text-2xl font-bold">{stats.promotions}</div>
        </div>

        {/* Transfers */}
        <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl p-4 text-white shadow-lg">
          <div className="text-xs font-medium opacity-90 mb-1">Transfers</div>
          <div className="text-2xl font-bold">{stats.transfers}</div>
        </div>

        {/* Lateral Moves */}
        <div className="bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl p-4 text-white shadow-lg">
          <div className="text-xs font-medium opacity-90 mb-1">Lateral</div>
          <div className="text-2xl font-bold">{stats.lateralMoves}</div>
        </div>

        {/* New Hires */}
        <div className="bg-gradient-to-br from-green-500 to-green-600 rounded-xl p-4 text-white shadow-lg">
          <div className="text-xs font-medium opacity-90 mb-1">New Hires</div>
          <div className="text-2xl font-bold">{stats.newHires}</div>
        </div>

        {/* Demotions */}
        <div className="bg-gradient-to-br from-red-500 to-red-600 rounded-xl p-4 text-white shadow-lg">
          <div className="text-xs font-medium opacity-90 mb-1">Demotions</div>
          <div className="text-2xl font-bold">{stats.demotions}</div>
        </div>

        {/* Terminations */}
        <div className="bg-gradient-to-br from-gray-500 to-gray-600 rounded-xl p-4 text-white shadow-lg">
          <div className="text-xs font-medium opacity-90 mb-1">Exits</div>
          <div className="text-2xl font-bold">{stats.terminations}</div>
        </div>
      </div>
    );
  };

  // ========================================
  // CHANGE TYPE FILTERS
  // ========================================

  const ChangeTypeFilters = () => (
    <div className="flex flex-wrap gap-2 mb-6">
      <button
        onClick={() => setSelectedChangeType(null)}
        className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all ${
          selectedChangeType === null
            ? 'bg-indigo-600 text-white shadow-md'
            : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700'
        }`}
      >
        <History className="w-4 h-4" />
        All Changes
      </button>
      {CHANGE_TYPES.map((type) => {
        const Icon = type.icon;
        return (
          <button
            key={type.value}
            onClick={() => setSelectedChangeType(type.value)}
            className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all ${
              selectedChangeType === type.value
                ? 'bg-indigo-600 text-white shadow-md'
                : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700'
            }`}
          >
            <Icon className="w-4 h-4" />
            {type.label}
          </button>
        );
      })}
    </div>
  );

  // ========================================
  // COLUMN DEFINITIONS
  // ========================================

  const columns = [
    {
      key: 'effectiveDate',
      label: 'Effective Date',
      sortable: true,
      render: (row: EmploymentHistory) => (
        <div className="flex items-center gap-2">
          <Calendar className="w-4 h-4 text-slate-400" />
          <div>
            <div className="font-medium text-slate-900 dark:text-slate-100">
              {new Date(row.effectiveDate).toLocaleDateString()}
            </div>
            <div className="text-xs text-slate-500">
              {new Date(row.effectiveDate).toLocaleDateString('en-US', { month: 'short', year: 'numeric' })}
            </div>
          </div>
        </div>
      ),
    },
    {
      key: 'changeType',
      label: 'Change Type',
      sortable: true,
      render: (row: EmploymentHistory) => {
        const typeConfig = CHANGE_TYPES.find((t) => t.value === row.changeType);
        const Icon = typeConfig?.icon || History;
        return (
          <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium border-2 ${typeConfig?.color || 'bg-gray-100 text-gray-700'}`}>
            <Icon className="w-4 h-4" />
            {typeConfig?.label || row.changeType}
          </div>
        );
      },
    },
    {
      key: 'changes',
      label: 'What Changed',
      sortable: false,
      render: (row: EmploymentHistory) => {
        const changes = [];

        if (row.previousJobProfile?.title !== row.newJobProfile?.title) {
          changes.push({
            icon: Briefcase,
            label: 'Role',
            from: row.previousJobProfile?.title || 'N/A',
            to: row.newJobProfile?.title || 'N/A',
          });
        }

        if (row.previousDepartment?.name !== row.newDepartment?.name) {
          changes.push({
            icon: Building,
            label: 'Department',
            from: row.previousDepartment?.name || 'N/A',
            to: row.newDepartment?.name || 'N/A',
          });
        }

        if (row.previousLocation?.name !== row.newLocation?.name) {
          changes.push({
            icon: MapPin,
            label: 'Location',
            from: row.previousLocation?.name || 'N/A',
            to: row.newLocation?.name || 'N/A',
          });
        }

        if (row.previousGrade?.name !== row.newGrade?.name) {
          changes.push({
            icon: Award,
            label: 'Grade',
            from: row.previousGrade?.name || 'N/A',
            to: row.newGrade?.name || 'N/A',
          });
        }

        if (changes.length === 0) {
          return <span className="text-slate-400 text-sm">No tracked changes</span>;
        }

        return (
          <div className="space-y-1">
            {changes.slice(0, 2).map((change, idx) => {
              const Icon = change.icon;
              return (
                <div key={idx} className="flex items-center gap-2 text-xs">
                  <Icon className="w-3 h-3 text-slate-400" />
                  <span className="text-slate-600 dark:text-slate-400">{change.label}:</span>
                  <span className="text-slate-400 line-through">{change.from}</span>
                  <span className="text-slate-400">→</span>
                  <span className="font-semibold text-slate-900 dark:text-slate-100">{change.to}</span>
                </div>
              );
            })}
            {changes.length > 2 && (
              <div className="text-xs text-slate-500">+{changes.length - 2} more</div>
            )}
          </div>
        );
      },
    },
    {
      key: 'status',
      label: 'Status',
      sortable: true,
      render: (row: EmploymentHistory) => {
        const statusConfig = STATUS_CONFIG.find((s) => s.value === row.status);
        const Icon = statusConfig?.icon || Clock;
        return (
          <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${statusConfig?.color || 'bg-gray-100 text-gray-700'}`}>
            <Icon className="w-3.5 h-3.5" />
            {statusConfig?.label || row.status}
          </span>
        );
      },
    },
    {
      key: 'reason',
      label: 'Reason',
      sortable: false,
      render: (row: EmploymentHistory) => (
        <div className="max-w-xs">
          {row.reason ? (
            <p className="text-sm text-slate-600 dark:text-slate-400 line-clamp-2">{row.reason}</p>
          ) : (
            <span className="text-slate-400 text-sm">-</span>
          )}
        </div>
      ),
    },
  ];

  // ========================================
  // FORM RENDERER
  // ========================================

  const renderForm = (data: Partial<EmploymentHistory>, onChange: (field: string, value: any) => void) => {
    return (
      <div className="space-y-4">
        {/* Change Details */}
        <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4">
          <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3 flex items-center gap-2">
            <History className="w-4 h-4" />
            Change Details
          </h3>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                Change Type <span className="text-red-500">*</span>
              </label>
              <select
                value={data.changeType || ''}
                onChange={(e) => onChange('changeType', e.target.value)}
                className="w-full px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-slate-100"
                required
              >
                <option value="">Select change type</option>
                {CHANGE_TYPES.map((type) => (
                  <option key={type.value} value={type.value}>
                    {type.label}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                Effective Date <span className="text-red-500">*</span>
              </label>
              <input
                type="date"
                value={data.effectiveDate ? new Date(data.effectiveDate).toISOString().split('T')[0] : ''}
                onChange={(e) => onChange('effectiveDate', e.target.value)}
                className="w-full px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-slate-100"
                required
              />
            </div>
            <div className="col-span-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                Reason
              </label>
              <input
                type="text"
                value={data.reason || ''}
                onChange={(e) => onChange('reason', e.target.value)}
                className="w-full px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-slate-100"
                placeholder="Performance excellence, Relocation, etc."
              />
            </div>
            <div className="col-span-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                Notes
              </label>
              <textarea
                value={data.notes || ''}
                onChange={(e) => onChange('notes', e.target.value)}
                className="w-full px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-slate-100"
                rows={3}
                placeholder="Additional details about this change..."
              />
            </div>
          </div>
        </div>

        {/* Status */}
        <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4">
          <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">
            Status
          </h3>
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
              Record Status
            </label>
            <select
              value={data.status || 'COMPLETED'}
              onChange={(e) => onChange('status', e.target.value)}
              className="w-full px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-slate-900 dark:text-slate-100"
            >
              {STATUS_CONFIG.map((status) => (
                <option key={status.value} value={status.value}>
                  {status.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="text-xs text-slate-500 bg-blue-50 dark:bg-blue-900/20 p-3 rounded-lg">
          <strong>Note:</strong> The "Previous" and "New" state fields (department, job profile, etc.) should be set when creating employment history records through employee update workflows. For manual entries, use the employee edit form to update current values.
        </div>
      </div>
    );
  };

  // ========================================
  // ROW ACTIONS
  // ========================================

  const rowActions = (row: EmploymentHistory) => {
    const actions = [
      {
        label: 'View Details',
        icon: Eye,
        onClick: () => {
          toast.info('Opening employment history details...');
        },
      },
    ];

    if (row.status === 'PENDING') {
      actions.push(
        {
          label: 'Approve',
          icon: ThumbsUp,
          onClick: async () => {
            try {
              const response = await fetch(`/api/v1/employment-history/${row.id}/approve`, {
                method: 'POST',
              });
              const result = await response.json();
              if (result.success) {
                toast.success('Employment history change approved');
              } else {
                toast.error(result.error.message);
              }
            } catch (error) {
              toast.error('Failed to approve change');
            }
          },
          className: 'text-green-600 hover:bg-green-50',
        },
        {
          label: 'Reject',
          icon: ThumbsDown,
          onClick: async () => {
            const reason = prompt('Rejection reason:');
            if (!reason) return;

            try {
              const response = await fetch(`/api/v1/employment-history/${row.id}/reject`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ reason }),
              });
              const result = await response.json();
              if (result.success) {
                toast.success('Employment history change rejected');
              } else {
                toast.error(result.error.message);
              }
            } catch (error) {
              toast.error('Failed to reject change');
            }
          },
          className: 'text-red-600 hover:bg-red-50',
        }
      );
    }

    if (!row.isAutoGenerated) {
      actions.push(
        {
          label: 'Edit',
          icon: Edit,
          onClick: () => {
            toast.info('Opening edit form...');
          },
        },
        {
          label: 'Delete',
          icon: Trash2,
          onClick: () => {
            toast.error('Delete functionality coming soon');
          },
          className: 'text-red-600 hover:bg-red-50',
        }
      );
    }

    return actions;
  };

  // ========================================
  // FETCH STATS
  // ========================================

  const fetchStats = async () => {
    try {
      const response = await fetch('/api/v1/employment-history/stats');
      const result = await response.json();
      if (result.success) {
        setStats(result.data);
      }
    } catch (error) {
      console.error('Error fetching stats:', error);
    }
  };

  useEffect(() => {
    fetchStats();
  }, []);

  // ========================================
  // RENDER
  // ========================================

  return (
    <div className="space-y-6">
      <StatsCards />
      <ChangeTypeFilters />

      <DataPage<EmploymentHistory>
        title="Employment History"
        description="Track employee career progression, promotions, transfers, and organizational changes"
        icon={History}
        apiEndpoint="/api/v1/employment-history"
        columns={columns}
        renderForm={renderForm}
        rowActions={rowActions}
        searchPlaceholder="Search by reason or notes..."
        filterOptions={{
          changeType: selectedChangeType || undefined,
          employeeId: selectedEmployee || undefined,
        }}
        onDataChange={fetchStats}
        enableExport
        exportFilename="employment-history"
      />
    </div>
  );
}
