// Org Design Module - Sample Data
// Comprehensive mock data for testing and development

import type {
  OrgChart,
  OrgNode,
  Scenario,
  ScenarioChange,
  SpanOfControl,
  Position,
  MatrixStructure,
  SuccessionPool,
  PoolMember,
  OrgAnalytics,
  ChangeManagement,
  OrgDesignSettings} from './types';
import {
  PositionHierarchy,
  MatrixRelationship
} from './types';

// ============================================================================
// ORG CHART SAMPLE DATA
// ============================================================================

export const sampleOrgNodes: OrgNode[] = [
  // Level 1 - CEO
  {
    nodeId: 'node-001',
    positionId: 'pos-001',
    positionTitle: 'Chief Executive Officer',
    positionCode: 'CEO-001',
    department: 'Executive',
    location: 'New York HQ',
    level: 1,
    path: '/CEO',
    employeeId: 'emp-001',
    employeeName: 'John Anderson',
    employeePhoto: 'https://i.pravatar.cc/150?img=12',
    isVacant: false,
    directReports: 5,
    totalReports: 128,
    spanOfControl: 5,
    jobFamily: 'Executive',
    jobLevel: 'C-Suite',
    grade: 'E1',
    fte: 1.0,
    budgetedSalary: 500000,
    actualSalary: 500000,
    totalCost: 650000,
    displayOrder: 1,
    isCollapsed: false,
  },

  // Level 2 - Direct reports to CEO
  {
    nodeId: 'node-002',
    positionId: 'pos-002',
    positionTitle: 'Chief Technology Officer',
    positionCode: 'CTO-001',
    department: 'Technology',
    location: 'San Francisco',
    parentNodeId: 'node-001',
    level: 2,
    path: '/CEO/CTO',
    employeeId: 'emp-002',
    employeeName: 'Sarah Chen',
    employeePhoto: 'https://i.pravatar.cc/150?img=45',
    isVacant: false,
    directReports: 4,
    totalReports: 48,
    spanOfControl: 4,
    jobFamily: 'Technology',
    jobLevel: 'C-Suite',
    grade: 'E2',
    fte: 1.0,
    budgetedSalary: 350000,
    actualSalary: 350000,
    totalCost: 455000,
    displayOrder: 2,
    isCollapsed: false,
  },
  {
    nodeId: 'node-003',
    positionId: 'pos-003',
    positionTitle: 'Chief Financial Officer',
    positionCode: 'CFO-001',
    department: 'Finance',
    location: 'New York HQ',
    parentNodeId: 'node-001',
    level: 2,
    path: '/CEO/CFO',
    employeeId: 'emp-003',
    employeeName: 'Michael Roberts',
    employeePhoto: 'https://i.pravatar.cc/150?img=33',
    isVacant: false,
    directReports: 3,
    totalReports: 25,
    spanOfControl: 3,
    jobFamily: 'Finance',
    jobLevel: 'C-Suite',
    grade: 'E2',
    fte: 1.0,
    budgetedSalary: 325000,
    actualSalary: 325000,
    totalCost: 422500,
    displayOrder: 3,
    isCollapsed: false,
  },
  {
    nodeId: 'node-004',
    positionId: 'pos-004',
    positionTitle: 'Chief People Officer',
    positionCode: 'CPO-001',
    department: 'Human Resources',
    location: 'New York HQ',
    parentNodeId: 'node-001',
    level: 2,
    path: '/CEO/CPO',
    employeeId: 'emp-004',
    employeeName: 'Jennifer Martinez',
    employeePhoto: 'https://i.pravatar.cc/150?img=25',
    isVacant: false,
    directReports: 4,
    totalReports: 32,
    spanOfControl: 4,
    jobFamily: 'Human Resources',
    jobLevel: 'C-Suite',
    grade: 'E2',
    fte: 1.0,
    budgetedSalary: 300000,
    actualSalary: 300000,
    totalCost: 390000,
    displayOrder: 4,
    isCollapsed: false,
  },
  {
    nodeId: 'node-005',
    positionId: 'pos-005',
    positionTitle: 'Chief Operating Officer',
    positionCode: 'COO-001',
    department: 'Operations',
    location: 'Chicago',
    parentNodeId: 'node-001',
    level: 2,
    path: '/CEO/COO',
    employeeId: 'emp-005',
    employeeName: 'David Kim',
    employeePhoto: 'https://i.pravatar.cc/150?img=15',
    isVacant: false,
    directReports: 3,
    totalReports: 23,
    spanOfControl: 3,
    jobFamily: 'Operations',
    jobLevel: 'C-Suite',
    grade: 'E2',
    fte: 1.0,
    budgetedSalary: 320000,
    actualSalary: 320000,
    totalCost: 416000,
    displayOrder: 5,
    isCollapsed: false,
  },

  // Level 3 - Technology Department (reporting to CTO)
  {
    nodeId: 'node-006',
    positionId: 'pos-006',
    positionTitle: 'VP Engineering',
    positionCode: 'VP-ENG-001',
    department: 'Technology',
    location: 'San Francisco',
    parentNodeId: 'node-002',
    level: 3,
    path: '/CEO/CTO/VP-ENG',
    employeeId: 'emp-006',
    employeeName: 'Alex Johnson',
    employeePhoto: 'https://i.pravatar.cc/150?img=28',
    isVacant: false,
    directReports: 8,
    totalReports: 32,
    spanOfControl: 8,
    jobFamily: 'Technology',
    jobLevel: 'VP',
    grade: 'E3',
    fte: 1.0,
    budgetedSalary: 250000,
    actualSalary: 250000,
    totalCost: 325000,
    displayOrder: 6,
    isCollapsed: false,
  },
  {
    nodeId: 'node-007',
    positionId: 'pos-007',
    positionTitle: 'VP Product',
    positionCode: 'VP-PROD-001',
    department: 'Technology',
    location: 'San Francisco',
    parentNodeId: 'node-002',
    level: 3,
    path: '/CEO/CTO/VP-PROD',
    employeeId: 'emp-007',
    employeeName: 'Emily Davis',
    employeePhoto: 'https://i.pravatar.cc/150?img=47',
    isVacant: false,
    directReports: 5,
    totalReports: 12,
    spanOfControl: 5,
    jobFamily: 'Product',
    jobLevel: 'VP',
    grade: 'E3',
    fte: 1.0,
    budgetedSalary: 240000,
    actualSalary: 240000,
    totalCost: 312000,
    displayOrder: 7,
    isCollapsed: false,
  },
  {
    nodeId: 'node-008',
    positionId: 'pos-008',
    positionTitle: 'Director of Data Science',
    positionCode: 'DIR-DS-001',
    department: 'Technology',
    location: 'Seattle',
    parentNodeId: 'node-002',
    level: 3,
    path: '/CEO/CTO/DIR-DS',
    employeeId: 'emp-008',
    employeeName: 'Raj Patel',
    employeePhoto: 'https://i.pravatar.cc/150?img=51',
    isVacant: false,
    directReports: 4,
    totalReports: 10,
    spanOfControl: 4,
    jobFamily: 'Technology',
    jobLevel: 'Director',
    grade: 'M1',
    fte: 1.0,
    budgetedSalary: 220000,
    actualSalary: 220000,
    totalCost: 286000,
    displayOrder: 8,
    isCollapsed: false,
  },

  // Vacant Position Example
  {
    nodeId: 'node-009',
    positionId: 'pos-009',
    positionTitle: 'VP Infrastructure',
    positionCode: 'VP-INFRA-001',
    department: 'Technology',
    location: 'Austin',
    parentNodeId: 'node-002',
    level: 3,
    path: '/CEO/CTO/VP-INFRA',
    isVacant: true,
    directReports: 0,
    totalReports: 0,
    spanOfControl: 0,
    jobFamily: 'Technology',
    jobLevel: 'VP',
    grade: 'E3',
    fte: 1.0,
    budgetedSalary: 240000,
    totalCost: 312000,
    displayOrder: 9,
    isCollapsed: false,
  },
];

export const sampleOrgCharts: OrgChart[] = [
  {
    chartId: 'chart-001',
    chartName: 'Current Organization Structure',
    chartType: 'current',
    effectiveDate: new Date('2024-01-01'),
    status: 'active',
    isCurrentChart: true,
    rootPosition: 'pos-001',
    nodes: sampleOrgNodes,
    totalPositions: 9,
    totalEmployees: 8,
    totalVacancies: 1,
    createdDate: new Date('2024-01-01'),
    createdBy: 'admin',
    createdByName: 'Admin User',
    lastUpdatedDate: new Date(),
    lastUpdatedBy: 'admin',
    version: 3,
    notes: 'Current organizational structure as of Q1 2024',
  },
  {
    chartId: 'chart-002',
    chartName: '2024 Growth Plan',
    chartType: 'proposed',
    effectiveDate: new Date('2024-07-01'),
    status: 'draft',
    isCurrentChart: false,
    rootPosition: 'pos-001',
    nodes: [...sampleOrgNodes],
    totalPositions: 12,
    totalEmployees: 8,
    totalVacancies: 4,
    createdDate: new Date('2024-03-15'),
    createdBy: 'admin',
    createdByName: 'Admin User',
    lastUpdatedDate: new Date(),
    lastUpdatedBy: 'admin',
    version: 1,
    notes: 'Proposed structure for H2 2024 expansion',
  },
];

// ============================================================================
// SCENARIO SAMPLE DATA
// ============================================================================

export const sampleScenarioChanges: ScenarioChange[] = [
  {
    changeId: 'change-001',
    changeType: 'add_position',
    changeDescription: 'Add VP of Sales position',
    affectedPosition: 'new-pos-001',
    affectedPositionTitle: 'VP Sales',
    beforeState: null,
    afterState: {
      positionTitle: 'VP Sales',
      department: 'Sales',
      level: 2,
      budgetedSalary: 280000,
    },
    impactLevel: 'high',
    impactedEmployees: 1,
    costImpact: 364000,
  },
  {
    changeId: 'change-002',
    changeType: 'change_reporting',
    changeDescription: 'Move Data Science to report to VP Product',
    affectedPosition: 'pos-008',
    affectedPositionTitle: 'Director of Data Science',
    affectedEmployee: 'emp-008',
    affectedEmployeeName: 'Raj Patel',
    beforeState: {
      reportsTo: 'pos-002',
      reportingLine: 'CTO',
    },
    afterState: {
      reportsTo: 'pos-007',
      reportingLine: 'VP Product',
    },
    impactLevel: 'medium',
    impactedEmployees: 10,
    costImpact: 0,
  },
  {
    changeId: 'change-003',
    changeType: 'add_position',
    changeDescription: 'Add Regional Sales Manager - East',
    affectedPosition: 'new-pos-002',
    affectedPositionTitle: 'Regional Sales Manager - East',
    beforeState: null,
    afterState: {
      positionTitle: 'Regional Sales Manager - East',
      department: 'Sales',
      level: 3,
      budgetedSalary: 150000,
    },
    impactLevel: 'medium',
    impactedEmployees: 1,
    costImpact: 195000,
  },
];

export const sampleScenarios: Scenario[] = [
  {
    scenarioId: 'scenario-001',
    scenarioName: 'H2 2024 Growth Expansion',
    scenarioType: 'growth',
    description:
      'Expansion plan to support 30% revenue growth target in H2 2024. Includes adding Sales organization and expanding Product team.',
    baselineChartId: 'chart-001',
    effectiveDate: new Date('2024-07-01'),
    status: 'under_review',
    changes: sampleScenarioChanges,
    totalChanges: 3,
    impactSummary: {
      departmentsAffected: 2,
      locationsAffected: 3,
      levelsAffected: 2,
      employeesImpacted: 12,
      newHires: 3,
      terminations: 0,
      relocations: 0,
      promotions: 2,
      demotions: 0,
      averageSpanBefore: 4.8,
      averageSpanAfter: 5.6,
      spanIssues: [],
      salaryImpact: 559000,
      benefitsImpact: 111800,
      overheadImpact: 50000,
      oneTimeCosts: 150000,
      recurringCosts: 720800,
    },
    currentCost: 3250000,
    projectedCost: 3970800,
    costDelta: 720800,
    costDeltaPercentage: 22.2,
    currentHeadcount: 128,
    projectedHeadcount: 145,
    headcountDelta: 17,
    createdDate: new Date('2024-03-15'),
    createdBy: 'admin',
    createdByName: 'Admin User',
    lastUpdatedDate: new Date(),
    notes: 'Pending approval from Executive Committee',
  },
  {
    scenarioId: 'scenario-002',
    scenarioName: 'Cost Optimization Initiative',
    scenarioType: 'cost_reduction',
    description:
      'Streamline organizational structure by consolidating overlapping functions and flattening hierarchy.',
    baselineChartId: 'chart-001',
    effectiveDate: new Date('2024-06-01'),
    status: 'draft',
    changes: [],
    totalChanges: 0,
    impactSummary: {
      departmentsAffected: 4,
      locationsAffected: 2,
      levelsAffected: 3,
      employeesImpacted: 25,
      newHires: 0,
      terminations: 8,
      relocations: 3,
      promotions: 0,
      demotions: 0,
      averageSpanBefore: 4.8,
      averageSpanAfter: 6.2,
      spanIssues: [],
      salaryImpact: -850000,
      benefitsImpact: -170000,
      overheadImpact: -120000,
      oneTimeCosts: 500000,
      recurringCosts: -1140000,
    },
    currentCost: 3250000,
    projectedCost: 2110000,
    costDelta: -1140000,
    costDeltaPercentage: -35.1,
    currentHeadcount: 128,
    projectedHeadcount: 120,
    headcountDelta: -8,
    createdDate: new Date('2024-04-01'),
    createdBy: 'admin',
    createdByName: 'Admin User',
    lastUpdatedDate: new Date(),
  },
];

// ============================================================================
// SPAN OF CONTROL SAMPLE DATA
// ============================================================================

export const sampleSpanOfControl: SpanOfControl = {
  analysisId: 'span-001',
  analysisName: 'Q1 2024 Span of Control Analysis',
  chartId: 'chart-001',
  analysisDate: new Date(),
  overallMetrics: {
    totalManagers: 26,
    averageSpan: 5.2,
    medianSpan: 5,
    minSpan: 2,
    maxSpan: 12,
    idealSpanRange: { min: 5, max: 9 },
    withinIdealRange: 18,
    withinIdealRangePercentage: 69.2,
    tooNarrow: 5,
    tooWide: 3,
  },
  levelAnalysis: [
    {
      level: 1,
      levelName: 'Executive',
      managerCount: 1,
      averageSpan: 5,
      minSpan: 5,
      maxSpan: 5,
      idealRange: { min: 3, max: 7 },
      complianceRate: 100,
    },
    {
      level: 2,
      levelName: 'C-Suite',
      managerCount: 5,
      averageSpan: 3.8,
      minSpan: 3,
      maxSpan: 4,
      idealRange: { min: 3, max: 7 },
      complianceRate: 100,
    },
    {
      level: 3,
      levelName: 'VP/Director',
      managerCount: 12,
      averageSpan: 5.5,
      minSpan: 4,
      maxSpan: 8,
      idealRange: { min: 5, max: 9 },
      complianceRate: 75,
    },
    {
      level: 4,
      levelName: 'Senior Manager',
      managerCount: 8,
      averageSpan: 6.8,
      minSpan: 5,
      maxSpan: 12,
      idealRange: { min: 5, max: 9 },
      complianceRate: 50,
    },
  ],
  departmentAnalysis: [
    {
      departmentId: 'dept-tech',
      departmentName: 'Technology',
      managerCount: 12,
      averageSpan: 5.8,
      totalEmployees: 48,
      layers: 5,
      complianceRate: 75,
    },
    {
      departmentId: 'dept-finance',
      departmentName: 'Finance',
      managerCount: 5,
      averageSpan: 4.2,
      totalEmployees: 25,
      layers: 4,
      complianceRate: 80,
    },
    {
      departmentId: 'dept-hr',
      departmentName: 'Human Resources',
      managerCount: 6,
      averageSpan: 4.8,
      totalEmployees: 32,
      layers: 4,
      complianceRate: 83,
    },
    {
      departmentId: 'dept-ops',
      departmentName: 'Operations',
      managerCount: 3,
      averageSpan: 6.3,
      totalEmployees: 23,
      layers: 3,
      complianceRate: 67,
    },
  ],
  spanIssues: [
    {
      issueId: 'issue-001',
      positionId: 'pos-015',
      positionTitle: 'Engineering Manager - Platform',
      currentSpan: 12,
      recommendedSpan: 8,
      severity: 'high',
      recommendation:
        'Span too wide - consider adding a senior engineer lead or splitting team',
    },
    {
      issueId: 'issue-002',
      positionId: 'pos-022',
      positionTitle: 'Finance Manager',
      currentSpan: 2,
      recommendedSpan: 5,
      severity: 'medium',
      recommendation:
        'Span too narrow - consider consolidating with adjacent team',
    },
  ],
  totalIssues: 2,
  recommendations: [
    {
      recommendationId: 'rec-001',
      positionId: 'pos-015',
      positionTitle: 'Engineering Manager - Platform',
      currentSpan: 12,
      recommendedAction: 'add_layer',
      targetSpan: 8,
      rationale:
        'Current span of 12 exceeds ideal maximum. Adding a tech lead would reduce span and provide better support.',
      estimatedCost: 180000,
      priority: 'high',
    },
    {
      recommendationId: 'rec-002',
      positionId: 'pos-022',
      positionTitle: 'Finance Manager',
      currentSpan: 2,
      recommendedAction: 'remove_layer',
      targetSpan: 5,
      rationale:
        'Span of 2 is inefficient. Merge with Accounting Manager role to create broader Finance Manager position.',
      estimatedCost: -125000,
      priority: 'medium',
    },
  ],
};

// ============================================================================
// POSITION HIERARCHY SAMPLE DATA
// ============================================================================

export const samplePositions: Position[] = [
  {
    positionId: 'pos-001',
    positionCode: 'CEO-001',
    positionTitle: 'Chief Executive Officer',
    positionType: 'regular',
    level: 1,
    reportingPath: [],
    department: 'Executive',
    departmentId: 'dept-exec',
    location: 'New York HQ',
    locationId: 'loc-nyc',
    businessUnit: 'Corporate',
    costCenter: 'CC-001',
    jobFamily: 'Executive',
    jobFamilyId: 'jf-exec',
    jobTitle: 'Chief Executive Officer',
    jobLevel: 'C-Suite',
    grade: 'E1',
    gradeId: 'grade-e1',
    employmentType: 'full_time',
    fte: 1.0,
    isVacant: false,
    incumbentId: 'emp-001',
    incumbentName: 'John Anderson',
    budgetedSalary: 500000,
    salaryMin: 450000,
    salaryMax: 600000,
    salaryMidpoint: 525000,
    currency: 'USD',
    totalCompensation: 650000,
    effectiveDate: new Date('2023-01-01'),
    createdDate: new Date('2023-01-01'),
    lastModifiedDate: new Date(),
    status: 'active',
    approvalStatus: 'approved',
    requiresBackgroundCheck: true,
    isCritical: true,
    successionPlanRequired: true,
  },
  {
    positionId: 'pos-002',
    positionCode: 'CTO-001',
    positionTitle: 'Chief Technology Officer',
    positionType: 'regular',
    parentPositionId: 'pos-001',
    level: 2,
    reportingPath: ['pos-001'],
    department: 'Technology',
    departmentId: 'dept-tech',
    location: 'San Francisco',
    locationId: 'loc-sf',
    businessUnit: 'Technology',
    costCenter: 'CC-002',
    jobFamily: 'Technology',
    jobFamilyId: 'jf-tech',
    jobTitle: 'Chief Technology Officer',
    jobLevel: 'C-Suite',
    grade: 'E2',
    gradeId: 'grade-e2',
    employmentType: 'full_time',
    fte: 1.0,
    isVacant: false,
    incumbentId: 'emp-002',
    incumbentName: 'Sarah Chen',
    budgetedSalary: 350000,
    salaryMin: 320000,
    salaryMax: 420000,
    salaryMidpoint: 370000,
    currency: 'USD',
    totalCompensation: 455000,
    effectiveDate: new Date('2023-01-01'),
    createdDate: new Date('2023-01-01'),
    lastModifiedDate: new Date(),
    status: 'active',
    approvalStatus: 'approved',
    requiresBackgroundCheck: true,
    isCritical: true,
    successionPlanRequired: true,
  },
];

// ============================================================================
// MATRIX STRUCTURE SAMPLE DATA
// ============================================================================

export const sampleMatrixStructure: MatrixStructure = {
  matrixId: 'matrix-001',
  matrixName: 'Product & Engineering Matrix',
  matrixType: 'balanced',
  description:
    'Balanced matrix between Product (customer-focused) and Engineering (technical) dimensions',
  effectiveDate: new Date('2024-01-01'),
  status: 'active',
  primaryDimension: {
    dimensionId: 'dim-prod',
    dimensionType: 'product',
    dimensionName: 'Product Lines',
    leaders: [
      {
        leaderId: 'emp-007',
        leaderName: 'Emily Davis',
        positionId: 'pos-007',
        positionTitle: 'VP Product',
        scope: 'All Products',
        authority: 'full',
      },
    ],
    weight: 50,
  },
  secondaryDimension: {
    dimensionId: 'dim-eng',
    dimensionType: 'functional',
    dimensionName: 'Engineering Functions',
    leaders: [
      {
        leaderId: 'emp-006',
        leaderName: 'Alex Johnson',
        positionId: 'pos-006',
        positionTitle: 'VP Engineering',
        scope: 'All Engineering',
        authority: 'shared',
      },
    ],
    weight: 50,
  },
  matrixRelationships: [
    {
      relationshipId: 'rel-001',
      employeeId: 'emp-020',
      employeeName: 'James Wilson',
      positionId: 'pos-020',
      primaryManagerId: 'emp-007',
      primaryManagerName: 'Emily Davis',
      primaryManagerPosition: 'VP Product',
      primaryAllocation: 60,
      secondaryManagerId: 'emp-006',
      secondaryManagerName: 'Alex Johnson',
      secondaryManagerPosition: 'VP Engineering',
      secondaryAllocation: 40,
      relationshipType: 'dotted_line',
      startDate: new Date('2024-01-01'),
      status: 'active',
      performanceReviewOwner: 'joint',
      approvalAuthority: {
        'Product Decisions': 'primary',
        'Technical Decisions': 'secondary',
        'Budget Approval': 'joint',
        'Hiring Decisions': 'primary',
      },
    },
  ],
  totalRelationships: 1,
  decisionRights: [
    {
      decisionId: 'dec-001',
      decisionType: 'Product Roadmap',
      decisionDescription: 'Product feature prioritization and roadmap planning',
      owner: 'primary',
      requiredConsent: ['secondary'],
    },
    {
      decisionId: 'dec-002',
      decisionType: 'Architecture Decisions',
      decisionDescription: 'Major technical architecture and platform decisions',
      owner: 'secondary',
      requiredConsent: ['primary'],
    },
    {
      decisionId: 'dec-003',
      decisionType: 'Resource Allocation',
      decisionDescription: 'Engineering resource allocation across products',
      owner: 'joint',
    },
  ],
  escalationPath: [
    {
      pathId: 'esc-001',
      scenario: 'Product vs Engineering Priority Conflict',
      steps: [
        {
          stepNumber: 1,
          escalateTo: 'CTO',
          escalateToRole: 'Chief Technology Officer',
          conditions: 'Unable to resolve at VP level',
          timeframe: 3,
        },
        {
          stepNumber: 2,
          escalateTo: 'CEO',
          escalateToRole: 'Chief Executive Officer',
          conditions: 'CTO unable to resolve',
          timeframe: 5,
        },
      ],
    },
  ],
  createdDate: new Date('2024-01-01'),
  createdBy: 'admin',
  lastUpdatedDate: new Date(),
};

// ============================================================================
// SUCCESSION POOL SAMPLE DATA
// ============================================================================

export const samplePoolMembers: PoolMember[] = [
  {
    memberId: 'member-001',
    employeeId: 'emp-025',
    employeeName: 'Lisa Wong',
    currentPosition: 'Senior Engineering Manager',
    currentLevel: 'M2',
    department: 'Technology',
    readinessLevel: 'ready_1_year',
    targetPositions: [
      {
        positionId: 'pos-006',
        positionTitle: 'VP Engineering',
        positionLevel: 'E3',
        readinessForPosition: 'ready_1_year',
        gapAnalysis: 'Needs more experience leading multi-site teams',
        priority: 1,
      },
      {
        positionId: 'pos-009',
        positionTitle: 'VP Infrastructure',
        positionLevel: 'E3',
        readinessForPosition: 'ready_now',
        gapAnalysis: 'Ready immediately, strong infrastructure background',
        priority: 2,
      },
    ],
    performanceRating: 4.5,
    potentialRating: 4,
    riskOfLoss: 'medium',
    developmentPlan: {
      planId: 'plan-001',
      objectives: [
        'Develop multi-site leadership skills',
        'Build strategic planning capabilities',
        'Strengthen executive presence',
      ],
      actions: [
        {
          actionId: 'action-001',
          actionType: 'stretch_assignment',
          description: 'Lead cross-functional initiative across SF and Seattle teams',
          targetCompetency: 'Multi-site Leadership',
          startDate: new Date('2024-03-01'),
          endDate: new Date('2024-09-01'),
          status: 'in_progress',
          completionPercentage: 45,
        },
        {
          actionId: 'action-002',
          actionType: 'coaching',
          description: 'Executive coaching with external leadership coach',
          targetCompetency: 'Executive Presence',
          startDate: new Date('2024-01-15'),
          endDate: new Date('2024-12-31'),
          status: 'in_progress',
          completionPercentage: 30,
        },
      ],
      completionPercentage: 38,
      startDate: new Date('2024-01-01'),
      targetCompletionDate: new Date('2024-12-31'),
    },
    competencyGaps: [
      {
        competencyId: 'comp-001',
        competencyName: 'Strategic Planning',
        currentLevel: 3,
        requiredLevel: 4,
        gap: 1,
        priority: 'high',
        developmentActions: ['action-001', 'action-002'],
      },
      {
        competencyId: 'comp-002',
        competencyName: 'Multi-site Management',
        currentLevel: 2,
        requiredLevel: 4,
        gap: 2,
        priority: 'critical',
        developmentActions: ['action-001'],
      },
    ],
    joinedPoolDate: new Date('2024-01-01'),
    lastReviewDate: new Date('2024-03-01'),
    nextReviewDate: new Date('2024-09-01'),
    status: 'active',
  },
];

export const sampleSuccessionPool: SuccessionPool = {
  poolId: 'pool-001',
  poolName: 'Technology Leadership Pipeline',
  poolType: 'senior_management',
  description: 'Succession pool for VP and Director level positions in Technology',
  eligibilityCriteria: {
    minPerformanceRating: 4,
    minTenure: 24,
    minPotentialRating: 3,
    requiredCompetencies: [
      'Strategic Thinking',
      'People Leadership',
      'Technical Excellence',
    ],
    requiredExperiences: [
      'Led team of 10+',
      'Cross-functional project leadership',
    ],
    excludeRecentPromotion: true,
    recentPromotionMonths: 12,
  },
  members: samplePoolMembers,
  totalMembers: 1,
  developmentPrograms: [
    {
      programId: 'prog-001',
      programName: 'Leadership Accelerator Program',
      programType: 'Leadership Development',
      targetAudience: ['High Potential Managers'],
      duration: 9,
      participants: 12,
      completionRate: 92,
      effectivenessRating: 4.5,
    },
  ],
  readinessDistribution: [
    { level: 'ready_now', count: 2 },
    { level: 'ready_1_year', count: 5 },
    { level: 'ready_2_3_years', count: 8 },
  ],
  averageReadiness: 2.1,
  promotionRate: 35,
  retentionRate: 92,
  createdDate: new Date('2024-01-01'),
  createdBy: 'admin',
  lastUpdatedDate: new Date(),
  status: 'active',
};

// ============================================================================
// ORG ANALYTICS SAMPLE DATA
// ============================================================================

export const sampleOrgAnalytics: OrgAnalytics = {
  totalEmployees: 128,
  totalPositions: 135,
  vacancyRate: 5.2,
  averageTenure: 3.8,
  totalLevels: 6,
  averageSpanOfControl: 5.2,
  totalCompensationCost: 12450000,
  averageCompensation: 97266,
  compensationByLevel: [
    { level: 'C-Suite', average: 375000, total: 1875000 },
    { level: 'VP', average: 235000, total: 2115000 },
    { level: 'Director', average: 185000, total: 2960000 },
    { level: 'Manager', average: 135000, total: 4050000 },
    { level: 'Individual Contributor', average: 95000, total: 1450000 },
  ],
  compensationByDepartment: [
    { department: 'Technology', average: 125000, total: 6000000 },
    { department: 'Finance', average: 110000, total: 2750000 },
    { department: 'Human Resources', average: 95000, total: 3040000 },
    { department: 'Operations', average: 88000, total: 660000 },
  ],
  employeesByLevel: [
    { level: 'C-Suite', count: 5, percentage: 3.9 },
    { level: 'VP', count: 9, percentage: 7.0 },
    { level: 'Director', count: 16, percentage: 12.5 },
    { level: 'Manager', count: 30, percentage: 23.4 },
    { level: 'Individual Contributor', count: 68, percentage: 53.1 },
  ],
  employeesByDepartment: [
    { department: 'Technology', count: 48, percentage: 37.5 },
    { department: 'Finance', count: 25, percentage: 19.5 },
    { department: 'Human Resources', count: 32, percentage: 25.0 },
    { department: 'Operations', count: 23, percentage: 18.0 },
  ],
  employeesByLocation: [
    { location: 'San Francisco', count: 42, percentage: 32.8 },
    { location: 'New York', count: 38, percentage: 29.7 },
    { location: 'Chicago', count: 25, percentage: 19.5 },
    { location: 'Austin', count: 15, percentage: 11.7 },
    { location: 'Seattle', count: 8, percentage: 6.3 },
  ],
  employeesByGrade: [
    { grade: 'E1-E3', count: 14, percentage: 10.9 },
    { grade: 'M1-M3', count: 46, percentage: 35.9 },
    { grade: 'IC1-IC5', count: 68, percentage: 53.1 },
  ],
  averageAge: 36,
  genderDistribution: [
    { gender: 'Male', count: 64, percentage: 50.0 },
    { gender: 'Female', count: 60, percentage: 46.9 },
    { gender: 'Non-binary', count: 4, percentage: 3.1 },
  ],
  generationDistribution: [
    { generation: 'Baby Boomer', count: 8, percentage: 6.3 },
    { generation: 'Gen X', count: 35, percentage: 27.3 },
    { generation: 'Millennial', count: 72, percentage: 56.3 },
    { generation: 'Gen Z', count: 13, percentage: 10.2 },
  ],
  internalMobility: {
    totalMoves: 45,
    lateralMoves: 25,
    promotions: 15,
    demotions: 0,
    crossFunctionalMoves: 12,
    crossLocationMoves: 8,
    mobilityRate: 12.5,
  },
  promotionMetrics: {
    totalPromotions: 15,
    promotionRate: 4.2,
    averageTimeToPromotion: 2.5,
    promotionsByLevel: [
      { level: 'Manager to Director', count: 6 },
      { level: 'IC to Manager', count: 9 },
    ],
    promotionsByDepartment: [
      { department: 'Technology', count: 8 },
      { department: 'Finance', count: 3 },
      { department: 'HR', count: 2 },
      { department: 'Operations', count: 2 },
    ],
  },
  attritionMetrics: {
    totalAttrition: 28,
    attritionRate: 7.8,
    voluntaryAttrition: 22,
    involuntaryAttrition: 6,
    attritionByLevel: [
      { level: 'C-Suite', count: 1, rate: 3.2 },
      { level: 'Manager', count: 8, rate: 9.5 },
      { level: 'IC', count: 19, rate: 12.1 },
    ],
    attritionByDepartment: [
      { department: 'Technology', count: 12, rate: 8.5 },
      { department: 'Sales', count: 8, rate: 15.2 },
      { department: 'Finance', count: 5, rate: 5.8 },
      { department: 'HR', count: 3, rate: 4.2 },
    ],
    averageTerminationReason: [
      { reason: 'Career Growth', count: 10 },
      { reason: 'Compensation', count: 7 },
      { reason: 'Work-Life Balance', count: 5 },
    ],
  },
  layerMetrics: {
    totalLayers: 6,
    averageLayers: 5,
    maxLayers: 6,
    layersByDepartment: [
      { department: 'Technology', layers: 6 },
      { department: 'Finance', layers: 5 },
      { department: 'HR', layers: 5 },
      { department: 'Operations', layers: 4 },
    ],
    excessiveLayers: [
      { department: 'Technology', layers: 6, recommended: 5 },
    ],
  },
  spanMetrics: {
    totalManagers: 26,
    averageSpan: 5.2,
    medianSpan: 5,
    minSpan: 2,
    maxSpan: 12,
    idealSpanRange: { min: 5, max: 9 },
    withinIdealRange: 18,
    withinIdealRangePercentage: 69.2,
    tooNarrow: 5,
    tooWide: 3,
  },
  headcountTrend: [
    { month: 'Jan 2024', count: 120 },
    { month: 'Feb 2024', count: 122 },
    { month: 'Mar 2024', count: 125 },
    { month: 'Apr 2024', count: 128 },
  ],
  costTrend: [
    { month: 'Jan 2024', cost: 11800000 },
    { month: 'Feb 2024', cost: 12000000 },
    { month: 'Mar 2024', cost: 12250000 },
    { month: 'Apr 2024', cost: 12450000 },
  ],
};

// ============================================================================
// CHANGE MANAGEMENT SAMPLE DATA
// ============================================================================

export const sampleChangeManagement: ChangeManagement[] = [
  {
    changeId: 'chg-001',
    changeTitle: 'Technology Department Restructure',
    changeType: 'restructure',
    changeScope: 'department',
    description:
      'Restructure Technology department to better align Product and Engineering, create dedicated Data Science group, and improve span of control.',
    plannedStartDate: new Date('2024-06-01'),
    plannedEndDate: new Date('2024-09-30'),
    status: 'in_progress',
    completionPercentage: 35,
    impactAssessment: {
      assessmentDate: new Date('2024-04-15'),
      assessedBy: 'emp-004',
      totalAffected: 48,
      highImpact: 8,
      mediumImpact: 22,
      lowImpact: 18,
      processesAffected: 12,
      systemsAffected: 5,
      policiesAffected: 3,
      readinessScore: 72,
      readinessLevel: 'medium',
      readinessFactors: [
        { factor: 'Leadership Alignment', score: 85 },
        { factor: 'Employee Readiness', score: 65 },
        { factor: 'Communication Plan', score: 75 },
        { factor: 'Change Resources', score: 60 },
      ],
    },
    affectedEmployees: [
      {
        employeeId: 'emp-008',
        employeeName: 'Raj Patel',
        currentPosition: 'Director of Data Science',
        department: 'Technology',
        impactType: 'reporting_change',
        impactLevel: 'medium',
        impactDescription: 'Reporting line changes from CTO to VP Product',
        newManager: 'Emily Davis',
        communicationStatus: 'informed',
        acceptanceLevel: 'supportive',
        supportRequired: ['Team communication support', '1-on-1 coaching'],
      },
    ],
    totalAffected: 1,
    changeOwner: 'emp-002',
    changeOwnerName: 'Sarah Chen',
    stakeholders: [
      {
        stakeholderId: 'stake-001',
        stakeholderName: 'John Anderson',
        stakeholderType: 'sponsor',
        role: 'CEO',
        influence: 'high',
        support: 'supporter',
        engagementLevel: 'committed',
      },
      {
        stakeholderId: 'stake-002',
        stakeholderName: 'Sarah Chen',
        stakeholderType: 'champion',
        role: 'CTO',
        influence: 'high',
        support: 'supporter',
        engagementLevel: 'committed',
      },
    ],
    communicationPlan: {
      planId: 'comm-001',
      activities: [
        {
          activityId: 'comm-act-001',
          activityType: 'announcement',
          title: 'Initial Restructure Announcement',
          audience: ['Technology Department'],
          channel: 'Town Hall',
          scheduledDate: new Date('2024-05-15'),
          status: 'completed',
          attendees: 48,
          feedback: 'Generally positive, many questions about timelines',
        },
      ],
      channels: ['Email', 'Town Hall', 'Slack', 'One-on-ones'],
      frequency: 'Weekly updates',
    },
    announcements: [
      {
        announcementId: 'ann-001',
        title: 'Technology Restructure - Making Our Teams More Effective',
        content:
          'We are excited to announce organizational changes that will strengthen collaboration...',
        audience: ['All Technology'],
        publishDate: new Date('2024-05-15'),
        channel: ['Email', 'Slack'],
        views: 48,
        acknowledgements: 45,
      },
    ],
    resistanceLevel: 'low',
    risks: [
      {
        riskId: 'risk-001',
        riskDescription: 'Key talent may leave during transition',
        probability: 'medium',
        impact: 'high',
        riskLevel: 'high',
        mitigation: 'Retention bonuses for critical roles, frequent communication',
        owner: 'emp-002',
        status: 'open',
      },
    ],
    mitigationActions: [
      {
        actionId: 'mit-001',
        action: 'Implement retention bonuses for 5 critical positions',
        owner: 'emp-004',
        dueDate: new Date('2024-06-01'),
        status: 'completed',
        effectiveness: 'high',
      },
    ],
    milestones: [
      {
        milestoneId: 'mile-001',
        milestoneName: 'Communication Complete',
        milestoneDate: new Date('2024-05-31'),
        status: 'achieved',
        description: 'All affected employees informed of changes',
      },
      {
        milestoneId: 'mile-002',
        milestoneName: 'New Structure Active',
        milestoneDate: new Date('2024-07-01'),
        status: 'pending',
        description: 'New reporting lines and teams officially active',
      },
    ],
    tasks: [
      {
        taskId: 'task-001',
        taskName: 'Update org chart in HRIS',
        taskType: 'System Update',
        assignedTo: 'HR Operations',
        dueDate: new Date('2024-06-15'),
        status: 'in_progress',
        priority: 'high',
        dependencies: [],
      },
    ],
    createdDate: new Date('2024-04-01'),
    createdBy: 'emp-002',
    lastUpdatedDate: new Date(),
  },
];

// ============================================================================
// SETTINGS SAMPLE DATA
// ============================================================================

export const sampleSettings: OrgDesignSettings = {
  settingsId: 'settings-1',
  orgChartSettings: {
    defaultView: 'tree',
    allowExport: true,
    exportFormats: ['pdf', 'png', 'svg', 'excel'],
    showPhotos: true,
    showVacancies: true,
    colorScheme: 'professional',
  },
  spanSettings: {
    idealSpanMin: 5,
    idealSpanMax: 9,
    executiveSpanMin: 3,
    executiveSpanMax: 7,
    managerSpanMin: 5,
    managerSpanMax: 12,
    enableAlerts: true,
  },
  hierarchySettings: {
    maxLevels: 10,
    requireApprovalForNewPositions: true,
    approvalWorkflow: ['Hiring Manager', 'Department Head', 'HR', 'CFO'],
    enforceGradeProgression: true,
  },
  scenarioSettings: {
    allowMultipleScenarios: true,
    requireApprovalForImplementation: true,
    retentionPeriod: 365,
  },
  successionSettings: {
    minReadyNowCoverage: 80,
    minPipelineCoverage: 100,
    reviewFrequency: 'semi_annually',
    enableAlerts: true,
  },
  lastUpdatedDate: new Date(),
  lastUpdatedBy: 'admin',
  lastUpdatedByName: 'Admin User',
};
