/**
 * @service EmploymentHistoryService
 * @description Service layer for Employment History tracking
 * @project AURA HCM Platform
 */

import { PrismaClient } from '@aura/database';
import { z } from 'zod';

const prisma = new PrismaClient();

// ========================================
// VALIDATION SCHEMAS
// ========================================

export const createEmploymentHistorySchema = z.object({
  tenantId: z.string(),
  employeeId: z.string(),

  // Change Details
  changeType: z.enum(['PROMOTION', 'DEMOTION', 'TRANSFER', 'LATERAL_MOVE', 'NEW_HIRE', 'TERMINATION', 'REHIRE']),
  effectiveDate: z.string(),
  reason: z.string().optional(),
  notes: z.string().optional(),

  // Previous State
  previousDepartmentId: z.string().optional(),
  previousPositionId: z.string().optional(),
  previousJobProfileId: z.string().optional(),
  previousGradeId: z.string().optional(),
  previousLocationId: z.string().optional(),
  previousManagerId: z.string().optional(),
  previousSalary: z.number().optional(),
  previousEmploymentType: z.string().optional(),

  // New State
  newDepartmentId: z.string().optional(),
  newPositionId: z.string().optional(),
  newJobProfileId: z.string().optional(),
  newGradeId: z.string().optional(),
  newLocationId: z.string().optional(),
  newManagerId: z.string().optional(),
  newSalary: z.number().optional(),
  newEmploymentType: z.string().optional(),

  // Approval
  requestedBy: z.string().optional(),
  approvedBy: z.string().optional(),
  approvedAt: z.string().optional(),
  status: z.enum(['PENDING', 'APPROVED', 'REJECTED', 'COMPLETED']).default('COMPLETED'),

  isAutoGenerated: z.boolean().default(false),
});

export const updateEmploymentHistorySchema = createEmploymentHistorySchema.partial().omit({ tenantId: true, employeeId: true });

// ========================================
// TYPES
// ========================================

export interface EmploymentHistoryFilter {
  tenantId: string;
  employeeId?: string;
  changeType?: string;
  status?: string;
  startDate?: string;
  endDate?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

// ========================================
// EMPLOYMENT HISTORY SERVICE
// ========================================

export class EmploymentHistoryService {
  /**
   * Find all employment history records with filtering and pagination
   */
  static async findAll(filter: EmploymentHistoryFilter) {
    const {
      tenantId,
      employeeId,
      changeType,
      status,
      startDate,
      endDate,
      page = 1,
      limit = 20,
      sortBy = 'effectiveDate',
      sortOrder = 'desc',
    } = filter;

    const skip = (page - 1) * limit;

    const where: any = {
      tenantId,
      ...(employeeId && { employeeId }),
      ...(changeType && { changeType }),
      ...(status && { status }),
      ...(startDate || endDate
        ? {
            effectiveDate: {
              ...(startDate && { gte: new Date(startDate) }),
              ...(endDate && { lte: new Date(endDate) }),
            },
          }
        : {}),
    };

    const [records, total] = await Promise.all([
      prisma.employmentHistory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { [sortBy]: sortOrder },
        include: {
          previousDepartment: true,
          previousJobProfile: true,
          previousGrade: true,
          previousLocation: true,
          newDepartment: true,
          newJobProfile: true,
          newGrade: true,
          newLocation: true,
        },
      }),
      prisma.employmentHistory.count({ where }),
    ]);

    return {
      data: records,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /**
   * Find employment history by ID
   */
  static async findById(id: string, tenantId: string) {
    const record = await prisma.employmentHistory.findFirst({
      where: { id, tenantId },
      include: {
        previousDepartment: true,
        previousJobProfile: true,
        previousGrade: true,
        previousLocation: true,
        newDepartment: true,
        newJobProfile: true,
        newGrade: true,
        newLocation: true,
      },
    });

    return record;
  }

  /**
   * Get employment timeline for specific employee
   */
  static async getEmployeeTimeline(employeeId: string, tenantId: string) {
    const timeline = await prisma.employmentHistory.findMany({
      where: { employeeId, tenantId },
      orderBy: { effectiveDate: 'desc' },
      include: {
        previousDepartment: true,
        previousJobProfile: true,
        previousGrade: true,
        previousLocation: true,
        newDepartment: true,
        newJobProfile: true,
        newGrade: true,
        newLocation: true,
      },
    });

    return timeline;
  }

  /**
   * Create new employment history record
   */
  static async create(data: z.infer<typeof createEmploymentHistorySchema>) {
    // Validate input
    const validatedData = createEmploymentHistorySchema.parse(data);

    // Create employment history record
    const record = await prisma.employmentHistory.create({
      data: {
        ...validatedData,
        effectiveDate: new Date(validatedData.effectiveDate),
        approvedAt: validatedData.approvedAt ? new Date(validatedData.approvedAt) : undefined,
      },
      include: {
        previousDepartment: true,
        previousJobProfile: true,
        previousGrade: true,
        previousLocation: true,
        newDepartment: true,
        newJobProfile: true,
        newGrade: true,
        newLocation: true,
      },
    });

    return record;
  }

  /**
   * Update employment history record
   */
  static async update(id: string, tenantId: string, data: z.infer<typeof updateEmploymentHistorySchema>) {
    // Validate input
    const validatedData = updateEmploymentHistorySchema.parse(data);

    // Check if record exists
    const existing = await prisma.employmentHistory.findFirst({
      where: { id, tenantId },
    });

    if (!existing) {
      throw new Error('Employment history record not found');
    }

    // Update record
    const record = await prisma.employmentHistory.update({
      where: { id },
      data: {
        ...validatedData,
        effectiveDate: validatedData.effectiveDate ? new Date(validatedData.effectiveDate) : undefined,
        approvedAt: validatedData.approvedAt ? new Date(validatedData.approvedAt) : undefined,
      },
      include: {
        previousDepartment: true,
        previousJobProfile: true,
        previousGrade: true,
        previousLocation: true,
        newDepartment: true,
        newJobProfile: true,
        newGrade: true,
        newLocation: true,
      },
    });

    return record;
  }

  /**
   * Delete employment history record
   */
  static async delete(id: string, tenantId: string) {
    // Check if record exists
    const existing = await prisma.employmentHistory.findFirst({
      where: { id, tenantId },
    });

    if (!existing) {
      throw new Error('Employment history record not found');
    }

    // Delete record
    await prisma.employmentHistory.delete({
      where: { id },
    });

    return { success: true };
  }

  /**
   * Auto-create history record when employee data changes
   */
  static async createFromEmployeeChange(
    employeeId: string,
    tenantId: string,
    previousState: any,
    newState: any,
    changeType: string,
    effectiveDate: Date,
    requestedBy?: string
  ) {
    const record = await prisma.employmentHistory.create({
      data: {
        tenantId,
        employeeId,
        changeType,
        effectiveDate,
        previousDepartmentId: previousState.departmentId,
        previousJobProfileId: previousState.jobProfileId,
        previousGradeId: previousState.gradeId,
        previousLocationId: previousState.locationId,
        previousManagerId: previousState.managerId,
        newDepartmentId: newState.departmentId,
        newJobProfileId: newState.jobProfileId,
        newGradeId: newState.gradeId,
        newLocationId: newState.locationId,
        newManagerId: newState.managerId,
        requestedBy,
        status: 'COMPLETED',
        isAutoGenerated: true,
      },
      include: {
        previousDepartment: true,
        previousJobProfile: true,
        previousGrade: true,
        previousLocation: true,
        newDepartment: true,
        newJobProfile: true,
        newGrade: true,
        newLocation: true,
      },
    });

    return record;
  }

  /**
   * Get statistics about employment changes
   */
  static async getStatistics(tenantId: string, startDate?: Date, endDate?: Date) {
    const where: any = {
      tenantId,
      ...(startDate || endDate
        ? {
            effectiveDate: {
              ...(startDate && { gte: startDate }),
              ...(endDate && { lte: endDate }),
            },
          }
        : {}),
    };

    const [
      totalChanges,
      promotions,
      demotions,
      transfers,
      lateralMoves,
      newHires,
      terminations,
      changesByType,
    ] = await Promise.all([
      prisma.employmentHistory.count({ where }),
      prisma.employmentHistory.count({ where: { ...where, changeType: 'PROMOTION' } }),
      prisma.employmentHistory.count({ where: { ...where, changeType: 'DEMOTION' } }),
      prisma.employmentHistory.count({ where: { ...where, changeType: 'TRANSFER' } }),
      prisma.employmentHistory.count({ where: { ...where, changeType: 'LATERAL_MOVE' } }),
      prisma.employmentHistory.count({ where: { ...where, changeType: 'NEW_HIRE' } }),
      prisma.employmentHistory.count({ where: { ...where, changeType: 'TERMINATION' } }),
      prisma.employmentHistory.groupBy({
        by: ['changeType'],
        where,
        _count: true,
      }),
    ]);

    return {
      totalChanges,
      promotions,
      demotions,
      transfers,
      lateralMoves,
      newHires,
      terminations,
      changesByType,
    };
  }

  /**
   * Get tenure in current position for employees
   */
  static async getCurrentPositionTenure(employeeId: string, tenantId: string) {
    // Get most recent employment history record
    const latestChange = await prisma.employmentHistory.findFirst({
      where: { employeeId, tenantId },
      orderBy: { effectiveDate: 'desc' },
    });

    if (!latestChange) {
      // No history, check employee creation date
      const employee = await prisma.employee.findFirst({
        where: { id: employeeId },
        select: { createdAt: true },
      });

      if (employee) {
        const tenure = Math.floor((Date.now() - employee.createdAt.getTime()) / (1000 * 60 * 60 * 24));
        return {
          days: tenure,
          months: Math.floor(tenure / 30),
          years: Math.floor(tenure / 365),
        };
      }

      return null;
    }

    const tenure = Math.floor((Date.now() - latestChange.effectiveDate.getTime()) / (1000 * 60 * 60 * 24));

    return {
      days: tenure,
      months: Math.floor(tenure / 30),
      years: Math.floor(tenure / 365),
      sinceDate: latestChange.effectiveDate,
    };
  }

  /**
   * Compare two employment history records
   */
  static async compare(id1: string, id2: string, tenantId: string) {
    const [record1, record2] = await Promise.all([
      this.findById(id1, tenantId),
      this.findById(id2, tenantId),
    ]);

    if (!record1 || !record2) {
      throw new Error('One or both records not found');
    }

    return {
      record1,
      record2,
      changes: {
        department: record1.newDepartmentId !== record2.newDepartmentId,
        jobProfile: record1.newJobProfileId !== record2.newJobProfileId,
        grade: record1.newGradeId !== record2.newGradeId,
        location: record1.newLocationId !== record2.newLocationId,
        manager: record1.newManagerId !== record2.newManagerId,
        salary: record1.newSalary !== record2.newSalary,
        employmentType: record1.newEmploymentType !== record2.newEmploymentType,
      },
    };
  }

  /**
   * Get pending approval records
   */
  static async getPendingApprovals(tenantId: string) {
    const pending = await prisma.employmentHistory.findMany({
      where: {
        tenantId,
        status: 'PENDING',
      },
      orderBy: { createdAt: 'asc' },
      include: {
        previousDepartment: true,
        previousJobProfile: true,
        previousGrade: true,
        newDepartment: true,
        newJobProfile: true,
        newGrade: true,
      },
    });

    return pending;
  }

  /**
   * Approve employment history change
   */
  static async approve(id: string, tenantId: string, approvedBy: string) {
    const record = await prisma.employmentHistory.findFirst({
      where: { id, tenantId },
    });

    if (!record) {
      throw new Error('Employment history record not found');
    }

    if (record.status !== 'PENDING') {
      throw new Error('Only pending records can be approved');
    }

    const updated = await prisma.employmentHistory.update({
      where: { id },
      data: {
        status: 'APPROVED',
        approvedBy,
        approvedAt: new Date(),
      },
    });

    return updated;
  }

  /**
   * Reject employment history change
   */
  static async reject(id: string, tenantId: string, rejectedBy: string, reason?: string) {
    const record = await prisma.employmentHistory.findFirst({
      where: { id, tenantId },
    });

    if (!record) {
      throw new Error('Employment history record not found');
    }

    if (record.status !== 'PENDING') {
      throw new Error('Only pending records can be rejected');
    }

    const updated = await prisma.employmentHistory.update({
      where: { id },
      data: {
        status: 'REJECTED',
        approvedBy: rejectedBy,
        approvedAt: new Date(),
        notes: reason ? `${record.notes || ''}\n\nRejection Reason: ${reason}` : record.notes,
      },
    });

    return updated;
  }
}
