BEGIN;

CREATE TABLE IF NOT EXISTS auraos.aura_automotive_part_inventory (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  part TEXT NOT NULL,
  sku TEXT NOT NULL,
  stock INTEGER NOT NULL,
  min_stock INTEGER NOT NULL,
  status TEXT NOT NULL,
  supplier TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;