"use client";

import React, { useState } from 'react';
import {
    FileText,
    Download,
    Calendar,
    Filter
} from 'lucide-react';

export default function GovernmentReportsPage() {
    return (
        <div className="space-y-6 pb-10 h-[calc(100vh-6rem)] flex flex-col relative text-slate-900 dark:text-slate-100">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 shrink-0">
                <div>
                    <h1 className="text-2xl font-bold flex items-center gap-2">
                        <FileText className="w-6 h-6 text-indigo-500" />
                        Government Reports
                    </h1>
                    <p className="text-slate-500 text-sm">Generate compliance reports for local authorities.</p>
                </div>
                <div className="flex items-center gap-2">
                    <select className="px-4 py-2 border border-slate-200 dark:border-slate-700 rounded-lg bg-transparent text-sm">
                        <option>United States</option>
                        <option>India</option>
                        <option>United Kingdom</option>
                    </select>
                    <button className="px-4 py-2 bg-indigo-600 text-white rounded-lg font-bold hover:bg-indigo-700 flex items-center gap-2">
                        <Filter className="w-4 h-4" /> Filter
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6">
                    <h3 className="font-bold text-lg mb-4">Required Filings (US)</h3>
                    <div className="space-y-4">
                        {[
                            { name: 'Form 941 (Quarterly)', due: 'Jan 31, 2025', status: 'Pending' },
                            { name: 'W-2 Statements', due: 'Jan 31, 2025', status: 'In Progress' },
                            { name: 'Form 940 (Annual)', due: 'Jan 31, 2025', status: 'Pending' },
                        ].map((form, i) => (
                            <div key={i} className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-100 dark:border-slate-800">
                                <div className="font-bold text-lg">{form.name}</div>
                                <div className="text-sm text-slate-500 flex items-center gap-2 mt-1">
                                    <Calendar className="w-3 h-3" /> Due: {form.due}
                                </div>
                                <div className="flex justify-between items-center mt-3">
                                    <span className={`px-2 py-1 rounded text-xs font-bold ${form.status === 'Pending' ? 'bg-amber-100 text-amber-600' : 'bg-indigo-100 text-indigo-600'
                                        }`}>{form.status}</span>
                                    <button className="text-sm font-bold text-indigo-600 hover:underline">Prepare</button>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="lg:col-span-2 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6">
                    <h3 className="font-bold text-lg mb-4">Generated Reports Archive</h3>
                    <table className="w-full text-sm text-left">
                        <thead className="bg-slate-50 dark:bg-slate-800/50 text-xs text-slate-500 uppercase">
                            <tr>
                                <th className="px-6 py-4">Report Name</th>
                                <th className="px-6 py-4">Period</th>
                                <th className="px-6 py-4">Generated On</th>
                                <th className="px-6 py-4">Generated By</th>
                                <th className="px-6 py-4 text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                            {[
                                { name: 'EEO-1 Component 1', period: '2023', date: 'Dec 01, 2024', user: 'Admin' },
                                { name: 'OSHA 300 Log', period: 'Q3 2024', date: 'Oct 15, 2024', user: 'Safety Officer' },
                                { name: '401k Censust', period: '2023', date: 'Jun 15, 2024', user: 'HR Mgr' },
                            ].map((row, i) => (
                                <tr key={i} className="hover:bg-slate-50 dark:hover:bg-slate-800/50">
                                    <td className="px-6 py-4 font-bold flex items-center gap-2">
                                        <FileText className="w-4 h-4 text-slate-400" /> {row.name}
                                    </td>
                                    <td className="px-6 py-4">{row.period}</td>
                                    <td className="px-6 py-4">{row.date}</td>
                                    <td className="px-6 py-4">{row.user}</td>
                                    <td className="px-6 py-4 text-center">
                                        <button className="text-slate-400 hover:text-indigo-600">
                                            <Download className="w-4 h-4" />
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}
