"use client";
import { useState, useEffect, useCallback } from 'react';
import { FIFOWorker, CampFacility, HazardPayRule, HazardPayment, MiningSettings, MiningAlert } from '../types';
import { FIFOLogisticsService, CampManagementService, HazardPayService, MiningSettingsService, AlertsService } from '../services';
import { sampleFIFOWorkers, sampleCampFacilities, sampleHazardPayRules, sampleHazardPayments, sampleMiningSettings } from '../data';
interface Toast { type: 'success' | 'error' | 'info'; message: string; }
export const useMining = () => { const [fifoWorkers, setFifoWorkers] = useState<FIFOWorker[]>([]); const [campFacilities, setCampFacilities] = useState<CampFacility[]>([]); const [hazardPayRules, setHazardPayRules] = useState<HazardPayRule[]>([]); const [hazardPayments, setHazardPayments] = useState<HazardPayment[]>([]); const [settings, setSettings] = useState<MiningSettings | null>(null); const [alerts, setAlerts] = useState<MiningAlert[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [toasts, setToasts] = useState<Toast[]>([]);
const addToast = useCallback((toast: Toast) => { setToasts(prev => [...prev, toast]); setTimeout(() => setToasts(prev => prev.slice(1)), 5000); }, []);
const loadAllData = useCallback(async () => { setLoading(true); try { const [workersData, facilitiesData, rulesData, paymentsData, settingsData] = await Promise.all([FIFOLogisticsService.getAllWorkers(), CampManagementService.getAllFacilities(), HazardPayService.getAllRules(), HazardPayService.getAllPayments(), MiningSettingsService.getSettings()]); if (workersData.length === 0) { for (const w of sampleFIFOWorkers) await FIFOLogisticsService.createWorker(w); setFifoWorkers(sampleFIFOWorkers); } else setFifoWorkers(workersData); if (facilitiesData.length === 0) { for (const f of sampleCampFacilities) await CampManagementService.createFacility(f); setCampFacilities(sampleCampFacilities); } else setCampFacilities(facilitiesData); if (rulesData.length === 0) { for (const r of sampleHazardPayRules) await HazardPayService.createRule(r); setHazardPayRules(sampleHazardPayRules); } else setHazardPayRules(rulesData); if (paymentsData.length === 0) { for (const p of sampleHazardPayments) await HazardPayService.createPayment(p); setHazardPayments(sampleHazardPayments); } else setHazardPayments(paymentsData); if (!settingsData) { await MiningSettingsService.updateSettings(sampleMiningSettings); setSettings(sampleMiningSettings); } else setSettings(settingsData); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to load data'); addToast({ type: 'error', message: 'Failed to load mining data' }); } finally { setLoading(false); } }, [addToast]);
useEffect(() => { loadAllData(); }, [loadAllData]);
const createFIFOWorker = async (data: Partial<FIFOWorker>) => { setLoading(true); try { const worker = await FIFOLogisticsService.createWorker(data); setFifoWorkers(await FIFOLogisticsService.getAllWorkers()); addToast({ type: 'success', message: 'FIFO worker created' }); return worker; } catch (err) { addToast({ type: 'error', message: 'Failed to create worker' }); throw err; } finally { setLoading(false); } };
const updateFIFOWorker = async (workerId: string, updates: Partial<FIFOWorker>) => { setLoading(true); try { const worker = await FIFOLogisticsService.updateWorker(workerId, updates); setFifoWorkers(await FIFOLogisticsService.getAllWorkers()); addToast({ type: 'success', message: 'FIFO worker updated' }); return worker; } catch (err) { addToast({ type: 'error', message: 'Failed to update worker' }); throw err; } finally { setLoading(false); } };
const createCampFacility = async (data: Partial<CampFacility>) => { setLoading(true); try { const facility = await CampManagementService.createFacility(data); setCampFacilities(await CampManagementService.getAllFacilities()); addToast({ type: 'success', message: 'Camp facility created' }); return facility; } catch (err) { addToast({ type: 'error', message: 'Failed to create facility' }); throw err; } finally { setLoading(false); } };
const createHazardPayment = async (data: Partial<HazardPayment>) => { setLoading(true); try { const payment = await HazardPayService.createPayment(data); setHazardPayments(await HazardPayService.getAllPayments()); addToast({ type: 'success', message: 'Hazard payment created' }); return payment; } catch (err) { addToast({ type: 'error', message: 'Failed to create payment' }); throw err; } finally { setLoading(false); } };
return { fifoWorkers, campFacilities, hazardPayRules, hazardPayments, settings, alerts, loading, error, toasts, createFIFOWorker, updateFIFOWorker, createCampFacility, createHazardPayment, loadAllData }; };
