/**
 * Learning Management System - Sample Data
 */

import type {
    Course,
    LearningPath,
    Enrollment,
    Assessment,
    Certification,
    TrainingSession,
    ExternalTraining,
    SkillGapAnalysis,
    MentoringProgram,
    TrainingBudget,
    KnowledgeArticle,
    TrainingFeedback,
    LearningSettings,
} from './types';

export const generateSampleCourses = (): Course[] => [
    {
        id: 'course_001',
        courseCode: 'TECH-101',
        title: 'Introduction to TypeScript',
        description: 'Learn the fundamentals of TypeScript programming',
        type: 'e_learning',
        level: 'beginner',
        status: 'published',
        categoryId: 'cat_tech',
        categoryName: 'Technology',
        instructorId: 'inst_001',
        instructorName: 'Sarah Johnson',
        duration: 8,
        durationUnit: 'hours',
        objectives: [
            'Understand TypeScript basics',
            'Work with types and interfaces',
            'Build type-safe applications',
        ],
        prerequisites: ['Basic JavaScript knowledge'],
        targetAudience: 'Software developers',
        skills: ['TypeScript', 'Programming', 'Web Development'],
        competencies: ['Technical Skills', 'Problem Solving'],
        maxParticipants: 50,
        currentEnrollments: 35,
        passingScore: 70,
        credits: 8,
        ceus: 0.8,
        cost: 299,
        currency: 'USD',
        tags: ['programming', 'typescript', 'web-development'],
        isComplianceTraining: false,
        validityPeriod: 365,
        modules: [
            {
                id: 'mod_001',
                courseId: 'course_001',
                title: 'Getting Started with TypeScript',
                description: 'Introduction and setup',
                order: 1,
                duration: 60,
                isRequired: true,
                content: [],
            },
        ],
        publishedDate: '2025-01-01T00:00:00Z',
        createdBy: 'admin_001',
        createdAt: '2024-12-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
    },
    {
        id: 'course_002',
        courseCode: 'LEAD-201',
        title: 'Leadership Essentials',
        description: 'Develop core leadership competencies',
        type: 'blended',
        level: 'intermediate',
        status: 'published',
        categoryId: 'cat_leadership',
        categoryName: 'Leadership & Management',
        instructorId: 'inst_002',
        instructorName: 'Michael Chen',
        duration: 16,
        durationUnit: 'hours',
        objectives: [
            'Build leadership presence',
            'Motivate and inspire teams',
            'Make effective decisions',
        ],
        prerequisites: [],
        targetAudience: 'Managers and aspiring leaders',
        skills: ['Leadership', 'Communication', 'Decision Making'],
        competencies: ['Leadership', 'People Management'],
        maxParticipants: 25,
        currentEnrollments: 20,
        passingScore: 75,
        credits: 16,
        ceus: 1.6,
        cost: 599,
        currency: 'USD',
        tags: ['leadership', 'management', 'soft-skills'],
        isComplianceTraining: false,
        modules: [],
        publishedDate: '2025-01-05T00:00:00Z',
        createdBy: 'admin_001',
        createdAt: '2024-12-15T00:00:00Z',
        updatedAt: '2025-01-05T00:00:00Z',
    },
    {
        id: 'course_003',
        courseCode: 'COMP-301',
        title: 'Data Privacy & GDPR Compliance',
        description: 'Mandatory compliance training on data protection',
        type: 'e_learning',
        level: 'intermediate',
        status: 'published',
        categoryId: 'cat_compliance',
        categoryName: 'Compliance',
        instructorId: 'inst_003',
        instructorName: 'Emily Rodriguez',
        duration: 4,
        durationUnit: 'hours',
        objectives: [
            'Understand GDPR requirements',
            'Protect customer data',
            'Handle data breach scenarios',
        ],
        prerequisites: [],
        targetAudience: 'All employees',
        skills: ['Data Protection', 'Compliance', 'Privacy'],
        competencies: ['Legal & Compliance'],
        currentEnrollments: 150,
        passingScore: 80,
        credits: 4,
        isComplianceTraining: true,
        validityPeriod: 365,
        tags: ['compliance', 'gdpr', 'data-privacy', 'mandatory'],
        modules: [],
        publishedDate: '2025-01-01T00:00:00Z',
        createdBy: 'admin_001',
        createdAt: '2024-11-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
    },
];

export const generateSampleLearningPaths = (): LearningPath[] => [
    {
        id: 'path_001',
        pathCode: 'PATH-FULLSTACK',
        title: 'Full Stack Developer Pathway',
        description: 'Complete path to becoming a full stack developer',
        level: 'intermediate',
        categoryId: 'cat_tech',
        categoryName: 'Technology',
        duration: 120,
        courses: [
            {
                courseId: 'course_001',
                courseTitle: 'Introduction to TypeScript',
                order: 1,
                isRequired: true,
            },
            {
                courseId: 'course_004',
                courseTitle: 'React Fundamentals',
                order: 2,
                isRequired: true,
                prerequisites: ['course_001'],
            },
        ],
        skills: ['TypeScript', 'React', 'Node.js', 'Databases'],
        competencies: ['Full Stack Development', 'Problem Solving'],
        isActive: true,
        enrollmentCount: 45,
        completionRate: 68,
        createdAt: '2024-12-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
    },
];

export const generateSampleEnrollments = (): Enrollment[] => [
    {
        id: 'enroll_001',
        enrollmentNumber: 'ENR-2025-001',
        courseId: 'course_001',
        courseTitle: 'Introduction to TypeScript',
        learnerId: 'emp_001',
        learnerName: 'John Doe',
        learnerEmail: 'john.doe@company.com',
        enrollmentType: 'self_enrolled',
        status: 'in_progress',
        enrolledDate: '2025-01-10T00:00:00Z',
        startDate: '2025-01-10T00:00:00Z',
        dueDate: '2025-02-10T00:00:00Z',
        progress: 45,
        timeSpent: 180,
        passingScore: 70,
        attempts: 0,
        maxAttempts: 3,
        completionPercentage: 45,
        lastAccessedDate: '2025-01-15T00:00:00Z',
        modules: [
            {
                moduleId: 'mod_001',
                moduleTitle: 'Getting Started with TypeScript',
                status: 'completed',
                progress: 100,
                timeSpent: 60,
                completedDate: '2025-01-12T00:00:00Z',
            },
        ],
        createdAt: '2025-01-10T00:00:00Z',
        updatedAt: '2025-01-15T00:00:00Z',
    },
    {
        id: 'enroll_002',
        enrollmentNumber: 'ENR-2025-002',
        courseId: 'course_003',
        courseTitle: 'Data Privacy & GDPR Compliance',
        learnerId: 'emp_002',
        learnerName: 'Jane Smith',
        learnerEmail: 'jane.smith@company.com',
        enrollmentType: 'mandatory',
        status: 'completed',
        enrolledDate: '2025-01-01T00:00:00Z',
        startDate: '2025-01-02T00:00:00Z',
        dueDate: '2025-01-31T00:00:00Z',
        completedDate: '2025-01-08T00:00:00Z',
        progress: 100,
        timeSpent: 240,
        score: 92,
        passingScore: 80,
        attempts: 1,
        completionPercentage: 100,
        certificateId: 'cert_001',
        modules: [],
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-08T00:00:00Z',
    },
];

export const generateSampleAssessments = (): Assessment[] => [
    {
        id: 'assess_001',
        assessmentCode: 'ASS-TS-FINAL',
        title: 'TypeScript Final Assessment',
        description: 'Final exam for TypeScript course',
        type: 'exam',
        courseId: 'course_001',
        courseTitle: 'Introduction to TypeScript',
        duration: 60,
        passingScore: 70,
        maxAttempts: 3,
        questions: [
            {
                id: 'q_001',
                assessmentId: 'assess_001',
                questionText: 'What is TypeScript?',
                type: 'multiple_choice',
                order: 1,
                points: 10,
                options: [
                    { id: 'opt_001', text: 'A superset of JavaScript', isCorrect: true },
                    { id: 'opt_002', text: 'A database language', isCorrect: false },
                    { id: 'opt_003', text: 'A styling framework', isCorrect: false },
                ],
                correctAnswer: 'opt_001',
            },
        ],
        isRandomized: true,
        showCorrectAnswers: true,
        allowReview: true,
        isActive: true,
        createdBy: 'inst_001',
        createdAt: '2024-12-01T00:00:00Z',
        updatedAt: '2024-12-01T00:00:00Z',
    },
];

export const generateSampleCertifications = (): Certification[] => [
    {
        id: 'cert_001',
        certificateNumber: 'CERT-2025-001',
        certificateName: 'GDPR Compliance Certificate',
        courseId: 'course_003',
        courseTitle: 'Data Privacy & GDPR Compliance',
        learnerId: 'emp_002',
        learnerName: 'Jane Smith',
        issuedDate: '2025-01-08T00:00:00Z',
        expiryDate: '2026-01-08T00:00:00Z',
        status: 'active',
        score: 92,
        credits: 4,
        issuedBy: 'Learning & Development',
        verificationCode: 'VERIFY-CERT-001',
        renewalRequired: true,
        renewalReminderSent: false,
        createdAt: '2025-01-08T00:00:00Z',
        updatedAt: '2025-01-08T00:00:00Z',
    },
];

export const generateSampleTrainingSessions = (): TrainingSession[] => [
    {
        id: 'session_001',
        sessionCode: 'SES-LEAD-2025-01',
        courseId: 'course_002',
        courseTitle: 'Leadership Essentials',
        type: 'classroom',
        status: 'scheduled',
        instructorId: 'inst_002',
        instructorName: 'Michael Chen',
        startDate: '2025-02-01T09:00:00Z',
        endDate: '2025-02-02T17:00:00Z',
        location: 'Conference Room A, Building 1',
        maxParticipants: 25,
        enrolledCount: 20,
        waitlistCount: 5,
        cost: 599,
        currency: 'USD',
        attendees: [
            {
                learnerId: 'emp_003',
                learnerName: 'Alice Brown',
                enrollmentId: 'enroll_003',
                attendanceStatus: 'present',
            },
        ],
        createdAt: '2024-12-15T00:00:00Z',
        updatedAt: '2025-01-10T00:00:00Z',
    },
];

export const generateSampleExternalTraining = (): ExternalTraining[] => [
    {
        id: 'ext_001',
        trainingCode: 'EXT-AWS-2025-001',
        title: 'AWS Certified Solutions Architect',
        provider: 'Amazon Web Services',
        learnerId: 'emp_001',
        learnerName: 'John Doe',
        category: 'Cloud Computing',
        startDate: '2025-03-01',
        endDate: '2025-03-05',
        duration: 40,
        cost: 2500,
        currency: 'USD',
        approvalStatus: 'approved',
        approvedBy: 'mgr_001',
        approvedDate: '2025-01-20T00:00:00Z',
        completionStatus: 'not_started',
        skills: ['AWS', 'Cloud Architecture', 'DevOps'],
        notes: 'Critical certification for cloud infrastructure role',
        createdAt: '2025-01-15T00:00:00Z',
        updatedAt: '2025-01-20T00:00:00Z',
    },
];

export const generateSampleSkillGapAnalysis = (): SkillGapAnalysis[] => [
    {
        id: 'gap_001',
        employeeId: 'emp_001',
        employeeName: 'John Doe',
        jobRoleId: 'role_senior_dev',
        jobRoleTitle: 'Senior Software Developer',
        assessmentDate: '2025-01-15T00:00:00Z',
        skills: [
            {
                skillId: 'skill_ts',
                skillName: 'TypeScript',
                requiredLevel: 'advanced',
                currentLevel: 'intermediate',
                gap: 1,
                priority: 'high',
            },
            {
                skillId: 'skill_aws',
                skillName: 'AWS',
                requiredLevel: 'advanced',
                currentLevel: 'beginner',
                gap: 2,
                priority: 'critical',
            },
        ],
        recommendedCourses: ['course_001', 'ext_001'],
        status: 'completed',
        createdAt: '2025-01-15T00:00:00Z',
        updatedAt: '2025-01-15T00:00:00Z',
    },
];

export const generateSampleMentoringPrograms = (): MentoringProgram[] => [
    {
        id: 'mentor_001',
        programName: 'Senior Dev Mentorship',
        description: 'Mentoring program for career advancement',
        mentorId: 'emp_senior_001',
        mentorName: 'Sarah Johnson',
        menteeId: 'emp_001',
        menteeName: 'John Doe',
        startDate: '2025-01-01',
        endDate: '2025-06-30',
        status: 'active',
        objectives: [
            'Develop advanced TypeScript skills',
            'Learn system design principles',
            'Prepare for senior role',
        ],
        meetingFrequency: 'Bi-weekly',
        sessions: [
            {
                id: 'session_m_001',
                programId: 'mentor_001',
                sessionDate: '2025-01-10T14:00:00Z',
                duration: 60,
                topics: ['Career goals', 'Learning plan'],
                status: 'completed',
            },
        ],
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-10T00:00:00Z',
    },
];

export const generateSampleTrainingBudgets = (): TrainingBudget[] => [
    {
        id: 'budget_001',
        fiscalYear: '2025',
        departmentId: 'dept_engineering',
        departmentName: 'Engineering',
        totalBudget: 100000,
        allocatedAmount: 80000,
        spentAmount: 35000,
        remainingAmount: 45000,
        currency: 'USD',
        allocations: [
            {
                categoryId: 'cat_tech',
                categoryName: 'Technology',
                allocatedAmount: 50000,
                spentAmount: 25000,
            },
            {
                categoryId: 'cat_leadership',
                categoryName: 'Leadership',
                allocatedAmount: 30000,
                spentAmount: 10000,
            },
        ],
        createdAt: '2024-12-01T00:00:00Z',
        updatedAt: '2025-01-15T00:00:00Z',
    },
];

export const generateSampleKnowledgeArticles = (): KnowledgeArticle[] => [
    {
        id: 'article_001',
        title: 'TypeScript Best Practices',
        content: 'A comprehensive guide to writing clean TypeScript code...',
        categoryId: 'cat_tech',
        categoryName: 'Technology',
        authorId: 'emp_senior_001',
        authorName: 'Sarah Johnson',
        tags: ['typescript', 'best-practices', 'coding'],
        viewCount: 245,
        likeCount: 67,
        isPublished: true,
        publishedDate: '2025-01-05T00:00:00Z',
        lastUpdatedBy: 'emp_senior_001',
        createdAt: '2025-01-03T00:00:00Z',
        updatedAt: '2025-01-05T00:00:00Z',
    },
];

export const generateSampleTrainingFeedback = (): TrainingFeedback[] => [
    {
        id: 'feedback_001',
        enrollmentId: 'enroll_002',
        courseId: 'course_003',
        courseTitle: 'Data Privacy & GDPR Compliance',
        learnerId: 'emp_002',
        learnerName: 'Jane Smith',
        overallRating: 5,
        contentQuality: 5,
        relevance: 5,
        difficultyLevel: 'appropriate',
        paceRating: 'appropriate',
        strengths: 'Clear explanations, practical examples',
        improvements: 'More case studies would be helpful',
        wouldRecommend: true,
        submittedDate: '2025-01-09T00:00:00Z',
    },
];

export const generateSampleLearningSettings = (): LearningSettings => ({
    defaultPassingScore: 70,
    maxAttemptsDefault: 3,
    certificateExpiryDays: 365,
    reminderDaysBeforeExpiry: 30,
    autoEnrollCompliance: true,
    allowSelfEnrollment: true,
    requireManagerApproval: false,
    enableWaitlist: true,
    emailNotifications: {
        enrollmentConfirmation: true,
        courseCompletion: true,
        certificateIssued: true,
        sessionReminder: true,
        deadlineReminder: true,
        certificationExpiry: true,
    },
});
